# Auto-generated by ChipLoop Testbench Generator Agent
# Verification collateral used by simulation
VERILOG_SOURCES += pwm_controller_assertions.sv
VERILOG_SOURCES += pwm_controller_assertions_bind.sv
