# Auto-generated by ChipLoop Testbench Generator Agent
# Explicit RTL sources used by simulation
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_csr_decode.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_top.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_transport_ctrl.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_req_fifo_wrapper.v
