"""Auto-generated Cocotb testbench skeleton for: adaptive_aero_control_top

Generated by ChipLoop Testbench Generator Agent.
- Uses spec JSON as the source of truth for ports/clocks/resets
- Supports digital mode and future system/SoC mode
- Avoids hardcoded DUT signal assumptions
"""

import os
import random
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, Timer

try:
    from scoreboard import Scoreboard
except Exception:
    Scoreboard = None

try:
    from coverage_model import CoverageModel
except Exception:
    CoverageModel = None


def _seed() -> int:
    env = os.getenv("RANDOM_SEED")
    if env and env.isdigit():
        return int(env)
    return 1


async def _advance_time(dut):
    clocks = [
  "clk"
]
    for clk_name in clocks:
        if hasattr(dut, clk_name):
            await RisingEdge(getattr(dut, clk_name))
            return
    await Timer(10, units="ns")


def _safe_drive_random(sig, width_expr: str):
    try:
        width = int(width_expr)
    except Exception:
        try:
            width = len(sig.value.binstr)
        except Exception:
            width = 1
    width = max(int(width), 1)
    sig.value = random.getrandbits(width)


def _fit_to_signal(sig, value: int) -> int:
    try:
        width = len(sig)
    except Exception:
        try:
            width = len(sig.value.binstr)
        except Exception:
            width = 32
    width = max(int(width), 1)
    return int(value) & ((1 << width) - 1)


def _assert_outputs_known(dut, observable_outputs):
    for p in observable_outputs:
        name = p.get("name")
        if not name or not hasattr(dut, name):
            continue
        sig = getattr(dut, name)
        value = str(sig.value).lower()
        assert "x" not in value and "z" not in value, f"Output {name} is unknown/high-Z: {sig.value}"


@cocotb.test()
async def smoke_test(dut):
    """Basic smoke test: clock/reset bring-up and brief settle window."""
    seed = _seed()
    random.seed(seed)

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "rst_n"):
        getattr(dut, "rst_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "rst_n"):
        getattr(dut, "rst_n").value = 1
    await Timer(5, units='ns')

    # Initialize discoverable DUT inputs from spec
    if hasattr(dut, "s_axis_req_data"):
        getattr(dut, "s_axis_req_data").value = 0
    if hasattr(dut, "s_axis_req_valid"):
        getattr(dut, "s_axis_req_valid").value = 0
    if hasattr(dut, "m_axis_resp_ready"):
        getattr(dut, "m_axis_resp_ready").value = 0
    if hasattr(dut, "m_axis_act_ready"):
        getattr(dut, "m_axis_act_ready").value = 0
    if hasattr(dut, "csr_addr_data"):
        getattr(dut, "csr_addr_data").value = 0
    if hasattr(dut, "csr_wr_en"):
        getattr(dut, "csr_wr_en").value = 0
    if hasattr(dut, "csr_wr_data"):
        getattr(dut, "csr_wr_data").value = 0
    if hasattr(dut, "mem_dout"):
        getattr(dut, "mem_dout").value = 0
    if hasattr(dut, "model_req_ready"):
        getattr(dut, "model_req_ready").value = 0
    if hasattr(dut, "model_rsp_valid"):
        getattr(dut, "model_rsp_valid").value = 0
    if hasattr(dut, "model_rsp_data"):
        getattr(dut, "model_rsp_data").value = 0
    if hasattr(dut, "resp_record_seq"):
        getattr(dut, "resp_record_seq").value = 0
    if hasattr(dut, "resp_record_status"):
        getattr(dut, "resp_record_status").value = 0
    if hasattr(dut, "resp_record_freshness"):
        getattr(dut, "resp_record_freshness").value = 0
    if hasattr(dut, "resp_record_complete"):
        getattr(dut, "resp_record_complete").value = 0
    if hasattr(dut, "resp_record_ctrl_result"):
        getattr(dut, "resp_record_ctrl_result").value = 0
    if hasattr(dut, "resp_record_valid"):
        getattr(dut, "resp_record_valid").value = 0
    if hasattr(dut, "cmd_raw_data"):
        getattr(dut, "cmd_raw_data").value = 0
    if hasattr(dut, "cmd_raw_valid"):
        getattr(dut, "cmd_raw_valid").value = 0

    await Timer(20, units="ns")

    sb = Scoreboard(dut) if Scoreboard else None
    cov = CoverageModel() if CoverageModel else None

    if sb:
        sb.start()
    if cov:
        cov.start(dut)

    for _ in range(5):
        await _advance_time(dut)
        if cov:
            try:
                cov.sample()
            except Exception:
                pass

    _assert_outputs_known(dut, [
  {
    "name": "s_axis_req_ready",
    "width_expr": "1"
  },
  {
    "name": "m_axis_resp_data",
    "width_expr": "128"
  },
  {
    "name": "m_axis_resp_valid",
    "width_expr": "1"
  },
  {
    "name": "m_axis_act_data",
    "width_expr": "64"
  },
  {
    "name": "m_axis_act_valid",
    "width_expr": "1"
  },
  {
    "name": "csr_rd_data",
    "width_expr": "64"
  },
  {
    "name": "csr_rd_valid",
    "width_expr": "1"
  }
])

    if cov:
        try:
            cov.stop()
            cov.write_reports()
        except Exception:
            pass

    

    if sb:
        sb.stop()


@cocotb.test()
async def constrained_random_sanity(dut):
    """Constrained-random sanity test derived only from spec-declared inputs."""
    seed = _seed()
    random.seed(seed)

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "rst_n"):
        getattr(dut, "rst_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "rst_n"):
        getattr(dut, "rst_n").value = 1
    await Timer(5, units='ns')

    randomizable_inputs = [
  {
    "name": "s_axis_req_data",
    "width_expr": "128"
  },
  {
    "name": "s_axis_req_valid",
    "width_expr": "1"
  },
  {
    "name": "m_axis_resp_ready",
    "width_expr": "1"
  },
  {
    "name": "m_axis_act_ready",
    "width_expr": "1"
  },
  {
    "name": "csr_addr_data",
    "width_expr": "64"
  },
  {
    "name": "csr_wr_en",
    "width_expr": "1"
  },
  {
    "name": "csr_wr_data",
    "width_expr": "64"
  },
  {
    "name": "mem_dout",
    "width_expr": "128"
  },
  {
    "name": "model_req_ready",
    "width_expr": "1"
  },
  {
    "name": "model_rsp_valid",
    "width_expr": "1"
  },
  {
    "name": "model_rsp_data",
    "width_expr": "128"
  },
  {
    "name": "resp_record_seq",
    "width_expr": "32"
  },
  {
    "name": "resp_record_status",
    "width_expr": "4"
  },
  {
    "name": "resp_record_freshness",
    "width_expr": "4"
  },
  {
    "name": "resp_record_complete",
    "width_expr": "1"
  },
  {
    "name": "resp_record_ctrl_result",
    "width_expr": "16"
  },
  {
    "name": "resp_record_valid",
    "width_expr": "1"
  },
  {
    "name": "cmd_raw_data",
    "width_expr": "64"
  },
  {
    "name": "cmd_raw_valid",
    "width_expr": "1"
  }
]

    cov = CoverageModel() if CoverageModel else None
    if cov:
        cov.start(dut)

    for _ in range(int(os.getenv("NUM_ITERS", "25"))):
        for p in randomizable_inputs:
            name = p.get("name")
            width_expr = str(p.get("width_expr", "1"))
            if not name or not hasattr(dut, name):
                continue
            try:
                sig = getattr(dut, name)
                _safe_drive_random(sig, width_expr)
            except Exception:
                continue

        await _advance_time(dut)

        if cov:
            try:
                cov.sample()
            except Exception:
                pass

    _assert_outputs_known(dut, [
  {
    "name": "s_axis_req_ready",
    "width_expr": "1"
  },
  {
    "name": "m_axis_resp_data",
    "width_expr": "128"
  },
  {
    "name": "m_axis_resp_valid",
    "width_expr": "1"
  },
  {
    "name": "m_axis_act_data",
    "width_expr": "64"
  },
  {
    "name": "m_axis_act_valid",
    "width_expr": "1"
  },
  {
    "name": "csr_rd_data",
    "width_expr": "64"
  },
  {
    "name": "csr_rd_valid",
    "width_expr": "1"
  }
])

    if cov:
        try:
            cov.stop()
            cov.write_reports()
        except Exception:
            pass

    

