# Auto-generated by ChipLoop Testbench Generator Agent
# Explicit RTL sources used by simulation
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_top.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_top_spi_fpga_top.sv
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_model_gateway.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_register_bank.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_safety_control.v
