# Auto-generated by ChipLoop Testbench Generator Agent
# Explicit RTL sources used by simulation
VERILOG_SOURCES += ../../handoff/rtl/domino_cfg_supervisor.v
VERILOG_SOURCES += ../../handoff/rtl/domino_input_supervisor.v
VERILOG_SOURCES += ../../handoff/rtl/domino_telemetry_fabric.v
VERILOG_SOURCES += ../../handoff/rtl/domino_model_request_manager.v
VERILOG_SOURCES += ../../handoff/rtl/domino_actuator_command_manager.v
VERILOG_SOURCES += ../../handoff/rtl/domino_model_response_validator.v
VERILOG_SOURCES += ../../handoff/rtl/domino_active_aero_control_wrapper.v
