"""Auto-generated Cocotb testbench skeleton for: domino_active_aero_control_wrapper

Generated by ChipLoop Testbench Generator Agent.
- Uses spec JSON as the source of truth for ports/clocks/resets
- Supports digital mode and future system/SoC mode
- Avoids hardcoded DUT signal assumptions
"""

import os
import random
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, Timer

try:
    from scoreboard import Scoreboard
except Exception:
    Scoreboard = None

try:
    from coverage_model import CoverageModel
except Exception:
    CoverageModel = None


def _seed() -> int:
    env = os.getenv("RANDOM_SEED")
    if env and env.isdigit():
        return int(env)
    return 1


async def _advance_time(dut):
    clocks = [
  "clk"
]
    for clk_name in clocks:
        if hasattr(dut, clk_name):
            await RisingEdge(getattr(dut, clk_name))
            return
    await Timer(10, units="ns")


def _safe_drive_random(sig, width_expr: str):
    try:
        width = int(width_expr)
    except Exception:
        try:
            width = len(sig.value.binstr)
        except Exception:
            width = 1
    width = max(int(width), 1)
    sig.value = random.getrandbits(width)


def _fit_to_signal(sig, value: int) -> int:
    try:
        width = len(sig)
    except Exception:
        try:
            width = len(sig.value.binstr)
        except Exception:
            width = 32
    width = max(int(width), 1)
    return int(value) & ((1 << width) - 1)


def _assert_outputs_known(dut, observable_outputs):
    for p in observable_outputs:
        name = p.get("name")
        if not name or not hasattr(dut, name):
            continue
        sig = getattr(dut, name)
        value = str(sig.value).lower()
        assert "x" not in value and "z" not in value, f"Output {name} is unknown/high-Z: {sig.value}"


@cocotb.test()
async def smoke_test(dut):
    """Basic smoke test: clock/reset bring-up and brief settle window."""
    seed = _seed()
    random.seed(seed)

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "rst_n"):
        getattr(dut, "rst_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "rst_n"):
        getattr(dut, "rst_n").value = 1
    await Timer(5, units='ns')

    # Initialize discoverable DUT inputs from spec
    if hasattr(dut, "host_cfg_valid"):
        getattr(dut, "host_cfg_valid").value = 0
    if hasattr(dut, "host_cfg_write"):
        getattr(dut, "host_cfg_write").value = 0
    if hasattr(dut, "host_cfg_addr"):
        getattr(dut, "host_cfg_addr").value = 0
    if hasattr(dut, "host_cfg_wdata"):
        getattr(dut, "host_cfg_wdata").value = 0
    if hasattr(dut, "enable"):
        getattr(dut, "enable").value = 0
    if hasattr(dut, "freshness_timeout_cycles"):
        getattr(dut, "freshness_timeout_cycles").value = 0
    if hasattr(dut, "request_timeout_cycles"):
        getattr(dut, "request_timeout_cycles").value = 0
    if hasattr(dut, "actuator_min_limit"):
        getattr(dut, "actuator_min_limit").value = 0
    if hasattr(dut, "actuator_max_limit"):
        getattr(dut, "actuator_max_limit").value = 0
    if hasattr(dut, "safe_fallback_command_value"):
        getattr(dut, "safe_fallback_command_value").value = 0
    if hasattr(dut, "stream_velocity_mps"):
        getattr(dut, "stream_velocity_mps").value = 0
    if hasattr(dut, "flow_update_strobe"):
        getattr(dut, "flow_update_strobe").value = 0
    if hasattr(dut, "geometry_update_strobe"):
        getattr(dut, "geometry_update_strobe").value = 0
    if hasattr(dut, "geometry_format_selector"):
        getattr(dut, "geometry_format_selector").value = 0
    if hasattr(dut, "geometry_metadata_valid"):
        getattr(dut, "geometry_metadata_valid").value = 0
    if hasattr(dut, "geometry_metadata_tag"):
        getattr(dut, "geometry_metadata_tag").value = 0
    if hasattr(dut, "geometry_handle_in"):
        getattr(dut, "geometry_handle_in").value = 0
    if hasattr(dut, "geometry_reference_is_driaverml_stl"):
        getattr(dut, "geometry_reference_is_driaverml_stl").value = 0
    if hasattr(dut, "fault_clear"):
        getattr(dut, "fault_clear").value = 0
    if hasattr(dut, "mode_select_fallback_when_valid"):
        getattr(dut, "mode_select_fallback_when_valid").value = 0
    if hasattr(dut, "model_req_ready"):
        getattr(dut, "model_req_ready").value = 0
    if hasattr(dut, "model_rsp_valid"):
        getattr(dut, "model_rsp_valid").value = 0
    if hasattr(dut, "model_rsp_id"):
        getattr(dut, "model_rsp_id").value = 0
    if hasattr(dut, "model_rsp_epoch"):
        getattr(dut, "model_rsp_epoch").value = 0
    if hasattr(dut, "model_rsp_status_valid"):
        getattr(dut, "model_rsp_status_valid").value = 0
    if hasattr(dut, "model_rsp_status_unavailable"):
        getattr(dut, "model_rsp_status_unavailable").value = 0
    if hasattr(dut, "model_rsp_drag_force"):
        getattr(dut, "model_rsp_drag_force").value = 0
    if hasattr(dut, "model_rsp_lift_force"):
        getattr(dut, "model_rsp_lift_force").value = 0
    if hasattr(dut, "model_rsp_surface_pressure"):
        getattr(dut, "model_rsp_surface_pressure").value = 0
    if hasattr(dut, "model_rsp_flow_field_meta"):
        getattr(dut, "model_rsp_flow_field_meta").value = 0
    if hasattr(dut, "telemetry_ready"):
        getattr(dut, "telemetry_ready").value = 0

    await Timer(20, units="ns")

    sb = Scoreboard(dut) if Scoreboard else None
    cov = CoverageModel() if CoverageModel else None

    if sb:
        sb.start()
    if cov:
        cov.start(dut)

    for _ in range(5):
        await _advance_time(dut)
        if cov:
            try:
                cov.sample()
            except Exception:
                pass

    _assert_outputs_known(dut, [
  {
    "name": "host_cfg_ready",
    "width_expr": "1"
  },
  {
    "name": "host_cfg_rdata",
    "width_expr": "32"
  },
  {
    "name": "host_cfg_rvalid",
    "width_expr": "1"
  },
  {
    "name": "model_req_valid",
    "width_expr": "1"
  },
  {
    "name": "model_req_id",
    "width_expr": "32"
  },
  {
    "name": "model_req_epoch",
    "width_expr": "32"
  },
  {
    "name": "model_req_geometry_handle",
    "width_expr": "32"
  },
  {
    "name": "model_req_stream_velocity_mps",
    "width_expr": "16"
  },
  {
    "name": "model_req_timeout_cycles",
    "width_expr": "16"
  },
  {
    "name": "actuator_cmd_valid",
    "width_expr": "1"
  },
  {
    "name": "actuator_cmd",
    "width_expr": "16"
  },
  {
    "name": "actuator_cmd_safe_fallback",
    "width_expr": "1"
  },
  {
    "name": "cmd_clamped",
    "width_expr": "1"
  },
  {
    "name": "status_mode_fallback",
    "width_expr": "1"
  },
  {
    "name": "status_mode_model",
    "width_expr": "1"
  },
  {
    "name": "status_stale_rejected",
    "width_expr": "1"
  },
  {
    "name": "status_faulted",
    "width_expr": "1"
  },
  {
    "name": "status_req_id",
    "width_expr": "32"
  },
  {
    "name": "status_rsp_id",
    "width_expr": "32"
  },
  {
    "name": "status_last_accepted_req_id",
    "width_expr": "32"
  },
  {
    "name": "status_last_accepted_rsp_id",
    "width_expr": "32"
  },
  {
    "name": "status_cfg_fault",
    "width_expr": "1"
  },
  {
    "name": "status_geometry_fault",
    "width_expr": "1"
  },
  {
    "name": "status_flow_fault",
    "width_expr": "1"
  },
  {
    "name": "status_request_timeout_fault",
    "width_expr": "1"
  },
  {
    "name": "status_stale_response_fault",
    "width_expr": "1"
  },
  {
    "name": "status_response_mismatch_fault",
    "width_expr": "1"
  },
  {
    "name": "status_model_unavailable_fault",
    "width_expr": "1"
  },
  {
    "name": "status_actuator_saturation_fault",
    "width_expr": "1"
  },
  {
    "name": "telemetry_valid",
    "width_expr": "1"
  },
  {
    "name": "telemetry_mode",
    "width_expr": "2"
  },
  {
    "name": "telemetry_fault_bits",
    "width_expr": "8"
  },
  {
    "name": "telemetry_stale",
    "width_expr": "1"
  },
  {
    "name": "telemetry_req_id",
    "width_expr": "32"
  },
  {
    "name": "telemetry_rsp_id",
    "width_expr": "32"
  },
  {
    "name": "telemetry_last_clamped",
    "width_expr": "1"
  },
  {
    "name": "telemetry_last_fallback",
    "width_expr": "1"
  }
])

    if cov:
        try:
            cov.stop()
            cov.write_reports()
        except Exception:
            pass

    

    if sb:
        sb.stop()


@cocotb.test()
async def constrained_random_sanity(dut):
    """Constrained-random sanity test derived only from spec-declared inputs."""
    seed = _seed()
    random.seed(seed)

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "rst_n"):
        getattr(dut, "rst_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "rst_n"):
        getattr(dut, "rst_n").value = 1
    await Timer(5, units='ns')

    randomizable_inputs = [
  {
    "name": "host_cfg_valid",
    "width_expr": "1"
  },
  {
    "name": "host_cfg_write",
    "width_expr": "1"
  },
  {
    "name": "host_cfg_addr",
    "width_expr": "8"
  },
  {
    "name": "host_cfg_wdata",
    "width_expr": "32"
  },
  {
    "name": "enable",
    "width_expr": "1"
  },
  {
    "name": "freshness_timeout_cycles",
    "width_expr": "16"
  },
  {
    "name": "request_timeout_cycles",
    "width_expr": "16"
  },
  {
    "name": "actuator_min_limit",
    "width_expr": "16"
  },
  {
    "name": "actuator_max_limit",
    "width_expr": "16"
  },
  {
    "name": "safe_fallback_command_value",
    "width_expr": "16"
  },
  {
    "name": "stream_velocity_mps",
    "width_expr": "16"
  },
  {
    "name": "flow_update_strobe",
    "width_expr": "1"
  },
  {
    "name": "geometry_update_strobe",
    "width_expr": "1"
  },
  {
    "name": "geometry_format_selector",
    "width_expr": "8"
  },
  {
    "name": "geometry_metadata_valid",
    "width_expr": "1"
  },
  {
    "name": "geometry_metadata_tag",
    "width_expr": "16"
  },
  {
    "name": "geometry_handle_in",
    "width_expr": "32"
  },
  {
    "name": "geometry_reference_is_driaverml_stl",
    "width_expr": "1"
  },
  {
    "name": "fault_clear",
    "width_expr": "1"
  },
  {
    "name": "mode_select_fallback_when_valid",
    "width_expr": "1"
  },
  {
    "name": "model_req_ready",
    "width_expr": "1"
  },
  {
    "name": "model_rsp_valid",
    "width_expr": "1"
  },
  {
    "name": "model_rsp_id",
    "width_expr": "32"
  },
  {
    "name": "model_rsp_epoch",
    "width_expr": "32"
  },
  {
    "name": "model_rsp_status_valid",
    "width_expr": "1"
  },
  {
    "name": "model_rsp_status_unavailable",
    "width_expr": "1"
  },
  {
    "name": "model_rsp_drag_force",
    "width_expr": "32"
  },
  {
    "name": "model_rsp_lift_force",
    "width_expr": "32"
  },
  {
    "name": "model_rsp_surface_pressure",
    "width_expr": "32"
  },
  {
    "name": "model_rsp_flow_field_meta",
    "width_expr": "32"
  },
  {
    "name": "telemetry_ready",
    "width_expr": "1"
  }
]

    cov = CoverageModel() if CoverageModel else None
    if cov:
        cov.start(dut)

    for _ in range(int(os.getenv("NUM_ITERS", "25"))):
        for p in randomizable_inputs:
            name = p.get("name")
            width_expr = str(p.get("width_expr", "1"))
            if not name or not hasattr(dut, name):
                continue
            try:
                sig = getattr(dut, name)
                _safe_drive_random(sig, width_expr)
            except Exception:
                continue

        await _advance_time(dut)

        if cov:
            try:
                cov.sample()
            except Exception:
                pass

    _assert_outputs_known(dut, [
  {
    "name": "host_cfg_ready",
    "width_expr": "1"
  },
  {
    "name": "host_cfg_rdata",
    "width_expr": "32"
  },
  {
    "name": "host_cfg_rvalid",
    "width_expr": "1"
  },
  {
    "name": "model_req_valid",
    "width_expr": "1"
  },
  {
    "name": "model_req_id",
    "width_expr": "32"
  },
  {
    "name": "model_req_epoch",
    "width_expr": "32"
  },
  {
    "name": "model_req_geometry_handle",
    "width_expr": "32"
  },
  {
    "name": "model_req_stream_velocity_mps",
    "width_expr": "16"
  },
  {
    "name": "model_req_timeout_cycles",
    "width_expr": "16"
  },
  {
    "name": "actuator_cmd_valid",
    "width_expr": "1"
  },
  {
    "name": "actuator_cmd",
    "width_expr": "16"
  },
  {
    "name": "actuator_cmd_safe_fallback",
    "width_expr": "1"
  },
  {
    "name": "cmd_clamped",
    "width_expr": "1"
  },
  {
    "name": "status_mode_fallback",
    "width_expr": "1"
  },
  {
    "name": "status_mode_model",
    "width_expr": "1"
  },
  {
    "name": "status_stale_rejected",
    "width_expr": "1"
  },
  {
    "name": "status_faulted",
    "width_expr": "1"
  },
  {
    "name": "status_req_id",
    "width_expr": "32"
  },
  {
    "name": "status_rsp_id",
    "width_expr": "32"
  },
  {
    "name": "status_last_accepted_req_id",
    "width_expr": "32"
  },
  {
    "name": "status_last_accepted_rsp_id",
    "width_expr": "32"
  },
  {
    "name": "status_cfg_fault",
    "width_expr": "1"
  },
  {
    "name": "status_geometry_fault",
    "width_expr": "1"
  },
  {
    "name": "status_flow_fault",
    "width_expr": "1"
  },
  {
    "name": "status_request_timeout_fault",
    "width_expr": "1"
  },
  {
    "name": "status_stale_response_fault",
    "width_expr": "1"
  },
  {
    "name": "status_response_mismatch_fault",
    "width_expr": "1"
  },
  {
    "name": "status_model_unavailable_fault",
    "width_expr": "1"
  },
  {
    "name": "status_actuator_saturation_fault",
    "width_expr": "1"
  },
  {
    "name": "telemetry_valid",
    "width_expr": "1"
  },
  {
    "name": "telemetry_mode",
    "width_expr": "2"
  },
  {
    "name": "telemetry_fault_bits",
    "width_expr": "8"
  },
  {
    "name": "telemetry_stale",
    "width_expr": "1"
  },
  {
    "name": "telemetry_req_id",
    "width_expr": "32"
  },
  {
    "name": "telemetry_rsp_id",
    "width_expr": "32"
  },
  {
    "name": "telemetry_last_clamped",
    "width_expr": "1"
  },
  {
    "name": "telemetry_last_fallback",
    "width_expr": "1"
  }
])

    if cov:
        try:
            cov.stop()
            cov.write_reports()
        except Exception:
            pass

    

