/* Generated by Yosys 0.56 (git sha1 9c447ad9d4b1ea589369364eea38b4d70da2c599, x86_64-w64-mingw32-g++ 15.2.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

module adaptive_aero_control_top(clk, reset_n, wb_adr_i, wb_dat_i, wb_dat_o, wb_we_i, wb_stb_i, wb_cyc_i, wb_ack_o, wb_err_o, model_req_desc_o, model_req_valid_o, model_req_ready_i, model_rsp_desc_i, model_rsp_valid_i, model_rsp_ready_o, actuator_cmd_o, actuator_cmd_valid_o, fault_o, irq_o);
  output [15:0] actuator_cmd_o;
  wire [15:0] actuator_cmd_o;
  output actuator_cmd_valid_o;
  wire actuator_cmd_valid_o;
  wire cfg_allow_multi_outstanding;
  wire [15:0] cfg_clamp_max;
  wire [15:0] cfg_clamp_min;
  wire [3:0] cfg_command_mode;
  wire [15:0] cfg_fallback_cmd;
  wire [15:0] cfg_flow_handle;
  wire cfg_force_safe_mode;
  wire [15:0] cfg_geometry_handle;
  wire [15:0] cfg_oper_en_max;
  wire [15:0] cfg_oper_en_min;
  wire cfg_rate_limit_en;
  wire [15:0] cfg_rate_limit_step;
  wire [7:0] cfg_request_id;
  wire cfg_request_issue;
  wire [7:0] cfg_status_flags;
  wire [31:0] cfg_timeout_cycles;
  wire [31:0] cfg_timestamp;
  input clk;
  wire clk;
  output fault_o;
  wire fault_o;
  output irq_o;
  wire irq_o;
  wire [15:0] last_accepted_cmd_o;
  output [63:0] model_req_desc_o;
  wire [63:0] model_req_desc_o;
  input model_req_ready_i;
  wire model_req_ready_i;
  output model_req_valid_o;
  wire model_req_valid_o;
  input [63:0] model_rsp_desc_i;
  wire [63:0] model_rsp_desc_i;
  output model_rsp_ready_o;
  wire model_rsp_ready_o;
  input model_rsp_valid_i;
  wire model_rsp_valid_i;
  wire [31:0] reg_capabilities;
  wire reg_clamp_active;
  wire reg_envelope_violation;
  wire reg_fallback_active;
  wire [15:0] reg_fault_summary;
  wire reg_irq_pulse;
  wire [15:0] reg_last_accepted_cmd;
  wire [7:0] reg_outstanding_req_id;
  wire reg_pending;
  wire reg_response_received;
  wire [7:0] reg_response_req_id;
  wire reg_service_error;
  wire reg_stale_reject;
  wire [7:0] reg_state;
  wire reg_timeout_expired;
  wire [31:0] reg_version;
  input reset_n;
  wire reset_n;
  output wb_ack_o;
  wire wb_ack_o;
  input [31:0] wb_adr_i;
  wire [31:0] wb_adr_i;
  input wb_cyc_i;
  wire wb_cyc_i;
  input [31:0] wb_dat_i;
  wire [31:0] wb_dat_i;
  output [31:0] wb_dat_o;
  wire [31:0] wb_dat_o;
  output wb_err_o;
  wire wb_err_o;
  input wb_stb_i;
  wire wb_stb_i;
  input wb_we_i;
  wire wb_we_i;
  adaptive_aero_control_top_request_fsm u_fsm (
    .cfg_allow_multi_outstanding(cfg_allow_multi_outstanding),
    .cfg_command_mode(cfg_command_mode),
    .cfg_flow_handle(cfg_flow_handle),
    .cfg_force_safe_mode(cfg_force_safe_mode),
    .cfg_geometry_handle(cfg_geometry_handle),
    .cfg_oper_en_max(cfg_oper_en_max),
    .cfg_oper_en_min(cfg_oper_en_min),
    .cfg_request_id(cfg_request_id),
    .cfg_request_issue(cfg_request_issue),
    .cfg_status_flags(cfg_status_flags),
    .cfg_timeout_cycles(cfg_timeout_cycles),
    .cfg_timestamp(cfg_timestamp),
    .clk(clk),
    .model_req_desc_o(model_req_desc_o),
    .model_req_ready_i(model_req_ready_i),
    .model_req_valid_o(model_req_valid_o),
    .model_rsp_desc_i(model_rsp_desc_i),
    .model_rsp_ready_o(model_rsp_ready_o),
    .model_rsp_valid_i(model_rsp_valid_i),
    .reg_envelope_violation(reg_envelope_violation),
    .reg_fallback_active(reg_fallback_active),
    .reg_fault_summary(reg_fault_summary),
    .reg_irq_pulse(reg_irq_pulse),
    .reg_outstanding_req_id(reg_outstanding_req_id),
    .reg_pending(reg_pending),
    .reg_response_received(reg_response_received),
    .reg_response_req_id(reg_response_req_id),
    .reg_service_error(reg_service_error),
    .reg_stale_reject(reg_stale_reject),
    .reg_state(reg_state),
    .reg_timeout_expired(reg_timeout_expired),
    .reset_n(reset_n)
  );
  adaptive_aero_control_top_mmio u_mmio (
    .cfg_allow_multi_outstanding(cfg_allow_multi_outstanding),
    .cfg_clamp_max(cfg_clamp_max),
    .cfg_clamp_min(cfg_clamp_min),
    .cfg_command_mode(cfg_command_mode),
    .cfg_fallback_cmd(cfg_fallback_cmd),
    .cfg_flow_handle(cfg_flow_handle),
    .cfg_force_safe_mode(cfg_force_safe_mode),
    .cfg_geometry_handle(cfg_geometry_handle),
    .cfg_oper_en_max(cfg_oper_en_max),
    .cfg_oper_en_min(cfg_oper_en_min),
    .cfg_rate_limit_en(cfg_rate_limit_en),
    .cfg_rate_limit_step(cfg_rate_limit_step),
    .cfg_request_id(cfg_request_id),
    .cfg_request_issue(cfg_request_issue),
    .cfg_status_flags(cfg_status_flags),
    .cfg_timeout_cycles(cfg_timeout_cycles),
    .cfg_timestamp(cfg_timestamp),
    .clk(clk),
    .reg_capabilities(reg_capabilities),
    .reg_clamp_active(reg_clamp_active),
    .reg_envelope_violation(reg_envelope_violation),
    .reg_fallback_active(reg_fallback_active),
    .reg_fault_summary(reg_fault_summary),
    .reg_irq_pulse(reg_irq_pulse),
    .reg_last_accepted_cmd(reg_last_accepted_cmd),
    .reg_outstanding_req_id(reg_outstanding_req_id),
    .reg_pending(reg_pending),
    .reg_response_received(reg_response_received),
    .reg_response_req_id(reg_response_req_id),
    .reg_service_error(reg_service_error),
    .reg_stale_reject(reg_stale_reject),
    .reg_state(reg_state),
    .reg_timeout_expired(reg_timeout_expired),
    .reg_version(reg_version),
    .reset_n(reset_n),
    .wb_ack_o(wb_ack_o),
    .wb_adr_i(wb_adr_i),
    .wb_cyc_i(wb_cyc_i),
    .wb_dat_i(wb_dat_i),
    .wb_dat_o(wb_dat_o),
    .wb_err_o(wb_err_o),
    .wb_stb_i(wb_stb_i),
    .wb_we_i(wb_we_i)
  );
  adaptive_aero_control_top_actuator_safety u_safety (
    .actuator_cmd_o(actuator_cmd_o),
    .actuator_cmd_valid_o(actuator_cmd_valid_o),
    .cfg_clamp_max(cfg_clamp_max),
    .cfg_clamp_min(cfg_clamp_min),
    .cfg_fallback_cmd(cfg_fallback_cmd),
    .cfg_rate_limit_en(cfg_rate_limit_en),
    .cfg_rate_limit_step(cfg_rate_limit_step),
    .clk(clk),
    .last_accepted_cmd_o(last_accepted_cmd_o),
    .reg_clamp_active(reg_clamp_active),
    .reg_envelope_violation(reg_envelope_violation),
    .reg_fallback_active(reg_fallback_active),
    .reg_last_accepted_cmd(reg_last_accepted_cmd),
    .reg_pending(reg_pending),
    .reg_service_error(reg_service_error),
    .reg_stale_reject(reg_stale_reject),
    .reg_timeout_expired(reg_timeout_expired),
    .reset_n(reset_n),
    .selected_cmd_o(16'h0000),
    .selected_cmd_valid_o(1'h0)
  );
  assign fault_o = reg_fallback_active;
  assign irq_o = reg_irq_pulse;
endmodule

module adaptive_aero_control_top_actuator_safety(clk, reset_n, cfg_clamp_min, cfg_clamp_max, cfg_rate_limit_en, cfg_rate_limit_step, cfg_fallback_cmd, reg_fallback_active, reg_envelope_violation, reg_timeout_expired, reg_stale_reject, reg_service_error, reg_pending, selected_cmd_o, selected_cmd_valid_o, last_accepted_cmd_o, actuator_cmd_o, actuator_cmd_valid_o, reg_clamp_active, reg_last_accepted_cmd);
  wire [15:0] _00_;
  wire _01_;
  wire [15:0] _02_;
  wire _03_;
  wire [15:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire [15:0] _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire [15:0] _35_;
  wire [15:0] _36_;
  wire [15:0] _37_;
  output [15:0] actuator_cmd_o;
  wire [15:0] actuator_cmd_o;
  reg [15:0] actuator_cmd_r;
  output actuator_cmd_valid_o;
  wire actuator_cmd_valid_o;
  reg actuator_cmd_valid_r;
  wire [15:0] bounded_cmd;
  input [15:0] cfg_clamp_max;
  wire [15:0] cfg_clamp_max;
  input [15:0] cfg_clamp_min;
  wire [15:0] cfg_clamp_min;
  input [15:0] cfg_fallback_cmd;
  wire [15:0] cfg_fallback_cmd;
  input cfg_rate_limit_en;
  wire cfg_rate_limit_en;
  input [15:0] cfg_rate_limit_step;
  wire [15:0] cfg_rate_limit_step;
  wire clamp_high;
  wire clamp_low;
  wire [15:0] clamp_max_eff;
  wire [15:0] clamp_min_eff;
  input clk;
  wire clk;
  wire [15:0] delta_down;
  wire [15:0] delta_up;
  wire fault_mode;
  output [15:0] last_accepted_cmd_o;
  wire [15:0] last_accepted_cmd_o;
  reg [15:0] last_accepted_cmd_r;
  wire [15:0] pre_clamped_cmd;
  wire [15:0] rate_limited_cmd;
  wire [15:0] rate_step_eff;
  output reg_clamp_active;
  wire reg_clamp_active;
  reg reg_clamp_active_r;
  input reg_envelope_violation;
  wire reg_envelope_violation;
  input reg_fallback_active;
  wire reg_fallback_active;
  output [15:0] reg_last_accepted_cmd;
  wire [15:0] reg_last_accepted_cmd;
  input reg_pending;
  wire reg_pending;
  input reg_service_error;
  wire reg_service_error;
  input reg_stale_reject;
  wire reg_stale_reject;
  input reg_timeout_expired;
  wire reg_timeout_expired;
  input reset_n;
  wire reset_n;
  input [15:0] selected_cmd_o;
  wire [15:0] selected_cmd_o;
  input selected_cmd_valid_o;
  wire selected_cmd_valid_o;
  wire step_down;
  wire step_up;
  assign _04_ = last_accepted_cmd_r + rate_step_eff;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) last_accepted_cmd_r <= 16'h0000;
    else if (_05_) last_accepted_cmd_r <= _02_;
  assign _05_ = { _16_, _23_ } != 2'h1;
  assign _06_ = ! cfg_rate_limit_step;
  assign _07_ = delta_up > rate_step_eff;
  assign _08_ = selected_cmd_o > last_accepted_cmd_r;
  assign _09_ = delta_down > rate_step_eff;
  assign _10_ = pre_clamped_cmd > cfg_clamp_max;
  assign clamp_high = selected_cmd_o > cfg_clamp_max;
  assign step_up = _08_ && _07_;
  assign step_down = _24_ && _09_;
  assign _11_ = ! selected_cmd_valid_o;
  assign _12_ = ! reg_pending;
  assign _13_ = reg_fallback_active || reg_envelope_violation;
  assign _14_ = _13_ || reg_timeout_expired;
  assign _15_ = _14_ || reg_stale_reject;
  assign _16_ = _15_ || reg_service_error;
  assign _17_ = _25_ || clamp_low;
  assign _18_ = _17_ || clamp_high;
  assign _19_ = _18_ || step_up;
  assign _20_ = _19_ || step_down;
  assign _21_ = clamp_low || clamp_high;
  assign _22_ = fault_mode || _11_;
  assign _23_ = _22_ || _12_;
  assign _24_ = selected_cmd_o < last_accepted_cmd_r;
  assign clamp_low = selected_cmd_o < cfg_clamp_min;
  assign _25_ = rate_limited_cmd != selected_cmd_o;
  assign _26_ = cfg_fallback_cmd != last_accepted_cmd_r;
  assign _27_ = reg_fallback_active | reg_envelope_violation;
  assign _28_ = _27_ | reg_timeout_expired;
  assign _29_ = _28_ | reg_stale_reject;
  assign fault_mode = _29_ | reg_service_error;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) actuator_cmd_r <= 16'h0000;
    else actuator_cmd_r <= _00_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) actuator_cmd_valid_r <= 1'h0;
    else actuator_cmd_valid_r <= _01_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) reg_clamp_active_r <= 1'h0;
    else reg_clamp_active_r <= _03_;
  assign _01_ = _23_ ? selected_cmd_valid_o : 1'h1;
  assign _30_ = cfg_rate_limit_en ? rate_limited_cmd : bounded_cmd;
  assign _00_ = _23_ ? cfg_fallback_cmd : _30_;
  assign _31_ = _21_ ? 1'h1 : 1'h0;
  assign _32_ = _20_ ? 1'h1 : 1'h0;
  assign _33_ = cfg_rate_limit_en ? _32_ : _31_;
  assign _34_ = _26_ ? 1'h1 : 1'h0;
  assign _03_ = _23_ ? _34_ : _33_;
  assign _35_ = _16_ ? cfg_fallback_cmd : 16'hxxxx;
  assign _02_ = _23_ ? _35_ : actuator_cmd_r;
  assign delta_up = selected_cmd_o - last_accepted_cmd_r;
  assign delta_down = last_accepted_cmd_r - selected_cmd_o;
  assign _36_ = last_accepted_cmd_r - rate_step_eff;
  assign rate_step_eff = _06_ ? 16'h0001 : cfg_rate_limit_step;
  assign pre_clamped_cmd = clamp_low ? cfg_clamp_min : selected_cmd_o;
  assign bounded_cmd = _10_ ? cfg_clamp_max : pre_clamped_cmd;
  assign rate_limited_cmd = step_up ? _04_ : _37_;
  assign _37_ = step_down ? _36_ : bounded_cmd;
  assign actuator_cmd_o = actuator_cmd_r;
  assign actuator_cmd_valid_o = actuator_cmd_valid_r;
  assign clamp_max_eff = cfg_clamp_max;
  assign clamp_min_eff = cfg_clamp_min;
  assign last_accepted_cmd_o = last_accepted_cmd_r;
  assign reg_clamp_active = reg_clamp_active_r;
  assign reg_last_accepted_cmd = last_accepted_cmd_r;
endmodule

module adaptive_aero_control_top_mmio(clk, reset_n, wb_adr_i, wb_dat_i, wb_dat_o, wb_we_i, wb_stb_i, wb_cyc_i, wb_ack_o, wb_err_o, cfg_oper_en_min, cfg_oper_en_max, cfg_timeout_cycles, cfg_clamp_min, cfg_clamp_max, cfg_rate_limit_en, cfg_rate_limit_step, cfg_fallback_cmd, cfg_force_safe_mode, cfg_allow_multi_outstanding, cfg_request_issue
, cfg_request_id, cfg_geometry_handle, cfg_flow_handle, cfg_timestamp, cfg_command_mode, cfg_status_flags, reg_version, reg_capabilities, reg_state, reg_fault_summary, reg_outstanding_req_id, reg_response_req_id, reg_last_accepted_cmd, reg_pending, reg_response_received, reg_stale_reject, reg_timeout_expired, reg_clamp_active, reg_fallback_active, reg_envelope_violation, reg_service_error
, reg_irq_pulse);
  wire [31:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire access;
  wire [7:0] addr_word;
  output cfg_allow_multi_outstanding;
  wire cfg_allow_multi_outstanding;
  output [15:0] cfg_clamp_max;
  wire [15:0] cfg_clamp_max;
  output [15:0] cfg_clamp_min;
  wire [15:0] cfg_clamp_min;
  output [3:0] cfg_command_mode;
  wire [3:0] cfg_command_mode;
  output [15:0] cfg_fallback_cmd;
  wire [15:0] cfg_fallback_cmd;
  output [15:0] cfg_flow_handle;
  wire [15:0] cfg_flow_handle;
  output cfg_force_safe_mode;
  wire cfg_force_safe_mode;
  output [15:0] cfg_geometry_handle;
  wire [15:0] cfg_geometry_handle;
  output [15:0] cfg_oper_en_max;
  wire [15:0] cfg_oper_en_max;
  output [15:0] cfg_oper_en_min;
  wire [15:0] cfg_oper_en_min;
  output cfg_rate_limit_en;
  wire cfg_rate_limit_en;
  output [15:0] cfg_rate_limit_step;
  wire [15:0] cfg_rate_limit_step;
  output [7:0] cfg_request_id;
  wire [7:0] cfg_request_id;
  output cfg_request_issue;
  wire cfg_request_issue;
  output [7:0] cfg_status_flags;
  wire [7:0] cfg_status_flags;
  output [31:0] cfg_timeout_cycles;
  wire [31:0] cfg_timeout_cycles;
  output [31:0] cfg_timestamp;
  wire [31:0] cfg_timestamp;
  input clk;
  wire clk;
  wire illegal_addr;
  reg r_allow_multi_outstanding;
  reg [15:0] r_clamp_max;
  reg [15:0] r_clamp_min;
  reg [3:0] r_command_mode;
  reg [15:0] r_fallback_cmd;
  reg [15:0] r_flow_handle;
  reg r_force_safe_mode;
  reg [15:0] r_geometry_handle;
  reg [15:0] r_oper_en_max;
  reg [15:0] r_oper_en_min;
  reg r_rate_limit_en;
  reg [15:0] r_rate_limit_step;
  reg [7:0] r_request_id;
  reg r_request_issue;
  reg [7:0] r_status_flags;
  reg [31:0] r_timeout_cycles;
  reg [31:0] r_timestamp;
  output [31:0] reg_capabilities;
  wire [31:0] reg_capabilities;
  input reg_clamp_active;
  wire reg_clamp_active;
  input reg_envelope_violation;
  wire reg_envelope_violation;
  input reg_fallback_active;
  wire reg_fallback_active;
  input [15:0] reg_fault_summary;
  wire [15:0] reg_fault_summary;
  input reg_irq_pulse;
  wire reg_irq_pulse;
  input [15:0] reg_last_accepted_cmd;
  wire [15:0] reg_last_accepted_cmd;
  input [7:0] reg_outstanding_req_id;
  wire [7:0] reg_outstanding_req_id;
  input reg_pending;
  wire reg_pending;
  input reg_response_received;
  wire reg_response_received;
  input [7:0] reg_response_req_id;
  wire [7:0] reg_response_req_id;
  input reg_service_error;
  wire reg_service_error;
  input reg_stale_reject;
  wire reg_stale_reject;
  input [7:0] reg_state;
  wire [7:0] reg_state;
  input reg_timeout_expired;
  wire reg_timeout_expired;
  output [31:0] reg_version;
  wire [31:0] reg_version;
  input reset_n;
  wire reset_n;
  output wb_ack_o;
  wire wb_ack_o;
  reg wb_ack_o_r;
  input [31:0] wb_adr_i;
  wire [31:0] wb_adr_i;
  input wb_cyc_i;
  wire wb_cyc_i;
  input [31:0] wb_dat_i;
  wire [31:0] wb_dat_i;
  output [31:0] wb_dat_o;
  wire [31:0] wb_dat_o;
  reg [31:0] wb_dat_o_r;
  output wb_err_o;
  wire wb_err_o;
  reg wb_err_o_r;
  input wb_stb_i;
  wire wb_stb_i;
  input wb_we_i;
  wire wb_we_i;
  wire write_access;
  assign access = wb_cyc_i & wb_stb_i;
  assign write_access = access & wb_we_i;
  assign _001_ = access & illegal_addr;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_timestamp <= 32'd0;
    else if (_002_) r_timestamp <= wb_dat_i;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_oper_en_max <= 16'hffff;
    else if (_003_) r_oper_en_max <= wb_dat_i[15:0];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_fallback_cmd <= 16'h0000;
    else if (_004_) r_fallback_cmd <= wb_dat_i[15:0];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_request_issue <= 1'h0;
    else if (_005_) r_request_issue <= wb_dat_i[0];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_timeout_cycles <= 32'd50000;
    else if (_006_) r_timeout_cycles <= wb_dat_i;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_command_mode <= 4'h0;
    else if (_007_) r_command_mode <= wb_dat_i[19:16];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_clamp_min <= 16'h0000;
    else if (_008_) r_clamp_min <= wb_dat_i[15:0];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_force_safe_mode <= 1'h0;
    else if (_009_) r_force_safe_mode <= wb_dat_i[1];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_flow_handle <= 16'h0000;
    else if (_007_) r_flow_handle <= wb_dat_i[15:0];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_clamp_max <= 16'hffff;
    else if (_010_) r_clamp_max <= wb_dat_i[15:0];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_geometry_handle <= 16'h0000;
    else if (_011_) r_geometry_handle <= wb_dat_i[31:16];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_status_flags <= 8'h00;
    else if (_007_) r_status_flags <= wb_dat_i[31:24];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_rate_limit_en <= 1'h0;
    else if (_009_) r_rate_limit_en <= wb_dat_i[3];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_allow_multi_outstanding <= 1'h0;
    else if (_009_) r_allow_multi_outstanding <= wb_dat_i[2];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_rate_limit_step <= 16'h0010;
    else if (_012_) r_rate_limit_step <= wb_dat_i[15:0];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_request_id <= 8'h00;
    else if (_011_) r_request_id <= wb_dat_i[15:8];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) r_oper_en_min <= 16'h0000;
    else if (_013_) r_oper_en_min <= wb_dat_i[15:0];
  assign _002_ = & { _057_, write_access };
  assign _003_ = & { _065_, write_access };
  assign _004_ = & { _060_, write_access };
  assign _005_ = & { _014_, write_access };
  assign _006_ = & { _064_, write_access };
  assign _007_ = & { _058_, write_access };
  assign _008_ = & { _063_, write_access };
  assign _009_ = & { _067_, write_access };
  assign _010_ = & { _062_, write_access };
  assign _011_ = & { _059_, write_access };
  assign _012_ = & { _061_, write_access };
  assign _013_ = & { _066_, write_access };
  assign _014_ = | { _067_, _059_ };
  assign _015_ = _032_ && _033_;
  assign _016_ = _015_ && _034_;
  assign _017_ = _016_ && _035_;
  assign _018_ = _017_ && _036_;
  assign _019_ = _018_ && _037_;
  assign _020_ = _019_ && _038_;
  assign _021_ = _020_ && _039_;
  assign _022_ = _021_ && _040_;
  assign _023_ = _022_ && _041_;
  assign _024_ = _023_ && _042_;
  assign _025_ = _024_ && _043_;
  assign _026_ = _025_ && _044_;
  assign _027_ = _026_ && _045_;
  assign _028_ = _027_ && _046_;
  assign _029_ = _028_ && _047_;
  assign _030_ = _029_ && _048_;
  assign _031_ = _030_ && _049_;
  assign illegal_addr = _031_ && _050_;
  assign _032_ = | wb_adr_i[7:0];
  assign _033_ = wb_adr_i[7:0] != 8'h04;
  assign _034_ = wb_adr_i[7:0] != 8'h08;
  assign _035_ = wb_adr_i[7:0] != 8'h0c;
  assign _036_ = wb_adr_i[7:0] != 8'h10;
  assign _037_ = wb_adr_i[7:0] != 8'h14;
  assign _038_ = wb_adr_i[7:0] != 8'h18;
  assign _039_ = wb_adr_i[7:0] != 8'h1c;
  assign _040_ = wb_adr_i[7:0] != 8'h20;
  assign _041_ = wb_adr_i[7:0] != 8'h24;
  assign _042_ = wb_adr_i[7:0] != 8'h28;
  assign _043_ = wb_adr_i[7:0] != 8'h2c;
  assign _044_ = wb_adr_i[7:0] != 8'h30;
  assign _045_ = wb_adr_i[7:0] != 8'h34;
  assign _046_ = wb_adr_i[7:0] != 8'h38;
  assign _047_ = wb_adr_i[7:0] != 8'h3c;
  assign _048_ = wb_adr_i[7:0] != 8'h40;
  assign _049_ = wb_adr_i[7:0] != 8'h44;
  assign _050_ = wb_adr_i[7:0] != 8'h48;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) wb_dat_o_r <= 32'd0;
    else wb_dat_o_r <= _000_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) wb_ack_o_r <= 1'h0;
    else wb_ack_o_r <= access;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) wb_err_o_r <= 1'h0;
    else wb_err_o_r <= _001_;
  function [31:0] _143_;
    input [31:0] a;
    input [607:0] b;
    input [18:0] s;
    casez (s) // synopsys parallel_case
      19'b??????????????????1:
        _143_ = b[31:0];
      19'b?????????????????1?:
        _143_ = b[63:32];
      19'b????????????????1??:
        _143_ = b[95:64];
      19'b???????????????1???:
        _143_ = b[127:96];
      19'b??????????????1????:
        _143_ = b[159:128];
      19'b?????????????1?????:
        _143_ = b[191:160];
      19'b????????????1??????:
        _143_ = b[223:192];
      19'b???????????1???????:
        _143_ = b[255:224];
      19'b??????????1????????:
        _143_ = b[287:256];
      19'b?????????1?????????:
        _143_ = b[319:288];
      19'b????????1??????????:
        _143_ = b[351:320];
      19'b???????1???????????:
        _143_ = b[383:352];
      19'b??????1????????????:
        _143_ = b[415:384];
      19'b?????1?????????????:
        _143_ = b[447:416];
      19'b????1??????????????:
        _143_ = b[479:448];
      19'b???1???????????????:
        _143_ = b[511:480];
      19'b??1????????????????:
        _143_ = b[543:512];
      19'b?1?????????????????:
        _143_ = b[575:544];
      19'b1??????????????????:
        _143_ = b[607:576];
      default:
        _143_ = a;
    endcase
  endfunction
  assign _000_ = _143_(32'd0, { 92'h000100000000001f0000000, r_rate_limit_en, r_allow_multi_outstanding, r_force_safe_mode, r_request_issue, 16'h0000, r_oper_en_min, 16'h0000, r_oper_en_max, r_timeout_cycles, 16'h0000, r_clamp_min, 16'h0000, r_clamp_max, 16'h0000, r_rate_limit_step, 16'h0000, r_fallback_cmd, 8'h00, r_request_id, r_geometry_handle, r_status_flags, 4'h0, r_command_mode, r_flow_handle, r_timestamp, 16'h0000, reg_service_error, reg_envelope_violation, reg_fallback_active, reg_clamp_active, reg_timeout_expired, reg_stale_reject, reg_response_received, reg_pending, reg_state, 24'h000000, reg_outstanding_req_id, 24'h000000, reg_response_req_id, 16'h0000, reg_last_accepted_cmd, 16'h0000, reg_fault_summary, 31'h00000000, reg_irq_pulse }, { _069_, _068_, _067_, _066_, _065_, _064_, _063_, _062_, _061_, _060_, _059_, _058_, _057_, _056_, _055_, _054_, _053_, _052_, _051_ });
  assign _051_ = wb_adr_i[7:0] == 8'h48;
  assign _052_ = wb_adr_i[7:0] == 8'h44;
  assign _053_ = wb_adr_i[7:0] == 8'h40;
  assign _054_ = wb_adr_i[7:0] == 8'h3c;
  assign _055_ = wb_adr_i[7:0] == 8'h38;
  assign _056_ = wb_adr_i[7:0] == 8'h34;
  assign _068_ = wb_adr_i[7:0] == 8'h04;
  assign _069_ = ! wb_adr_i[7:0];
  assign _057_ = wb_adr_i[7:0] == 8'h30;
  assign _058_ = wb_adr_i[7:0] == 8'h2c;
  assign _059_ = wb_adr_i[7:0] == 8'h28;
  assign _060_ = wb_adr_i[7:0] == 8'h24;
  assign _061_ = wb_adr_i[7:0] == 8'h20;
  assign _067_ = wb_adr_i[7:0] == 8'h08;
  assign _062_ = wb_adr_i[7:0] == 8'h1c;
  assign _063_ = wb_adr_i[7:0] == 8'h18;
  assign _064_ = wb_adr_i[7:0] == 8'h14;
  assign _065_ = wb_adr_i[7:0] == 8'h10;
  assign _066_ = wb_adr_i[7:0] == 8'h0c;
  assign addr_word = wb_adr_i[7:0];
  assign cfg_allow_multi_outstanding = r_allow_multi_outstanding;
  assign cfg_clamp_max = r_clamp_max;
  assign cfg_clamp_min = r_clamp_min;
  assign cfg_command_mode = r_command_mode;
  assign cfg_fallback_cmd = r_fallback_cmd;
  assign cfg_flow_handle = r_flow_handle;
  assign cfg_force_safe_mode = r_force_safe_mode;
  assign cfg_geometry_handle = r_geometry_handle;
  assign cfg_oper_en_max = r_oper_en_max;
  assign cfg_oper_en_min = r_oper_en_min;
  assign cfg_rate_limit_en = r_rate_limit_en;
  assign cfg_rate_limit_step = r_rate_limit_step;
  assign cfg_request_id = r_request_id;
  assign cfg_request_issue = r_request_issue;
  assign cfg_status_flags = r_status_flags;
  assign cfg_timeout_cycles = r_timeout_cycles;
  assign cfg_timestamp = r_timestamp;
  assign reg_capabilities = 32'd31;
  assign reg_version = 32'd65536;
  assign wb_ack_o = wb_ack_o_r;
  assign wb_dat_o = wb_dat_o_r;
  assign wb_err_o = wb_err_o_r;
endmodule

module adaptive_aero_control_top_request_fsm(clk, reset_n, cfg_request_issue, cfg_allow_multi_outstanding, cfg_request_id, cfg_geometry_handle, cfg_flow_handle, cfg_timestamp, cfg_command_mode, cfg_status_flags, cfg_timeout_cycles, cfg_force_safe_mode, cfg_oper_en_min, cfg_oper_en_max, model_req_desc_o, model_req_valid_o, model_req_ready_i, model_rsp_desc_i, model_rsp_valid_i, model_rsp_ready_o, reg_state
, reg_fault_summary, reg_outstanding_req_id, reg_response_req_id, reg_pending, reg_response_received, reg_stale_reject, reg_timeout_expired, reg_envelope_violation, reg_service_error, reg_fallback_active, reg_irq_pulse, selected_cmd_o, selected_cmd_valid_o);
  wire [31:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire [7:0] _004_;
  wire [15:0] _005_;
  wire _006_;
  wire [31:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire [7:0] _013_;
  wire [15:0] _014_;
  wire _015_;
  wire [31:0] _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire [7:0] _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire [7:0] _026_;
  wire _027_;
  wire [7:0] _028_;
  wire _029_;
  wire [15:0] _030_;
  wire [7:0] _031_;
  wire [7:0] _032_;
  wire [31:0] _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  reg [31:0] age_counter_r;
  input cfg_allow_multi_outstanding;
  wire cfg_allow_multi_outstanding;
  input [3:0] cfg_command_mode;
  wire [3:0] cfg_command_mode;
  input [15:0] cfg_flow_handle;
  wire [15:0] cfg_flow_handle;
  input cfg_force_safe_mode;
  wire cfg_force_safe_mode;
  input [15:0] cfg_geometry_handle;
  wire [15:0] cfg_geometry_handle;
  input [15:0] cfg_oper_en_max;
  wire [15:0] cfg_oper_en_max;
  input [15:0] cfg_oper_en_min;
  wire [15:0] cfg_oper_en_min;
  input [7:0] cfg_request_id;
  wire [7:0] cfg_request_id;
  input cfg_request_issue;
  wire cfg_request_issue;
  input [7:0] cfg_status_flags;
  wire [7:0] cfg_status_flags;
  input [31:0] cfg_timeout_cycles;
  wire [31:0] cfg_timeout_cycles;
  input [31:0] cfg_timestamp;
  wire [31:0] cfg_timestamp;
  input clk;
  wire clk;
  wire [15:0] cmd_raw;
  wire envelope_bad;
  reg envelope_violation_r;
  reg fallback_active_r;
  wire [15:0] fault_summary_r;
  reg irq_pulse_r;
  wire issue_req;
  output [63:0] model_req_desc_o;
  wire [63:0] model_req_desc_o;
  wire [63:0] model_req_desc_r;
  input model_req_ready_i;
  wire model_req_ready_i;
  output model_req_valid_o;
  wire model_req_valid_o;
  wire model_req_valid_r;
  input [63:0] model_rsp_desc_i;
  wire [63:0] model_rsp_desc_i;
  output model_rsp_ready_o;
  wire model_rsp_ready_o;
  wire model_rsp_ready_r;
  input model_rsp_valid_i;
  wire model_rsp_valid_i;
  wire [31:0] next_age_counter;
  wire next_envelope_violation;
  wire next_fallback_active;
  wire [15:0] next_fault_summary;
  wire next_irq_pulse;
  wire next_pending;
  wire next_response_received;
  wire next_service_error;
  wire next_stale_reject;
  wire [7:0] next_state;
  reg [7:0] outstanding_req_id_r;
  reg pending_r;
  output reg_envelope_violation;
  wire reg_envelope_violation;
  output reg_fallback_active;
  wire reg_fallback_active;
  output [15:0] reg_fault_summary;
  wire [15:0] reg_fault_summary;
  output reg_irq_pulse;
  wire reg_irq_pulse;
  output [7:0] reg_outstanding_req_id;
  wire [7:0] reg_outstanding_req_id;
  output reg_pending;
  wire reg_pending;
  output reg_response_received;
  wire reg_response_received;
  output [7:0] reg_response_req_id;
  wire [7:0] reg_response_req_id;
  output reg_service_error;
  wire reg_service_error;
  output reg_stale_reject;
  wire reg_stale_reject;
  output [7:0] reg_state;
  wire [7:0] reg_state;
  output reg_timeout_expired;
  wire reg_timeout_expired;
  wire [63:0] req_desc_comb;
  input reset_n;
  wire reset_n;
  reg response_received_r;
  reg [7:0] response_req_id_r;
  wire [15:0] selected_cmd_next;
  output [15:0] selected_cmd_o;
  wire [15:0] selected_cmd_o;
  reg [15:0] selected_cmd_r;
  wire selected_cmd_valid_next;
  output selected_cmd_valid_o;
  wire selected_cmd_valid_o;
  reg selected_cmd_valid_r;
  reg service_error_r;
  wire stale_reject_r;
  reg [7:0] state_r;
  wire timeout_bad;
  reg timeout_expired_r;
  assign _033_ = age_counter_r + 32'd1;
  reg [12:0] _059_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) _059_ <= 13'h0000;
    else if (model_rsp_valid_i) _059_ <= { _030_[15:5], _012_, _012_ };
  assign { fault_summary_r[15:4], fault_summary_r[1] } = _059_;
  reg [2:0] _060_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) _060_ <= 3'h0;
    else _060_ <= { next_fault_summary[3:2], next_fault_summary[0] };
  assign { fault_summary_r[3:2], fault_summary_r[0] } = _060_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) outstanding_req_id_r <= 8'h00;
    else if (_052_) outstanding_req_id_r <= cfg_request_id;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) response_req_id_r <= 8'h00;
    else if (model_rsp_valid_i) response_req_id_r <= model_rsp_desc_i[7:0];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) selected_cmd_r <= 16'h0000;
    else if (_038_) selected_cmd_r <= selected_cmd_next;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) pending_r <= 1'h0;
    else if (_039_) pending_r <= next_pending;
  reg [55:0] _065_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) _065_ <= 56'h00000000000000;
    else _065_ <= { cfg_timestamp, cfg_geometry_handle[15:8], cfg_flow_handle[15:8], cfg_request_id };
  assign model_req_desc_r[55:0] = _065_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) timeout_expired_r <= 1'h0;
    else if (_040_) timeout_expired_r <= 1'h1;
  assign _034_ = | { _043_, model_rsp_valid_i };
  assign _035_ = | { _043_, _049_ };
  assign _036_ = | { _052_, _041_, envelope_bad, cfg_force_safe_mode, model_rsp_valid_i };
  assign _037_ = | { _052_, _046_, envelope_bad, cfg_force_safe_mode, model_rsp_valid_i };
  assign _038_ = & { _034_, _035_ };
  assign _039_ = & { _037_, _036_ };
  assign _040_ = & { _046_, _041_ };
  assign _041_ = state_r == 8'h01;
  assign _042_ = model_rsp_desc_i[7:0] == outstanding_req_id_r;
  assign _043_ = _032_ == 8'h03;
  assign _044_ = _032_ == 8'h02;
  assign _045_ = age_counter_r >= cfg_timeout_cycles;
  assign envelope_bad = cfg_oper_en_min > cfg_oper_en_max;
  assign _046_ = _057_ && _045_;
  assign _047_ = _042_ && _053_;
  assign _048_ = _047_ && _054_;
  assign _049_ = _048_ && _055_;
  assign _050_ = cfg_request_issue && _056_;
  assign _051_ = _050_ && _055_;
  assign _052_ = _051_ && _054_;
  assign _053_ = ! timeout_bad;
  assign _056_ = ! pending_r;
  assign _055_ = ! cfg_force_safe_mode;
  assign _054_ = ! envelope_bad;
  assign _057_ = | cfg_timeout_cycles;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) state_r <= 8'h00;
    else state_r <= next_state;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) response_received_r <= 1'h0;
    else response_received_r <= next_response_received;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) envelope_violation_r <= 1'h0;
    else envelope_violation_r <= next_envelope_violation;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) service_error_r <= 1'h0;
    else service_error_r <= next_service_error;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) fallback_active_r <= 1'h0;
    else fallback_active_r <= next_fallback_active;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) irq_pulse_r <= 1'h0;
    else irq_pulse_r <= next_irq_pulse;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) selected_cmd_valid_r <= 1'h0;
    else selected_cmd_valid_r <= selected_cmd_valid_next;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) age_counter_r <= 32'd0;
    else age_counter_r <= next_age_counter;
  assign next_state = _044_ ? 8'h00 : _032_;
  assign selected_cmd_next = _043_ ? 16'h0000 : _005_;
  assign selected_cmd_valid_next = _043_ ? 1'h0 : _006_;
  assign next_age_counter = _052_ ? 32'd0 : _007_;
  assign _032_ = _052_ ? 8'h01 : _028_;
  assign next_pending = _052_ ? 1'h1 : _027_;
  assign _030_[15:5] = _049_ ? 11'h000 : fault_summary_r[15:5];
  assign _030_[3:2] = _049_ ? 2'h0 : { _018_, _023_ };
  assign _030_[0] = _049_ ? 1'h0 : _002_;
  assign _016_ = _049_ ? 32'd0 : _000_;
  assign _015_ = _049_ ? 1'h1 : 1'h0;
  assign _014_ = _049_ ? model_rsp_desc_i[31:16] : 16'hxxxx;
  assign _031_ = _049_ ? 8'h02 : 8'h03;
  assign _029_ = _049_ ? _022_ : 1'h1;
  assign _012_ = _049_ ? 1'h0 : 1'h1;
  assign next_fault_summary = model_rsp_valid_i ? { _030_[15:5], _012_, _030_[3:2], _012_, _030_[0] } : { fault_summary_r[15:4], _018_, _023_, fault_summary_r[1], _002_ };
  assign _007_ = model_rsp_valid_i ? _016_ : _000_;
  assign next_irq_pulse = model_rsp_valid_i ? 1'h1 : _024_;
  assign next_fallback_active = model_rsp_valid_i ? _029_ : _022_;
  assign next_service_error = model_rsp_valid_i ? _012_ : 1'h0;
  assign _027_ = model_rsp_valid_i ? 1'h0 : _025_;
  assign _028_ = model_rsp_valid_i ? _031_ : _026_;
  assign _006_ = model_rsp_valid_i ? _015_ : 1'h0;
  assign _005_ = model_rsp_valid_i ? _014_ : 16'hxxxx;
  assign next_response_received = model_rsp_valid_i ? _049_ : 1'h0;
  assign _023_ = envelope_bad ? 1'h1 : fault_summary_r[2];
  assign _024_ = envelope_bad ? 1'h1 : _019_;
  assign _025_ = envelope_bad ? 1'h0 : _020_;
  assign _026_ = envelope_bad ? 8'h03 : _021_;
  assign _022_ = envelope_bad ? 1'h1 : _017_;
  assign next_envelope_violation = envelope_bad ? 1'h1 : 1'h0;
  assign _018_ = cfg_force_safe_mode ? 1'h1 : fault_summary_r[3];
  assign _020_ = cfg_force_safe_mode ? 1'h0 : _003_;
  assign _021_ = cfg_force_safe_mode ? 8'h03 : _004_;
  assign _019_ = cfg_force_safe_mode ? 1'h1 : timeout_bad;
  assign _017_ = cfg_force_safe_mode ? 1'h1 : _001_;
  assign _009_ = _046_ ? 1'h1 : fault_summary_r[0];
  assign _011_ = _046_ ? 1'h0 : 1'hx;
  assign _013_ = _046_ ? 8'h03 : state_r;
  assign _008_ = _046_ ? 1'h1 : fallback_active_r;
  assign _010_ = _046_ ? 1'h1 : 1'h0;
  assign timeout_bad = _041_ ? _010_ : 1'h0;
  assign _002_ = _041_ ? _009_ : fault_summary_r[0];
  assign _001_ = _041_ ? _008_ : fallback_active_r;
  assign _003_ = _041_ ? _011_ : 1'hx;
  assign _004_ = _041_ ? _013_ : state_r;
  assign _000_ = _041_ ? _033_ : age_counter_r;
  assign { _030_[4], _030_[1] } = { _012_, _012_ };
  assign cmd_raw = { cfg_oper_en_min[7:0], cfg_oper_en_max[7:0] };
  assign issue_req = cfg_request_issue;
  assign model_req_desc_o = { 8'h00, model_req_desc_r[55:0] };
  assign model_req_desc_r[63:56] = 8'h00;
  assign model_req_valid_o = 1'h0;
  assign model_req_valid_r = 1'h0;
  assign model_rsp_ready_o = 1'h1;
  assign model_rsp_ready_r = 1'h1;
  assign next_stale_reject = next_service_error;
  assign reg_envelope_violation = envelope_violation_r;
  assign reg_fallback_active = fallback_active_r;
  assign reg_fault_summary = fault_summary_r;
  assign reg_irq_pulse = irq_pulse_r;
  assign reg_outstanding_req_id = outstanding_req_id_r;
  assign reg_pending = pending_r;
  assign reg_response_received = response_received_r;
  assign reg_response_req_id = response_req_id_r;
  assign reg_service_error = service_error_r;
  assign reg_stale_reject = service_error_r;
  assign reg_state = state_r;
  assign reg_timeout_expired = timeout_expired_r;
  assign req_desc_comb = { 8'h00, cfg_timestamp, cfg_geometry_handle[15:8], cfg_flow_handle[15:8], cfg_request_id };
  assign selected_cmd_o = selected_cmd_r;
  assign selected_cmd_valid_o = selected_cmd_valid_r;
  assign stale_reject_r = service_error_r;
endmodule

module adaptive_aero_control_top_spi_fpga_top(clk, reset_n, spi_sclk, spi_cs_n, spi_mosi, spi_miso, fault_indicator);
  wire _00_;
  wire _01_;
  wire [118:0] _02_;
  input clk;
  wire clk;
  wire [15:0] core_actuator_cmd_o;
  wire core_actuator_cmd_valid_o;
  wire core_fault_o;
  wire core_irq_o;
  wire [63:0] core_model_req_desc_o;
  wire core_model_req_ready_i;
  wire core_model_req_valid_o;
  wire [63:0] core_model_rsp_desc_i;
  wire core_model_rsp_ready_o;
  wire core_model_rsp_valid_i;
  wire [118:0] core_response;
  wire core_wb_ack_o;
  wire [31:0] core_wb_adr_i;
  wire core_wb_cyc_i;
  wire [31:0] core_wb_dat_i;
  wire [31:0] core_wb_dat_o;
  wire core_wb_err_o;
  wire core_wb_stb_i;
  wire core_wb_we_i;
  output fault_indicator;
  wire fault_indicator;
  input reset_n;
  wire reset_n;
  reg [132:0] rx_active;
  reg [132:0] rx_shift;
  reg spi_active;
  reg spi_cs_meta;
  input spi_cs_n;
  wire spi_cs_n;
  reg spi_cs_prev;
  reg spi_cs_sync;
  output spi_miso;
  wire spi_miso;
  input spi_mosi;
  wire spi_mosi;
  input spi_sclk;
  wire spi_sclk;
  reg [118:0] tx_shift;
  reg [118:0] tx_snapshot;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) rx_active <= 133'h0000000000000000000000000000000000;
    else if (_00_) rx_active <= rx_shift;
  always @(posedge spi_sclk)
    if (!spi_cs_n) rx_shift <= { rx_shift[131:0], spi_mosi };
  always @(posedge spi_sclk)
    if (!spi_cs_n) tx_shift <= _02_;
  assign _00_ = spi_cs_sync && _01_;
  assign _01_ = ! spi_cs_prev;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) tx_snapshot <= 119'h000000000000000000000000000000;
    else tx_snapshot <= { core_wb_dat_o, core_wb_ack_o, core_wb_err_o, core_model_req_desc_o, core_model_req_valid_o, core_model_rsp_ready_o, core_actuator_cmd_o, core_actuator_cmd_valid_o, core_fault_o, core_irq_o };
  always @(posedge clk, negedge reset_n)
    if (!reset_n) spi_cs_meta <= 1'h1;
    else spi_cs_meta <= spi_cs_n;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) spi_cs_sync <= 1'h1;
    else spi_cs_sync <= spi_cs_meta;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) spi_cs_prev <= 1'h1;
    else spi_cs_prev <= spi_cs_sync;
  always @(posedge spi_sclk, posedge spi_cs_n)
    if (spi_cs_n) spi_active <= 1'h0;
    else spi_active <= 1'h1;
  assign _02_ = spi_active ? { tx_shift[117:0], 1'h0 } : { tx_snapshot[117:0], 1'h0 };
  assign spi_miso = spi_active ? tx_shift[118] : tx_snapshot[118];
  adaptive_aero_control_top u_core (
    .actuator_cmd_o(core_actuator_cmd_o),
    .actuator_cmd_valid_o(core_actuator_cmd_valid_o),
    .clk(clk),
    .fault_o(core_fault_o),
    .irq_o(core_irq_o),
    .model_req_desc_o(core_model_req_desc_o),
    .model_req_ready_i(rx_active[67]),
    .model_req_valid_o(core_model_req_valid_o),
    .model_rsp_desc_i(rx_active[131:68]),
    .model_rsp_ready_o(core_model_rsp_ready_o),
    .model_rsp_valid_i(rx_active[132]),
    .reset_n(reset_n),
    .wb_ack_o(core_wb_ack_o),
    .wb_adr_i(rx_active[31:0]),
    .wb_cyc_i(rx_active[66]),
    .wb_dat_i(rx_active[63:32]),
    .wb_dat_o(core_wb_dat_o),
    .wb_err_o(core_wb_err_o),
    .wb_stb_i(rx_active[65]),
    .wb_we_i(rx_active[64])
  );
  assign core_model_req_ready_i = rx_active[67];
  assign core_model_rsp_desc_i = rx_active[131:68];
  assign core_model_rsp_valid_i = rx_active[132];
  assign core_response = { core_wb_dat_o, core_wb_ack_o, core_wb_err_o, core_model_req_desc_o, core_model_req_valid_o, core_model_rsp_ready_o, core_actuator_cmd_o, core_actuator_cmd_valid_o, core_fault_o, core_irq_o };
  assign core_wb_adr_i = rx_active[31:0];
  assign core_wb_cyc_i = rx_active[66];
  assign core_wb_dat_i = rx_active[63:32];
  assign core_wb_stb_i = rx_active[65];
  assign core_wb_we_i = rx_active[64];
  assign fault_indicator = 1'h0;
endmodule
