"""Auto-generated Cocotb testbench skeleton for: pwm_controller

Generated by ChipLoop Testbench Generator Agent.
- Uses spec JSON as the source of truth for ports/clocks/resets
- Supports digital mode and future system/SoC mode
- Avoids hardcoded DUT signal assumptions
"""

import os
import random
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, Timer

try:
    from scoreboard import Scoreboard
except Exception:
    Scoreboard = None

try:
    from coverage_model import CoverageModel
except Exception:
    CoverageModel = None


def _seed() -> int:
    env = os.getenv("RANDOM_SEED")
    if env and env.isdigit():
        return int(env)
    return 1


async def _advance_time(dut):
    clocks = ['clk']
    for clk_name in clocks:
        if hasattr(dut, clk_name):
            await RisingEdge(getattr(dut, clk_name))
            return
    await Timer(10, units="ns")


def _safe_drive_random(sig, width_expr: str):
    try:
        width = int(width_expr)
    except Exception:
        try:
            width = len(sig.value.binstr)
        except Exception:
            width = 1
    width = max(int(width), 1)
    sig.value = random.getrandbits(width)


def _fit_to_signal(sig, value: int) -> int:
    try:
        width = len(sig)
    except Exception:
        try:
            width = len(sig.value.binstr)
        except Exception:
            width = 32
    width = max(int(width), 1)
    return int(value) & ((1 << width) - 1)


def _assert_outputs_known(dut, observable_outputs):
    for p in observable_outputs:
        name = p.get("name")
        if not name or not hasattr(dut, name):
            continue
        sig = getattr(dut, name)
        value = str(sig.value).lower()
        assert "x" not in value and "z" not in value, f"Output {name} is unknown/high-Z: {sig.value}"


@cocotb.test()
async def smoke_test(dut):
    """Basic smoke test: clock/reset bring-up and brief settle window."""
    seed = _seed()
    random.seed(seed)

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 1
    await Timer(5, units='ns')

    # Initialize discoverable DUT inputs from spec
    if hasattr(dut, "enable"):
        getattr(dut, "enable").value = 0
    if hasattr(dut, "duty_cycle"):
        getattr(dut, "duty_cycle").value = 0
    if hasattr(dut, "period"):
        getattr(dut, "period").value = 0

    await Timer(20, units="ns")

    sb = Scoreboard(dut) if Scoreboard else None
    cov = CoverageModel() if CoverageModel else None

    if sb:
        sb.start()
    if cov:
        cov.start(dut)

    for _ in range(5):
        await _advance_time(dut)
        if cov:
            try:
                cov.sample()
            except Exception:
                pass

    _assert_outputs_known(dut, [{'name': 'pwm_out', 'width_expr': '1'}, {'name': 'counter_value', 'width_expr': '8'}])

    if cov:
        try:
            cov.stop()
            cov.write_reports()
        except Exception:
            pass

    

    if sb:
        sb.stop()


@cocotb.test()
async def constrained_random_sanity(dut):
    """Constrained-random sanity test derived only from spec-declared inputs."""
    seed = _seed()
    random.seed(seed)

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 1
    await Timer(5, units='ns')

    randomizable_inputs = [{'name': 'enable', 'width_expr': '1'},
 {'name': 'duty_cycle', 'width_expr': '8'},
 {'name': 'period', 'width_expr': '8'}]

    cov = CoverageModel() if CoverageModel else None
    if cov:
        cov.start(dut)

    for _ in range(int(os.getenv("NUM_ITERS", "25"))):
        for p in randomizable_inputs:
            name = p.get("name")
            width_expr = str(p.get("width_expr", "1"))
            if not name or not hasattr(dut, name):
                continue
            try:
                sig = getattr(dut, name)
                _safe_drive_random(sig, width_expr)
            except Exception:
                continue

        await _advance_time(dut)

        if cov:
            try:
                cov.sample()
            except Exception:
                pass

    _assert_outputs_known(dut, [{'name': 'pwm_out', 'width_expr': '1'}, {'name': 'counter_value', 'width_expr': '8'}])

    if cov:
        try:
            cov.stop()
            cov.write_reports()
        except Exception:
            pass

    

@cocotb.test()
async def application_spec_boundary_directed(dut):
    """Exercise boundary and transition vectors derived from the application specification."""

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 1
    await Timer(5, units='ns')

    if hasattr(dut, "enable"):
        getattr(dut, "enable").value = 0
    if hasattr(dut, "duty_cycle"):
        getattr(dut, "duty_cycle").value = 0
    if hasattr(dut, "period"):
        getattr(dut, "period").value = 0

    stimulus_plan = [{'name': 'enable', 'source': 'application_spec_port_boundary', 'values': [0, 1], 'width': 1},
 {'name': 'duty_cycle',
  'source': 'application_spec_port_boundary',
  'values': [0, 1, 255, 128, 127, 85],
  'width': 8},
 {'name': 'period',
  'source': 'application_spec_port_boundary',
  'values': [0, 1, 255, 128, 127, 85],
  'width': 8}]
    cov = CoverageModel() if CoverageModel else None
    if cov:
        cov.start(dut)
    for point in stimulus_plan:
        if not hasattr(dut, point["name"]):
            continue
        signal = getattr(dut, point["name"])
        for value in point["values"]:
            signal.value = _fit_to_signal(signal, value)
            await _advance_time(dut)
            if cov:
                try:
                    cov.sample()
                except Exception:
                    pass
    for phase in range(2):
        for point in stimulus_plan:
            if hasattr(dut, point["name"]):
                signal = getattr(dut, point["name"])
                signal.value = _fit_to_signal(signal, point["values"][-1 if phase else 0])
        await _advance_time(dut)
        if cov:
            try:
                cov.sample()
            except Exception:
                pass
    _assert_outputs_known(dut, [{'name': 'pwm_out', 'width_expr': '1'}, {'name': 'counter_value', 'width_expr': '8'}])
    if cov:
        try:
            cov.stop()
            cov.write_reports()
        except Exception:
            pass


@cocotb.test()
async def feature_contract_directed(dut):
    """Execute feature scenarios compiled from explicit application-spec expectations."""

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 1
    await Timer(5, units='ns')

    if hasattr(dut, "enable"):
        getattr(dut, "enable").value = 0
    if hasattr(dut, "duty_cycle"):
        getattr(dut, "duty_cycle").value = 0
    if hasattr(dut, "period"):
        getattr(dut, "period").value = 0

    feature_contracts = [{'coverage_bins': ['reset_clears_outputs.stimulus_applied',
                    'reset_clears_outputs.expected_observed'],
  'executable': True,
  'expected': {'counter_value': {'eq': 0}, 'pwm_out': {'eq': 0}},
  'feature_id': 'reset_clears_outputs',
  'monitors': ['counter_value', 'pwm_out', 'reset_n'],
  'non_executable_reason': None,
  'registers': [],
  'statement': 'Asserting reset_n low clears the registered counter state, which forces '
               'counter_value to zero and pwm_out low on the next observable cycle.',
  'status': 'executable',
  'stimulus': {'duty_cycle': 128, 'enable': 1, 'period': 10, 'reset_n': 0},
  'stimulus_steps': [{'cycles': 1,
                      'signals': {'duty_cycle': 128, 'enable': 1, 'period': 10, 'reset_n': 0}}],
  'unresolved_bindings': [],
  'wait_cycles': 1},
 {'coverage_bins': ['count_advances_when_enabled.stimulus_applied',
                    'count_advances_when_enabled.expected_observed'],
  'executable': True,
  'expected': {'counter_value': {'max': 255, 'min': 1}},
  'feature_id': 'count_advances_when_enabled',
  'monitors': ['counter_value', 'enable'],
  'non_executable_reason': None,
  'registers': [],
  'statement': 'With reset released and enable high, the counter increments on each rising clock '
               'edge until rollover.',
  'status': 'executable',
  'stimulus': {},
  'stimulus_steps': [{'cycles': 1,
                      'signals': {'duty_cycle': 200, 'enable': 1, 'period': 10, 'reset_n': 1}},
                     {'cycles': 1, 'signals': {'enable': 1, 'reset_n': 1}}],
  'unresolved_bindings': [],
  'wait_cycles': 2},
 {'coverage_bins': ['counter_holds_when_disabled.stimulus_applied',
                    'counter_holds_when_disabled.expected_observed'],
  'executable': True,
  'expected': {'counter_value': {'eq': 0}},
  'feature_id': 'counter_holds_when_disabled',
  'monitors': ['counter_value', 'enable'],
  'non_executable_reason': None,
  'registers': [],
  'statement': 'With enable low, the counter does not change across clock cycles.',
  'status': 'executable',
  'stimulus': {'duty_cycle': 200, 'enable': 0, 'period': 10, 'reset_n': 1},
  'stimulus_steps': [{'cycles': 2,
                      'signals': {'duty_cycle': 200, 'enable': 0, 'period': 10, 'reset_n': 1}}],
  'unresolved_bindings': [],
  'wait_cycles': 2},
 {'coverage_bins': ['rollover_at_period.stimulus_applied', 'rollover_at_period.expected_observed'],
  'executable': True,
  'expected': {'counter_value': {'eq': 0}},
  'feature_id': 'rollover_at_period',
  'monitors': ['counter_value', 'period'],
  'non_executable_reason': None,
  'registers': [],
  'statement': 'When enabled, the counter rolls over to zero after reaching the programmed period '
               'value.',
  'status': 'executable',
  'stimulus': {'duty_cycle': 200, 'enable': 1, 'period': 3, 'reset_n': 1},
  'stimulus_steps': [{'cycles': 4,
                      'signals': {'duty_cycle': 200, 'enable': 1, 'period': 3, 'reset_n': 1}}],
  'unresolved_bindings': [],
  'wait_cycles': 4},
 {'coverage_bins': ['pwm_high_below_duty.stimulus_applied',
                    'pwm_high_below_duty.expected_observed'],
  'executable': True,
  'expected': {'pwm_out': {'eq': 1}},
  'feature_id': 'pwm_high_below_duty',
  'monitors': ['pwm_out', 'duty_cycle', 'counter_value'],
  'non_executable_reason': None,
  'registers': [],
  'statement': 'pwm_out is high whenever counter_value is strictly less than duty_cycle.',
  'status': 'executable',
  'stimulus': {'duty_cycle': 5, 'enable': 0, 'period': 10, 'reset_n': 1},
  'stimulus_steps': [{'cycles': 1,
                      'signals': {'duty_cycle': 5, 'enable': 0, 'period': 10, 'reset_n': 1}}],
  'unresolved_bindings': [],
  'wait_cycles': 1},
 {'coverage_bins': ['pwm_low_at_or_above_duty.stimulus_applied',
                    'pwm_low_at_or_above_duty.expected_observed'],
  'executable': True,
  'expected': {'pwm_out': {'eq': 0}},
  'feature_id': 'pwm_low_at_or_above_duty',
  'monitors': ['pwm_out', 'duty_cycle', 'counter_value'],
  'non_executable_reason': None,
  'registers': [],
  'statement': 'pwm_out is low when counter_value is greater than or equal to duty_cycle.',
  'status': 'executable',
  'stimulus': {'duty_cycle': 0, 'enable': 0, 'period': 10, 'reset_n': 1},
  'stimulus_steps': [{'cycles': 1,
                      'signals': {'duty_cycle': 0, 'enable': 0, 'period': 10, 'reset_n': 1}}],
  'unresolved_bindings': [],
  'wait_cycles': 1}]
    for feature in feature_contracts:
        for step in feature.get("stimulus_steps", []):
            for name, value in step.get("signals", {}).items():
                assert hasattr(dut, name), f"{feature['feature_id']} stimulus signal {name} is unavailable"
                signal = getattr(dut, name)
                signal.value = _fit_to_signal(signal, value)
            for _ in range(int(step.get("cycles", 1))):
                await _advance_time(dut)
        for _ in range(int(feature.get("wait_cycles", 1))):
            await _advance_time(dut)
        for name, rule in feature["expected"].items():
            assert hasattr(dut, name), f"{feature['feature_id']} monitor signal {name} is unavailable"
            actual = int(getattr(dut, name).value)
            if isinstance(rule, dict):
                if "value" in rule:
                    assert actual == int(rule["value"]), f"{feature['feature_id']}: {name}={actual}, expected {rule['value']}"
                if "eq" in rule:
                    assert actual == int(rule["eq"]), f"{feature['feature_id']}: {name}={actual}, expected {rule['eq']}"
                if "min" in rule:
                    assert actual >= int(rule["min"]), f"{feature['feature_id']}: {name}={actual} below {rule['min']}"
                if "max" in rule:
                    assert actual <= int(rule["max"]), f"{feature['feature_id']}: {name}={actual} above {rule['max']}"
            else:
                assert actual == int(rule), f"{feature['feature_id']}: {name}={actual}, expected {rule}"

