import glob
import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any

from tooling.runner import run_command, tool_path
from utils.artifact_utils import save_text_artifact_and_record

AGENT_NAME = "Digital Logic Equivalence Check Agent"


def _ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def _write_text(path: str, content: str) -> None:
    _ensure_dir(os.path.dirname(path))
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def _existing_path(value: Any, workflow_dir: str | None = None) -> str | None:
    if not isinstance(value, str) or not value.strip():
        return None
    raw = value.strip()
    candidates = [raw]
    if workflow_dir and not os.path.isabs(raw):
        candidates.insert(0, os.path.join(workflow_dir, raw))
    for cand in candidates:
        try:
            cand = os.path.abspath(cand)
            if os.path.exists(cand):
                return cand
        except (TypeError, ValueError, OSError):
            continue
    return None


def _dedupe(paths: list[str]) -> list[str]:
    out = []
    seen = set()
    for path in paths:
        ap = os.path.abspath(path)
        if ap not in seen:
            seen.add(ap)
            out.append(ap)
    return out


def _rtl_sources(state: dict, workflow_dir: str) -> list[str]:
    digital = state.get("digital") if isinstance(state.get("digital"), dict) else {}
    candidates: list[str] = []
    for value in (
        state.get("rtl_files"),
        state.get("rtl_inputs"),
        state.get("source_rtl_files"),
        digital.get("rtl_files"),
    ):
        if isinstance(value, list):
            candidates.extend([p for p in (_existing_path(x, workflow_dir) for x in value) if p])
    if not candidates:
        for pattern in (
            "handoff/rtl/**/*.v",
            "handoff/rtl/**/*.sv",
            "digital/handoff/rtl/**/*.v",
            "digital/handoff/rtl/**/*.sv",
            "digital/rtl/**/*.v",
            "digital/rtl/**/*.sv",
        ):
            candidates.extend(glob.glob(os.path.join(workflow_dir, pattern), recursive=True))
    synth_dir = os.path.join(workflow_dir, "digital", "synth")
    return [p for p in _dedupe(candidates) if not os.path.abspath(p).startswith(os.path.abspath(synth_dir))]


def _synth_netlist(state: dict, workflow_dir: str) -> str | None:
    digital = state.get("digital") if isinstance(state.get("digital"), dict) else {}
    synth = digital.get("synth") if isinstance(digital.get("synth"), dict) else {}
    for cand in (
        synth.get("netlist"),
        digital.get("synth_netlist"),
        state.get("synth_netlist"),
    ):
        path = _existing_path(cand, workflow_dir)
        if path:
            return path
    hits = sorted(glob.glob(os.path.join(workflow_dir, "digital", "synth", "netlist", "*.v")))
    return hits[0] if hits else None


def _top_module(state: dict, rtl_files: list[str], netlist: str | None) -> str:
    digital = state.get("digital") if isinstance(state.get("digital"), dict) else {}
    synth = digital.get("synth") if isinstance(digital.get("synth"), dict) else {}
    for value in (synth.get("top_module"), digital.get("top_module"), state.get("top_module")):
        if isinstance(value, str) and value.strip() and value.strip() != "imported_from_arch2rtl":
            return value.strip()
    for path in [netlist, *rtl_files]:
        if not path:
            continue
        try:
            text = Path(path).read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        match = re.search(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_$]*)\b", text, flags=re.MULTILINE)
        if match:
            return match.group(1)
    return "top"


def _yosys_script(golden: list[str], gate: str, top: str) -> str:
    read_golden = "\n".join(f"read_verilog -sv {json.dumps(path)}" for path in golden)
    return f"""# Auto-generated by {AGENT_NAME}
{read_golden}
prep -top {top}
rename -top gold
design -stash gold

read_verilog -sv {json.dumps(gate)}
prep -top {top}
rename -top gate
design -stash gate

design -copy-from gold -as gold gold
design -copy-from gate -as gate gate
equiv_make gold gate equiv
hierarchy -top equiv
equiv_simple
equiv_induct -undef
equiv_status -assert
"""


def _classify(returncode: int | None, log: str, tool_available: bool) -> tuple[str, int]:
    if not tool_available:
        return "tool_unavailable", 0
    text = log.lower()
    if returncode == 0 and "equivalence successfully proven" in text:
        return "pass", 0
    if returncode == 0 and "unproven" not in text and "failed" not in text:
        return "pass", 0
    unproven = 0
    for match in re.finditer(r"(\d+)\s+unproven", text):
        try:
            unproven += int(match.group(1))
        except Exception:
            pass
    if "equivalence checking failed" in text or "assert failed" in text:
        return "fail", unproven or 1
    return "inconclusive", unproven


def run_agent(state: dict) -> dict:
    workflow_id = state.get("workflow_id", "default")
    workflow_dir = os.path.abspath(state.get("workflow_dir") or f"backend/workflows/{workflow_id}")
    stage_dir = os.path.join(workflow_dir, "digital", "lec")
    logs_dir = os.path.join(stage_dir, "logs")
    _ensure_dir(logs_dir)

    rtl_files = _rtl_sources(state, workflow_dir)
    netlist = _synth_netlist(state, workflow_dir)
    top = _top_module(state, rtl_files, netlist)
    yosys = tool_path("yosys", state)

    script_path = os.path.join(stage_dir, "yosys_lec.ys")
    log_path = os.path.join(logs_dir, "yosys_lec.log")
    report_path = os.path.join(stage_dir, "lec_report.md")
    summary_path = os.path.join(stage_dir, "lec_summary.json")

    if rtl_files and netlist:
        script = _yosys_script(rtl_files, netlist, top)
    else:
        script = "# Missing RTL or synthesized netlist; LEC not run.\n"
    _write_text(script_path, script)

    rc = None
    log = ""
    if yosys and rtl_files and netlist:
        proc = run_command(state, "logic_equivalence", ["yosys", "-s", script_path], cwd=stage_dir, timeout_sec=900)
        rc = proc.returncode
        log = (proc.stdout or "") + (proc.stderr or "")
    elif not yosys:
        log = "Yosys executable was not found in the active ChipLoop tool profile.\n"
    else:
        log = "Missing RTL or synthesized netlist for LEC.\n"
    _write_text(log_path, log)

    verdict, unproven = _classify(rc, log, bool(yosys))
    if not rtl_files or not netlist:
        verdict = "incomplete_inputs"

    summary = {
        "workflow_id": workflow_id,
        "agent": AGENT_NAME,
        "status": verdict,
        "tool": "yosys",
        "tool_available": bool(yosys),
        "return_code": rc,
        "top_module": top,
        "rtl_files": [os.path.basename(p) for p in rtl_files],
        "synth_netlist": os.path.basename(netlist) if netlist else None,
        "unproven_points": unproven,
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "artifacts": {
            "script": "digital/lec/yosys_lec.ys",
            "log": "digital/lec/logs/yosys_lec.log",
            "summary": "digital/lec/lec_summary.json",
            "report": "digital/lec/lec_report.md",
        },
    }
    report = "\n".join([
        "# Logic Equivalence Check",
        "",
        f"- Status: `{verdict}`",
        f"- Tool: `yosys`",
        f"- Top module: `{top}`",
        f"- RTL files: `{len(rtl_files)}`",
        f"- Synth netlist: `{os.path.basename(netlist) if netlist else 'missing'}`",
        f"- Unproven points: `{unproven}`",
        f"- Return code: `{rc}`",
        "",
        "If this is inconclusive, inspect `digital/lec/logs/yosys_lec.log` for unsupported cells, black boxes, or reset/initial-state assumptions.",
    ]) + "\n"
    _write_text(summary_path, json.dumps(summary, indent=2))
    _write_text(report_path, report)

    save_text_artifact_and_record(workflow_id, AGENT_NAME, "digital", "lec/yosys_lec.ys", script)
    save_text_artifact_and_record(workflow_id, AGENT_NAME, "digital", "lec/logs/yosys_lec.log", log)
    save_text_artifact_and_record(workflow_id, AGENT_NAME, "digital", "lec/lec_summary.json", json.dumps(summary, indent=2))
    save_text_artifact_and_record(workflow_id, AGENT_NAME, "digital", "lec/lec_report.md", report)

    digital = state.setdefault("digital", {})
    digital["lec"] = {
        "status": verdict,
        "summary_json": summary_path,
        "report_md": report_path,
        "log": log_path,
        "script": script_path,
    }
    state["status"] = f"{AGENT_NAME}: {verdict}"
    return state
