import os
import json
from datetime import datetime

from utils.artifact_utils import save_text_artifact_and_record

AGENT_NAME = "Digital Implementation Setup Agent"

def _read_json(path: str) -> dict:
    with open(path, "r") as f:
        return json.load(f)

def run_agent(state: dict) -> dict:
    workflow_id = state.get("workflow_id", "default")
    workflow_dir = state.get("workflow_dir", f"backend/workflows/{workflow_id}")
    os.makedirs(workflow_dir, exist_ok=True)

    digital_root = os.path.join(workflow_dir, "digital", "foundry")
    os.makedirs(digital_root, exist_ok=True)

    profile_path = os.path.join(digital_root, "foundry_profile.json")
    if not os.path.exists(profile_path):
        state["status"] = "❌ Missing foundry_profile.json. Run 'Digital Foundry Profile Agent' first."
        return state

    profile = _read_json(profile_path)

    # Paths
    constraints_dir = os.path.join(digital_root, "constraints")
    corners_dir = os.path.join(digital_root, "corners")
    openlane_dir = os.path.join(digital_root, "openlane")
    setup_dir = os.path.join(digital_root, "setup")
    os.makedirs(constraints_dir, exist_ok=True)
    os.makedirs(corners_dir, exist_ok=True)
    os.makedirs(openlane_dir, exist_ok=True)
    os.makedirs(setup_dir, exist_ok=True)

    # --- 1) Base SDC (safe defaults; no fake precision) ---
    clk_mhz = (profile.get("timing") or {}).get("target_clock_mhz", 50)
    clk_name = (profile.get("timing") or {}).get("clock_name", "clk")
    reset_name = (profile.get("timing") or {}).get("reset_name", "reset_n")
    period_ns = 1000.0 / float(clk_mhz)

    base_sdc = f"""# Auto-generated by {AGENT_NAME}
# Safe defaults ONLY. Override in future via UI scope/toggles.
# Clock: {clk_name} @ {clk_mhz}MHz ({period_ns:.3f} ns period)
create_clock -name {clk_name} -period {period_ns:.3f} [get_ports {clk_name}]

# Reset (placeholder - adjust for async/sync per design)
# set_false_path -from [get_ports {reset_name}]

# IO delays (placeholders)
# set_input_delay  0.1 -clock {clk_name} [all_inputs]
# set_output_delay 0.1 -clock {clk_name} [all_outputs]
"""

    base_sdc_path = os.path.join(constraints_dir, "base.sdc")
    with open(base_sdc_path, "w") as f:
        f.write(base_sdc)

    # --- 2) Corners canonical JSON ---
    corners = profile.get("corners") or []
    corners_json = {
        "pdk": profile.get("pdk"),
        "pdk_root": profile.get("pdk_root"),
        "corners": corners,
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "note": "Corner names are intent labels; OpenLane2 config will map them to available libs later.",
    }

    corners_path = os.path.join(corners_dir, "corners.json")
    with open(corners_path, "w") as f:
        json.dump(corners_json, f, indent=2)

    # --- 3) OpenLane2 config.json (minimal + scalable) ---
    # IMPORTANT: no hardcoded foundry-specific library paths here.
    # We only set PDK selector + point to SDC.
    openlane_cfg = {
        "DESIGN_NAME": state.get("design_name") or "top",
        "PDK": profile.get("pdk") or "sky130A",
        "PDK_ROOT": profile.get("pdk_root") or "backend/pdk",
        "CLOCK_PORT": clk_name,
        "CLOCK_PERIOD": period_ns,
        "SYNTH_SDC_FILE": "digital/foundry/constraints/base.sdc",
        "OPENLANE_NUM_CORES": int(os.getenv("OPENLANE_NUM_CORES", "2")),
        "NOTE": "Generated by Implementation Setup Agent. Stage agents will consume this.",
    }

    cfg_path = os.path.join(openlane_dir, "config.json")
    with open(cfg_path, "w") as f:
        json.dump(openlane_cfg, f, indent=2)

    # --- 4) Setup log ---
    log_lines = [
        f"[{datetime.utcnow().isoformat()}Z] {AGENT_NAME}",
        f"workflow_id={workflow_id}",
        f"workflow_dir={os.path.abspath(workflow_dir)}",
        f"pdk={openlane_cfg['PDK']}",
        f"pdk_root={openlane_cfg['PDK_ROOT']}",
        f"base_sdc={base_sdc_path}",
        f"corners={corners_path}",
        f"openlane_cfg={cfg_path}",
        "Rules: no hardcoded lib/lef paths; portable foundry profile drives config.",
    ]
    setup_log = "\n".join(log_lines) + "\n"
    setup_log_path = os.path.join(setup_dir, "implementation_setup.log")
    with open(setup_log_path, "w") as f:
        f.write(setup_log)

    # Upload (Supabase storage is truth) :contentReference[oaicite:11]{index=11}
    save_text_artifact_and_record(workflow_id, AGENT_NAME, "digital/foundry/constraints", "base.sdc", base_sdc)
    save_text_artifact_and_record(workflow_id, AGENT_NAME, "digital/foundry/corners", "corners.json", json.dumps(corners_json, indent=2))
    save_text_artifact_and_record(workflow_id, AGENT_NAME, "digital/foundry/openlane", "config.json", json.dumps(openlane_cfg, indent=2))
    save_text_artifact_and_record(workflow_id, AGENT_NAME, "digital/foundry/setup", "implementation_setup.log", setup_log)

    state.setdefault("digital", {})
    state["digital"]["constraints_sdc"] = "digital/foundry/constraints/base.sdc"
    state["digital"]["openlane_config"] = "digital/foundry/openlane/config.json"
    state["status"] = "✅ Digital implementation collateral generated (constraints + corners + OpenLane config)."
    return state