import json
import re
from pathlib import PurePosixPath
from typing import Dict, List

from .models import AgentFactoryRequest, GeneratedFilePlan, RegistryPatchPlan


STANDARD_HOOKS = [
    "pre_run_validate_inputs",
    "post_run_collect_artifacts",
    "post_run_update_state",
    "on_failure_capture_traceback",
    "on_failure_preserve_logs",
    "artifact_publish_to_supabase",
]


def slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", (value or "").lower()).strip("_") or "generated_agent"


def module_name_for(request: AgentFactoryRequest) -> str:
    base = slugify(request.name)
    return base if base.endswith("_agent") else f"{base}_agent"


def build_agent_spec(request: AgentFactoryRequest, skills: List[str], tools: List[str]) -> Dict:
    module_name = module_name_for(request)
    return {
        "name": request.name,
        "loop_type": request.loop_type or request.domain or "system",
        "domain": request.domain or request.loop_type or "system",
        "description": request.natural_language_request,
        "entrypoint": f"generated_studio_agents.{module_name}:run_agent",
        "execution_mode": "native",
        "inputs": request.inputs or ["state.workflow_id", "state.workflow_dir"],
        "outputs": request.outputs or ["state update", "reviewable generated artifacts"],
        "artifact_paths": ["agent-defined generated artifact paths"],
        "artifact_types": ["review_artifact"],
        "required_skills": skills,
        "required_tools": tools,
        "hooks": STANDARD_HOOKS,
        "metadata": {
            "generated_by": "studio_factory_v1",
            "review_required": True,
        },
    }


def build_agent_stub(request: AgentFactoryRequest) -> str:
    agent_name = request.name.replace('"', '\\"')
    return f'''import logging
from typing import Dict

from agents.runtime import AgentContext, AgentResult, execute_agent


AGENT_NAME = "{agent_name}"
logger = logging.getLogger("chiploop.generated_studio_agent")


def _run(context: AgentContext) -> AgentResult:
    """
    TODO: Implement generated agent behavior after human review.

    This stub intentionally does not assume secrets, local tools, or input files.
    Preserve existing Supabase artifact patterns by using the backend artifact
    helper when reviewed implementation starts producing artifacts.
    """
    state = context.state
    logger.info(
        "generated_agent.stub_run",
        extra={{
            "workflow_id": context.workflow_id,
            "run_id": context.run_id,
            "loop_type": context.loop_type,
            "agent_name": context.agent_name,
        }},
    )
    state["status"] = "TODO: generated agent stub requires implementation review"
    state["generated_agent_stub"] = AGENT_NAME
    return AgentResult(
        status=state["status"],
        data={{"generated_agent_stub": AGENT_NAME}},
        log="Generated Studio Agent Factory v1 stub executed in review mode.",
    )


def run_agent(state: Dict) -> Dict:
    context = AgentContext.from_state(state, AGENT_NAME)
    result = execute_agent(context, _run)
    state.update(result.to_state_update())
    return state
'''


def build_test_stub(request: AgentFactoryRequest) -> str:
    module_name = module_name_for(request)
    return f'''from generated_studio_agents.{module_name} import run_agent


def test_generated_agent_stub_runs():
    state = {{"workflow_id": "wf-generated", "loop_type": "{request.loop_type or "system"}"}}
    result = run_agent(state)
    assert result["generated_agent_stub"] == "{request.name}"
'''


def build_readme(request: AgentFactoryRequest) -> str:
    return f"""# {request.name}

Generated by Studio Agent Factory v1.

## Review Required

- Fill in agent implementation logic.
- Confirm inputs and outputs.
- Confirm Supabase artifact behavior before promotion.
- Run generated tests.
- Manually copy reviewed files into production paths only after approval.
"""


def build_registry_patch(spec: Dict, proposed_skills: List[Dict]) -> str:
    patch = {
        "agents": [spec],
        "skills": proposed_skills,
        "review_required": True,
        "instructions": "Manually merge these entries into registry files after review.",
    }
    return json.dumps(patch, indent=2) + "\n"


def build_generated_files(request: AgentFactoryRequest, agent_spec: Dict, proposed_skills: List[Dict]) -> List[GeneratedFilePlan]:
    module_name = module_name_for(request)
    return [
        GeneratedFilePlan(
            path=str(PurePosixPath("generated_studio_agents") / f"{module_name}.py"),
            description="Reviewable generated agent stub.",
            content=build_agent_stub(request),
        ),
        GeneratedFilePlan(
            path=str(PurePosixPath("generated_studio_agents") / f"test_{module_name}.py"),
            description="Reviewable generated test stub.",
            content=build_test_stub(request),
        ),
        GeneratedFilePlan(
            path=str(PurePosixPath("generated_studio_agents") / f"{module_name}_README.md"),
            description="Generated migration notes.",
            content=build_readme(request),
        ),
        GeneratedFilePlan(
            path=str(PurePosixPath("generated_patches") / f"{module_name}_registry_patch.yaml"),
            description="Proposed registry patch, JSON-compatible YAML.",
            content=build_registry_patch(agent_spec, proposed_skills),
        ),
    ]


def build_registry_patch_plan(request: AgentFactoryRequest, agent_spec: Dict, proposed_skills: List[Dict]) -> RegistryPatchPlan:
    module_name = module_name_for(request)
    return RegistryPatchPlan(
        path=str(PurePosixPath("generated_patches") / f"{module_name}_registry_patch.yaml"),
        content=build_registry_patch(agent_spec, proposed_skills),
    )
