/* Generated by Yosys 0.56 (git sha1 9c447ad9d4b1ea589369364eea38b4d70da2c599, x86_64-w64-mingw32-g++ 15.2.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

module adaptive_aero_control_csr(clk, rst_n, cfg_wr_en, cfg_rd_en, cfg_addr, cfg_wdata, cfg_rdata, enable, clear_faults, mode_select, freshness_limit, timeout_limit, max_cmd, min_cmd, rate_limit, fallback_mode, sequence_counter, fault_status, idle_safe);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [63:0] _07_;
  wire _08_;
  wire _09_;
  input [5:0] cfg_addr;
  wire [5:0] cfg_addr;
  input cfg_rd_en;
  wire cfg_rd_en;
  output [63:0] cfg_rdata;
  wire [63:0] cfg_rdata;
  reg [63:0] cfg_rdata_r;
  input [63:0] cfg_wdata;
  wire [63:0] cfg_wdata;
  input cfg_wr_en;
  wire cfg_wr_en;
  output clear_faults;
  wire clear_faults;
  reg clear_faults_r;
  input clk;
  wire clk;
  output enable;
  wire enable;
  reg enable_r;
  output [3:0] fallback_mode;
  wire [3:0] fallback_mode;
  reg [3:0] fallback_mode_r;
  input [15:0] fault_status;
  wire [15:0] fault_status;
  output [7:0] freshness_limit;
  wire [7:0] freshness_limit;
  reg [7:0] freshness_limit_r;
  input idle_safe;
  wire idle_safe;
  output [15:0] max_cmd;
  wire [15:0] max_cmd;
  reg [15:0] max_cmd_r;
  output [15:0] min_cmd;
  wire [15:0] min_cmd;
  reg [15:0] min_cmd_r;
  output [2:0] mode_select;
  wire [2:0] mode_select;
  reg [2:0] mode_select_r;
  output [15:0] rate_limit;
  wire [15:0] rate_limit;
  reg [15:0] rate_limit_r;
  input rst_n;
  wire rst_n;
  output [15:0] sequence_counter;
  wire [15:0] sequence_counter;
  reg [15:0] sequence_counter_r;
  output [7:0] timeout_limit;
  wire [7:0] timeout_limit;
  reg [7:0] timeout_limit_r;
  assign _01_ = cfg_wdata[1] & idle_safe;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sequence_counter_r <= 16'h0001;
    else if (_02_) sequence_counter_r <= cfg_wdata[15:0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) freshness_limit_r <= 8'h00;
    else if (_03_) freshness_limit_r <= cfg_wdata[12:5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cfg_rdata_r <= 64'h0000000000000000;
    else if (cfg_rd_en) cfg_rdata_r <= _07_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) enable_r <= 1'h0;
    else if (_03_) enable_r <= cfg_wdata[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rate_limit_r <= 16'h0000;
    else if (_03_) rate_limit_r <= cfg_wdata[63:48];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timeout_limit_r <= 8'h00;
    else if (_03_) timeout_limit_r <= cfg_wdata[20:13];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) fallback_mode_r <= 4'h0;
    else if (_02_) fallback_mode_r <= cfg_wdata[19:16];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) min_cmd_r <= 16'h0000;
    else if (_03_) min_cmd_r <= cfg_wdata[52:37];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mode_select_r <= 3'h0;
    else if (_03_) mode_select_r <= cfg_wdata[4:2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) max_cmd_r <= 16'h0000;
    else if (_03_) max_cmd_r <= cfg_wdata[36:21];
  assign _04_ = ~ _05_;
  assign _02_ = & { _04_, _06_, cfg_wr_en };
  assign _03_ = & { _05_, cfg_wr_en };
  always @(posedge clk, negedge rst_n)
    if (!rst_n) clear_faults_r <= 1'h0;
    else clear_faults_r <= _00_;
  function [63:0] _25_;
    input [63:0] a;
    input [191:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _25_ = b[63:0];
      3'b?1?:
        _25_ = b[127:64];
      3'b1??:
        _25_ = b[191:128];
      default:
        _25_ = a;
    endcase
  endfunction
  assign _07_ = _25_(64'h0000000000000000, { rate_limit_r[9:0], min_cmd_r, max_cmd_r, 1'h0, timeout_limit_r, freshness_limit_r, mode_select_r, 1'h0, enable_r, 44'h00000000000, fallback_mode_r, sequence_counter_r, 48'h000000000000, fault_status }, { _05_, _06_, _08_ });
  assign _08_ = cfg_addr == 6'h02;
  assign _06_ = cfg_addr == 6'h01;
  assign _05_ = ! cfg_addr;
  assign _09_ = _05_ ? _01_ : 1'h0;
  assign _00_ = cfg_wr_en ? _09_ : 1'h0;
  assign cfg_rdata = cfg_rdata_r;
  assign clear_faults = clear_faults_r;
  assign enable = enable_r;
  assign fallback_mode = fallback_mode_r;
  assign freshness_limit = freshness_limit_r;
  assign max_cmd = max_cmd_r;
  assign min_cmd = min_cmd_r;
  assign mode_select = mode_select_r;
  assign rate_limit = rate_limit_r;
  assign sequence_counter = sequence_counter_r;
  assign timeout_limit = timeout_limit_r;
endmodule

module adaptive_aero_control_fsm(clk, rst_n, enable, clear_faults, mode_select, fault_status_in, req_issued, rsp_accepted, rsp_malformed, rsp_stale, rsp_seq_mismatch, rsp_duplicate, outstanding_timer_expired, service_unavailable, candidate_valid, candidate_invalid, candidate_fallback, idle_safe, issue_request, validate_response, apply_command
, enter_fallback, latch_fault, fsm_state, fault_status_out);
  wire [15:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire [2:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire [2:0] _008_;
  wire _009_;
  wire [2:0] _010_;
  wire _011_;
  wire [2:0] _012_;
  wire [2:0] _013_;
  wire [2:0] _014_;
  wire [2:0] _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire [15:0] _048_;
  wire [8:0] _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  output apply_command;
  wire apply_command;
  wire apply_command_r;
  input candidate_fallback;
  wire candidate_fallback;
  input candidate_invalid;
  wire candidate_invalid;
  input candidate_valid;
  wire candidate_valid;
  input clear_faults;
  wire clear_faults;
  input clk;
  wire clk;
  input enable;
  wire enable;
  output enter_fallback;
  wire enter_fallback;
  wire enter_fallback_r;
  input [15:0] fault_status_in;
  wire [15:0] fault_status_in;
  output [15:0] fault_status_out;
  wire [15:0] fault_status_out;
  reg [15:0] fault_status_r;
  output [2:0] fsm_state;
  wire [2:0] fsm_state;
  output idle_safe;
  wire idle_safe;
  wire idle_safe_r;
  output issue_request;
  wire issue_request;
  wire issue_request_r;
  output latch_fault;
  wire latch_fault;
  wire latch_fault_r;
  input [2:0] mode_select;
  wire [2:0] mode_select;
  input outstanding_timer_expired;
  wire outstanding_timer_expired;
  input req_issued;
  wire req_issued;
  input rsp_accepted;
  wire rsp_accepted;
  input rsp_duplicate;
  wire rsp_duplicate;
  input rsp_malformed;
  wire rsp_malformed;
  input rsp_seq_mismatch;
  wire rsp_seq_mismatch;
  input rsp_stale;
  wire rsp_stale;
  input rst_n;
  wire rst_n;
  input service_unavailable;
  wire service_unavailable;
  wire [2:0] state_n;
  reg [2:0] state_r;
  output validate_response;
  wire validate_response;
  wire validate_response_r;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) fault_status_r[0] <= 1'h1;
    else if (_016_) fault_status_r[0] <= _000_[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) fault_status_r[1] <= 1'h0;
    else if (_017_) fault_status_r[1] <= _000_[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) fault_status_r[3] <= 1'h0;
    else if (_018_) fault_status_r[3] <= _000_[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) fault_status_r[4] <= 1'h0;
    else if (_019_) fault_status_r[4] <= _000_[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) fault_status_r[5] <= 1'h0;
    else if (_020_) fault_status_r[5] <= _000_[5];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) fault_status_r[6] <= 1'h0;
    else if (_021_) fault_status_r[6] <= _000_[6];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) fault_status_r[2] <= 1'h0;
    else if (_022_) fault_status_r[2] <= _000_[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) fault_status_r[15:7] <= 9'h000;
    else if (_023_) fault_status_r[15:7] <= _000_[15:7];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_r <= 3'h0;
    else if (_028_) state_r <= state_n;
  assign _016_ = | { _047_, _039_, rsp_malformed };
  assign _017_ = | { _047_, _039_, rsp_stale };
  assign _018_ = | { _047_, _039_, outstanding_timer_expired };
  assign _019_ = | { _047_, _039_, service_unavailable };
  assign _020_ = | { _047_, _039_, candidate_invalid };
  assign _021_ = | { _047_, _039_, candidate_fallback };
  assign _022_ = | { _047_, _039_, _046_ };
  assign _023_ = | { _047_, _039_ };
  assign _024_ = { _067_, _040_, enable } != 3'h4;
  assign _025_ = { _066_, _044_, rsp_accepted } != 3'h4;
  assign _026_ = { _065_, candidate_fallback, candidate_invalid, candidate_valid } != 4'h8;
  assign _027_ = ~ _064_;
  assign _028_ = & { _027_, _026_, _025_, _024_ };
  assign _029_ = | { _071_, _070_, _069_, _068_, _067_, _066_, _064_ };
  assign _030_ = | { _068_, _064_ };
  assign _031_ = | { _071_, _070_, _069_, _067_, _065_ };
  assign _032_ = | { _071_, _069_, _068_, _066_, _065_, _064_ };
  assign _033_ = | { _070_, _069_, _068_, _066_, _065_, _064_ };
  assign _034_ = | { _071_, _067_ };
  assign _035_ = | { _071_, _069_ };
  assign _036_ = | { _071_, _070_, _068_, _067_, _066_, _064_ };
  assign _037_ = | { _071_, _070_, _069_, _067_, _064_ };
  assign _038_ = ! fault_status_in;
  assign _039_ = clear_faults && idle_safe_r;
  assign _040_ = clear_faults && _038_;
  assign _041_ = _045_ || rsp_stale;
  assign _042_ = _041_ || rsp_seq_mismatch;
  assign _043_ = _042_ || rsp_duplicate;
  assign _044_ = _043_ || service_unavailable;
  assign _045_ = outstanding_timer_expired || rsp_malformed;
  assign _046_ = rsp_seq_mismatch || rsp_duplicate;
  assign _047_ = | fault_status_in;
  assign _048_ = fault_status_r | fault_status_in;
  assign _049_ = _039_ ? 9'h000 : 9'hxxx;
  assign _000_[15:7] = _047_ ? _048_[15:7] : _049_;
  assign _050_ = service_unavailable ? 1'h1 : 1'hx;
  assign _051_ = _039_ ? 1'h0 : _050_;
  assign _000_[4] = _047_ ? _048_[4] : _051_;
  assign _052_ = outstanding_timer_expired ? 1'h1 : 1'hx;
  assign _053_ = _039_ ? 1'h0 : _052_;
  assign _000_[3] = _047_ ? _048_[3] : _053_;
  assign _054_ = _046_ ? 1'h1 : 1'hx;
  assign _055_ = _039_ ? 1'h0 : _054_;
  assign _000_[2] = _047_ ? _048_[2] : _055_;
  assign _056_ = rsp_stale ? 1'h1 : 1'hx;
  assign _057_ = _039_ ? 1'h0 : _056_;
  assign _000_[1] = _047_ ? _048_[1] : _057_;
  assign _058_ = rsp_malformed ? 1'h1 : 1'hx;
  assign _059_ = _039_ ? 1'h0 : _058_;
  assign _000_[0] = _047_ ? _048_[0] : _059_;
  assign _060_ = candidate_fallback ? 1'h1 : 1'hx;
  assign _061_ = _039_ ? 1'h0 : _060_;
  assign _000_[6] = _047_ ? _048_[6] : _061_;
  assign _062_ = candidate_invalid ? 1'h1 : 1'hx;
  assign _063_ = _039_ ? 1'h0 : _062_;
  assign _000_[5] = _047_ ? _048_[5] : _063_;
  assign _015_ = candidate_fallback ? 3'h6 : 3'hx;
  assign _011_ = candidate_fallback ? 1'h1 : 1'h0;
  assign _014_ = candidate_valid ? 3'h5 : _015_;
  assign _005_ = candidate_valid ? 1'h1 : 1'h0;
  assign _009_ = candidate_valid ? 1'h0 : _011_;
  assign _013_ = candidate_invalid ? 3'h6 : _014_;
  assign _006_ = candidate_invalid ? 1'h1 : _009_;
  assign _001_ = candidate_invalid ? 1'h0 : _005_;
  assign _012_ = rsp_accepted ? 3'h4 : 3'hx;
  assign _010_ = _044_ ? 3'h7 : _012_;
  assign _002_ = _044_ ? 1'h1 : 1'h0;
  assign _008_ = enable ? 3'h2 : 3'hx;
  assign _007_ = enable ? 1'h1 : 1'h0;
  assign _004_ = _040_ ? 3'h1 : _008_;
  assign _003_ = _040_ ? 1'h0 : _007_;
  function [2:0] _152_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    casez (s) // synopsys parallel_case
      6'b?????1:
        _152_ = b[2:0];
      6'b????1?:
        _152_ = b[5:3];
      6'b???1??:
        _152_ = b[8:6];
      6'b??1???:
        _152_ = b[11:9];
      6'b?1????:
        _152_ = b[14:12];
      6'b1?????:
        _152_ = b[17:15];
      default:
        _152_ = a;
    endcase
  endfunction
  assign state_n = _152_(3'hx, { _004_, 3'h3, _010_, _013_, 6'h0f }, { _067_, _070_, _066_, _065_, _035_, _068_ });
  function [0:0] _153_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _153_ = b[0:0];
      2'b1?:
        _153_ = b[1:1];
      default:
        _153_ = a;
    endcase
  endfunction
  assign idle_safe_r = _153_(1'hx, 2'h2, { _034_, _033_ });
  function [0:0] _154_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _154_ = b[0:0];
      3'b?1?:
        _154_ = b[1:1];
      3'b1??:
        _154_ = b[2:2];
      default:
        _154_ = a;
    endcase
  endfunction
  assign latch_fault = _154_(1'hx, { _002_, 2'h1 }, { _066_, _031_, _030_ });
  function [0:0] _155_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _155_ = b[0:0];
      4'b??1?:
        _155_ = b[1:1];
      4'b?1??:
        _155_ = b[2:2];
      4'b1???:
        _155_ = b[3:3];
      default:
        _155_ = a;
    endcase
  endfunction
  assign enter_fallback = _155_(1'hx, { _002_, _006_, 2'h2 }, { _066_, _065_, _068_, _037_ });
  function [0:0] _156_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _156_ = b[0:0];
      3'b?1?:
        _156_ = b[1:1];
      3'b1??:
        _156_ = b[2:2];
      default:
        _156_ = a;
    endcase
  endfunction
  assign apply_command = _156_(1'hx, { _001_, 2'h2 }, { _065_, _069_, _036_ });
  function [0:0] _157_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _157_ = b[0:0];
      2'b1?:
        _157_ = b[1:1];
      default:
        _157_ = a;
    endcase
  endfunction
  assign validate_response = _157_(1'hx, 2'h2, { _065_, _029_ });
  function [0:0] _158_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _158_ = b[0:0];
      3'b?1?:
        _158_ = b[1:1];
      3'b1??:
        _158_ = b[2:2];
      default:
        _158_ = a;
    endcase
  endfunction
  assign issue_request = _158_(1'hx, { _003_, 2'h2 }, { _067_, _070_, _032_ });
  assign _064_ = state_r == 3'h7;
  assign _068_ = state_r == 3'h6;
  assign _069_ = state_r == 3'h5;
  assign _065_ = state_r == 3'h4;
  assign _066_ = state_r == 3'h3;
  assign _070_ = state_r == 3'h2;
  assign _067_ = state_r == 3'h1;
  assign _071_ = ! state_r;
  assign apply_command_r = apply_command;
  assign enter_fallback_r = enter_fallback;
  assign fault_status_out = fault_status_r;
  assign fsm_state = state_r;
  assign idle_safe = idle_safe_r;
  assign issue_request_r = issue_request;
  assign latch_fault_r = latch_fault;
  assign validate_response_r = validate_response;
endmodule

module adaptive_aero_control_top(clk, rst_n, cfg_wr_en, cfg_rd_en, cfg_addr, cfg_wdata, cfg_rdata, req_stream_valid, req_stream_ready, req_stream_data, rsp_stream_valid, rsp_stream_ready, rsp_stream_data, actuator_cmd_valid, actuator_cmd_ready, actuator_cmd_data);
  wire _0_;
  wire _1_;
  output [31:0] actuator_cmd_data;
  wire [31:0] actuator_cmd_data;
  input actuator_cmd_ready;
  wire actuator_cmd_ready;
  output actuator_cmd_valid;
  wire actuator_cmd_valid;
  wire apply_command;
  wire [15:0] candidate_cmd;
  wire candidate_fallback;
  wire candidate_invalid;
  wire candidate_valid;
  input [5:0] cfg_addr;
  wire [5:0] cfg_addr;
  input cfg_rd_en;
  wire cfg_rd_en;
  output [63:0] cfg_rdata;
  wire [63:0] cfg_rdata;
  input [63:0] cfg_wdata;
  wire [63:0] cfg_wdata;
  input cfg_wr_en;
  wire cfg_wr_en;
  wire clear_faults;
  input clk;
  wire clk;
  wire [15:0] cmd_bounded;
  wire cmd_clamped_high;
  wire cmd_clamped_low;
  wire cmd_valid;
  wire enable;
  wire enter_fallback;
  wire [3:0] fallback_mode;
  wire fallback_selected;
  wire [15:0] fault_status;
  wire [7:0] freshness_limit;
  wire [2:0] fsm_state;
  wire idle_safe;
  wire issue_request;
  wire latch_fault;
  wire [15:0] max_cmd;
  wire [15:0] min_cmd;
  wire [2:0] mode_select;
  wire [7:0] outstanding_age;
  wire [15:0] outstanding_seq;
  wire outstanding_timer_expired;
  wire outstanding_valid;
  wire [15:0] rate_limit;
  wire rate_limited;
  wire [7:0] req_age_tag;
  wire [15:0] req_handle;
  wire req_issued;
  wire [31:0] req_metadata;
  wire [15:0] req_seq;
  output [127:0] req_stream_data;
  wire [127:0] req_stream_data;
  input req_stream_ready;
  wire req_stream_ready;
  output req_stream_valid;
  wire req_stream_valid;
  wire rsp_accepted;
  wire [7:0] rsp_age_tag;
  wire rsp_duplicate;
  wire [15:0] rsp_handle;
  wire rsp_malformed;
  wire [31:0] rsp_metadata;
  wire [15:0] rsp_seq;
  wire rsp_seq_mismatch;
  wire rsp_stale;
  input [127:0] rsp_stream_data;
  wire [127:0] rsp_stream_data;
  output rsp_stream_ready;
  wire rsp_stream_ready;
  input rsp_stream_valid;
  wire rsp_stream_valid;
  input rst_n;
  wire rst_n;
  wire [15:0] sequence_counter;
  wire service_unavailable;
  wire [7:0] timeout_limit;
  wire transport_fault;
  wire validate_response;
  assign actuator_cmd_valid = cmd_valid & _1_;
  assign _0_ = apply_command | candidate_fallback;
  assign _1_ = _0_ | fallback_selected;
  adaptive_aero_control_csr u_csr (
    .cfg_addr(cfg_addr),
    .cfg_rd_en(cfg_rd_en),
    .cfg_rdata(cfg_rdata),
    .cfg_wdata(cfg_wdata),
    .cfg_wr_en(cfg_wr_en),
    .clear_faults(clear_faults),
    .clk(clk),
    .enable(enable),
    .fallback_mode(fallback_mode),
    .fault_status(fault_status),
    .freshness_limit(freshness_limit),
    .idle_safe(idle_safe),
    .max_cmd(max_cmd),
    .min_cmd(min_cmd),
    .mode_select(mode_select),
    .rate_limit(rate_limit),
    .rst_n(rst_n),
    .sequence_counter(sequence_counter),
    .timeout_limit(timeout_limit)
  );
  adaptive_aero_control_fsm u_fsm (
    .apply_command(apply_command),
    .candidate_fallback(candidate_fallback),
    .candidate_invalid(candidate_invalid),
    .candidate_valid(candidate_valid),
    .clear_faults(clear_faults),
    .clk(clk),
    .enable(enable),
    .enter_fallback(enter_fallback),
    .fault_status_in(fault_status),
    .fault_status_out(fault_status),
    .fsm_state(fsm_state),
    .idle_safe(idle_safe),
    .issue_request(issue_request),
    .latch_fault(latch_fault),
    .mode_select(mode_select),
    .outstanding_timer_expired(outstanding_timer_expired),
    .req_issued(req_issued),
    .rsp_accepted(rsp_accepted),
    .rsp_duplicate(rsp_duplicate),
    .rsp_malformed(rsp_malformed),
    .rsp_seq_mismatch(rsp_seq_mismatch),
    .rsp_stale(rsp_stale),
    .rst_n(rst_n),
    .service_unavailable(service_unavailable),
    .validate_response(validate_response)
  );
  adaptive_aero_control_transport u_transport (
    .clk(clk),
    .enable(enable),
    .freshness_limit(freshness_limit),
    .mode_select(mode_select),
    .outstanding_age(outstanding_age),
    .outstanding_seq(outstanding_seq),
    .outstanding_timer_expired(outstanding_timer_expired),
    .outstanding_valid(outstanding_valid),
    .req_age_tag(req_age_tag),
    .req_handle(req_handle),
    .req_issued(req_issued),
    .req_metadata(req_metadata),
    .req_seq(req_seq),
    .req_stream_data(req_stream_data),
    .req_stream_ready(req_stream_ready),
    .req_stream_valid(req_stream_valid),
    .rsp_accepted(rsp_accepted),
    .rsp_age_tag(rsp_age_tag),
    .rsp_duplicate(rsp_duplicate),
    .rsp_handle(rsp_handle),
    .rsp_malformed(rsp_malformed),
    .rsp_metadata(rsp_metadata),
    .rsp_seq(rsp_seq),
    .rsp_seq_mismatch(rsp_seq_mismatch),
    .rsp_stale(rsp_stale),
    .rsp_stream_data(rsp_stream_data),
    .rsp_stream_ready(rsp_stream_ready),
    .rsp_stream_valid(rsp_stream_valid),
    .rst_n(rst_n),
    .sequence_counter(sequence_counter),
    .timeout_limit(timeout_limit),
    .transport_fault(transport_fault)
  );
  adaptive_aero_control_validator u_validator (
    .candidate_cmd(candidate_cmd),
    .candidate_fallback(candidate_fallback),
    .candidate_invalid(candidate_invalid),
    .candidate_valid(candidate_valid),
    .clk(clk),
    .cmd_bounded(cmd_bounded),
    .cmd_clamped_high(cmd_clamped_high),
    .cmd_clamped_low(cmd_clamped_low),
    .cmd_valid(cmd_valid),
    .enable(enable),
    .fallback_mode(fallback_mode),
    .fallback_selected(fallback_selected),
    .max_cmd(max_cmd),
    .min_cmd(min_cmd),
    .mode_select(mode_select),
    .outstanding_timer_expired(outstanding_timer_expired),
    .rate_limit(rate_limit),
    .rate_limited(rate_limited),
    .rsp_accepted(rsp_accepted),
    .rsp_age_tag(rsp_age_tag),
    .rsp_duplicate(rsp_duplicate),
    .rsp_handle(rsp_handle),
    .rsp_malformed(rsp_malformed),
    .rsp_metadata(rsp_metadata),
    .rsp_seq(rsp_seq),
    .rsp_seq_mismatch(rsp_seq_mismatch),
    .rsp_stale(rsp_stale),
    .rst_n(rst_n),
    .service_unavailable(service_unavailable),
    .transport_fault(transport_fault)
  );
  assign actuator_cmd_data = { 16'h0000, candidate_cmd };
endmodule

module adaptive_aero_control_top_spi_fpga_top(clk, reset_n, spi_sclk, spi_cs_n, spi_mosi, spi_miso, fault_indicator);
  wire _00_;
  wire _01_;
  wire [226:0] _02_;
  input clk;
  wire clk;
  wire [31:0] core_actuator_cmd_data;
  wire core_actuator_cmd_ready;
  wire core_actuator_cmd_valid;
  wire [5:0] core_cfg_addr;
  wire core_cfg_rd_en;
  wire [63:0] core_cfg_rdata;
  wire [63:0] core_cfg_wdata;
  wire core_cfg_wr_en;
  wire [127:0] core_req_stream_data;
  wire core_req_stream_ready;
  wire core_req_stream_valid;
  wire [226:0] core_response;
  wire [127:0] core_rsp_stream_data;
  wire core_rsp_stream_ready;
  wire core_rsp_stream_valid;
  output fault_indicator;
  wire fault_indicator;
  input reset_n;
  wire reset_n;
  reg [202:0] rx_active;
  reg [202:0] rx_shift;
  reg spi_active;
  reg spi_cs_meta;
  input spi_cs_n;
  wire spi_cs_n;
  reg spi_cs_prev;
  reg spi_cs_sync;
  output spi_miso;
  wire spi_miso;
  input spi_mosi;
  wire spi_mosi;
  input spi_sclk;
  wire spi_sclk;
  reg [226:0] tx_shift;
  reg [226:0] tx_snapshot;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) rx_active <= 203'h000000000000000000000000000000000000000000000000000;
    else if (_00_) rx_active <= rx_shift;
  always @(posedge spi_sclk)
    if (!spi_cs_n) rx_shift <= { rx_shift[201:0], spi_mosi };
  always @(posedge spi_sclk)
    if (!spi_cs_n) tx_shift <= _02_;
  assign _00_ = spi_cs_sync && _01_;
  assign _01_ = ! spi_cs_prev;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) tx_snapshot <= 227'h000000000000000000000000000000000000000000000000000000000;
    else tx_snapshot <= { core_cfg_rdata, core_req_stream_valid, core_req_stream_data, core_rsp_stream_ready, core_actuator_cmd_valid, core_actuator_cmd_data };
  always @(posedge clk, negedge reset_n)
    if (!reset_n) spi_cs_meta <= 1'h1;
    else spi_cs_meta <= spi_cs_n;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) spi_cs_sync <= 1'h1;
    else spi_cs_sync <= spi_cs_meta;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) spi_cs_prev <= 1'h1;
    else spi_cs_prev <= spi_cs_sync;
  always @(posedge spi_sclk, posedge spi_cs_n)
    if (spi_cs_n) spi_active <= 1'h0;
    else spi_active <= 1'h1;
  assign _02_ = spi_active ? { tx_shift[225:0], 1'h0 } : { tx_snapshot[225:0], 1'h0 };
  assign spi_miso = spi_active ? tx_shift[226] : tx_snapshot[226];
  adaptive_aero_control_top u_core (
    .actuator_cmd_data(core_actuator_cmd_data),
    .actuator_cmd_ready(rx_active[202]),
    .actuator_cmd_valid(core_actuator_cmd_valid),
    .cfg_addr(rx_active[7:2]),
    .cfg_rd_en(rx_active[1]),
    .cfg_rdata(core_cfg_rdata),
    .cfg_wdata(rx_active[71:8]),
    .cfg_wr_en(rx_active[0]),
    .clk(clk),
    .req_stream_data(core_req_stream_data),
    .req_stream_ready(rx_active[72]),
    .req_stream_valid(core_req_stream_valid),
    .rsp_stream_data(rx_active[201:74]),
    .rsp_stream_ready(core_rsp_stream_ready),
    .rsp_stream_valid(rx_active[73]),
    .rst_n(reset_n)
  );
  assign core_actuator_cmd_ready = rx_active[202];
  assign core_cfg_addr = rx_active[7:2];
  assign core_cfg_rd_en = rx_active[1];
  assign core_cfg_wdata = rx_active[71:8];
  assign core_cfg_wr_en = rx_active[0];
  assign core_req_stream_ready = rx_active[72];
  assign core_response = { core_cfg_rdata, core_req_stream_valid, core_req_stream_data, core_rsp_stream_ready, core_actuator_cmd_valid, core_actuator_cmd_data };
  assign core_rsp_stream_data = rx_active[201:74];
  assign core_rsp_stream_valid = rx_active[73];
  assign fault_indicator = 1'h0;
endmodule

module adaptive_aero_control_transport(clk, rst_n, enable, mode_select, freshness_limit, timeout_limit, sequence_counter, req_stream_valid, req_stream_ready, req_stream_data, rsp_stream_valid, rsp_stream_ready, rsp_stream_data, req_issued, req_seq, req_age_tag, req_metadata, req_handle, rsp_accepted, rsp_seq, rsp_age_tag
, rsp_metadata, rsp_handle, rsp_malformed, rsp_stale, rsp_seq_mismatch, rsp_duplicate, outstanding_valid, outstanding_seq, outstanding_age, outstanding_timer_expired, transport_fault);
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire [7:0] _011_;
  wire _012_;
  wire [7:0] _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire [7:0] _047_;
  wire [7:0] _048_;
  wire [7:0] _049_;
  wire [7:0] _050_;
  wire [7:0] _051_;
  wire [7:0] _052_;
  wire [7:0] _053_;
  wire [7:0] _054_;
  wire [7:0] _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  reg [7:0] age_counter_r;
  input clk;
  wire clk;
  input enable;
  wire enable;
  input [7:0] freshness_limit;
  wire [7:0] freshness_limit;
  input [2:0] mode_select;
  wire [2:0] mode_select;
  output [7:0] outstanding_age;
  wire [7:0] outstanding_age;
  reg [7:0] outstanding_age_r;
  output [15:0] outstanding_seq;
  wire [15:0] outstanding_seq;
  reg [15:0] outstanding_seq_r;
  output outstanding_timer_expired;
  wire outstanding_timer_expired;
  reg outstanding_timer_expired_r;
  output outstanding_valid;
  wire outstanding_valid;
  reg outstanding_valid_r;
  output [7:0] req_age_tag;
  wire [7:0] req_age_tag;
  reg [7:0] req_age_tag_r;
  output [15:0] req_handle;
  wire [15:0] req_handle;
  wire [15:0] req_handle_r;
  output req_issued;
  wire req_issued;
  reg req_issued_r;
  output [31:0] req_metadata;
  wire [31:0] req_metadata;
  wire [31:0] req_metadata_r;
  output [15:0] req_seq;
  wire [15:0] req_seq;
  reg [15:0] req_seq_r;
  output [127:0] req_stream_data;
  wire [127:0] req_stream_data;
  wire [127:0] req_stream_data_r;
  input req_stream_ready;
  wire req_stream_ready;
  output req_stream_valid;
  wire req_stream_valid;
  reg req_stream_valid_r;
  output rsp_accepted;
  wire rsp_accepted;
  reg rsp_accepted_r;
  output [7:0] rsp_age_tag;
  wire [7:0] rsp_age_tag;
  reg [7:0] rsp_age_tag_r;
  output rsp_duplicate;
  wire rsp_duplicate;
  reg rsp_duplicate_r;
  output [15:0] rsp_handle;
  wire [15:0] rsp_handle;
  reg [15:0] rsp_handle_r;
  output rsp_malformed;
  wire rsp_malformed;
  reg rsp_malformed_r;
  output [31:0] rsp_metadata;
  wire [31:0] rsp_metadata;
  reg [31:0] rsp_metadata_r;
  reg rsp_seen_r;
  output [15:0] rsp_seq;
  wire [15:0] rsp_seq;
  output rsp_seq_mismatch;
  wire rsp_seq_mismatch;
  reg rsp_seq_mismatch_r;
  reg [15:0] rsp_seq_r;
  output rsp_stale;
  wire rsp_stale;
  reg rsp_stale_r;
  input [127:0] rsp_stream_data;
  wire [127:0] rsp_stream_data;
  output rsp_stream_ready;
  wire rsp_stream_ready;
  wire rsp_stream_ready_r;
  input rsp_stream_valid;
  wire rsp_stream_valid;
  input rst_n;
  wire rst_n;
  input [15:0] sequence_counter;
  wire [15:0] sequence_counter;
  input [7:0] timeout_limit;
  wire [7:0] timeout_limit;
  reg [7:0] timer_r;
  output transport_fault;
  wire transport_fault;
  reg transport_fault_r;
  assign _013_ = timer_r + 8'h01;
  assign _000_ = age_counter_r + 8'h01;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rsp_seen_r <= 1'h0;
    else if (_014_) rsp_seen_r <= _008_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rsp_seq_r <= 16'h0000;
    else if (rsp_stream_valid) rsp_seq_r <= rsp_stream_data[15:0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) outstanding_age_r <= 8'h00;
    else if (_015_) outstanding_age_r <= age_counter_r;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rsp_age_tag_r <= 8'h00;
    else if (rsp_stream_valid) rsp_age_tag_r <= rsp_stream_data[23:16];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) req_seq_r <= 16'h0000;
    else if (_019_) req_seq_r <= sequence_counter;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rsp_metadata_r <= 32'd0;
    else if (rsp_stream_valid) rsp_metadata_r <= rsp_stream_data[55:24];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) req_age_tag_r <= 8'h00;
    else if (_019_) req_age_tag_r <= age_counter_r;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rsp_handle_r <= 16'h0000;
    else if (rsp_stream_valid) rsp_handle_r <= rsp_stream_data[71:56];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) outstanding_seq_r <= 16'h0000;
    else if (_015_) outstanding_seq_r <= sequence_counter;
  reg [18:0] _076_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) _076_ <= 19'h00000;
    else if (_019_) _076_ <= { mode_select, freshness_limit, timeout_limit };
  assign req_metadata_r[31:13] = _076_;
  reg [58:0] _077_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) _077_ <= 59'h000000000000000;
    else if (_019_) _077_ <= { sequence_counter, age_counter_r, mode_select, freshness_limit, timeout_limit, sequence_counter };
  assign { req_stream_data_r[119:77], req_stream_data_r[63:48] } = _077_;
  assign _014_ = | { _020_, rsp_stream_valid };
  assign _015_ = & { _019_, req_stream_ready };
  assign _016_ = timer_r == timeout_limit;
  assign _017_ = rsp_stream_data[127:120] == 8'ha5;
  assign _018_ = rsp_stream_data[23:16] > freshness_limit;
  assign _019_ = enable && _021_;
  assign _020_ = rsp_seen_r && _022_;
  assign _021_ = ! outstanding_valid_r;
  assign _022_ = ! rsp_stream_valid;
  assign _023_ = rsp_stream_data[15:0] != outstanding_seq_r;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) req_stream_valid_r <= 1'h0;
    else req_stream_valid_r <= _004_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) req_issued_r <= 1'h0;
    else req_issued_r <= _003_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rsp_accepted_r <= 1'h0;
    else rsp_accepted_r <= _005_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rsp_malformed_r <= 1'h0;
    else rsp_malformed_r <= _007_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rsp_stale_r <= 1'h0;
    else rsp_stale_r <= _010_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rsp_seq_mismatch_r <= 1'h0;
    else rsp_seq_mismatch_r <= _009_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rsp_duplicate_r <= 1'h0;
    else rsp_duplicate_r <= _006_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) outstanding_valid_r <= 1'h0;
    else outstanding_valid_r <= _002_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) outstanding_timer_expired_r <= 1'h0;
    else outstanding_timer_expired_r <= _001_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) transport_fault_r <= 1'h0;
    else transport_fault_r <= _012_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_r <= 8'h00;
    else timer_r <= _011_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) age_counter_r <= 8'h00;
    else age_counter_r <= _000_;
  assign _024_ = req_stream_ready ? 1'h0 : 1'h1;
  assign _004_ = _019_ ? _024_ : 1'h0;
  assign _026_ = _017_ ? _001_ : 1'h1;
  assign _012_ = rsp_stream_valid ? _026_ : _001_;
  assign _025_ = _016_ ? 1'h1 : 1'h0;
  assign _001_ = outstanding_valid_r ? _025_ : 1'h0;
  assign _027_ = rsp_seen_r ? 1'h1 : 1'h0;
  assign _028_ = _018_ ? 1'h0 : _027_;
  assign _029_ = _023_ ? 1'h0 : _028_;
  assign _030_ = outstanding_valid_r ? _029_ : 1'h0;
  assign _031_ = _017_ ? _030_ : 1'h0;
  assign _006_ = rsp_stream_valid ? _031_ : 1'h0;
  assign _032_ = _023_ ? 1'h1 : 1'h0;
  assign _033_ = outstanding_valid_r ? _032_ : 1'h0;
  assign _034_ = _017_ ? _033_ : 1'h0;
  assign _009_ = rsp_stream_valid ? _034_ : 1'h0;
  assign _035_ = _018_ ? 1'h1 : 1'h0;
  assign _036_ = _023_ ? 1'h1 : _035_;
  assign _037_ = outstanding_valid_r ? _036_ : 1'h1;
  assign _038_ = _017_ ? _037_ : 1'h0;
  assign _010_ = rsp_stream_valid ? _038_ : 1'h0;
  assign _039_ = _017_ ? 1'h0 : 1'h1;
  assign _007_ = rsp_stream_valid ? _039_ : 1'h0;
  assign _040_ = rsp_seen_r ? 1'h0 : 1'h1;
  assign _041_ = _018_ ? 1'h0 : _040_;
  assign _042_ = _023_ ? 1'h0 : _041_;
  assign _043_ = outstanding_valid_r ? _042_ : 1'h0;
  assign _044_ = _017_ ? _043_ : 1'h0;
  assign _005_ = rsp_stream_valid ? _044_ : 1'h0;
  assign _045_ = req_stream_ready ? 1'h1 : 1'h0;
  assign _003_ = _019_ ? _045_ : 1'h0;
  assign _046_ = rsp_stream_valid ? 1'h1 : 1'hx;
  assign _008_ = _020_ ? 1'h0 : _046_;
  assign _047_ = req_stream_ready ? 8'h00 : timer_r;
  assign _048_ = _019_ ? _047_ : timer_r;
  assign _049_ = _016_ ? _048_ : _013_;
  assign _050_ = outstanding_valid_r ? _049_ : 8'h00;
  assign _051_ = rsp_seen_r ? _050_ : 8'h00;
  assign _052_ = _018_ ? _050_ : _051_;
  assign _053_ = _023_ ? _050_ : _052_;
  assign _054_ = outstanding_valid_r ? _053_ : _050_;
  assign _055_ = _017_ ? _054_ : _050_;
  assign _011_ = rsp_stream_valid ? _055_ : _050_;
  assign _056_ = req_stream_ready ? 1'h1 : outstanding_valid_r;
  assign _057_ = _019_ ? _056_ : outstanding_valid_r;
  assign _058_ = _016_ ? 1'h0 : _057_;
  assign _059_ = outstanding_valid_r ? _058_ : _057_;
  assign _060_ = rsp_seen_r ? _059_ : 1'h0;
  assign _061_ = _018_ ? _059_ : _060_;
  assign _062_ = _023_ ? _059_ : _061_;
  assign _063_ = outstanding_valid_r ? _062_ : _059_;
  assign _064_ = _017_ ? _063_ : _059_;
  assign _002_ = rsp_stream_valid ? _064_ : _059_;
  assign outstanding_age = outstanding_age_r;
  assign outstanding_seq = outstanding_seq_r;
  assign outstanding_timer_expired = outstanding_timer_expired_r;
  assign outstanding_valid = outstanding_valid_r;
  assign req_age_tag = req_age_tag_r;
  assign req_handle = req_seq_r;
  assign req_handle_r = req_seq_r;
  assign req_issued = req_issued_r;
  assign req_metadata = { req_metadata_r[31:13], 13'h0000 };
  assign req_metadata_r[12:0] = 13'h0000;
  assign req_seq = req_seq_r;
  assign req_stream_data = { 8'h00, req_stream_data_r[119:77], 13'h0000, req_stream_data_r[63:48], 48'h000000000000 };
  assign { req_stream_data_r[127:120], req_stream_data_r[76:64], req_stream_data_r[47:0] } = 69'h000000000000000000;
  assign req_stream_valid = req_stream_valid_r;
  assign rsp_accepted = rsp_accepted_r;
  assign rsp_age_tag = rsp_age_tag_r;
  assign rsp_duplicate = rsp_duplicate_r;
  assign rsp_handle = rsp_handle_r;
  assign rsp_malformed = rsp_malformed_r;
  assign rsp_metadata = rsp_metadata_r;
  assign rsp_seq = rsp_seq_r;
  assign rsp_seq_mismatch = rsp_seq_mismatch_r;
  assign rsp_stale = rsp_stale_r;
  assign rsp_stream_ready = 1'h1;
  assign rsp_stream_ready_r = 1'h1;
  assign transport_fault = transport_fault_r;
endmodule

module adaptive_aero_control_validator(clk, rst_n, enable, mode_select, max_cmd, min_cmd, rate_limit, fallback_mode, rsp_accepted, rsp_seq, rsp_age_tag, rsp_metadata, rsp_handle, rsp_malformed, rsp_stale, rsp_seq_mismatch, rsp_duplicate, outstanding_timer_expired, transport_fault, candidate_cmd, candidate_valid
, candidate_fallback, candidate_invalid, cmd_bounded, cmd_valid, cmd_clamped_low, cmd_clamped_high, rate_limited, service_unavailable, fallback_selected);
  wire [15:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire [15:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire [15:0] _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire [15:0] _035_;
  wire [15:0] _036_;
  wire [15:0] _037_;
  wire [15:0] _038_;
  wire [15:0] _039_;
  wire [15:0] _040_;
  wire [15:0] _041_;
  wire [15:0] _042_;
  wire [15:0] _043_;
  wire [15:0] _044_;
  wire [15:0] _045_;
  output [15:0] candidate_cmd;
  wire [15:0] candidate_cmd;
  reg [15:0] candidate_cmd_r;
  output candidate_fallback;
  wire candidate_fallback;
  wire candidate_fallback_r;
  output candidate_invalid;
  wire candidate_invalid;
  reg candidate_invalid_r;
  output candidate_valid;
  wire candidate_valid;
  reg candidate_valid_r;
  input clk;
  wire clk;
  output [15:0] cmd_bounded;
  wire [15:0] cmd_bounded;
  reg [15:0] cmd_bounded_r;
  output cmd_clamped_high;
  wire cmd_clamped_high;
  reg cmd_clamped_high_r;
  output cmd_clamped_low;
  wire cmd_clamped_low;
  reg cmd_clamped_low_r;
  output cmd_valid;
  wire cmd_valid;
  reg cmd_valid_r;
  input enable;
  wire enable;
  input [3:0] fallback_mode;
  wire [3:0] fallback_mode;
  output fallback_selected;
  wire fallback_selected;
  reg fallback_selected_r;
  reg [15:0] last_cmd_r;
  input [15:0] max_cmd;
  wire [15:0] max_cmd;
  input [15:0] min_cmd;
  wire [15:0] min_cmd;
  input [2:0] mode_select;
  wire [2:0] mode_select;
  input outstanding_timer_expired;
  wire outstanding_timer_expired;
  input [15:0] rate_limit;
  wire [15:0] rate_limit;
  output rate_limited;
  wire rate_limited;
  reg rate_limited_r;
  wire [15:0] raw_candidate;
  input rsp_accepted;
  wire rsp_accepted;
  input [7:0] rsp_age_tag;
  wire [7:0] rsp_age_tag;
  input rsp_duplicate;
  wire rsp_duplicate;
  input [15:0] rsp_handle;
  wire [15:0] rsp_handle;
  input rsp_malformed;
  wire rsp_malformed;
  input [31:0] rsp_metadata;
  wire [31:0] rsp_metadata;
  input [15:0] rsp_seq;
  wire [15:0] rsp_seq;
  input rsp_seq_mismatch;
  wire rsp_seq_mismatch;
  input rsp_stale;
  wire rsp_stale;
  input rst_n;
  wire rst_n;
  output service_unavailable;
  wire service_unavailable;
  wire service_unavailable_r;
  input transport_fault;
  wire transport_fault;
  assign _009_ = last_cmd_r + rate_limit;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) last_cmd_r <= 16'h0000;
    else if (_010_) last_cmd_r <= cmd_bounded_r;
  assign _011_ = ~ _020_;
  assign _010_ = & { _011_, rsp_accepted };
  assign _012_ = raw_candidate > max_cmd;
  assign _013_ = raw_candidate > _009_;
  assign _014_ = ! enable;
  assign _015_ = _014_ || rsp_malformed;
  assign _016_ = _015_ || rsp_stale;
  assign _017_ = _016_ || rsp_seq_mismatch;
  assign _018_ = _017_ || rsp_duplicate;
  assign _019_ = _018_ || outstanding_timer_expired;
  assign _020_ = _019_ || transport_fault;
  assign _021_ = raw_candidate < min_cmd;
  assign _022_ = raw_candidate < _042_;
  assign _023_ = | rate_limit;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) candidate_cmd_r <= 16'h0000;
    else candidate_cmd_r <= _000_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) candidate_valid_r <= 1'h0;
    else candidate_valid_r <= _003_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) candidate_invalid_r <= 1'h0;
    else candidate_invalid_r <= _002_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_bounded_r <= 16'h0000;
    else cmd_bounded_r <= _004_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_valid_r <= 1'h0;
    else cmd_valid_r <= _007_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_clamped_low_r <= 1'h0;
    else cmd_clamped_low_r <= _006_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_clamped_high_r <= 1'h0;
    else cmd_clamped_high_r <= _005_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rate_limited_r <= 1'h0;
    else rate_limited_r <= _008_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) fallback_selected_r <= 1'h1;
    else fallback_selected_r <= _001_;
  assign _025_ = _022_ ? 1'h1 : 1'h0;
  assign _026_ = _013_ ? 1'h1 : _025_;
  assign _027_ = _023_ ? _026_ : 1'h0;
  assign _028_ = rsp_accepted ? _027_ : 1'h0;
  assign _008_ = _020_ ? 1'h0 : _028_;
  assign _029_ = _012_ ? 1'h1 : 1'h0;
  assign _030_ = rsp_accepted ? _029_ : 1'h0;
  assign _005_ = _020_ ? 1'h0 : _030_;
  assign _031_ = _021_ ? 1'h1 : 1'h0;
  assign _032_ = _012_ ? 1'h0 : _031_;
  assign _033_ = rsp_accepted ? _032_ : 1'h0;
  assign _006_ = _020_ ? 1'h0 : _033_;
  assign _007_ = _020_ ? 1'h1 : _034_;
  assign _002_ = _020_ ? 1'h1 : 1'h0;
  assign _024_ = rsp_accepted ? 1'h0 : 1'h1;
  assign _001_ = _020_ ? 1'h1 : _024_;
  assign _034_ = rsp_accepted ? 1'h1 : 1'h0;
  assign _003_ = _020_ ? 1'h0 : _034_;
  assign _035_ = rsp_accepted ? raw_candidate : { 12'h000, fallback_mode };
  assign _000_ = _020_ ? { 12'h000, fallback_mode } : _035_;
  assign _036_ = _021_ ? min_cmd : raw_candidate;
  assign _037_ = _012_ ? max_cmd : _036_;
  assign _038_ = _022_ ? _042_ : _037_;
  assign _039_ = _013_ ? _009_ : _038_;
  assign _040_ = _023_ ? _039_ : _037_;
  assign _041_ = rsp_accepted ? _040_ : { 12'h000, fallback_mode };
  assign _004_ = _020_ ? { 12'h000, fallback_mode } : _041_;
  assign _042_ = last_cmd_r - rate_limit;
  assign _043_ = rsp_metadata[15:0] ^ rsp_handle;
  assign _044_ = _043_ ^ { 8'h00, rsp_age_tag };
  assign _045_ = _044_ ^ rsp_seq;
  assign raw_candidate = _045_ ^ { 13'h0000, mode_select };
  assign candidate_cmd = candidate_cmd_r;
  assign candidate_fallback = fallback_selected_r;
  assign candidate_fallback_r = fallback_selected_r;
  assign candidate_invalid = candidate_invalid_r;
  assign candidate_valid = candidate_valid_r;
  assign cmd_bounded = cmd_bounded_r;
  assign cmd_clamped_high = cmd_clamped_high_r;
  assign cmd_clamped_low = cmd_clamped_low_r;
  assign cmd_valid = cmd_valid_r;
  assign fallback_selected = fallback_selected_r;
  assign rate_limited = rate_limited_r;
  assign service_unavailable = fallback_selected_r;
  assign service_unavailable_r = fallback_selected_r;
endmodule
