"""Auto-generated lightweight functional coverage model for sram_mbist_demo_controller

Generated by ChipLoop Functional Coverage Agent.
- Coverage points are derived from spec-declared DUT ports
- No hardcoded DUT signal names
- Works without cocotb-coverage; uses lightweight hit tracking
"""

import json
import os

TB_ROOT = os.path.dirname(__file__)
REPORT_DIR = os.path.join(TB_ROOT, "reports")
os.makedirs(REPORT_DIR, exist_ok=True)


COVERAGE_SPEC = {
  "top_module": "sram_mbist_demo_controller",
  "output_points": [
    {
      "name": "rd_data",
      "direction": "output",
      "width_expr": "32"
    },
    {
      "name": "ready",
      "direction": "output",
      "width_expr": "1"
    },
    {
      "name": "bist_done",
      "direction": "output",
      "width_expr": "1"
    },
    {
      "name": "bist_fail",
      "direction": "output",
      "width_expr": "1"
    },
    {
      "name": "irq",
      "direction": "output",
      "width_expr": "1"
    }
  ],
  "input_points": [
    {
      "name": "clk",
      "direction": "input",
      "width_expr": "1"
    },
    {
      "name": "reset_n",
      "direction": "input",
      "width_expr": "1"
    },
    {
      "name": "wr_en",
      "direction": "input",
      "width_expr": "1"
    },
    {
      "name": "wr_addr",
      "direction": "input",
      "width_expr": "8"
    },
    {
      "name": "wr_data",
      "direction": "input",
      "width_expr": "32"
    },
    {
      "name": "rd_en",
      "direction": "input",
      "width_expr": "1"
    },
    {
      "name": "rd_addr",
      "direction": "input",
      "width_expr": "8"
    },
    {
      "name": "bist_start",
      "direction": "input",
      "width_expr": "1"
    }
  ],
  "user_coverage_plan_points": []
}


def _safe_width_int(sig, width_expr: str) -> int:
    try:
        return max(int(width_expr), 1)
    except Exception:
        try:
            return max(len(sig.value.binstr), 1)
        except Exception:
            return 1


class CoverageModel:
    def __init__(self):
        self.started = False
        self.stopped = False
        self.output_hits = {
            p["name"]: {"seen_values": set(), "samples": 0}
            for p in COVERAGE_SPEC.get("output_points", [])
        }
        self.input_hits = {
            p["name"]: {"seen_values": set(), "samples": 0}
            for p in COVERAGE_SPEC.get("input_points", [])
        }

    def start(self, dut=None):
        self.started = True
        self.dut = dut

    def _sample_group(self, dut, points, target):
        for p in points:
            name = p.get("name")
            if not name or not hasattr(dut, name):
                continue
            try:
                sig = getattr(dut, name)
                width = _safe_width_int(sig, str(p.get("width_expr", "1")))
                value = int(sig.value)
                bucket = target[name]
                bucket["samples"] += 1
                bucket["seen_values"].add(value)

                if width == 1:
                    bucket.setdefault("bin_0", 0)
                    bucket.setdefault("bin_1", 0)
                    if value == 0:
                        bucket["bin_0"] += 1
                    elif value == 1:
                        bucket["bin_1"] += 1
                else:
                    bucket.setdefault("bin_nonzero", 0)
                    bucket.setdefault("bin_zero", 0)
                    if value == 0:
                        bucket["bin_zero"] += 1
                    else:
                        bucket["bin_nonzero"] += 1
            except Exception:
                continue

    def sample(self):
        dut = getattr(self, "dut", None)
        if dut is None:
            return
        self._sample_group(dut, COVERAGE_SPEC.get("output_points", []), self.output_hits)
        self._sample_group(dut, COVERAGE_SPEC.get("input_points", []), self.input_hits)

    def stop(self):
        self.stopped = True

    def summary(self):
        total_bins = 0
        hit_bins = 0
        outputs = {}
        inputs = {}

        for _, source, target in [
            ("outputs", self.output_hits, outputs),
            ("inputs", self.input_hits, inputs),
        ]:
            for name, data in source.items():
                local_total = 0
                local_hit = 0

                if "bin_0" in data:
                    local_total += 2
                    if data.get("bin_0", 0) > 0:
                        local_hit += 1
                    if data.get("bin_1", 0) > 0:
                        local_hit += 1
                else:
                    local_total += 2
                    if data.get("bin_zero", 0) > 0:
                        local_hit += 1
                    if data.get("bin_nonzero", 0) > 0:
                        local_hit += 1

                total_bins += local_total
                hit_bins += local_hit

                target[name] = {
                    "samples": data.get("samples", 0),
                    "seen_values": sorted(list(data.get("seen_values", set()))),
                    "hit_bins": local_hit,
                    "total_bins": local_total,
                }

        pct = round(100.0 * hit_bins / max(total_bins, 1), 2)

        return {
            "type": "functional_coverage_summary",
            "top_module": COVERAGE_SPEC.get("top_module"),
            "functional_coverage_pct": pct,
            "bins_hit": hit_bins,
            "total_bins": total_bins,
            "outputs": outputs,
            "inputs": inputs,
        }

    def write_reports(self):
        summary = self.summary()

        json_path = os.path.join(REPORT_DIR, "functional_coverage_summary.json")
        md_path = os.path.join(REPORT_DIR, "COVERAGE.md")

        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(summary, f, indent=2)

        lines = []
        lines.append("# Functional Coverage Summary")
        lines.append("")
        lines.append(f"- Top module: {summary.get('top_module')}")
        lines.append(f"- Functional coverage: {summary.get('functional_coverage_pct')}%")
        lines.append(f"- Bins hit: {summary.get('bins_hit')}")
        lines.append(f"- Total bins: {summary.get('total_bins')}")
        lines.append("")
        lines.append("## Outputs")
        for name, data in summary.get("outputs", {}).items():
            lines.append(f"- {name}: samples={data.get('samples')}, bins={data.get('hit_bins')}/{data.get('total_bins')}")
        lines.append("")
        lines.append("## Inputs")
        for name, data in summary.get("inputs", {}).items():
            lines.append(f"- {name}: samples={data.get('samples')}, bins={data.get('hit_bins')}/{data.get('total_bins')}")

        with open(md_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
