/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module smart_sensor_hub_mcu(clk, reset_n, wr_en, wr_addr, wr_data, rd_en, rd_addr, sensor_temp_raw, sensor_humidity_raw, sensor_air_raw, sensor_valid, rd_data, sensor_sample_req, alert_irq, fifo_level, low_power_active, sample_count, alert_status);
  output alert_irq;
  wire alert_irq;
  output [7:0] alert_status;
  wire [7:0] alert_status;
  input clk;
  wire clk;
  output [5:0] fifo_level;
  wire [5:0] fifo_level;
  output low_power_active;
  wire low_power_active;
  input [11:0] rd_addr;
  wire [11:0] rd_addr;
  output [31:0] rd_data;
  wire [31:0] rd_data;
  input rd_en;
  wire rd_en;
  input reset_n;
  wire reset_n;
  output [31:0] sample_count;
  wire [31:0] sample_count;
  input [15:0] sensor_air_raw;
  wire [15:0] sensor_air_raw;
  input [15:0] sensor_humidity_raw;
  wire [15:0] sensor_humidity_raw;
  output sensor_sample_req;
  wire sensor_sample_req;
  input [15:0] sensor_temp_raw;
  wire [15:0] sensor_temp_raw;
  input sensor_valid;
  wire sensor_valid;
  input [11:0] wr_addr;
  wire [11:0] wr_addr;
  input [31:0] wr_data;
  wire [31:0] wr_data;
  input wr_en;
  wire wr_en;
  sky130_fd_sc_hd__conb_1 _00_ (
    .LO(fifo_level[0])
  );
  sky130_fd_sc_hd__conb_1 _01_ (
    .LO(fifo_level[1])
  );
  sky130_fd_sc_hd__conb_1 _02_ (
    .LO(fifo_level[2])
  );
  sky130_fd_sc_hd__conb_1 _03_ (
    .LO(fifo_level[3])
  );
  sky130_fd_sc_hd__conb_1 _04_ (
    .LO(fifo_level[4])
  );
  sky130_fd_sc_hd__conb_1 _05_ (
    .LO(fifo_level[5])
  );
  sky130_fd_sc_hd__conb_1 _06_ (
    .LO(low_power_active)
  );
  sky130_fd_sc_hd__conb_1 _07_ (
    .LO(rd_data[0])
  );
  sky130_fd_sc_hd__conb_1 _08_ (
    .LO(rd_data[1])
  );
  sky130_fd_sc_hd__conb_1 _09_ (
    .LO(rd_data[2])
  );
  sky130_fd_sc_hd__conb_1 _10_ (
    .LO(rd_data[3])
  );
  sky130_fd_sc_hd__conb_1 _11_ (
    .LO(rd_data[4])
  );
  sky130_fd_sc_hd__conb_1 _12_ (
    .LO(rd_data[5])
  );
  sky130_fd_sc_hd__conb_1 _13_ (
    .LO(rd_data[6])
  );
  sky130_fd_sc_hd__conb_1 _14_ (
    .LO(rd_data[7])
  );
  sky130_fd_sc_hd__conb_1 _15_ (
    .LO(rd_data[8])
  );
  sky130_fd_sc_hd__conb_1 _16_ (
    .LO(rd_data[9])
  );
  sky130_fd_sc_hd__conb_1 _17_ (
    .LO(rd_data[10])
  );
  sky130_fd_sc_hd__conb_1 _18_ (
    .LO(rd_data[11])
  );
  sky130_fd_sc_hd__conb_1 _19_ (
    .LO(rd_data[12])
  );
  sky130_fd_sc_hd__conb_1 _20_ (
    .LO(rd_data[13])
  );
  sky130_fd_sc_hd__conb_1 _21_ (
    .LO(rd_data[14])
  );
  sky130_fd_sc_hd__conb_1 _22_ (
    .LO(rd_data[15])
  );
  sky130_fd_sc_hd__conb_1 _23_ (
    .LO(rd_data[16])
  );
  sky130_fd_sc_hd__conb_1 _24_ (
    .LO(rd_data[17])
  );
  sky130_fd_sc_hd__conb_1 _25_ (
    .LO(rd_data[18])
  );
  sky130_fd_sc_hd__conb_1 _26_ (
    .LO(rd_data[19])
  );
  sky130_fd_sc_hd__conb_1 _27_ (
    .LO(rd_data[20])
  );
  sky130_fd_sc_hd__conb_1 _28_ (
    .LO(rd_data[21])
  );
  sky130_fd_sc_hd__conb_1 _29_ (
    .LO(rd_data[22])
  );
  sky130_fd_sc_hd__conb_1 _30_ (
    .LO(rd_data[23])
  );
  sky130_fd_sc_hd__conb_1 _31_ (
    .LO(rd_data[24])
  );
  sky130_fd_sc_hd__conb_1 _32_ (
    .LO(rd_data[25])
  );
  sky130_fd_sc_hd__conb_1 _33_ (
    .LO(rd_data[26])
  );
  sky130_fd_sc_hd__conb_1 _34_ (
    .LO(rd_data[27])
  );
  sky130_fd_sc_hd__conb_1 _35_ (
    .LO(rd_data[28])
  );
  sky130_fd_sc_hd__conb_1 _36_ (
    .LO(rd_data[29])
  );
  sky130_fd_sc_hd__conb_1 _37_ (
    .LO(rd_data[30])
  );
  sky130_fd_sc_hd__conb_1 _38_ (
    .LO(rd_data[31])
  );
  sky130_fd_sc_hd__conb_1 _39_ (
    .LO(sample_count[0])
  );
  sky130_fd_sc_hd__conb_1 _40_ (
    .LO(sample_count[1])
  );
  sky130_fd_sc_hd__conb_1 _41_ (
    .LO(sample_count[2])
  );
  sky130_fd_sc_hd__conb_1 _42_ (
    .LO(sample_count[3])
  );
  sky130_fd_sc_hd__conb_1 _43_ (
    .LO(sample_count[4])
  );
  sky130_fd_sc_hd__conb_1 _44_ (
    .LO(sample_count[5])
  );
  sky130_fd_sc_hd__conb_1 _45_ (
    .LO(sample_count[6])
  );
  sky130_fd_sc_hd__conb_1 _46_ (
    .LO(sample_count[7])
  );
  sky130_fd_sc_hd__conb_1 _47_ (
    .LO(sample_count[8])
  );
  sky130_fd_sc_hd__conb_1 _48_ (
    .LO(sample_count[9])
  );
  sky130_fd_sc_hd__conb_1 _49_ (
    .LO(sample_count[10])
  );
  sky130_fd_sc_hd__conb_1 _50_ (
    .LO(sample_count[11])
  );
  sky130_fd_sc_hd__conb_1 _51_ (
    .LO(sample_count[12])
  );
  sky130_fd_sc_hd__conb_1 _52_ (
    .LO(sample_count[13])
  );
  sky130_fd_sc_hd__conb_1 _53_ (
    .LO(sample_count[14])
  );
  sky130_fd_sc_hd__conb_1 _54_ (
    .LO(sample_count[15])
  );
  sky130_fd_sc_hd__conb_1 _55_ (
    .LO(sample_count[16])
  );
  sky130_fd_sc_hd__conb_1 _56_ (
    .LO(sample_count[17])
  );
  sky130_fd_sc_hd__conb_1 _57_ (
    .LO(sample_count[18])
  );
  sky130_fd_sc_hd__conb_1 _58_ (
    .LO(sample_count[19])
  );
  sky130_fd_sc_hd__conb_1 _59_ (
    .LO(sample_count[20])
  );
  sky130_fd_sc_hd__conb_1 _60_ (
    .LO(sample_count[21])
  );
  sky130_fd_sc_hd__conb_1 _61_ (
    .LO(sample_count[22])
  );
  sky130_fd_sc_hd__conb_1 _62_ (
    .LO(sample_count[23])
  );
  sky130_fd_sc_hd__conb_1 _63_ (
    .LO(sample_count[24])
  );
  sky130_fd_sc_hd__conb_1 _64_ (
    .LO(sample_count[25])
  );
  sky130_fd_sc_hd__conb_1 _65_ (
    .LO(sample_count[26])
  );
  sky130_fd_sc_hd__conb_1 _66_ (
    .LO(sample_count[27])
  );
  sky130_fd_sc_hd__conb_1 _67_ (
    .LO(sample_count[28])
  );
  sky130_fd_sc_hd__conb_1 _68_ (
    .LO(sample_count[29])
  );
  sky130_fd_sc_hd__conb_1 _69_ (
    .LO(sample_count[30])
  );
  sky130_fd_sc_hd__conb_1 _70_ (
    .LO(sample_count[31])
  );
  sky130_fd_sc_hd__conb_1 _71_ (
    .LO(sensor_sample_req)
  );
  sky130_fd_sc_hd__conb_1 _72_ (
    .LO(alert_irq)
  );
  sky130_fd_sc_hd__conb_1 _73_ (
    .LO(alert_status[0])
  );
  sky130_fd_sc_hd__conb_1 _74_ (
    .LO(alert_status[1])
  );
  sky130_fd_sc_hd__conb_1 _75_ (
    .LO(alert_status[2])
  );
  sky130_fd_sc_hd__conb_1 _76_ (
    .LO(alert_status[3])
  );
  sky130_fd_sc_hd__conb_1 _77_ (
    .LO(alert_status[4])
  );
  sky130_fd_sc_hd__conb_1 _78_ (
    .LO(alert_status[5])
  );
  sky130_fd_sc_hd__conb_1 _79_ (
    .LO(alert_status[6])
  );
  sky130_fd_sc_hd__conb_1 _80_ (
    .LO(alert_status[7])
  );
endmodule
