/* Generated by Yosys 0.56 (git sha1 9c447ad9d4b1ea589369364eea38b4d70da2c599, x86_64-w64-mingw32-g++ 15.2.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

module adaptive_aero_control_top(clk, reset_n, mmio_addr, mmio_wdata, mmio_we, mmio_re, mmio_rdata, mmio_ready, mmio_error, req_valid, req_ready, req_data, rsp_valid, rsp_ready, rsp_data, act_cmd_valid, act_cmd_fault, act_cmd_data, irq);
  wire _000_;
  wire _001_;
  wire [15:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire [1:0] _007_;
  wire _008_;
  wire _009_;
  wire [1:0] _010_;
  wire _011_;
  wire _012_;
  wire [1:0] _013_;
  wire [1:0] _014_;
  wire [15:0] _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire [15:0] _050_;
  wire [15:0] _051_;
  wire _052_;
  wire [15:0] accepted_count_reg;
  output [31:0] act_cmd_data;
  wire [31:0] act_cmd_data;
  wire [31:0] act_cmd_data_r;
  output act_cmd_fault;
  wire act_cmd_fault;
  wire act_cmd_fault_r;
  output act_cmd_valid;
  wire act_cmd_valid;
  reg act_cmd_valid_r;
  reg [63:0] bounds_reg;
  wire busy_reg;
  input clk;
  wire clk;
  wire [7:0] ctrl_reg;
  output irq;
  wire irq;
  reg [63:0] irq_en_reg;
  reg irq_r;
  wire launch_accept_pulse;
  reg [63:0] limits_reg;
  wire malformed_rsp_reg;
  input [3:0] mmio_addr;
  wire [3:0] mmio_addr;
  output mmio_error;
  wire mmio_error;
  wire mmio_error_r;
  output [63:0] mmio_rdata;
  wire [63:0] mmio_rdata;
  wire [63:0] mmio_rdata_r;
  input mmio_re;
  wire mmio_re;
  output mmio_ready;
  wire mmio_ready;
  wire mmio_ready_r;
  input [63:0] mmio_wdata;
  wire [63:0] mmio_wdata;
  input mmio_we;
  wire mmio_we;
  reg [63:0] mode_seq_reg;
  reg [15:0] outstanding_age_reg;
  reg [15:0] outstanding_seq_reg;
  reg outstanding_valid_reg;
  wire pending_clear_fault_reg;
  wire pending_launch_reg;
  wire pending_rearm_reg;
  wire [63:0] read_data_next;
  wire rearm_pulse;
  wire [15:0] rejected_count_reg;
  output [63:0] req_data;
  wire [63:0] req_data;
  wire [63:0] req_data_r;
  reg [3:0] req_hist_addr;
  wire [63:0] req_hist_dout;
  reg req_hist_read_pending_reg;
  reg req_hist_write_pending_reg;
  reg [63:0] req_meta_reg;
  input req_ready;
  wire req_ready;
  output req_valid;
  wire req_valid;
  wire req_valid_r;
  input reset_n;
  wire reset_n;
  wire [15:0] rsp_cmd_in;
  input [63:0] rsp_data;
  wire [63:0] rsp_data;
  output rsp_ready;
  wire rsp_ready;
  wire rsp_ready_r;
  wire rsp_schema_ok;
  wire [15:0] rsp_seq_in;
  input rsp_valid;
  wire rsp_valid;
  wire rsp_valid_sync;
  wire [1:0] state_next;
  reg [1:0] state_reg;
  wire status_clamp_applied_reg;
  wire status_fallback_active_reg;
  wire status_fault_active_reg;
  wire [63:0] status_reg_r;
  reg status_req_accepted_reg;
  reg status_rsp_received_reg;
  wire status_rsp_validated_reg;
  wire status_stale_reject_reg;
  wire status_timeout_reg;
  wire transport_error_reg;
  assign _015_ = outstanding_age_reg + 16'h0001;
  assign _016_ = irq_en_reg[0] & status_req_accepted_reg;
  assign _017_ = irq_en_reg[6] & status_rsp_received_reg;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) outstanding_seq_reg <= 16'h0000;
    else if (_030_) outstanding_seq_reg <= mode_seq_reg[23:8];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) state_reg <= 2'h0;
    else if (_019_) state_reg <= state_next;
  reg \ctrl_reg_reg[4] ;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \ctrl_reg_reg[4]  <= 1'h0;
    else if (_036_) \ctrl_reg_reg[4]  <= mmio_wdata[4];
  assign ctrl_reg[4] = \ctrl_reg_reg[4] ;
  reg \ctrl_reg_reg[0] ;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \ctrl_reg_reg[0]  <= 1'h0;
    else if (_036_) \ctrl_reg_reg[0]  <= mmio_wdata[0];
  assign ctrl_reg[0] = \ctrl_reg_reg[0] ;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) outstanding_valid_reg <= 1'h0;
    else if (_030_) outstanding_valid_reg <= 1'h1;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) mode_seq_reg <= 64'h0000000000000000;
    else if (_037_) mode_seq_reg <= mmio_wdata;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) limits_reg <= 64'h0000000000000000;
    else if (_038_) limits_reg <= mmio_wdata;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) req_meta_reg <= 64'h0000000000000000;
    else if (_041_) req_meta_reg <= mmio_wdata;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) act_cmd_valid_r <= 1'h0;
    else if (_018_) act_cmd_valid_r <= _000_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) bounds_reg <= 64'h0000000000000000;
    else if (_039_) bounds_reg <= mmio_wdata;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) req_hist_addr <= 4'h0;
    else if (_042_) req_hist_addr <= mmio_wdata[3:0];
  always @(posedge clk, negedge reset_n)
    if (!reset_n) irq_en_reg <= 64'h0000000000000000;
    else if (_040_) irq_en_reg <= mmio_wdata;
  assign _019_ = | { _035_, _033_, _030_, _032_ };
  assign _020_ = rsp_data[15:0] == outstanding_seq_reg;
  assign _018_ = ! state_reg;
  assign _028_ = outstanding_age_reg >= limits_reg[15:0];
  assign _031_ = outstanding_valid_reg && _028_;
  assign _032_ = _031_ && _044_;
  assign _034_ = rsp_schema_ok && _020_;
  assign _036_ = mmio_we && _021_;
  assign _037_ = mmio_we && _022_;
  assign _038_ = mmio_we && _023_;
  assign _039_ = mmio_we && _024_;
  assign _040_ = mmio_we && _025_;
  assign _041_ = mmio_we && _026_;
  assign _042_ = mmio_we && _027_;
  assign _029_ = launch_accept_pulse && ctrl_reg[0];
  assign _030_ = _029_ && _043_;
  assign _033_ = rsp_valid && outstanding_valid_reg;
  assign _035_ = rearm_pulse && ctrl_reg[0];
  assign _043_ = ! outstanding_valid_reg;
  assign _044_ = | limits_reg[15:0];
  assign _045_ = outstanding_age_reg != 16'hffff;
  assign rsp_schema_ok = ~ rsp_data[63];
  assign _046_ = _016_ | _017_;
  assign _001_ = irq_r | _046_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) irq_r <= 1'h0;
    else irq_r <= _001_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) outstanding_age_reg <= 16'h0000;
    else outstanding_age_reg <= _002_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) status_req_accepted_reg <= 1'h0;
    else status_req_accepted_reg <= _005_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) status_rsp_received_reg <= 1'h0;
    else status_rsp_received_reg <= _006_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) req_hist_write_pending_reg <= 1'h0;
    else req_hist_write_pending_reg <= _004_;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) req_hist_read_pending_reg <= 1'h0;
    else req_hist_read_pending_reg <= _003_;
  assign _006_ = _033_ ? 1'h1 : 1'h0;
  assign _005_ = _030_ ? 1'h1 : 1'h0;
  assign _047_ = _042_ ? mmio_wdata[5] : req_hist_read_pending_reg;
  assign _048_ = req_hist_read_pending_reg ? 1'h0 : _047_;
  assign _003_ = req_hist_write_pending_reg ? _047_ : _048_;
  assign _049_ = _042_ ? mmio_wdata[4] : 1'h0;
  assign _004_ = req_hist_write_pending_reg ? 1'h0 : _049_;
  assign _050_ = _030_ ? 16'h0000 : outstanding_age_reg;
  assign _051_ = _045_ ? _015_ : _050_;
  assign _002_ = outstanding_valid_reg ? _051_ : _050_;
  assign _000_ = _018_ ? 1'h0 : 1'hx;
  assign state_next = _035_ ? 2'h0 : _013_;
  assign _014_ = _034_ ? 2'h0 : 2'h3;
  assign _013_ = _033_ ? _014_ : _010_;
  assign _010_ = _032_ ? 2'h3 : _007_;
  assign _007_ = _030_ ? 2'h1 : 2'hx;
  assign mmio_rdata = mmio_re ? read_data_next : 64'h0000000000000000;
  assign _011_ = mmio_wdata[1] ? 1'h1 : 1'h0;
  assign _012_ = mmio_wdata[3] ? 1'h1 : 1'h0;
  assign _008_ = _021_ ? _011_ : 1'h0;
  assign _009_ = _021_ ? _012_ : 1'h0;
  assign rearm_pulse = mmio_we ? _009_ : 1'h0;
  assign launch_accept_pulse = mmio_we ? _008_ : 1'h0;
  function [63:0] _121_;
    input [63:0] a;
    input [511:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _121_ = b[63:0];
      8'b??????1?:
        _121_ = b[127:64];
      8'b?????1??:
        _121_ = b[191:128];
      8'b????1???:
        _121_ = b[255:192];
      8'b???1????:
        _121_ = b[319:256];
      8'b??1?????:
        _121_ = b[383:320];
      8'b?1??????:
        _121_ = b[447:384];
      8'b1???????:
        _121_ = b[511:448];
      default:
        _121_ = a;
    endcase
  endfunction
  assign read_data_next = _121_(64'h0000000000000000, { 59'h000000000000000, ctrl_reg[4], 3'h0, ctrl_reg[0], mode_seq_reg, limits_reg, bounds_reg, 61'h0000000000000000, status_rsp_received_reg, status_req_accepted_reg, 1'h0, irq_en_reg, req_meta_reg, 58'h000000000000000, req_hist_read_pending_reg, req_hist_write_pending_reg, req_hist_addr }, { _021_, _022_, _023_, _024_, _052_, _025_, _026_, _027_ });
  assign _027_ = mmio_addr == 4'h7;
  assign _026_ = mmio_addr == 4'h6;
  assign _025_ = mmio_addr == 4'h5;
  assign _052_ = mmio_addr == 4'h4;
  assign _024_ = mmio_addr == 4'h3;
  assign _023_ = mmio_addr == 4'h2;
  assign _022_ = mmio_addr == 4'h1;
  assign _021_ = ! mmio_addr;
  assign accepted_count_reg = 16'h0000;
  assign act_cmd_data = 32'd0;
  assign act_cmd_data_r = 32'd0;
  assign act_cmd_fault = act_cmd_valid_r;
  assign act_cmd_fault_r = act_cmd_valid_r;
  assign act_cmd_valid = act_cmd_valid_r;
  assign busy_reg = 1'h0;
  assign { ctrl_reg[7:5], ctrl_reg[3:1] } = 6'h00;
  assign irq = irq_r;
  assign malformed_rsp_reg = 1'h0;
  assign mmio_error = 1'h0;
  assign mmio_error_r = 1'h0;
  assign mmio_rdata_r = mmio_rdata;
  assign mmio_ready = 1'h1;
  assign mmio_ready_r = 1'h1;
  assign pending_clear_fault_reg = 1'h0;
  assign pending_launch_reg = 1'h0;
  assign pending_rearm_reg = 1'h0;
  assign rejected_count_reg = 16'h0000;
  assign req_data = 64'h0000000000000000;
  assign req_data_r = 64'h0000000000000000;
  assign req_hist_dout = 64'h0000000000000000;
  assign req_valid = 1'h0;
  assign req_valid_r = 1'h0;
  assign rsp_cmd_in = rsp_data[31:16];
  assign rsp_ready = 1'h1;
  assign rsp_ready_r = 1'h1;
  assign rsp_seq_in = rsp_data[15:0];
  assign rsp_valid_sync = rsp_valid;
  assign status_clamp_applied_reg = 1'h0;
  assign status_fallback_active_reg = 1'h0;
  assign status_fault_active_reg = 1'h0;
  assign status_reg_r = { 61'h0000000000000000, status_rsp_received_reg, status_req_accepted_reg, 1'h0 };
  assign status_rsp_validated_reg = 1'h0;
  assign status_stale_reject_reg = 1'h0;
  assign status_timeout_reg = 1'h0;
  assign transport_error_reg = 1'h0;
endmodule

module adaptive_aero_control_top_spi_fpga_top(clk, reset_n, spi_sclk, spi_cs_n, spi_mosi, spi_miso, fault_indicator);
  wire _00_;
  wire _01_;
  wire [166:0] _02_;
  input clk;
  wire clk;
  wire [31:0] core_act_cmd_data;
  wire core_act_cmd_fault;
  wire core_act_cmd_valid;
  wire core_irq;
  wire [3:0] core_mmio_addr;
  wire core_mmio_error;
  wire [63:0] core_mmio_rdata;
  wire core_mmio_re;
  wire core_mmio_ready;
  wire [63:0] core_mmio_wdata;
  wire core_mmio_we;
  wire [63:0] core_req_data;
  wire core_req_ready;
  wire core_req_valid;
  wire [166:0] core_response;
  wire [63:0] core_rsp_data;
  wire core_rsp_ready;
  wire core_rsp_valid;
  output fault_indicator;
  wire fault_indicator;
  input reset_n;
  wire reset_n;
  reg [135:0] rx_active;
  reg [135:0] rx_shift;
  reg spi_active;
  reg spi_cs_meta;
  input spi_cs_n;
  wire spi_cs_n;
  reg spi_cs_prev;
  reg spi_cs_sync;
  output spi_miso;
  wire spi_miso;
  input spi_mosi;
  wire spi_mosi;
  input spi_sclk;
  wire spi_sclk;
  reg [166:0] tx_shift;
  reg [166:0] tx_snapshot;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) rx_active <= 136'h0000000000000000000000000000000000;
    else if (_00_) rx_active <= rx_shift;
  always @(posedge spi_sclk)
    if (!spi_cs_n) rx_shift <= { rx_shift[134:0], spi_mosi };
  always @(posedge spi_sclk)
    if (!spi_cs_n) tx_shift <= _02_;
  assign _00_ = spi_cs_sync && _01_;
  assign _01_ = ! spi_cs_prev;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) tx_snapshot <= 167'h000000000000000000000000000000000000000000;
    else tx_snapshot <= { core_mmio_rdata, core_mmio_ready, core_mmio_error, core_req_valid, core_req_data, core_rsp_ready, core_act_cmd_valid, core_act_cmd_fault, core_act_cmd_data, core_irq };
  always @(posedge clk, negedge reset_n)
    if (!reset_n) spi_cs_meta <= 1'h1;
    else spi_cs_meta <= spi_cs_n;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) spi_cs_sync <= 1'h1;
    else spi_cs_sync <= spi_cs_meta;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) spi_cs_prev <= 1'h1;
    else spi_cs_prev <= spi_cs_sync;
  always @(posedge spi_sclk, posedge spi_cs_n)
    if (spi_cs_n) spi_active <= 1'h0;
    else spi_active <= 1'h1;
  assign _02_ = spi_active ? { tx_shift[165:0], 1'h0 } : { tx_snapshot[165:0], 1'h0 };
  assign spi_miso = spi_active ? tx_shift[166] : tx_snapshot[166];
  adaptive_aero_control_top u_core (
    .act_cmd_data(core_act_cmd_data),
    .act_cmd_fault(core_act_cmd_fault),
    .act_cmd_valid(core_act_cmd_valid),
    .clk(clk),
    .irq(core_irq),
    .mmio_addr(rx_active[3:0]),
    .mmio_error(core_mmio_error),
    .mmio_rdata(core_mmio_rdata),
    .mmio_re(rx_active[69]),
    .mmio_ready(core_mmio_ready),
    .mmio_wdata(rx_active[67:4]),
    .mmio_we(rx_active[68]),
    .req_data(core_req_data),
    .req_ready(rx_active[70]),
    .req_valid(core_req_valid),
    .reset_n(reset_n),
    .rsp_data(rx_active[135:72]),
    .rsp_ready(core_rsp_ready),
    .rsp_valid(rx_active[71])
  );
  assign core_mmio_addr = rx_active[3:0];
  assign core_mmio_re = rx_active[69];
  assign core_mmio_wdata = rx_active[67:4];
  assign core_mmio_we = rx_active[68];
  assign core_req_ready = rx_active[70];
  assign core_response = { core_mmio_rdata, core_mmio_ready, core_mmio_error, core_req_valid, core_req_data, core_rsp_ready, core_act_cmd_valid, core_act_cmd_fault, core_act_cmd_data, core_irq };
  assign core_rsp_data = rx_active[135:72];
  assign core_rsp_valid = rx_active[71];
  assign fault_indicator = 1'h0;
endmodule
