/* Generated by Yosys 0.56 (git sha1 9c447ad9d4b1ea589369364eea38b4d70da2c599, x86_64-w64-mingw32-g++ 15.2.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

module adaptive_aero_control_top(clk, reset, reg_cs, reg_we, reg_re, reg_addr, reg_wdata, reg_rdata, model_req_valid, model_req_ready, model_req_data, model_rsp_valid, model_rsp_ready, model_rsp_data, actuator_cmd_valid, actuator_cmd_ready, actuator_cmd_data, fault_summary, heartbeat_status);
  wire [63:0] act_data_int;
  wire act_ready_int;
  wire act_valid_int;
  output [63:0] actuator_cmd_data;
  wire [63:0] actuator_cmd_data;
  wire [63:0] actuator_cmd_data_unused_from_u_actuator_output_cmd_data;
  input actuator_cmd_ready;
  wire actuator_cmd_ready;
  output actuator_cmd_valid;
  wire actuator_cmd_valid;
  wire actuator_cmd_valid_unused_from_u_actuator_output_cmd_valid;
  wire [15:0] cfg_act0_max;
  wire [15:0] cfg_act0_min;
  wire [15:0] cfg_act1_max;
  wire [15:0] cfg_act1_min;
  wire [15:0] cfg_act2_max;
  wire [15:0] cfg_act2_min;
  wire [15:0] cfg_act3_max;
  wire [15:0] cfg_act3_min;
  wire [31:0] cfg_age_basis;
  wire cfg_enable;
  wire cfg_fallback_enable;
  wire [31:0] cfg_geometry_id;
  wire cfg_heartbeat_enable;
  wire [31:0] cfg_heartbeat_timeout_cycles;
  wire cfg_hold_last_valid;
  wire [2:0] cfg_mode;
  wire [3:0] cfg_mode_context;
  wire [11:0] cfg_operating_point_tag;
  wire [2:0] cfg_queue_depth;
  wire cfg_seq_reset;
  wire [7:0] cfg_service_flags;
  wire cfg_signed_clamp;
  wire [31:0] cfg_timeout_cycles;
  wire [31:0] cfg_velocity_setpoint;
  wire [15:0] cfg_velocity_tag;
  input clk;
  wire clk;
  output [7:0] fault_summary;
  wire [7:0] fault_summary;
  output [7:0] heartbeat_status;
  wire [7:0] heartbeat_status;
  output [127:0] model_req_data;
  wire [127:0] model_req_data;
  input model_req_ready;
  wire model_req_ready;
  output model_req_valid;
  wire model_req_valid;
  input [127:0] model_rsp_data;
  wire [127:0] model_rsp_data;
  output model_rsp_ready;
  wire model_rsp_ready;
  input model_rsp_valid;
  wire model_rsp_valid;
  input [3:0] reg_addr;
  wire [3:0] reg_addr;
  input reg_cs;
  wire reg_cs;
  output [63:0] reg_rdata;
  wire [63:0] reg_rdata;
  input reg_re;
  wire reg_re;
  input [63:0] reg_wdata;
  wire [63:0] reg_wdata;
  input reg_we;
  wire reg_we;
  wire [127:0] req_data_int;
  wire req_valid_int;
  input reset;
  wire reset;
  wire rsp_ready_int;
  wire [15:0] status_accepted_req_count;
  wire [15:0] status_accepted_rsp_count;
  wire [7:0] status_fallback_entry_count;
  wire [7:0] status_fault_summary;
  wire [7:0] status_heartbeat;
  wire [7:0] status_rejected_rsp_count;
  adaptive_aero_control_top_actuator u_actuator (
    .cfg_act0_max(cfg_act0_max),
    .cfg_act0_min(cfg_act0_min),
    .cfg_act1_max(cfg_act1_max),
    .cfg_act1_min(cfg_act1_min),
    .cfg_act2_max(cfg_act2_max),
    .cfg_act2_min(cfg_act2_min),
    .cfg_act3_max(cfg_act3_max),
    .cfg_act3_min(cfg_act3_min),
    .cfg_signed_clamp(cfg_signed_clamp),
    .clk(clk),
    .fallback_active(status_fault_summary[5]),
    .input_cmd_data(act_data_int),
    .input_cmd_ready(act_ready_int),
    .input_cmd_valid(act_valid_int),
    .output_cmd_data(actuator_cmd_data_unused_from_u_actuator_output_cmd_data),
    .output_cmd_ready(actuator_cmd_ready),
    .output_cmd_valid(actuator_cmd_valid_unused_from_u_actuator_output_cmd_valid),
    .reset(reset)
  );
  adaptive_aero_control_top_mmio u_mmio (
    .cfg_act0_max(cfg_act0_max),
    .cfg_act0_min(cfg_act0_min),
    .cfg_act1_max(cfg_act1_max),
    .cfg_act1_min(cfg_act1_min),
    .cfg_act2_max(cfg_act2_max),
    .cfg_act2_min(cfg_act2_min),
    .cfg_act3_max(cfg_act3_max),
    .cfg_act3_min(cfg_act3_min),
    .cfg_age_basis(cfg_age_basis),
    .cfg_enable(cfg_enable),
    .cfg_fallback_enable(cfg_fallback_enable),
    .cfg_geometry_id(cfg_geometry_id),
    .cfg_heartbeat_enable(cfg_heartbeat_enable),
    .cfg_heartbeat_timeout_cycles(cfg_heartbeat_timeout_cycles),
    .cfg_hold_last_valid(cfg_hold_last_valid),
    .cfg_mode(cfg_mode),
    .cfg_mode_context(cfg_mode_context),
    .cfg_operating_point_tag(cfg_operating_point_tag),
    .cfg_queue_depth(cfg_queue_depth),
    .cfg_seq_reset(cfg_seq_reset),
    .cfg_service_flags(cfg_service_flags),
    .cfg_signed_clamp(cfg_signed_clamp),
    .cfg_timeout_cycles(cfg_timeout_cycles),
    .cfg_velocity_setpoint(cfg_velocity_setpoint),
    .cfg_velocity_tag(cfg_velocity_tag),
    .clk(clk),
    .reg_addr(reg_addr),
    .reg_cs(reg_cs),
    .reg_rdata(reg_rdata),
    .reg_re(reg_re),
    .reg_wdata(reg_wdata),
    .reg_we(reg_we),
    .reset(reset),
    .status_accepted_req_count(status_accepted_req_count),
    .status_accepted_rsp_count(status_accepted_rsp_count),
    .status_fallback_entry_count(status_fallback_entry_count),
    .status_fault_summary(status_fault_summary),
    .status_heartbeat(status_heartbeat),
    .status_rejected_rsp_count(status_rejected_rsp_count)
  );
  adaptive_aero_control_top_transport u_transport (
    .accepted_req_count(status_accepted_req_count),
    .accepted_rsp_count(status_accepted_rsp_count),
    .act_data(act_data_int),
    .act_ready(act_ready_int),
    .act_valid(act_valid_int),
    .cfg_age_basis(cfg_age_basis),
    .cfg_enable(cfg_enable),
    .cfg_fallback_enable(cfg_fallback_enable),
    .cfg_geometry_id(cfg_geometry_id),
    .cfg_heartbeat_enable(cfg_heartbeat_enable),
    .cfg_heartbeat_timeout_cycles(cfg_heartbeat_timeout_cycles),
    .cfg_hold_last_valid(cfg_hold_last_valid),
    .cfg_mode(cfg_mode),
    .cfg_mode_context(cfg_mode_context),
    .cfg_operating_point_tag(cfg_operating_point_tag),
    .cfg_queue_depth(cfg_queue_depth),
    .cfg_seq_reset(cfg_seq_reset),
    .cfg_service_flags(cfg_service_flags),
    .cfg_signed_clamp(cfg_signed_clamp),
    .cfg_timeout_cycles(cfg_timeout_cycles),
    .cfg_velocity_setpoint(cfg_velocity_setpoint),
    .cfg_velocity_tag(cfg_velocity_tag),
    .clk(clk),
    .fallback_entry_count(status_fallback_entry_count),
    .fault_summary(status_fault_summary),
    .heartbeat_status(status_heartbeat),
    .rejected_rsp_count(status_rejected_rsp_count),
    .req_data(req_data_int),
    .req_ready(model_req_ready),
    .req_valid(req_valid_int),
    .reset(reset),
    .rsp_data(model_rsp_data),
    .rsp_ready(rsp_ready_int),
    .rsp_valid(model_rsp_valid)
  );
  assign actuator_cmd_data = act_data_int;
  assign actuator_cmd_valid = act_valid_int;
  assign fault_summary = status_fault_summary;
  assign heartbeat_status = status_heartbeat;
  assign model_req_data = req_data_int;
  assign model_req_valid = req_valid_int;
  assign model_rsp_ready = rsp_ready_int;
endmodule

module adaptive_aero_control_top_actuator(clk, reset, cfg_signed_clamp, cfg_act0_min, cfg_act0_max, cfg_act1_min, cfg_act1_max, cfg_act2_min, cfg_act2_max, cfg_act3_min, cfg_act3_max, fallback_active, input_cmd_valid, input_cmd_ready, input_cmd_data, output_cmd_valid, output_cmd_ready, output_cmd_data);
  wire [63:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [15:0] _22_;
  wire [15:0] _23_;
  wire [15:0] _24_;
  wire [15:0] _25_;
  wire [15:0] _26_;
  wire [15:0] _27_;
  wire [15:0] _28_;
  wire [15:0] _29_;
  wire [15:0] _30_;
  wire [15:0] _31_;
  wire [15:0] _32_;
  wire [15:0] _33_;
  wire [15:0] _34_;
  wire [15:0] _35_;
  wire [15:0] _36_;
  wire [15:0] _37_;
  wire [15:0] _38_;
  wire [15:0] _39_;
  wire [15:0] _40_;
  wire [15:0] _41_;
  wire [63:0] _42_;
  wire _43_;
  wire _44_;
  input [15:0] cfg_act0_max;
  wire [15:0] cfg_act0_max;
  input [15:0] cfg_act0_min;
  wire [15:0] cfg_act0_min;
  input [15:0] cfg_act1_max;
  wire [15:0] cfg_act1_max;
  input [15:0] cfg_act1_min;
  wire [15:0] cfg_act1_min;
  input [15:0] cfg_act2_max;
  wire [15:0] cfg_act2_max;
  input [15:0] cfg_act2_min;
  wire [15:0] cfg_act2_min;
  input [15:0] cfg_act3_max;
  wire [15:0] cfg_act3_max;
  input [15:0] cfg_act3_min;
  wire [15:0] cfg_act3_min;
  input cfg_signed_clamp;
  wire cfg_signed_clamp;
  reg [15:0] ch0;
  reg [15:0] ch1;
  reg [15:0] ch2;
  reg [15:0] ch3;
  reg [63:0] clamped_cmd;
  input clk;
  wire clk;
  input fallback_active;
  wire fallback_active;
  input [63:0] input_cmd_data;
  wire [63:0] input_cmd_data;
  output input_cmd_ready;
  reg input_cmd_ready;
  input input_cmd_valid;
  wire input_cmd_valid;
  output [63:0] output_cmd_data;
  reg [63:0] output_cmd_data;
  input output_cmd_ready;
  wire output_cmd_ready;
  output output_cmd_valid;
  reg output_cmd_valid;
  input reset;
  wire reset;
  wire [63:0] safe_cmd;
  always @(posedge clk, posedge reset)
    if (reset) ch3 <= 16'h0000;
    else if (!_13_) ch3 <= _26_;
  always @(posedge clk, posedge reset)
    if (reset) clamped_cmd <= 64'h0000000000000000;
    else if (!_13_) clamped_cmd <= { ch3, ch2, ch1, ch0 };
  always @(posedge clk, posedge reset)
    if (reset) output_cmd_valid <= 1'h0;
    else if (_02_) output_cmd_valid <= _01_;
  always @(posedge clk, posedge reset)
    if (reset) ch2 <= 16'h0000;
    else if (!_13_) ch2 <= _31_;
  always @(posedge clk, posedge reset)
    if (reset) output_cmd_data <= 64'h0000000000000000;
    else if (_03_) output_cmd_data <= _00_;
  always @(posedge clk, posedge reset)
    if (reset) ch0 <= 16'h0000;
    else if (!_13_) ch0 <= _41_;
  always @(posedge clk, posedge reset)
    if (reset) ch1 <= 16'h0000;
    else if (!_13_) ch1 <= _36_;
  assign _02_ = | { output_cmd_ready, input_cmd_valid, fallback_active };
  assign _03_ = | { input_cmd_valid, fallback_active };
  assign _04_ = $signed(input_cmd_data[15:0]) > $signed(cfg_act0_max);
  assign _05_ = $signed(input_cmd_data[31:16]) > $signed(cfg_act1_max);
  assign _06_ = $signed(input_cmd_data[47:32]) > $signed(cfg_act2_max);
  assign _07_ = $signed(input_cmd_data[63:48]) > $signed(cfg_act3_max);
  assign _08_ = input_cmd_data[15:0] > cfg_act0_max;
  assign _09_ = input_cmd_data[31:16] > cfg_act1_max;
  assign _10_ = input_cmd_data[47:32] > cfg_act2_max;
  assign _11_ = input_cmd_data[63:48] > cfg_act3_max;
  assign _12_ = ! input_cmd_valid;
  assign _13_ = fallback_active || _12_;
  assign _14_ = $signed(input_cmd_data[15:0]) < $signed(cfg_act0_min);
  assign _15_ = $signed(input_cmd_data[31:16]) < $signed(cfg_act1_min);
  assign _16_ = $signed(input_cmd_data[47:32]) < $signed(cfg_act2_min);
  assign _17_ = $signed(input_cmd_data[63:48]) < $signed(cfg_act3_min);
  assign _18_ = input_cmd_data[15:0] < cfg_act0_min;
  assign _19_ = input_cmd_data[31:16] < cfg_act1_min;
  assign _20_ = input_cmd_data[47:32] < cfg_act2_min;
  assign _21_ = input_cmd_data[63:48] < cfg_act3_min;
  always @(posedge clk, posedge reset)
    if (reset) input_cmd_ready <= 1'h1;
    else input_cmd_ready <= output_cmd_ready;
  assign _22_ = _11_ ? cfg_act3_max : input_cmd_data[63:48];
  assign _23_ = _21_ ? cfg_act3_min : _22_;
  assign _24_ = _07_ ? cfg_act3_max : input_cmd_data[63:48];
  assign _25_ = _17_ ? cfg_act3_min : _24_;
  assign _26_ = cfg_signed_clamp ? _25_ : _23_;
  assign _27_ = _10_ ? cfg_act2_max : input_cmd_data[47:32];
  assign _28_ = _20_ ? cfg_act2_min : _27_;
  assign _29_ = _06_ ? cfg_act2_max : input_cmd_data[47:32];
  assign _30_ = _16_ ? cfg_act2_min : _29_;
  assign _31_ = cfg_signed_clamp ? _30_ : _28_;
  assign _32_ = _09_ ? cfg_act1_max : input_cmd_data[31:16];
  assign _33_ = _19_ ? cfg_act1_min : _32_;
  assign _34_ = _05_ ? cfg_act1_max : input_cmd_data[31:16];
  assign _35_ = _15_ ? cfg_act1_min : _34_;
  assign _36_ = cfg_signed_clamp ? _35_ : _33_;
  assign _37_ = _08_ ? cfg_act0_max : input_cmd_data[15:0];
  assign _38_ = _18_ ? cfg_act0_min : _37_;
  assign _39_ = _04_ ? cfg_act0_max : input_cmd_data[15:0];
  assign _40_ = _14_ ? cfg_act0_min : _39_;
  assign _41_ = cfg_signed_clamp ? _40_ : _38_;
  assign _42_ = input_cmd_valid ? clamped_cmd : 64'hxxxxxxxxxxxxxxxx;
  assign _00_ = fallback_active ? 64'h0000000000000000 : _42_;
  assign _43_ = output_cmd_ready ? 1'h0 : 1'hx;
  assign _44_ = input_cmd_valid ? 1'h1 : _43_;
  assign _01_ = fallback_active ? 1'h1 : _44_;
  assign safe_cmd = 64'h0000000000000000;
endmodule

module adaptive_aero_control_top_mmio(clk, reset, reg_cs, reg_we, reg_re, reg_addr, reg_wdata, reg_rdata, cfg_enable, cfg_mode, cfg_hold_last_valid, cfg_fallback_enable, cfg_heartbeat_enable, cfg_seq_reset, cfg_signed_clamp, cfg_queue_depth, cfg_service_flags, cfg_timeout_cycles, cfg_heartbeat_timeout_cycles, cfg_act0_min, cfg_act0_max
, cfg_act1_min, cfg_act1_max, cfg_act2_min, cfg_act2_max, cfg_act3_min, cfg_act3_max, cfg_mode_context, cfg_operating_point_tag, cfg_velocity_tag, cfg_geometry_id, cfg_velocity_setpoint, cfg_age_basis, status_fault_summary, status_heartbeat, status_accepted_req_count, status_accepted_rsp_count, status_rejected_rsp_count, status_fallback_entry_count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  output [15:0] cfg_act0_max;
  reg [15:0] cfg_act0_max;
  output [15:0] cfg_act0_min;
  reg [15:0] cfg_act0_min;
  output [15:0] cfg_act1_max;
  reg [15:0] cfg_act1_max;
  output [15:0] cfg_act1_min;
  reg [15:0] cfg_act1_min;
  output [15:0] cfg_act2_max;
  reg [15:0] cfg_act2_max;
  output [15:0] cfg_act2_min;
  reg [15:0] cfg_act2_min;
  output [15:0] cfg_act3_max;
  reg [15:0] cfg_act3_max;
  output [15:0] cfg_act3_min;
  reg [15:0] cfg_act3_min;
  output [31:0] cfg_age_basis;
  reg [31:0] cfg_age_basis;
  output cfg_enable;
  reg cfg_enable;
  output cfg_fallback_enable;
  reg cfg_fallback_enable;
  output [31:0] cfg_geometry_id;
  reg [31:0] cfg_geometry_id;
  output cfg_heartbeat_enable;
  reg cfg_heartbeat_enable;
  output [31:0] cfg_heartbeat_timeout_cycles;
  reg [31:0] cfg_heartbeat_timeout_cycles;
  output cfg_hold_last_valid;
  reg cfg_hold_last_valid;
  output [2:0] cfg_mode;
  reg [2:0] cfg_mode;
  output [3:0] cfg_mode_context;
  reg [3:0] cfg_mode_context;
  output [11:0] cfg_operating_point_tag;
  reg [11:0] cfg_operating_point_tag;
  output [2:0] cfg_queue_depth;
  reg [2:0] cfg_queue_depth;
  output cfg_seq_reset;
  reg cfg_seq_reset;
  output [7:0] cfg_service_flags;
  reg [7:0] cfg_service_flags;
  output cfg_signed_clamp;
  reg cfg_signed_clamp;
  output [31:0] cfg_timeout_cycles;
  reg [31:0] cfg_timeout_cycles;
  output [31:0] cfg_velocity_setpoint;
  reg [31:0] cfg_velocity_setpoint;
  output [15:0] cfg_velocity_tag;
  reg [15:0] cfg_velocity_tag;
  input clk;
  wire clk;
  input [3:0] reg_addr;
  wire [3:0] reg_addr;
  input reg_cs;
  wire reg_cs;
  output [63:0] reg_rdata;
  wire [63:0] reg_rdata;
  wire [63:0] reg_rdata_r;
  input reg_re;
  wire reg_re;
  input [63:0] reg_wdata;
  wire [63:0] reg_wdata;
  input reg_we;
  wire reg_we;
  input reset;
  wire reset;
  input [15:0] status_accepted_req_count;
  wire [15:0] status_accepted_req_count;
  input [15:0] status_accepted_rsp_count;
  wire [15:0] status_accepted_rsp_count;
  input [7:0] status_fallback_entry_count;
  wire [7:0] status_fallback_entry_count;
  input [7:0] status_fault_summary;
  wire [7:0] status_fault_summary;
  input [7:0] status_heartbeat;
  wire [7:0] status_heartbeat;
  input [7:0] status_rejected_rsp_count;
  wire [7:0] status_rejected_rsp_count;
  always @(posedge clk, posedge reset)
    if (reset) cfg_age_basis <= 32'd0;
    else if (_01_) cfg_age_basis <= reg_wdata[63:32];
  always @(posedge clk, posedge reset)
    if (reset) cfg_enable <= 1'h0;
    else if (_02_) cfg_enable <= reg_wdata[0];
  always @(posedge clk, posedge reset)
    if (reset) cfg_act0_max <= 16'hffff;
    else if (_03_) cfg_act0_max <= reg_wdata[31:16];
  always @(posedge clk, posedge reset)
    if (reset) cfg_mode <= 3'h0;
    else if (_02_) cfg_mode <= reg_wdata[3:1];
  always @(posedge clk, posedge reset)
    if (reset) cfg_velocity_setpoint <= 32'd0;
    else if (_01_) cfg_velocity_setpoint <= reg_wdata[31:0];
  always @(posedge clk, posedge reset)
    if (reset) cfg_hold_last_valid <= 1'h0;
    else if (_02_) cfg_hold_last_valid <= reg_wdata[4];
  always @(posedge clk, posedge reset)
    if (reset) cfg_act2_min <= 16'h0000;
    else if (_04_) cfg_act2_min <= reg_wdata[15:0];
  always @(posedge clk, posedge reset)
    if (reset) cfg_fallback_enable <= 1'h1;
    else if (_02_) cfg_fallback_enable <= reg_wdata[5];
  always @(posedge clk, posedge reset)
    if (reset) cfg_geometry_id <= 32'd0;
    else if (_05_) cfg_geometry_id <= reg_wdata[63:32];
  always @(posedge clk, posedge reset)
    if (reset) cfg_heartbeat_enable <= 1'h1;
    else if (_02_) cfg_heartbeat_enable <= reg_wdata[6];
  always @(posedge clk, posedge reset)
    if (reset) cfg_act1_min <= 16'h0000;
    else if (_03_) cfg_act1_min <= reg_wdata[47:32];
  always @(posedge clk, posedge reset)
    if (reset) cfg_velocity_tag <= 16'h0000;
    else if (_05_) cfg_velocity_tag <= reg_wdata[31:16];
  always @(posedge clk, posedge reset)
    if (reset) cfg_signed_clamp <= 1'h0;
    else if (_02_) cfg_signed_clamp <= reg_wdata[8];
  always @(posedge clk, posedge reset)
    if (reset) cfg_act3_min <= 16'h0000;
    else if (_04_) cfg_act3_min <= reg_wdata[47:32];
  always @(posedge clk, posedge reset)
    if (reset) cfg_queue_depth <= 3'h1;
    else if (_02_) cfg_queue_depth <= reg_wdata[11:9];
  always @(posedge clk, posedge reset)
    if (reset) cfg_operating_point_tag <= 12'h000;
    else if (_05_) cfg_operating_point_tag <= reg_wdata[15:4];
  always @(posedge clk, posedge reset)
    if (reset) cfg_service_flags <= 8'h00;
    else if (_02_) cfg_service_flags <= reg_wdata[23:16];
  always @(posedge clk, posedge reset)
    if (reset) cfg_act1_max <= 16'hffff;
    else if (_03_) cfg_act1_max <= reg_wdata[63:48];
  always @(posedge clk, posedge reset)
    if (reset) cfg_timeout_cycles <= 32'd1000000;
    else if (_06_) cfg_timeout_cycles <= reg_wdata[31:0];
  always @(posedge clk, posedge reset)
    if (reset) cfg_mode_context <= 4'h0;
    else if (_05_) cfg_mode_context <= reg_wdata[3:0];
  always @(posedge clk, posedge reset)
    if (reset) cfg_heartbeat_timeout_cycles <= 32'd2000000;
    else if (_06_) cfg_heartbeat_timeout_cycles <= reg_wdata[63:32];
  always @(posedge clk, posedge reset)
    if (reset) cfg_act2_max <= 16'hffff;
    else if (_04_) cfg_act2_max <= reg_wdata[31:16];
  always @(posedge clk, posedge reset)
    if (reset) cfg_act0_min <= 16'h0000;
    else if (_03_) cfg_act0_min <= reg_wdata[15:0];
  always @(posedge clk, posedge reset)
    if (reset) cfg_act3_max <= 16'hffff;
    else if (_04_) cfg_act3_max <= reg_wdata[63:48];
  assign _01_ = & { _08_, _07_ };
  assign _02_ = & { _14_, _07_ };
  assign _03_ = & { _12_, _07_ };
  assign _04_ = & { _11_, _07_ };
  assign _05_ = & { _09_, _07_ };
  assign _06_ = & { _13_, _07_ };
  assign _07_ = reg_cs && reg_we;
  always @(posedge clk, posedge reset)
    if (reset) cfg_seq_reset <= 1'h0;
    else cfg_seq_reset <= _00_;
  function [63:0] _48_;
    input [63:0] a;
    input [447:0] b;
    input [6:0] s;
    casez (s) // synopsys parallel_case
      7'b??????1:
        _48_ = b[63:0];
      7'b?????1?:
        _48_ = b[127:64];
      7'b????1??:
        _48_ = b[191:128];
      7'b???1???:
        _48_ = b[255:192];
      7'b??1????:
        _48_ = b[319:256];
      7'b?1?????:
        _48_ = b[383:320];
      7'b1??????:
        _48_ = b[447:384];
      default:
        _48_ = a;
    endcase
  endfunction
  assign reg_rdata = _48_(64'h0000000000000000, { 39'h0000000000, cfg_service_flags, 5'h00, cfg_queue_depth, cfg_signed_clamp, cfg_seq_reset, cfg_heartbeat_enable, cfg_fallback_enable, cfg_hold_last_valid, cfg_mode, cfg_enable, cfg_heartbeat_timeout_cycles, cfg_timeout_cycles, cfg_act1_max, cfg_act1_min, cfg_act0_max, cfg_act0_min, cfg_act3_max, cfg_act3_min, cfg_act2_max, cfg_act2_min, status_fallback_entry_count, status_rejected_rsp_count, status_accepted_rsp_count, status_accepted_req_count, status_heartbeat, status_fault_summary, cfg_geometry_id, cfg_velocity_tag, cfg_operating_point_tag, cfg_mode_context, cfg_age_basis, cfg_velocity_setpoint }, { _14_, _13_, _12_, _11_, _10_, _09_, _08_ });
  assign _10_ = reg_addr == 4'h4;
  assign _15_ = _14_ ? reg_wdata[7] : 1'h0;
  assign _00_ = _07_ ? _15_ : 1'h0;
  assign _08_ = reg_addr == 4'h6;
  assign _09_ = reg_addr == 4'h5;
  assign _11_ = reg_addr == 4'h3;
  assign _12_ = reg_addr == 4'h2;
  assign _13_ = reg_addr == 4'h1;
  assign _14_ = ! reg_addr;
  assign reg_rdata_r = reg_rdata;
endmodule

module adaptive_aero_control_top_spi_fpga_top(clk, reset_n, spi_sclk, spi_cs_n, spi_mosi, spi_miso, fault_indicator);
  wire _00_;
  wire _01_;
  wire _02_;
  wire [274:0] _03_;
  input clk;
  wire clk;
  wire [63:0] core_actuator_cmd_data;
  wire core_actuator_cmd_ready;
  wire core_actuator_cmd_valid;
  wire [7:0] core_fault_summary;
  wire [7:0] core_heartbeat_status;
  wire [127:0] core_model_req_data;
  wire core_model_req_ready;
  wire core_model_req_valid;
  wire [127:0] core_model_rsp_data;
  wire core_model_rsp_ready;
  wire core_model_rsp_valid;
  wire [3:0] core_reg_addr;
  wire [63:0] core_reg_rdata;
  wire [63:0] core_reg_wdata;
  wire [274:0] core_response;
  output fault_indicator;
  wire fault_indicator;
  input reset_n;
  wire reset_n;
  reg [198:0] rx_active;
  reg [198:0] rx_shift;
  reg spi_active;
  reg spi_cs_meta;
  input spi_cs_n;
  wire spi_cs_n;
  reg spi_cs_prev;
  reg spi_cs_sync;
  output spi_miso;
  wire spi_miso;
  input spi_mosi;
  wire spi_mosi;
  input spi_sclk;
  wire spi_sclk;
  reg [274:0] tx_shift;
  reg [274:0] tx_snapshot;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) rx_active <= 199'h00000000000000000000000000000000000000000000000000;
    else if (_01_) rx_active <= rx_shift;
  always @(posedge spi_sclk)
    if (!spi_cs_n) rx_shift <= { rx_shift[197:0], spi_mosi };
  always @(posedge spi_sclk)
    if (!spi_cs_n) tx_shift <= _03_;
  assign _00_ = ~ reset_n;
  assign _01_ = spi_cs_sync && _02_;
  assign _02_ = ! spi_cs_prev;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) tx_snapshot <= 275'h000000000000000000000000000000000000000000000000000000000000000000000;
    else tx_snapshot <= { core_reg_rdata, core_model_req_valid, core_model_req_data, core_model_rsp_ready, core_actuator_cmd_valid, core_actuator_cmd_data, core_fault_summary, core_heartbeat_status };
  always @(posedge clk, negedge reset_n)
    if (!reset_n) spi_cs_meta <= 1'h1;
    else spi_cs_meta <= spi_cs_n;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) spi_cs_sync <= 1'h1;
    else spi_cs_sync <= spi_cs_meta;
  always @(posedge clk, negedge reset_n)
    if (!reset_n) spi_cs_prev <= 1'h1;
    else spi_cs_prev <= spi_cs_sync;
  always @(posedge spi_sclk, posedge spi_cs_n)
    if (spi_cs_n) spi_active <= 1'h0;
    else spi_active <= 1'h1;
  assign _03_ = spi_active ? { tx_shift[273:0], 1'h0 } : { tx_snapshot[273:0], 1'h0 };
  assign spi_miso = spi_active ? tx_shift[274] : tx_snapshot[274];
  adaptive_aero_control_top u_core (
    .actuator_cmd_data(core_actuator_cmd_data),
    .actuator_cmd_ready(rx_active[198]),
    .actuator_cmd_valid(core_actuator_cmd_valid),
    .clk(clk),
    .fault_summary(core_fault_summary),
    .heartbeat_status(core_heartbeat_status),
    .model_req_data(core_model_req_data),
    .model_req_ready(rx_active[68]),
    .model_req_valid(core_model_req_valid),
    .model_rsp_data(rx_active[197:70]),
    .model_rsp_ready(core_model_rsp_ready),
    .model_rsp_valid(rx_active[69]),
    .reg_addr(rx_active[3:0]),
    .reg_rdata(core_reg_rdata),
    .reg_wdata(rx_active[67:4]),
    .reset(_00_)
  );
  assign core_actuator_cmd_ready = rx_active[198];
  assign core_model_req_ready = rx_active[68];
  assign core_model_rsp_data = rx_active[197:70];
  assign core_model_rsp_valid = rx_active[69];
  assign core_reg_addr = rx_active[3:0];
  assign core_reg_wdata = rx_active[67:4];
  assign core_response = { core_reg_rdata, core_model_req_valid, core_model_req_data, core_model_rsp_ready, core_actuator_cmd_valid, core_actuator_cmd_data, core_fault_summary, core_heartbeat_status };
  assign fault_indicator = 1'h0;
endmodule

module adaptive_aero_control_top_transport(clk, reset, cfg_enable, cfg_mode, cfg_hold_last_valid, cfg_fallback_enable, cfg_heartbeat_enable, cfg_seq_reset, cfg_signed_clamp, cfg_queue_depth, cfg_service_flags, cfg_timeout_cycles, cfg_heartbeat_timeout_cycles, cfg_mode_context, cfg_operating_point_tag, cfg_velocity_tag, cfg_geometry_id, cfg_velocity_setpoint, cfg_age_basis, req_valid, req_ready
, req_data, rsp_valid, rsp_ready, rsp_data, act_valid, act_ready, act_data, fault_summary, heartbeat_status, accepted_req_count, accepted_rsp_count, rejected_rsp_count, fallback_entry_count);
  wire [63:0] _000_;
  wire _001_;
  wire [31:0] _002_;
  wire _003_;
  wire [7:0] _004_;
  wire _005_;
  wire [31:0] _006_;
  wire [7:0] _007_;
  wire [15:0] _008_;
  wire _009_;
  wire _010_;
  wire [31:0] _011_;
  wire [31:0] _012_;
  wire [15:0] _013_;
  wire [15:0] _014_;
  wire [15:0] _015_;
  wire [7:0] _016_;
  wire [7:0] _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire [31:0] _044_;
  wire [31:0] _045_;
  wire _046_;
  wire _047_;
  wire [31:0] _048_;
  wire [31:0] _049_;
  wire [15:0] _050_;
  wire _051_;
  wire _052_;
  wire [7:0] _053_;
  wire [7:0] _054_;
  wire [7:0] _055_;
  wire [63:0] _056_;
  wire [63:0] _057_;
  wire [63:0] _058_;
  wire [63:0] _059_;
  wire [63:0] _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  output [15:0] accepted_req_count;
  reg [15:0] accepted_req_count;
  output [15:0] accepted_rsp_count;
  reg [15:0] accepted_rsp_count;
  output [63:0] act_data;
  reg [63:0] act_data;
  input act_ready;
  wire act_ready;
  output act_valid;
  reg act_valid;
  input [31:0] cfg_age_basis;
  wire [31:0] cfg_age_basis;
  input cfg_enable;
  wire cfg_enable;
  input cfg_fallback_enable;
  wire cfg_fallback_enable;
  input [31:0] cfg_geometry_id;
  wire [31:0] cfg_geometry_id;
  input cfg_heartbeat_enable;
  wire cfg_heartbeat_enable;
  input [31:0] cfg_heartbeat_timeout_cycles;
  wire [31:0] cfg_heartbeat_timeout_cycles;
  input cfg_hold_last_valid;
  wire cfg_hold_last_valid;
  input [2:0] cfg_mode;
  wire [2:0] cfg_mode;
  input [3:0] cfg_mode_context;
  wire [3:0] cfg_mode_context;
  input [11:0] cfg_operating_point_tag;
  wire [11:0] cfg_operating_point_tag;
  input [2:0] cfg_queue_depth;
  wire [2:0] cfg_queue_depth;
  input cfg_seq_reset;
  wire cfg_seq_reset;
  input [7:0] cfg_service_flags;
  wire [7:0] cfg_service_flags;
  input cfg_signed_clamp;
  wire cfg_signed_clamp;
  input [31:0] cfg_timeout_cycles;
  wire [31:0] cfg_timeout_cycles;
  input [31:0] cfg_velocity_setpoint;
  wire [31:0] cfg_velocity_setpoint;
  input [15:0] cfg_velocity_tag;
  wire [15:0] cfg_velocity_tag;
  wire clamp_fault;
  input clk;
  wire clk;
  reg fallback_active;
  wire [63:0] fallback_cmd;
  output [7:0] fallback_entry_count;
  reg [7:0] fallback_entry_count;
  wire [7:0] fault_next;
  output [7:0] fault_summary;
  wire [7:0] fault_summary;
  wire [7:0] hb_next;
  reg [31:0] heartbeat_age;
  reg heartbeat_fault;
  output [7:0] heartbeat_status;
  wire [7:0] heartbeat_status;
  reg outstanding;
  reg [31:0] outstanding_age;
  reg protocol_fault;
  output [7:0] rejected_rsp_count;
  reg [7:0] rejected_rsp_count;
  wire req_accept;
  output [127:0] req_data;
  reg [127:0] req_data;
  wire req_fire;
  wire [127:0] req_next;
  input req_ready;
  wire req_ready;
  reg [15:0] req_seq;
  output req_valid;
  reg req_valid;
  input reset;
  wire reset;
  wire [31:0] rsp_cmd0;
  wire [31:0] rsp_cmd1;
  input [127:0] rsp_data;
  wire [127:0] rsp_data;
  wire rsp_fire;
  wire [15:0] rsp_proto_field;
  output rsp_ready;
  wire rsp_ready;
  wire [15:0] rsp_seq_field;
  wire [15:0] rsp_status_field;
  input rsp_valid;
  wire rsp_valid;
  reg seq_fault;
  reg stale_fault;
  wire timeout_fault;
  assign _011_ = heartbeat_age + 32'd1;
  assign _012_ = outstanding_age + 32'd1;
  assign _013_ = accepted_req_count + 16'h0001;
  assign _014_ = req_seq + 16'h0001;
  assign _015_ = accepted_rsp_count + 16'h0001;
  assign _017_ = fallback_entry_count + 8'h01;
  assign _016_ = rejected_rsp_count + 8'h01;
  always @(posedge clk, posedge reset)
    if (reset) accepted_rsp_count <= 16'h0000;
    else if (_021_) accepted_rsp_count <= _015_;
  always @(posedge clk)
    if (!reset)
      if (!_033_) seq_fault <= 1'h0;
      else seq_fault <= _042_;
  always @(posedge clk, posedge reset)
    if (reset) fallback_entry_count <= 8'h00;
    else if (_022_) fallback_entry_count <= _017_;
  always @(posedge clk)
    if (!reset) stale_fault <= _010_;
  always @(posedge clk)
    if (!reset)
      if (_034_) fallback_active <= 1'h0;
      else fallback_active <= _052_;
  always @(posedge clk)
    if (!reset)
      if (!_033_) protocol_fault <= 1'h0;
      else protocol_fault <= _043_;
  always @(posedge clk, posedge reset)
    if (reset) req_seq <= 16'h0000;
    else if (_018_) req_seq <= _008_;
  always @(posedge clk, posedge reset)
    if (reset) accepted_req_count <= 16'h0000;
    else if (req_fire) accepted_req_count <= _013_;
  always @(posedge clk, posedge reset)
    if (reset) outstanding_age <= 32'd0;
    else if (_019_) outstanding_age <= _006_;
  always @(posedge clk, posedge reset)
    if (reset) req_valid <= 1'h0;
    else if (_020_) req_valid <= _009_;
  always @(posedge clk)
    if (!reset) heartbeat_fault <= _003_;
  always @(posedge clk, posedge reset)
    if (reset) req_data <= 128'h00000000000000000000000000000000;
    else if (req_accept) req_data <= { cfg_service_flags[3:0], cfg_operating_point_tag, cfg_velocity_tag, cfg_geometry_id, cfg_velocity_setpoint, cfg_age_basis };
  reg \heartbeat_status_reg[0] ;
  always @(posedge clk, posedge reset)
    if (reset) \heartbeat_status_reg[0]  <= 1'h0;
    else \heartbeat_status_reg[0]  <= _004_[0];
  assign heartbeat_status[0] = \heartbeat_status_reg[0] ;
  reg [46:0] _088_;
  always @(posedge clk, posedge reset)
    if (reset) _088_ <= 47'h000000000000;
    else if (req_fire) _088_ <= { cfg_velocity_setpoint[15:0], cfg_geometry_id[15:0], cfg_mode_context, cfg_mode, cfg_service_flags };
  assign fallback_cmd[46:0] = _088_;
  reg [5:0] _089_;
  always @(posedge clk, posedge reset)
    if (reset) _089_ <= 6'h10;
    else _089_ <= { heartbeat_fault, fallback_active, stale_fault, seq_fault, protocol_fault, stale_fault };
  assign { fault_summary[7], fault_summary[5:1] } = _089_;
  assign _018_ = | { req_fire, cfg_seq_reset };
  assign _019_ = { req_fire, _038_, outstanding } != 3'h1;
  assign _020_ = | { req_accept, req_fire };
  assign _021_ = & { _028_, rsp_valid };
  assign _022_ = & { _031_, cfg_fallback_enable };
  assign _023_ = rsp_data[19:16] == 4'h1;
  assign _024_ = rsp_data[15:0] == req_seq;
  assign _025_ = outstanding_age >= cfg_timeout_cycles;
  assign _026_ = heartbeat_age >= cfg_heartbeat_timeout_cycles;
  assign _027_ = _023_ && outstanding;
  assign _028_ = _027_ && _024_;
  assign _029_ = act_valid && act_ready;
  assign _034_ = cfg_hold_last_valid && _041_;
  assign req_fire = req_valid && req_ready;
  assign _030_ = cfg_enable && _035_;
  assign req_accept = _030_ && _036_;
  assign _031_ = outstanding && _025_;
  assign _032_ = cfg_heartbeat_enable && _026_;
  assign _033_ = rsp_valid && outstanding;
  assign _035_ = ! outstanding;
  assign _036_ = ! req_valid;
  assign _037_ = heartbeat_age != 32'd4294967295;
  assign _038_ = outstanding_age != 32'd4294967295;
  assign _039_ = rsp_data[19:16] != 4'h1;
  assign _041_ = | accepted_rsp_count;
  assign _040_ = rsp_data[15:0] != req_seq;
  assign _004_[0] = ~ heartbeat_fault;
  always @(posedge clk, posedge reset)
    if (reset) act_valid <= 1'h0;
    else act_valid <= _001_;
  always @(posedge clk, posedge reset)
    if (reset) act_data <= 64'h0000000000000000;
    else act_data <= _000_;
  always @(posedge clk, posedge reset)
    if (reset) rejected_rsp_count <= 8'h00;
    else rejected_rsp_count <= _007_;
  always @(posedge clk, posedge reset)
    if (reset) outstanding <= 1'h0;
    else outstanding <= _005_;
  always @(posedge clk, posedge reset)
    if (reset) heartbeat_age <= 32'd0;
    else heartbeat_age <= _002_;
  assign _003_ = _032_ ? 1'h1 : 1'h0;
  assign _042_ = _040_ ? 1'h1 : 1'h0;
  assign _043_ = _039_ ? 1'h1 : 1'h0;
  assign _010_ = _031_ ? 1'h1 : 1'h0;
  assign _044_ = _037_ ? _011_ : heartbeat_age;
  assign _045_ = _028_ ? 32'd0 : _044_;
  assign _002_ = rsp_valid ? _045_ : _044_;
  assign _046_ = req_fire ? 1'h1 : outstanding;
  assign _047_ = _028_ ? 1'h0 : _046_;
  assign _005_ = rsp_valid ? _047_ : _046_;
  assign _048_ = _038_ ? _012_ : 32'hxxxxxxxx;
  assign _049_ = outstanding ? _048_ : 32'd0;
  assign _006_ = req_fire ? 32'd0 : _049_;
  assign _050_ = cfg_seq_reset ? 16'h0000 : 16'hxxxx;
  assign _008_ = req_fire ? _014_ : _050_;
  assign _051_ = _031_ ? cfg_fallback_enable : 1'h0;
  assign _052_ = _032_ ? cfg_fallback_enable : _051_;
  assign _053_ = _028_ ? rejected_rsp_count : _016_;
  assign _054_ = rsp_valid ? _053_ : rejected_rsp_count;
  assign _055_ = _039_ ? _016_ : _054_;
  assign _007_ = _033_ ? _055_ : _054_;
  assign _056_ = _028_ ? { rsp_data[79:64], rsp_data[47:32], rsp_data[95:80], rsp_data[63:48] } : act_data;
  assign _057_ = rsp_valid ? _056_ : act_data;
  assign _058_ = cfg_fallback_enable ? { 17'h00000, fallback_cmd[46:0] } : _057_;
  assign _059_ = _031_ ? _058_ : _057_;
  assign _060_ = cfg_fallback_enable ? { 17'h00000, fallback_cmd[46:0] } : _059_;
  assign _000_ = _032_ ? _060_ : _059_;
  assign _061_ = _028_ ? 1'h1 : act_valid;
  assign _062_ = rsp_valid ? _061_ : act_valid;
  assign _063_ = _029_ ? 1'h0 : _062_;
  assign _064_ = cfg_fallback_enable ? 1'h1 : _063_;
  assign _065_ = _031_ ? _064_ : _063_;
  assign _066_ = cfg_fallback_enable ? 1'h1 : _065_;
  assign _001_ = _032_ ? _066_ : _065_;
  assign _067_ = req_accept ? 1'h1 : 1'hx;
  assign _009_ = req_fire ? 1'h0 : _067_;
  assign _004_[7:1] = 7'h00;
  assign clamp_fault = 1'h0;
  assign fallback_cmd[63:47] = 17'h00000;
  assign fault_next = { fault_summary[7], 1'h0, fault_summary[5:1], 1'h0 };
  assign { fault_summary[6], fault_summary[0] } = 2'h0;
  assign hb_next = { 7'h00, heartbeat_status[0] };
  assign heartbeat_status[7:1] = 7'h00;
  assign req_next = req_data;
  assign rsp_cmd0 = rsp_data[63:32];
  assign rsp_cmd1 = rsp_data[95:64];
  assign rsp_fire = rsp_valid;
  assign rsp_proto_field = rsp_data[31:16];
  assign rsp_ready = 1'h1;
  assign rsp_seq_field = rsp_data[15:0];
  assign rsp_status_field = rsp_data[15:0];
  assign timeout_fault = stale_fault;
endmodule
