# Auto-generated by ChipLoop Testbench Generator Agent
# Explicit RTL sources used by simulation
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_actuator_control.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_mmio.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_top.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_top_spi_fpga_top.sv
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_request_supervisor.v
