# Auto-generated by ChipLoop Testbench Generator Agent
# Explicit RTL sources used by simulation
VERILOG_SOURCES += ../../handoff/rtl/demo_sram_32x256_model.v
VERILOG_SOURCES += ../../handoff/rtl/demo_sram_32x256_wrapper.v
VERILOG_SOURCES += ../../handoff/rtl/sram_mbist_demo_controller.v
