"""Auto-generated Cocotb testbench skeleton for: sram_mbist_demo_controller

Generated by ChipLoop Testbench Generator Agent.
- Uses spec JSON as the source of truth for ports/clocks/resets
- Supports digital mode and future system/SoC mode
- Avoids hardcoded DUT signal assumptions
"""

import os
import random
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, Timer

try:
    from scoreboard import Scoreboard
except Exception:
    Scoreboard = None

try:
    from coverage_model import CoverageModel
except Exception:
    CoverageModel = None


def _seed() -> int:
    env = os.getenv("RANDOM_SEED")
    if env and env.isdigit():
        return int(env)
    return 1


async def _advance_time(dut):
    clocks = [
  "clk"
]
    for clk_name in clocks:
        if hasattr(dut, clk_name):
            await RisingEdge(getattr(dut, clk_name))
            return
    await Timer(10, units="ns")


def _safe_drive_random(sig, width_expr: str):
    try:
        width = int(width_expr)
    except Exception:
        try:
            width = len(sig.value.binstr)
        except Exception:
            width = 1
    width = max(int(width), 1)
    sig.value = random.getrandbits(width)


def _assert_outputs_known(dut, observable_outputs):
    for p in observable_outputs:
        name = p.get("name")
        if not name or not hasattr(dut, name):
            continue
        sig = getattr(dut, name)
        value = str(sig.value).lower()
        assert "x" not in value and "z" not in value, f"Output {name} is unknown/high-Z: {sig.value}"


@cocotb.test()
async def smoke_test(dut):
    """Basic smoke test: clock/reset bring-up and brief settle window."""
    seed = _seed()
    random.seed(seed)

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 1
    await Timer(5, units='ns')

    # Initialize discoverable DUT inputs from spec
    if hasattr(dut, "wr_en"):
        getattr(dut, "wr_en").value = 0
    if hasattr(dut, "wr_addr"):
        getattr(dut, "wr_addr").value = 0
    if hasattr(dut, "wr_data"):
        getattr(dut, "wr_data").value = 0
    if hasattr(dut, "rd_en"):
        getattr(dut, "rd_en").value = 0
    if hasattr(dut, "rd_addr"):
        getattr(dut, "rd_addr").value = 0
    if hasattr(dut, "bist_start"):
        getattr(dut, "bist_start").value = 0

    await Timer(20, units="ns")

    sb = Scoreboard(dut) if Scoreboard else None
    cov = CoverageModel() if CoverageModel else None

    if sb:
        sb.start()
    if cov:
        cov.start(dut)

    for _ in range(5):
        await _advance_time(dut)
        if cov:
            try:
                cov.sample()
            except Exception:
                pass

    _assert_outputs_known(dut, [
  {
    "name": "rd_data",
    "width_expr": "32"
  },
  {
    "name": "ready",
    "width_expr": "1"
  },
  {
    "name": "bist_done",
    "width_expr": "1"
  },
  {
    "name": "bist_fail",
    "width_expr": "1"
  },
  {
    "name": "irq",
    "width_expr": "1"
  }
])

    if cov:
        try:
            cov.stop()
            cov.write_reports()
        except Exception:
            pass

    

    if sb:
        sb.stop()


@cocotb.test()
async def constrained_random_sanity(dut):
    """Constrained-random sanity test derived only from spec-declared inputs."""
    seed = _seed()
    random.seed(seed)

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 1
    await Timer(5, units='ns')

    randomizable_inputs = [
  {
    "name": "wr_en",
    "width_expr": "1"
  },
  {
    "name": "wr_addr",
    "width_expr": "8"
  },
  {
    "name": "wr_data",
    "width_expr": "32"
  },
  {
    "name": "rd_en",
    "width_expr": "1"
  },
  {
    "name": "rd_addr",
    "width_expr": "8"
  },
  {
    "name": "bist_start",
    "width_expr": "1"
  }
]

    cov = CoverageModel() if CoverageModel else None
    if cov:
        cov.start(dut)

    for _ in range(int(os.getenv("NUM_ITERS", "25"))):
        for p in randomizable_inputs:
            name = p.get("name")
            width_expr = str(p.get("width_expr", "1"))
            if not name or not hasattr(dut, name):
                continue
            try:
                sig = getattr(dut, name)
                _safe_drive_random(sig, width_expr)
            except Exception:
                continue

        await _advance_time(dut)

        if cov:
            try:
                cov.sample()
            except Exception:
                pass

    _assert_outputs_known(dut, [
  {
    "name": "rd_data",
    "width_expr": "32"
  },
  {
    "name": "ready",
    "width_expr": "1"
  },
  {
    "name": "bist_done",
    "width_expr": "1"
  },
  {
    "name": "bist_fail",
    "width_expr": "1"
  },
  {
    "name": "irq",
    "width_expr": "1"
  }
])

    if cov:
        try:
            cov.stop()
            cov.write_reports()
        except Exception:
            pass

    

@cocotb.test()
async def memory_write_read_directed(dut):
    """Directed memory access test emitted when a simple write/read interface is present."""

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 1
    await Timer(5, units='ns')

    # Initialize discoverable DUT inputs from spec
    if hasattr(dut, "wr_en"):
        getattr(dut, "wr_en").value = 0
    if hasattr(dut, "wr_addr"):
        getattr(dut, "wr_addr").value = 0
    if hasattr(dut, "wr_data"):
        getattr(dut, "wr_data").value = 0
    if hasattr(dut, "rd_en"):
        getattr(dut, "rd_en").value = 0
    if hasattr(dut, "rd_addr"):
        getattr(dut, "rd_addr").value = 0
    if hasattr(dut, "bist_start"):
        getattr(dut, "bist_start").value = 0

    test_addr = int(os.getenv("DIRECTED_MEM_ADDR", "3"))
    test_data = int(os.getenv("DIRECTED_MEM_DATA", "2779096485"))

    dut.wr_addr.value = test_addr
    dut.wr_data.value = test_data
    dut.wr_en.value = 1
    await _advance_time(dut)
    dut.wr_en.value = 0
    await _advance_time(dut)

    dut.rd_addr.value = test_addr
    dut.rd_en.value = 1
    await _advance_time(dut)
    await _advance_time(dut)
    dut.rd_en.value = 0

    _assert_outputs_known(dut, [
  {
    "name": "rd_data",
    "width_expr": "32"
  },
  {
    "name": "ready",
    "width_expr": "1"
  },
  {
    "name": "bist_done",
    "width_expr": "1"
  },
  {
    "name": "bist_fail",
    "width_expr": "1"
  },
  {
    "name": "irq",
    "width_expr": "1"
  }
])


@cocotb.test()
async def bist_start_directed(dut):
    """Directed BIST request test emitted when a BIST start/status interface is present."""

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "reset_n"):
        getattr(dut, "reset_n").value = 1
    await Timer(5, units='ns')

    # Initialize discoverable DUT inputs from spec
    if hasattr(dut, "wr_en"):
        getattr(dut, "wr_en").value = 0
    if hasattr(dut, "wr_addr"):
        getattr(dut, "wr_addr").value = 0
    if hasattr(dut, "wr_data"):
        getattr(dut, "wr_data").value = 0
    if hasattr(dut, "rd_en"):
        getattr(dut, "rd_en").value = 0
    if hasattr(dut, "rd_addr"):
        getattr(dut, "rd_addr").value = 0
    if hasattr(dut, "bist_start"):
        getattr(dut, "bist_start").value = 0

    dut.bist_start.value = 1
    await _advance_time(dut)
    dut.bist_start.value = 0

    for _ in range(int(os.getenv("BIST_DIRECTED_WAIT_CYCLES", "40"))):
        await _advance_time(dut)
        if hasattr(dut, "bist_done") and int(dut.bist_done.value) == 1:
            break

    _assert_outputs_known(dut, [
  {
    "name": "rd_data",
    "width_expr": "32"
  },
  {
    "name": "ready",
    "width_expr": "1"
  },
  {
    "name": "bist_done",
    "width_expr": "1"
  },
  {
    "name": "bist_fail",
    "width_expr": "1"
  },
  {
    "name": "irq",
    "width_expr": "1"
  }
])

