"""Auto-generated Cocotb testbench skeleton for: aero_safety_controller

Generated by ChipLoop Testbench Generator Agent.
- Uses spec JSON as the source of truth for ports/clocks/resets
- Supports digital mode and future system/SoC mode
- Avoids hardcoded DUT signal assumptions
"""

import os
import random
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, Timer

try:
    from scoreboard import Scoreboard
except Exception:
    Scoreboard = None

try:
    from coverage_model import CoverageModel
except Exception:
    CoverageModel = None


def _seed() -> int:
    env = os.getenv("RANDOM_SEED")
    if env and env.isdigit():
        return int(env)
    return 1


async def _advance_time(dut):
    clocks = [
  "clk"
]
    for clk_name in clocks:
        if hasattr(dut, clk_name):
            await RisingEdge(getattr(dut, clk_name))
            return
    await Timer(10, units="ns")


def _safe_drive_random(sig, width_expr: str):
    try:
        width = int(width_expr)
    except Exception:
        try:
            width = len(sig.value.binstr)
        except Exception:
            width = 1
    width = max(int(width), 1)
    sig.value = random.getrandbits(width)


def _fit_to_signal(sig, value: int) -> int:
    try:
        width = len(sig)
    except Exception:
        try:
            width = len(sig.value.binstr)
        except Exception:
            width = 32
    width = max(int(width), 1)
    return int(value) & ((1 << width) - 1)


def _assert_outputs_known(dut, observable_outputs):
    for p in observable_outputs:
        name = p.get("name")
        if not name or not hasattr(dut, name):
            continue
        sig = getattr(dut, name)
        value = str(sig.value).lower()
        assert "x" not in value and "z" not in value, f"Output {name} is unknown/high-Z: {sig.value}"


@cocotb.test()
async def smoke_test(dut):
    """Basic smoke test: clock/reset bring-up and brief settle window."""
    seed = _seed()
    random.seed(seed)

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "rst_n"):
        getattr(dut, "rst_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "rst_n"):
        getattr(dut, "rst_n").value = 1
    await Timer(5, units='ns')

    # Initialize discoverable DUT inputs from spec
    if hasattr(dut, "tick_1ms"):
        getattr(dut, "tick_1ms").value = 0
    if hasattr(dut, "host_reg_wr_valid"):
        getattr(dut, "host_reg_wr_valid").value = 0
    if hasattr(dut, "host_reg_rd_valid"):
        getattr(dut, "host_reg_rd_valid").value = 0
    if hasattr(dut, "host_reg_addr"):
        getattr(dut, "host_reg_addr").value = 0
    if hasattr(dut, "host_reg_wdata"):
        getattr(dut, "host_reg_wdata").value = 0
    if hasattr(dut, "stream_velocity_mps"):
        getattr(dut, "stream_velocity_mps").value = 0
    if hasattr(dut, "geom_valid"):
        getattr(dut, "geom_valid").value = 0
    if hasattr(dut, "geom_format_id_in"):
        getattr(dut, "geom_format_id_in").value = 0
    if hasattr(dut, "geom_source_id_in"):
        getattr(dut, "geom_source_id_in").value = 0
    if hasattr(dut, "geom_version_in"):
        getattr(dut, "geom_version_in").value = 0
    if hasattr(dut, "model_req_ready"):
        getattr(dut, "model_req_ready").value = 0
    if hasattr(dut, "model_rsp_valid"):
        getattr(dut, "model_rsp_valid").value = 0
    if hasattr(dut, "model_rsp_seq"):
        getattr(dut, "model_rsp_seq").value = 0
    if hasattr(dut, "model_rsp_drag_force"):
        getattr(dut, "model_rsp_drag_force").value = 0
    if hasattr(dut, "model_rsp_lift_force"):
        getattr(dut, "model_rsp_lift_force").value = 0
    if hasattr(dut, "model_rsp_surface_pressure"):
        getattr(dut, "model_rsp_surface_pressure").value = 0
    if hasattr(dut, "model_rsp_flow_field"):
        getattr(dut, "model_rsp_flow_field").value = 0
    if hasattr(dut, "model_rsp_inference_status_not_executed"):
        getattr(dut, "model_rsp_inference_status_not_executed").value = 0
    if hasattr(dut, "aero_regfile_cfg_enable"):
        getattr(dut, "aero_regfile_cfg_enable").value = 0
    if hasattr(dut, "aero_regfile_cfg_stream_velocity_mps_setpoint"):
        getattr(dut, "aero_regfile_cfg_stream_velocity_mps_setpoint").value = 0
    if hasattr(dut, "aero_regfile_cfg_velocity_min_limit"):
        getattr(dut, "aero_regfile_cfg_velocity_min_limit").value = 0
    if hasattr(dut, "aero_regfile_cfg_velocity_max_limit"):
        getattr(dut, "aero_regfile_cfg_velocity_max_limit").value = 0
    if hasattr(dut, "aero_regfile_cfg_actuator_min_limit"):
        getattr(dut, "aero_regfile_cfg_actuator_min_limit").value = 0
    if hasattr(dut, "aero_regfile_cfg_actuator_max_limit"):
        getattr(dut, "aero_regfile_cfg_actuator_max_limit").value = 0
    if hasattr(dut, "aero_regfile_cfg_actuator_safe_position"):
        getattr(dut, "aero_regfile_cfg_actuator_safe_position").value = 0
    if hasattr(dut, "aero_regfile_cfg_command_timeout_cycles"):
        getattr(dut, "aero_regfile_cfg_command_timeout_cycles").value = 0
    if hasattr(dut, "aero_regfile_cfg_max_slew_rate"):
        getattr(dut, "aero_regfile_cfg_max_slew_rate").value = 0
    if hasattr(dut, "aero_regfile_cfg_geometry_format_id"):
        getattr(dut, "aero_regfile_cfg_geometry_format_id").value = 0
    if hasattr(dut, "aero_regfile_cfg_geometry_source_id"):
        getattr(dut, "aero_regfile_cfg_geometry_source_id").value = 0
    if hasattr(dut, "aero_regfile_cfg_geometry_version"):
        getattr(dut, "aero_regfile_cfg_geometry_version").value = 0
    if hasattr(dut, "aero_regfile_cfg_clear_faults"):
        getattr(dut, "aero_regfile_cfg_clear_faults").value = 0
    if hasattr(dut, "aero_supervisor_req_valid"):
        getattr(dut, "aero_supervisor_req_valid").value = 0
    if hasattr(dut, "aero_supervisor_req_seq"):
        getattr(dut, "aero_supervisor_req_seq").value = 0
    if hasattr(dut, "aero_supervisor_req_inflight"):
        getattr(dut, "aero_supervisor_req_inflight").value = 0
    if hasattr(dut, "aero_supervisor_fault_code"):
        getattr(dut, "aero_supervisor_fault_code").value = 0
    if hasattr(dut, "aero_supervisor_request_age_cycles"):
        getattr(dut, "aero_supervisor_request_age_cycles").value = 0
    if hasattr(dut, "aero_supervisor_request_stale"):
        getattr(dut, "aero_supervisor_request_stale").value = 0
    if hasattr(dut, "aero_supervisor_geometry_invalid"):
        getattr(dut, "aero_supervisor_geometry_invalid").value = 0
    if hasattr(dut, "aero_supervisor_out_of_range_fault"):
        getattr(dut, "aero_supervisor_out_of_range_fault").value = 0
    if hasattr(dut, "aero_supervisor_sequence_mismatch_fault"):
        getattr(dut, "aero_supervisor_sequence_mismatch_fault").value = 0
    if hasattr(dut, "aero_supervisor_service_unavailable_fault"):
        getattr(dut, "aero_supervisor_service_unavailable_fault").value = 0
    if hasattr(dut, "aero_supervisor_protocol_error_fault"):
        getattr(dut, "aero_supervisor_protocol_error_fault").value = 0
    if hasattr(dut, "aero_supervisor_stale_response_fault"):
        getattr(dut, "aero_supervisor_stale_response_fault").value = 0
    if hasattr(dut, "aero_command_sanitizer_cmd_position"):
        getattr(dut, "aero_command_sanitizer_cmd_position").value = 0
    if hasattr(dut, "aero_command_sanitizer_cmd_valid"):
        getattr(dut, "aero_command_sanitizer_cmd_valid").value = 0
    if hasattr(dut, "aero_command_sanitizer_cmd_enable"):
        getattr(dut, "aero_command_sanitizer_cmd_enable").value = 0
    if hasattr(dut, "aero_command_sanitizer_cmd_seq"):
        getattr(dut, "aero_command_sanitizer_cmd_seq").value = 0
    if hasattr(dut, "aero_command_sanitizer_fallback_active_out"):
        getattr(dut, "aero_command_sanitizer_fallback_active_out").value = 0
    if hasattr(dut, "aero_command_sanitizer_clamp_applied"):
        getattr(dut, "aero_command_sanitizer_clamp_applied").value = 0
    if hasattr(dut, "aero_command_sanitizer_clamp_event_pulse"):
        getattr(dut, "aero_command_sanitizer_clamp_event_pulse").value = 0
    if hasattr(dut, "aero_command_sanitizer_sanitized_position"):
        getattr(dut, "aero_command_sanitizer_sanitized_position").value = 0

    await Timer(20, units="ns")

    sb = Scoreboard(dut) if Scoreboard else None
    cov = CoverageModel() if CoverageModel else None

    if sb:
        sb.start()
    if cov:
        cov.start(dut)

    for _ in range(5):
        await _advance_time(dut)
        if cov:
            try:
                cov.sample()
            except Exception:
                pass

    _assert_outputs_known(dut, [
  {
    "name": "host_reg_ready",
    "width_expr": "1"
  },
  {
    "name": "host_reg_rdata",
    "width_expr": "32"
  },
  {
    "name": "host_reg_rvalid",
    "width_expr": "1"
  },
  {
    "name": "model_req_valid",
    "width_expr": "1"
  },
  {
    "name": "model_req_seq",
    "width_expr": "16"
  },
  {
    "name": "model_req_enable",
    "width_expr": "1"
  },
  {
    "name": "model_req_stream_velocity_mps",
    "width_expr": "16"
  },
  {
    "name": "model_req_velocity_min_limit",
    "width_expr": "16"
  },
  {
    "name": "model_req_velocity_max_limit",
    "width_expr": "16"
  },
  {
    "name": "model_req_actuator_min_limit",
    "width_expr": "16"
  },
  {
    "name": "model_req_actuator_max_limit",
    "width_expr": "16"
  },
  {
    "name": "model_req_actuator_safe_position",
    "width_expr": "16"
  },
  {
    "name": "model_req_command_timeout_cycles",
    "width_expr": "16"
  },
  {
    "name": "model_req_max_slew_rate",
    "width_expr": "16"
  },
  {
    "name": "model_req_geometry_format_id",
    "width_expr": "8"
  },
  {
    "name": "model_req_geometry_source_id",
    "width_expr": "8"
  },
  {
    "name": "model_req_geometry_version",
    "width_expr": "16"
  },
  {
    "name": "model_req_flow_velocity_mps",
    "width_expr": "16"
  },
  {
    "name": "model_req_geom_valid",
    "width_expr": "1"
  },
  {
    "name": "actuator_cmd_valid",
    "width_expr": "1"
  },
  {
    "name": "actuator_cmd_enable",
    "width_expr": "1"
  },
  {
    "name": "actuator_cmd_position",
    "width_expr": "16"
  },
  {
    "name": "actuator_cmd_seq",
    "width_expr": "16"
  },
  {
    "name": "actuator_cmd_fallback_active",
    "width_expr": "1"
  },
  {
    "name": "current_state",
    "width_expr": "4"
  },
  {
    "name": "last_fault_code",
    "width_expr": "4"
  },
  {
    "name": "stale_reject_count",
    "width_expr": "16"
  },
  {
    "name": "clamp_event_count",
    "width_expr": "16"
  },
  {
    "name": "fallback_active",
    "width_expr": "1"
  },
  {
    "name": "last_accepted_seq",
    "width_expr": "16"
  },
  {
    "name": "last_response_age",
    "width_expr": "16"
  },
  {
    "name": "request_inflight",
    "width_expr": "1"
  },
  {
    "name": "model_response_valid_seen",
    "width_expr": "1"
  },
  {
    "name": "debug_seq_trace",
    "width_expr": "16"
  },
  {
    "name": "debug_timeout_age",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_status_current_state",
    "width_expr": "4"
  },
  {
    "name": "aero_regfile_status_last_fault_code",
    "width_expr": "4"
  },
  {
    "name": "aero_regfile_status_stale_reject_count",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_status_clamp_event_count",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_status_fallback_active",
    "width_expr": "1"
  },
  {
    "name": "aero_regfile_status_last_accepted_seq",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_status_last_response_age",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_status_request_inflight",
    "width_expr": "1"
  },
  {
    "name": "aero_regfile_status_model_response_valid_seen",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_cfg_enable",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_cfg_stream_velocity_mps_setpoint",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_velocity_min_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_velocity_max_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_actuator_min_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_actuator_max_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_actuator_safe_position",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_command_timeout_cycles",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_max_slew_rate",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_geometry_format_id",
    "width_expr": "8"
  },
  {
    "name": "aero_supervisor_cfg_geometry_source_id",
    "width_expr": "8"
  },
  {
    "name": "aero_supervisor_cfg_geometry_version",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_clear_faults",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_req_ready",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_rsp_valid",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_rsp_seq",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_rsp_drag_force",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_rsp_lift_force",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_rsp_surface_pressure",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_rsp_flow_field",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_rsp_inference_status_not_executed",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_cfg_actuator_min_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_cfg_actuator_max_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_cfg_actuator_safe_position",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_cfg_max_slew_rate",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_cfg_enable",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_fallback_active_in",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_fault_active_in",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_req_seq",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_rsp_valid",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_rsp_seq",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_rsp_drag_force",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_rsp_lift_force",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_rsp_surface_pressure",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_rsp_flow_field",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_safe_position_source",
    "width_expr": "16"
  }
])

    if cov:
        try:
            cov.stop()
            cov.write_reports()
        except Exception:
            pass

    

    if sb:
        sb.stop()


@cocotb.test()
async def constrained_random_sanity(dut):
    """Constrained-random sanity test derived only from spec-declared inputs."""
    seed = _seed()
    random.seed(seed)

    if hasattr(dut, "clk"):
        cocotb.start_soon(Clock(getattr(dut, "clk"), 10, units='ns').start())

    if hasattr(dut, "rst_n"):
        getattr(dut, "rst_n").value = 0
    await Timer(5, units='ns')
    if hasattr(dut, "rst_n"):
        getattr(dut, "rst_n").value = 1
    await Timer(5, units='ns')

    randomizable_inputs = [
  {
    "name": "tick_1ms",
    "width_expr": "1"
  },
  {
    "name": "host_reg_wr_valid",
    "width_expr": "1"
  },
  {
    "name": "host_reg_rd_valid",
    "width_expr": "1"
  },
  {
    "name": "host_reg_addr",
    "width_expr": "8"
  },
  {
    "name": "host_reg_wdata",
    "width_expr": "32"
  },
  {
    "name": "stream_velocity_mps",
    "width_expr": "16"
  },
  {
    "name": "geom_valid",
    "width_expr": "1"
  },
  {
    "name": "geom_format_id_in",
    "width_expr": "8"
  },
  {
    "name": "geom_source_id_in",
    "width_expr": "8"
  },
  {
    "name": "geom_version_in",
    "width_expr": "16"
  },
  {
    "name": "model_req_ready",
    "width_expr": "1"
  },
  {
    "name": "model_rsp_valid",
    "width_expr": "1"
  },
  {
    "name": "model_rsp_seq",
    "width_expr": "16"
  },
  {
    "name": "model_rsp_drag_force",
    "width_expr": "16"
  },
  {
    "name": "model_rsp_lift_force",
    "width_expr": "16"
  },
  {
    "name": "model_rsp_surface_pressure",
    "width_expr": "16"
  },
  {
    "name": "model_rsp_flow_field",
    "width_expr": "16"
  },
  {
    "name": "model_rsp_inference_status_not_executed",
    "width_expr": "1"
  },
  {
    "name": "aero_regfile_cfg_enable",
    "width_expr": "1"
  },
  {
    "name": "aero_regfile_cfg_stream_velocity_mps_setpoint",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_cfg_velocity_min_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_cfg_velocity_max_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_cfg_actuator_min_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_cfg_actuator_max_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_cfg_actuator_safe_position",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_cfg_command_timeout_cycles",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_cfg_max_slew_rate",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_cfg_geometry_format_id",
    "width_expr": "8"
  },
  {
    "name": "aero_regfile_cfg_geometry_source_id",
    "width_expr": "8"
  },
  {
    "name": "aero_regfile_cfg_geometry_version",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_cfg_clear_faults",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_req_valid",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_req_seq",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_req_inflight",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_fault_code",
    "width_expr": "4"
  },
  {
    "name": "aero_supervisor_request_age_cycles",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_request_stale",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_geometry_invalid",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_out_of_range_fault",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_sequence_mismatch_fault",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_service_unavailable_fault",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_protocol_error_fault",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_stale_response_fault",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_cmd_position",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_cmd_valid",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_cmd_enable",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_cmd_seq",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_fallback_active_out",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_clamp_applied",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_clamp_event_pulse",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_sanitized_position",
    "width_expr": "16"
  }
]

    cov = CoverageModel() if CoverageModel else None
    if cov:
        cov.start(dut)

    for _ in range(int(os.getenv("NUM_ITERS", "25"))):
        for p in randomizable_inputs:
            name = p.get("name")
            width_expr = str(p.get("width_expr", "1"))
            if not name or not hasattr(dut, name):
                continue
            try:
                sig = getattr(dut, name)
                _safe_drive_random(sig, width_expr)
            except Exception:
                continue

        await _advance_time(dut)

        if cov:
            try:
                cov.sample()
            except Exception:
                pass

    _assert_outputs_known(dut, [
  {
    "name": "host_reg_ready",
    "width_expr": "1"
  },
  {
    "name": "host_reg_rdata",
    "width_expr": "32"
  },
  {
    "name": "host_reg_rvalid",
    "width_expr": "1"
  },
  {
    "name": "model_req_valid",
    "width_expr": "1"
  },
  {
    "name": "model_req_seq",
    "width_expr": "16"
  },
  {
    "name": "model_req_enable",
    "width_expr": "1"
  },
  {
    "name": "model_req_stream_velocity_mps",
    "width_expr": "16"
  },
  {
    "name": "model_req_velocity_min_limit",
    "width_expr": "16"
  },
  {
    "name": "model_req_velocity_max_limit",
    "width_expr": "16"
  },
  {
    "name": "model_req_actuator_min_limit",
    "width_expr": "16"
  },
  {
    "name": "model_req_actuator_max_limit",
    "width_expr": "16"
  },
  {
    "name": "model_req_actuator_safe_position",
    "width_expr": "16"
  },
  {
    "name": "model_req_command_timeout_cycles",
    "width_expr": "16"
  },
  {
    "name": "model_req_max_slew_rate",
    "width_expr": "16"
  },
  {
    "name": "model_req_geometry_format_id",
    "width_expr": "8"
  },
  {
    "name": "model_req_geometry_source_id",
    "width_expr": "8"
  },
  {
    "name": "model_req_geometry_version",
    "width_expr": "16"
  },
  {
    "name": "model_req_flow_velocity_mps",
    "width_expr": "16"
  },
  {
    "name": "model_req_geom_valid",
    "width_expr": "1"
  },
  {
    "name": "actuator_cmd_valid",
    "width_expr": "1"
  },
  {
    "name": "actuator_cmd_enable",
    "width_expr": "1"
  },
  {
    "name": "actuator_cmd_position",
    "width_expr": "16"
  },
  {
    "name": "actuator_cmd_seq",
    "width_expr": "16"
  },
  {
    "name": "actuator_cmd_fallback_active",
    "width_expr": "1"
  },
  {
    "name": "current_state",
    "width_expr": "4"
  },
  {
    "name": "last_fault_code",
    "width_expr": "4"
  },
  {
    "name": "stale_reject_count",
    "width_expr": "16"
  },
  {
    "name": "clamp_event_count",
    "width_expr": "16"
  },
  {
    "name": "fallback_active",
    "width_expr": "1"
  },
  {
    "name": "last_accepted_seq",
    "width_expr": "16"
  },
  {
    "name": "last_response_age",
    "width_expr": "16"
  },
  {
    "name": "request_inflight",
    "width_expr": "1"
  },
  {
    "name": "model_response_valid_seen",
    "width_expr": "1"
  },
  {
    "name": "debug_seq_trace",
    "width_expr": "16"
  },
  {
    "name": "debug_timeout_age",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_status_current_state",
    "width_expr": "4"
  },
  {
    "name": "aero_regfile_status_last_fault_code",
    "width_expr": "4"
  },
  {
    "name": "aero_regfile_status_stale_reject_count",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_status_clamp_event_count",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_status_fallback_active",
    "width_expr": "1"
  },
  {
    "name": "aero_regfile_status_last_accepted_seq",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_status_last_response_age",
    "width_expr": "16"
  },
  {
    "name": "aero_regfile_status_request_inflight",
    "width_expr": "1"
  },
  {
    "name": "aero_regfile_status_model_response_valid_seen",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_cfg_enable",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_cfg_stream_velocity_mps_setpoint",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_velocity_min_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_velocity_max_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_actuator_min_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_actuator_max_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_actuator_safe_position",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_command_timeout_cycles",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_max_slew_rate",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_geometry_format_id",
    "width_expr": "8"
  },
  {
    "name": "aero_supervisor_cfg_geometry_source_id",
    "width_expr": "8"
  },
  {
    "name": "aero_supervisor_cfg_geometry_version",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_cfg_clear_faults",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_req_ready",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_rsp_valid",
    "width_expr": "1"
  },
  {
    "name": "aero_supervisor_rsp_seq",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_rsp_drag_force",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_rsp_lift_force",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_rsp_surface_pressure",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_rsp_flow_field",
    "width_expr": "16"
  },
  {
    "name": "aero_supervisor_rsp_inference_status_not_executed",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_cfg_actuator_min_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_cfg_actuator_max_limit",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_cfg_actuator_safe_position",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_cfg_max_slew_rate",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_cfg_enable",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_fallback_active_in",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_fault_active_in",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_req_seq",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_rsp_valid",
    "width_expr": "1"
  },
  {
    "name": "aero_command_sanitizer_rsp_seq",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_rsp_drag_force",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_rsp_lift_force",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_rsp_surface_pressure",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_rsp_flow_field",
    "width_expr": "16"
  },
  {
    "name": "aero_command_sanitizer_safe_position_source",
    "width_expr": "16"
  }
])

    if cov:
        try:
            cov.stop()
            cov.write_reports()
        except Exception:
            pass

    

