import os
import json
from typing import Any, Dict, List

from utils.artifact_utils import save_text_artifact_and_record


def _load_spec_from_state_or_disk(state: dict, workflow_dir: str) -> Dict[str, Any]:
    spec = state.get("analog_spec")
    if isinstance(spec, dict) and spec:
        return spec

    candidates = [
        os.path.join(workflow_dir, "analog", "spec", "spec_normalized.json"),
        os.path.join(workflow_dir, "analog", "spec.json"),
    ]
    for p in candidates:
        if os.path.exists(p):
            with open(p, "r", encoding="utf-8") as f:
                return json.load(f)

    return {}


def _spice_pin_name(port: Dict[str, Any]) -> str:
    return str(port.get("name", "")).strip()


def run_agent(state: dict) -> dict:
    agent_name = "Analog Netlist Scaffold Agent"
    print("\n🧩 Running Analog Netlist Scaffold Agent...")

    workflow_id = state.get("workflow_id", "default")
    workflow_dir = state.get("workflow_dir", f"backend/workflows/{workflow_id}")
    os.makedirs(workflow_dir, exist_ok=True)

    spec = _load_spec_from_state_or_disk(state, workflow_dir)
    if not spec:
        state["status"] = "❌ No analog spec available for netlist scaffold."
        return state

    analog_dir = os.path.join(workflow_dir, "analog")
    netlist_dir = os.path.join(analog_dir, "netlist")
    os.makedirs(netlist_dir, exist_ok=True)

    block_name = str(spec.get("block_name") or "analog_block").strip()
    ports: List[Dict[str, Any]] = spec.get("ports") or []
    pin_names = [_spice_pin_name(p) for p in ports if _spice_pin_name(p)]

    top_filename = f"{block_name}_top.sp"
    top_path = os.path.join(netlist_dir, top_filename)

    netlist_text = f"""
*------------------------------------------------------------------------------
* {block_name.upper()} Analog Block Netlist Scaffold
*
* Generated by ChipLoop Analog Flow
*
* Purpose
* -------
* Defines the SPICE interface for the analog block used in:
*
*   - analog simulation
*   - mixed-signal co-simulation
*   - SoC integration
*
* This file intentionally contains NO transistor-level implementation.
*
* Replace the internal implementation with:
*
*   - transistor-level circuit
*   - macro netlist
*   - behavioral SPICE model
*
* DO NOT CHANGE:
*
*   - subckt name
*   - port ordering
*
*------------------------------------------------------------------------------

.SUBCKT {block_name} {' '.join(pin_names) if pin_names else '* no_pins_defined'}

*------------------------------------------------------------------------------
* Implementation Boundary
*
* Insert transistor-level or macro-level implementation here.
* Preserve the subckt name and pin order for downstream integration.
*
*------------------------------------------------------------------------------

.ENDS {block_name}

*------------------------------------------------------------------------------
* End of {block_name}_top.sp
*------------------------------------------------------------------------------
""".lstrip()

    with open(top_path, "w", encoding="utf-8") as f:
        f.write(netlist_text)

    # Legacy compatibility mirrors
    legacy_flat = os.path.join(analog_dir, "netlist.sp")
    legacy_summary = os.path.join(analog_dir, "netlist_summary.md")
    with open(legacy_flat, "w", encoding="utf-8") as f:
        f.write(netlist_text)
    with open(legacy_summary, "w", encoding="utf-8") as f:
        f.write(
            "\n".join([
                f"# Netlist Scaffold for {block_name}",
                "",
                "## Pins",
                *([f"- {p}" for p in pin_names] if pin_names else ["- No pins were defined in the normalized spec."]),
                "",
                "## Notes",
                "- This is a spec-driven scaffold.",
                "- No block-type assumptions are hardcoded here.",
                "- Replace with transistor-level, macro-level, or behavioral SPICE content later.",
            ])
        )

    save_text_artifact_and_record(workflow_id, agent_name, "analog/netlist", top_filename, netlist_text)
    save_text_artifact_and_record(workflow_id, agent_name, "analog", "netlist.sp", netlist_text)
    save_text_artifact_and_record(
        workflow_id,
        agent_name,
        "analog",
        "netlist_summary.md",
        "\n".join([
            f"# Netlist Scaffold for {block_name}",
            "",
            "## Pins",
            *([f"- {p}" for p in pin_names] if pin_names else ["- No pins were defined in the normalized spec."]),
            "",
            "## Notes",
            "- This is a spec-driven scaffold.",
            "- No block-type assumptions are hardcoded here.",
            "- Replace with transistor-level, macro-level, or behavioral SPICE content later.",
        ])
    )

    state["analog_netlist_path"] = top_path
    state["analog_netlist_relpath"] = f"analog/netlist/{top_filename}"
    state["status"] = f"✅ Generated netlist scaffold for {block_name}"

    return state