import os
from utils.artifact_utils import save_text_artifact_and_record


def run_agent(state: dict) -> dict:

    print("\n🧩 Running Analog Netlist Scaffold Agent...")

    workflow_id = state.get("workflow_id")
    workflow_dir = state.get("workflow_dir")

    spec = state.get("analog_spec", {})

    block = spec.get("block_name", "analog_block")
    ports = spec.get("ports", [])

    pin_list = " ".join(p["name"] for p in ports)

    netlist_dir = os.path.join(workflow_dir, "analog", "netlist")
    models_dir = os.path.join(netlist_dir, "models")

    os.makedirs(netlist_dir, exist_ok=True)
    os.makedirs(models_dir, exist_ok=True)

    filename = f"{block}_top.sp"

    netlist = f"""
*------------------------------------------------------------------------------
* {block.upper()} Analog Block Netlist Wrapper
*
* This file is a SPEC-DRIVEN interface scaffold generated by ChipLoop.
*
* Purpose
* -------
* Provides the SPICE subcircuit interface used for:
*
*   - analog simulation
*   - SoC co-simulation
*   - digital/analog integration
*
* This wrapper intentionally contains no transistor-level implementation.
*
* Replace the internal implementation with one of the following:
*
*   1) transistor-level circuit
*   2) macro netlist delivered by analog team
*   3) behavioral SPICE model
*
* Do NOT change:
*
*   - subckt name
*   - port ordering
*
*------------------------------------------------------------------------------
"""

    netlist += f"""

.SUBCKT {block} {pin_list}

*------------------------------------------------------------------------------
* Integration Boundary
*
* All internal implementation should remain inside this subcircuit.
* Port ordering must remain stable for:
*
*   - analog simulation
*   - digital wrapper integration
*   - macro packaging
*
*------------------------------------------------------------------------------

* Include behavioral or macro models
.INCLUDE models/models.placeholder.inc


*------------------------------------------------------------------------------
* Implementation Placeholder
*
* Insert transistor-level implementation or macro instance below.
*
* Example:
*
* XCORE <internal nodes> core_cell
*
*------------------------------------------------------------------------------

.ENDS {block}

*------------------------------------------------------------------------------
* End of {block}_top.sp
*------------------------------------------------------------------------------
"""

    path = os.path.join(netlist_dir, filename)

    with open(path, "w") as f:
        f.write(netlist)

    # ------------------------------------------------------------------
    # models.placeholder.inc
    # ------------------------------------------------------------------

    model_file = os.path.join(models_dir, "models.placeholder.inc")

    model_text = f"""
*------------------------------------------------------------------------------
* Placeholder model include file
*
* Replace with one of the following:
*
*   - transistor-level model libraries
*   - behavioral analog models
*   - foundry macro models
*
* Example:
*
*   .include sky130.lib
*
*------------------------------------------------------------------------------
"""

    with open(model_file, "w") as f:
        f.write(model_text)

    # ------------------------------------------------------------------
    # README
    # ------------------------------------------------------------------

    readme = f"""
# Analog Netlist Scaffold — {block}

This directory contains the integration scaffold for the **{block}** analog block.

Generated by ChipLoop Analog Flow.

## Files

### `{block}_top.sp`

SPICE wrapper defining the block interface.

This file must remain stable because it is used by:

- analog simulation
- SoC integration
- macro packaging
- mixed signal verification

### `models/models.placeholder.inc`

Include file for:

- transistor libraries
- macro netlists
- behavioral models

## Integration Guidelines

When replacing the implementation:

1. Do NOT change `.SUBCKT {block}`
2. Do NOT reorder pins
3. Only modify content between `.SUBCKT` and `.ENDS`

## Example Integration
