# Auto-generated by ChipLoop Testbench Generator Agent
# Explicit RTL sources used by simulation
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_command_safety.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_csr_mmio.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_top.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_top_spi_fpga_top.sv
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_request_engine.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_response_validator.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_status_telemetry.v
VERILOG_SOURCES += ../../handoff/rtl/fpga_bram_512x32.v
