# Auto-generated by ChipLoop Testbench Generator Agent
# Explicit RTL sources used by simulation
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_registers.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_request_packager.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_response_parser.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_supervisor.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_top.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_top_spi_fpga_top.sv
