export type HelpTopic = {
  slug: string;
  title: string;
  category: "Basics" | "Apps" | "Inspection" | "Studio" | "Integrations" | "Developer" | "Examples";
  summary: string;
  body: string[];
  comparisonRows?: Array<{ area: string; traditional: string; chiploop: string; differentiation: string }>;
  actions: string[];
  exampleQuestions: string[];
  links: Array<{ label: string; href: string }>;
  keywords: string[];
};

export const helpTopics: HelpTopic[] = [
  {
    slug: "getting-started",
    title: "Getting Started",
    category: "Basics",
    summary: "Start with Apps for guided flows or Studio for custom workflows.",
    body: [
      "ChipLoop has two main work areas. Apps are reusable guided workflows such as Arch2RTL, System Architecture Explorer, Architecture-to-RTL Delivery, and Product App Builder. Studio is where users compose, inspect, and run agent workflows. Reference Journeys provide prefilled end-to-end examples across those Apps.",
      "A good first path is Apps, Arch2RTL, run the PWM demo, or System Architecture Explorer, run the matrix-multiply gem5 demo, then use Ask This Run after completion to inspect generated artifacts and logs. After a System Architecture run, Architecture-to-RTL Delivery can convert the selected gem5 result into reviewed Arch2RTL intent.",
      "Step 1: Log in and open Apps if you want a guided first run, or Studio if you want to compose a custom workflow.",
      "Step 2: Start with Arch2RTL or System Architecture Explorer so you can see inputs, execution, outputs, downloads, and Ask This Run in one path. Use Architecture-to-RTL Delivery when you want to bridge a completed architecture run into RTL intent.",
      "Step 3: After the run finishes, review downloads and open Ask This Run to ask what was generated, what needs review, and what to do next.",
      "Step 4: Move into Studio when you want to reuse agents, connect multiple steps, save private agents, or compose a workflow.",
    ],
    actions: ["Open Apps", "Run the Arch2RTL or System Architecture demo", "Ask This Run after the workflow finishes"],
    exampleQuestions: [
      "What should I try first in ChipLoop?",
      "Should I start with Apps or Studio?",
      "How do I inspect a completed demo run?",
    ],
    links: [
      { label: "Apps", href: "/apps" },
      { label: "Studio", href: "/workflow" },
    ],
    keywords: ["start", "begin", "onboarding", "apps", "studio", "demo"],
  },
  {
    slug: "apps-arch2rtl",
    title: "Apps and Arch2RTL",
    category: "Apps",
    summary: "Use Arch2RTL to turn a structured design requirement into RTL-oriented outputs.",
    body: [
      "Apps are the fastest way to run a prebuilt ChipLoop flow. Arch2RTL accepts a design requirement and produces workflow artifacts for RTL handoff.",
      "After a run completes, downloads and Ask This Run become available so users can inspect what was generated.",
      "Arch2RTL also shows a post-run evidence dashboard when the generated artifacts support it. The dashboard summarizes lint status, flip-flops, latches, full-cycle and half-cycle path counts, input and output counts, detected clock and reset names, module count, and RTL file count.",
      "The dashboard is evidence-only: values come from generated reports and parsed RTL artifacts. It does not duplicate a separate Registers count because flip-flops and latches are the storage view.",
      "Step 1: Open Apps and choose Arch2RTL.",
      "Step 2: Paste a clear architecture requirement with inputs, outputs, reset behavior, timing assumptions, and expected deliverables.",
      "Step 3: Optionally import repository context from GitHub if the design depends on existing files.",
      "Step 4: Run the workflow and wait for completion.",
      "Step 5: Review the evidence dashboard, download generated artifacts, and use Ask This Run to summarize the RTL, constraints, reports, and missing review items.",
      "If the requirement came from System Architecture, use Architecture-to-RTL Delivery first so the Arch2RTL spec carries selected gem5 metrics, assumptions, and traceability.",
    ],
    actions: ["Go to Apps", "Choose Arch2RTL", "Review outputs and Ask This Run"],
    exampleQuestions: [
      "What does Arch2RTL generate?",
      "What should I put in the Arch2RTL requirement?",
      "How do I review the Arch2RTL outputs?",
    ],
    links: [
      { label: "Apps", href: "/apps" },
      { label: "Arch2RTL", href: "/apps/arch2rtl" },
    ],
    keywords: ["arch2rtl", "apps", "demo", "rtl", "download", "artifacts"],
  },
  {
    slug: "chiploop-vs-traditional-flow",
    title: "ChipLoop vs Traditional Flow",
    category: "Basics",
    summary: "ChipLoop is a unified silicon-to-product platform that carries context, artifacts, evidence, and lineage from architecture and RTL through verification, implementation, software, validation, and product apps.",
    body: [
      "Traditional semiconductor flows hand off files, reports, scripts, and review notes between disconnected stages. ChipLoop keeps the workflow data visible in one platform so teams can see what was generated, what passed, what failed, what evidence exists, and what should happen next.",
      "The core difference is platform continuity: ChipLoop lets teams traverse from architecture intent to RTL, verification closure, DFT/tapeout evidence, firmware, software, full-system validation, and product app prototypes without losing context between stages.",
      "ChipLoop does not replace signoff tools. It acts as the execution, evidence, and lineage layer around them, surfacing real tool output and generated artifacts in a form that downstream agents and users can inspect.",
    ],
    comparisonRows: [
      {
        area: "End-to-end platform visibility",
        traditional: "Architecture, RTL, verification, physical design, firmware, software, and product demos live in separate tools, repos, dashboards, and meetings.",
        chiploop: "Workflows, artifacts, dashboards, reports, lineage, and Ask This Run stay available in one platform from RTL through product app.",
        differentiation: "Teams can traverse the full silicon-to-product path without losing context between stages.",
      },
      {
        area: "Starting point",
        traditional: "Requirements are written in documents and manually translated into architecture, RTL, and verification tasks.",
        chiploop: "Structured intent and guided Apps turn requirements into executable workflows and reviewable artifacts.",
        differentiation: "Intent becomes workflow data instead of static handoff text.",
      },
      {
        area: "Architecture to RTL",
        traditional: "Architecture exploration and RTL implementation are often disconnected.",
        chiploop: "System Architecture and Architecture-to-RTL Delivery carry selected metrics, assumptions, and traceability into Arch2RTL.",
        differentiation: "Architecture evidence feeds RTL planning instead of staying in a separate report.",
      },
      {
        area: "Verification closure",
        traditional: "Engineers manually inspect coverage, update plans, add tests, tune seeds, and rerun.",
        chiploop: "Closure Loop updates verification and coverage plans, adds testcase intents and seed plans, reruns executable generated tests, and charts coverage improvement.",
        differentiation: "Closure becomes an iterative, traceable loop with visible progress.",
      },
      {
        area: "Implementation evidence",
        traditional: "LEC, DFT, ATPG, STA, DRC, and LVS evidence is scattered across tool logs and scripts.",
        chiploop: "Arch2Synthesis and Arch2Tapeout dashboards surface real stage status and generated reports.",
        differentiation: "Tool readiness, missing collateral, and failures are visible earlier.",
      },
      {
        area: "Product app continuity",
        traditional: "Product-facing demos are usually built later from manually interpreted firmware, software, and validation state.",
        chiploop: "Product App Builder uses RTL, verification, firmware, software, and validation lineage to create simulator-backed product prototypes.",
        differentiation: "The same platform connects silicon evidence to product-facing behavior.",
      },
      {
        area: "Reporting policy",
        traditional: "Incomplete reports may need manual interpretation and can be easy to misread.",
        chiploop: "Unavailable coverage, LEC, ATPG, DRC, LVS, or validation evidence is reported as unavailable or failed.",
        differentiation: "No fake pass, fake coverage, or hidden fallback is presented as evidence.",
      },
    ],
    actions: ["Open Apps to run a guided flow", "Use Ask This Run after completion", "Follow handoff actions from RTL to Verify, Firmware, Validation, and Product App", "Use dashboards to inspect real evidence and missing outputs"],
    exampleQuestions: [
      "How is ChipLoop different from a traditional flow?",
      "How does ChipLoop keep RTL to product app data visible?",
      "What does platform continuity mean?",
      "Does ChipLoop replace signoff tools?",
    ],
    links: [
      { label: "Apps", href: "/apps" },
      { label: "Studio", href: "/workflow" },
      { label: "Verify", href: "/apps/verify" },
      { label: "Product App Builder", href: "/apps/system-product-builder" },
    ],
    keywords: ["traditional flow", "differentiation", "single platform", "unified platform", "platform continuity", "rtl to product app", "visibility", "lineage", "evidence", "handoff", "silicon to product", "product app"],
  },
  {
    slug: "agent-workflow-catalog",
    title: "Agent and Workflow Catalog",
    category: "Studio",
    summary: "Browse the registered ChipLoop agents and workflows in one place, including loop, domain, step count, and short descriptions.",
    body: [
      "The catalog table is loaded from the backend registry so users can see the current platform agents and workflow templates without opening registry files.",
      "Agents are individual execution units. Workflows are ordered collections of agents for a loop such as digital, analog, embedded, validation, or system.",
      "Use this catalog when deciding whether an existing agent or workflow already covers a task before creating a custom private agent or new workflow.",
    ],
    actions: ["Open Help", "Select Agent and Workflow Catalog", "Filter with the Help search box or browser find", "Open Studio when you want to compose or inspect workflows"],
    exampleQuestions: [
      "How many agents does ChipLoop have?",
      "Which digital agents are available?",
      "Which workflows are registered?",
      "Where can I browse all agents and workflows?",
    ],
    links: [
      { label: "Studio", href: "/workflow" },
      { label: "Apps", href: "/apps" },
    ],
    keywords: ["agent catalog", "workflow catalog", "agents", "workflows", "loop", "registry", "studio", "browse", "count", "digital agents", "system agents"],
  },
  {
    slug: "apps-verify",
    title: "Verify App",
    category: "Apps",
    summary: "Run RTL verification with simulation, functional coverage, code coverage, SVA evidence, optional formal, closure analysis, and closure-loop reruns.",
    body: [
      "Verify imports generated Arch2RTL output or accepts pasted RTL, then runs the selected verification flow and produces simulation, coverage, and review artifacts.",
      "The app supports directed tests, random tests, or both in one run. When both is selected, ChipLoop runs the directed intent first and then follows with randomized seed runs for broader exploration.",
      "The simulator/tool selectors show the current tool path, including Verilator, cocotb, verilator_coverage, SymbiYosys, and solver options when available. Optional formal and golden-model comparison can be enabled from the app controls.",
      "The Demo Evidence Dashboard shows a compact summary: simulation pass/fail counts, run count, functional coverage, code line/branch/condition/toggle coverage when reported, SVA assertion coverage, formal status, golden-model status, and tools used.",
      "Coverage closure can be run in two ways. Run closure analysis after Verify produces an advisory gap-analysis workflow only. Run closure loop after Verify automatically analyzes gaps, updates plans, adds testcase/seed intents, reruns verification, and emits a final loop summary.",
      "If both closure checkboxes are enabled, ChipLoop runs the closure loop and publishes the final analysis from the loop result instead of launching duplicate analysis and loop child workflows.",
      "Debug failing tests after Verify is a separate guarded option. When enabled, ChipLoop analyzes failing testcase/seed logs first, recommends targeted reruns, and requests VCD replay only when log-only debug is inconclusive.",
      "When failure debug and closure loop are both enabled, failure debug runs before coverage closure so the loop does not blindly chase coverage while tests are failing.",
      "Run Closure Loop ingests functional and code coverage gaps, updates the verification plan and coverage plan, creates traceable testcase intents and a seed plan, reruns executable generated tests when available, and emits a coverage trend chart.",
      "The closure chart tracks merged cumulative coverage across the base run and each iteration for functional coverage plus code line, branch, condition, and toggle coverage when reported. It also tracks coverage points added, testcase intents added, and seed updates per iteration.",
      "Closure iterations run sequentially. If iterations is set to 2, ChipLoop runs iteration 1, judges improvement, then runs iteration 2 unless closure is achieved or the loop stops early because there is no measurable improvement.",
      "Closure-loop reporting is evidence-only. ChipLoop does not invent coverage improvement, executable tests, or pass results when simulator artifacts are missing.",
      "Toggle coverage depends on simulator output. New Verilator runs attempt annotated coverage-point extraction; older LCOV-only artifacts may show toggle coverage as unavailable.",
    ],
    actions: ["Open Verify", "Choose directed, random, or both", "Run Verify", "Analyze Closure Gap", "Run Closure Loop", "Inspect the coverage trend chart", "Download closure artifacts"],
    exampleQuestions: [
      "What coverage does Verify report?",
      "Why is toggle coverage unavailable?",
      "How do I know which functional coverage bins are missing?",
      "Can I run both directed and random tests?",
      "How do I use the closure loop to improve coverage?",
      "Where is the coverage improvement chart?",
    ],
    links: [
      { label: "Verify", href: "/apps/verify" },
      { label: "Arch2RTL", href: "/apps/arch2rtl" },
    ],
    keywords: ["verify", "verification", "coverage", "functional coverage", "code coverage", "toggle", "branch", "condition", "sva", "formal", "symbiyosys", "verilator", "closure", "closure loop", "coverage trend", "coverage chart", "testcase", "seed"],
  },
  {
    slug: "verification-closure-loop",
    title: "Verification Closure Loop",
    category: "Apps",
    summary: "Update verification and coverage plans, add traceable testcase intents and seed plans, rerun verification, and chart coverage improvement.",
    body: [
      "Verification Closure Loop is the follow-on flow after a Verify run and closure-gap analysis. It is meant for iterative closure after Arch2RTL and baseline verification are complete.",
      "The loop ingests verification_source_handoff.json, simulation results, functional coverage, code coverage metrics, and closure gaps. It then emits updated planning and rerun artifacts instead of treating the first closure report as the final answer.",
      "Generated artifacts include verification_plan_v2.md, coverage_point_plan_v2.md, testcase_seed_update.json, rerun_manifest.json, closure_judgement.json, and closure_chart.json.",
      "The chart shows merged cumulative coverage: baseline, then baseline plus iteration 1, then baseline plus iteration 1 plus iteration 2, and so on. It tracks functional coverage and code line, branch, condition, and toggle coverage when those values exist.",
      "Rerun modes control scope. Failed only reruns failing testcase/seed pairs. Coverage targeted runs tests and seeds mapped to missing functional or code coverage gaps. Full regression runs the allowed baseline-style regression tests plus added closure seeds.",
      "The loop respects the Verify directed/random setting: directed runs directed closure tests, random runs constrained-random seed expansion, and both runs both categories.",
      "Failure debug is log-first. It uses failing testcase names, seeds, simulator return codes, stdout/stderr tails, assertion or scoreboard text, RTL intent, and testbench context before recommending waveform replay. Auto-apply RTL fixes is off by default; generated RTL or testbench fixes should be reviewed unless the user explicitly enables auto-apply.",
      "Testcase intents are traceable closure recommendations. They become executable only when the generated testbench contains matching runnable cocotb tests; otherwise the rerun manifest records the gap instead of pretending a test ran.",
      "Code coverage gaps are first-class closure inputs. Line, branch, condition, and toggle gaps can create coverage-plan objectives and testcase intents with traceability back to the source gap type.",
      "No fake closure is reported. Missing simulator output, missing executable tests, or unavailable coverage fields remain visible in the artifacts and dashboard.",
    ],
    actions: ["Open Verify", "Run baseline verification", "Analyze Closure Gap", "Run Closure Loop", "Review the coverage chart", "Inspect rerun_manifest.json and closure_judgement.json"],
    exampleQuestions: [
      "What does Run Closure Loop do?",
      "Why are testcase intents different from executable tests?",
      "Where is the coverage trend chart?",
      "How do I know whether another closure iteration is useful?",
    ],
    links: [
      { label: "Verify", href: "/apps/verify" },
      { label: "Arch2RTL", href: "/apps/arch2rtl" },
    ],
    keywords: ["verification closure loop", "closure loop", "coverage trend", "coverage chart", "functional coverage", "line coverage", "branch coverage", "condition coverage", "toggle coverage", "verification plan", "coverage plan", "testcase seed", "rerun", "iterations"],
  },
  {
    slug: "verify-user-flow",
    title: "Verify User Flow",
    category: "Apps",
    summary: "Understand the base Verify run, closure analysis, failure debug, and automatic closure-loop options.",
    body: [
      "The Verify app starts with a base verification run. Users select RTL input from an Arch2RTL handoff or paste/upload RTL, choose the verification style, and run the normal verification workflow.",
      "The base run generates or reuses verification collateral: testbench, assertions, functional coverage model, simulation control, simulation execution, summary coverage, run logs, and downloadable artifacts.",
      "Directed, random, or both controls the style of generated and rerun tests. Directed focuses on named scenarios and requirement intent. Random expands seed-driven constrained-random tests. Both allows the closure loop to use both categories.",
      "If both Run closure analysis after Verify and Run closure loop after Verify are unchecked, ChipLoop runs only the base Verify workflow. Users can inspect the dashboard, logs, generated files, and Ask This Run output after completion.",
      "Run closure analysis after Verify is advisory. After the base run completes, ChipLoop analyzes coverage gaps, failed tests, missing outputs, and recommended next actions. It does not automatically update plans, add tests, or rerun simulations.",
      "Debug failing tests after Verify is a guarded debug option. When enabled, ChipLoop uses failure triage and log-first analysis to classify likely root cause from failing testcase names, seeds, return codes, stdout/stderr tails, assertion text, scoreboard text, RTL intent, and testbench context.",
      "Failure debug does not require VCD first. If log-only analysis is inconclusive and VCD generation is enabled, ChipLoop recommends a targeted failing-test rerun with waveform. Auto-apply RTL fixes remains off by default; generated fixes are proposal-only unless the user explicitly enables auto-apply.",
      "Run closure loop after Verify is the automatic iterative closure option. When checked, the user provides max iterations, seed budget, and rerun mode. The loop starts after the base Verify run and runs iterations sequentially.",
      "If iterations is set to 2, ChipLoop can run iteration 1 and then iteration 2. It may stop early if closure is achieved or if the iteration judge sees no measurable improvement.",
      "Each closure-loop iteration analyzes functional and code coverage gaps, updates the verification plan and coverage plan, creates testcase intents and seed updates, plans the rerun, executes the allowed rerun tests, and judges whether another iteration is useful.",
      "Coverage is merged cumulatively across the base run and all completed iterations. The trend chart shows baseline, baseline plus iteration 1, baseline plus iteration 1 plus iteration 2, and so on for functional coverage and code line, branch, condition, and toggle coverage when those metrics exist.",
      "The chart also tracks how many coverage points were added, testcase intents were added, and seed updates were proposed or used per iteration. A metric can dip only when a tool reports a different measurement scope; the intended closure summary is the merged cumulative result.",
      "Rerun mode controls how much work each iteration does. Full regression runs the allowed baseline-style regression tests plus closure seeds. Coverage targeted reruns tests and seeds mapped to missing functional or code coverage gaps. Failed only focuses on failing testcase and seed pairs for debug.",
      "If both Run closure analysis after Verify and Run closure loop after Verify are checked, ChipLoop runs base Verify first, then the closure loop, then publishes final closure analysis from the loop result. It does not launch a duplicate standalone analysis before the loop.",
      "If Debug failing tests after Verify and Run closure loop after Verify are both enabled, failure debug runs before coverage closure so the loop does not blindly chase coverage while tests are failing.",
      "No fake closure is reported. Missing simulator output, missing executable tests, failed reruns, unavailable coverage fields, or inconclusive debug remain visible in the artifacts and dashboard.",
    ],
    actions: ["Open Verify", "Choose directed, random, or both", "Select closure/debug checkboxes", "Run Verify", "Inspect logs and dashboard", "Review closure chart and artifacts"],
    exampleQuestions: [
      "What happens if I only run base Verify?",
      "When should I enable failure debug?",
      "What happens when both closure analysis and closure loop are checked?",
      "How are coverage trends merged across iterations?",
      "What is the difference between full regression, coverage targeted, and failed only?",
    ],
    links: [
      { label: "Verify", href: "/apps/verify" },
      { label: "Arch2RTL", href: "/apps/arch2rtl" },
    ],
    keywords: ["verify user flow", "verify checkbox", "run closure analysis after verify", "run closure loop after verify", "debug failing tests after verify", "failure debug", "base verify", "coverage trend", "merged coverage", "rerun mode", "full regression", "coverage targeted", "failed only"],
  },
  {
    slug: "digital-implementation-signoff",
    title: "Digital Implementation, DFT, ATPG, LEC, and Tapeout",
    category: "Apps",
    summary: "Inspect synthesis and tapeout evidence with real synthesis LEC, tapeout LEC, scan DFT, ATPG, STA, DRC, LVS, XOR, GDS, and macro collateral status.",
    body: [
      "Arch2Synthesis and Arch2Tapeout dashboards are evidence dashboards. They report what the generated artifacts and configured tools produced; they do not insert fake pass, fake coverage, or fallback LEC/ATPG results.",
      "Synthesis LEC and Tapeout LEC are different checks. Synthesis LEC compares RTL against the synthesized gate netlist under digital/synth. Tapeout LEC compares RTL against the final implementation/tapeout netlist collected after physical implementation, and writes separate artifacts under digital/tapeout_lec.",
      "LEC requires real parseable RTL, a real comparison netlist, and standard-cell functional models. If models or netlists are missing or unparseable, the dashboard reports the issue rather than falling back to an invented equivalence result.",
      "When DFT is enabled, synthesis performs scan-cell replacement for supported flip-flops and records scan candidates and scan chains. Scan replacement passing means the netlist was transformed; ATPG still needs a working ATPG adapter and generated collateral.",
      "ATPG uses CHIPLOOP_ATPG_COMMAND, such as an Atalanta wrapper. The agents generate the needed bench collateral from the workflow artifacts and expect the adapter to return real pattern and coverage metrics. If bench generation, adapter execution, or metrics parsing fails, the dashboard reports that failure.",
      "For tapeout, the dashboard surfaces floorplan, placement, CTS, route, fill, STA, DRC, LVS, tapeout streamout, XOR, GDS, and Tapeout LEC evidence when reports exist. Missing reports stay visible as not produced or failed instead of being hidden.",
      "Tapeout status is signoff-gated. A streamout command returning zero is not enough: ChipLoop reports tapeout failed if DRC is not clean, LVS is not clean, XOR has differences, GDS is missing, or the streamout command fails.",
      "Analog or macro blocks require explicit collateral: LEF for physical abstract, LIB for timing, GDS for layout, SPICE/CDL for LVS, and placement or integration metadata that matches a real netlist instance. ChipLoop does not create hardcoded macro placement for a block that is not instantiated.",
      "OpenROAD/OpenLane availability depends on backend installation. If a tool is unavailable, configure the tool path in the backend environment and rerun the flow so the next artifacts are produced from the real tool.",
    ],
    actions: ["Open Arch2Synthesis or Arch2Tapeout", "Inspect Synthesis LEC and Tapeout LEC separately", "Inspect DFT, ATPG, STA, DRC, LVS, XOR, and GDS evidence", "Configure CHIPLOOP_ATPG_COMMAND for ATPG", "Provide explicit macro or analog collateral before mixed-signal tapeout", "Download the ZIP and inspect stage reports"],
    exampleQuestions: [
      "Why does LEC show a stdcell parse error?",
      "What is the difference between synthesis LEC and tapeout LEC?",
      "What does scan replace pass mean?",
      "How do I enable ATPG patterns and coverage?",
      "What collateral is needed for an analog macro?",
      "Why did tapeout fail even though streamout ran?",
      "Why are DRC, LVS, XOR, or GDS not produced?",
    ],
    links: [
      { label: "Arch2Synthesis", href: "/apps/arch2synthesis" },
      { label: "Arch2Tapeout", href: "/apps/arch2tapeout" },
    ],
    keywords: ["synthesis", "tapeout", "implementation", "dft", "scan", "scan replacement", "atpg", "atalanta", "podem", "lec", "synthesis lec", "tapeout lec", "logic equivalence", "stdcell", "sta", "timing", "drc", "lvs", "xor", "gds", "streamout", "signoff gated", "macro", "analog", "lef", "lib", "spice", "openroad", "openlane", "no fallback"],
  },
  {
    slug: "apps-system-architecture",
    title: "System Architecture and gem5 Apps",
    category: "Apps",
    summary: "Use System Architecture apps to explore X86/RISC-V workload, cache, CPU, memory, and PPA tradeoffs without writing gem5 configs.",
    body: [
      "System Architecture Explorer is a System Loop app family for no-code gem5 exploration. The startup demo uses matrix multiplication and cache sweeps, then shows PPA charts after the workflow completes.",
      "The app is run-driven like Arch2RTL: choose settings, click Run, wait for completion, then inspect charts, sweep tables, downloads, and Ask This Run.",
      "The current supported app entry points are System Architecture Explorer, System Cache Tuning, System ISA Compare, System Memory Bottleneck, and System CPU Model.",
      "Each System Architecture app is also available as a prebuilt workflow in Studio, where users can inspect the shared gem5 agent pipeline or adapt it into a larger System Loop workflow.",
      "ChipLoop supports gem5-backed X86 and RISC-V exploration for the current MVP. Users only choose workload and architecture settings in the app.",
      "Step 1: Open Apps and choose System Architecture Explorer or one of the focused System apps.",
      "Step 2: Review the prefilled workload and architecture settings. For the demo, matrix_multiply is already selected.",
      "Step 3: Adjust ISA, CPU model, cores, memory type, prefetcher, or L1/L2 cache sweep settings.",
      "Step 4: Run the workflow and wait for completion. PPA charts appear after the workflow reaches completed status.",
      "Step 5: Use Ask This Run or download the ZIP to inspect generated intent, gem5 config, sweep matrix, metrics, chart JSON, PPA summary, and report artifacts.",
      "Step 6: Click Open in Arch2RTL or open Architecture-to-RTL Delivery to review the selected sweep point, generate rtl_intent.yaml, requirements_trace.md, architecture_decision.md, and then open or run Arch2RTL.",
    ],
    actions: ["Open System Architecture Explorer", "Run the matrix-multiply gem5 demo", "Inspect PPA charts after completion", "Open Architecture-to-RTL Delivery"],
    exampleQuestions: [
      "What are the System Architecture apps?",
      "Can I compare X86 and RISC-V?",
      "Why do charts appear only after the run finishes?",
      "Do users need to install or configure gem5?",
    ],
    links: [
      { label: "System Architecture Explorer", href: "/apps/system-architecture" },
      { label: "Architecture-to-RTL Delivery", href: "/apps/architecture-to-rtl" },
      { label: "System Cache Tuning", href: "/apps/system-cache-tuning" },
      { label: "System ISA Compare", href: "/apps/system-isa-compare" },
      { label: "System Memory Bottleneck", href: "/apps/system-memory-bottleneck" },
      { label: "System CPU Model", href: "/apps/system-cpu-model" },
    ],
    keywords: ["system architecture", "gem5", "cache tuning", "isa compare", "riscv", "x86", "ppa", "power", "area", "memory bottleneck", "cpu model", "architecture to rtl", "traceability"],
  },
  {
    slug: "apps-pwm-full-stack-demo",
    title: "PWM Controller Reference Journey",
    category: "Apps",
    summary: "Carry one PWM controller from Arch2RTL through verification, Rust firmware, system software, full-stack validation, and a simulator-backed product app.",
    body: [
      "PWM Controller Reference Journey is a prefilled end-to-end example. It starts in the standard Arch2RTL app with a PWM controller and preserves the completed run context through each downstream reusable app.",
      "The RTL Verification step imports the generated Arch2RTL spec and PWM RTL, then applies prefilled reset and duty-cycle test intent. The Embedded step imports that RTL and its register map before generating Rust fan-control firmware artifacts.",
      "After Embedded completes, System Software is prefilled to create a fan-control API and application package from the firmware handoff. System Software Validation opens in full co-simulation mode with the software, firmware, and RTL workflow references already filled.",
      "After Full Validation completes, Product App Builder uses workflow lineage from RTL, Verify, Firmware, Software, and Validation to generate a simulator-backed product dashboard. The generated HTML app is runnable from the ZIP at system/product/app/index.html, and its simulator adapter can later be replaced by board or silicon transport.",
      "During the guided PWM path, each completed stage displays a Demo Evidence Dashboard from that workflow's generated artifacts: Arch2RTL shows lint status, flip-flops, latches, path and port counts, clock and reset names, Verification shows pass or fail counts plus functional, code, SVA, formal, and golden-model evidence, Firmware shows co-simulation results, Software shows generated API and package evidence, Full Validation shows scenario verdict results, and Product App shows generated dashboard/package evidence.",
      "The dashboard does not insert estimated demonstration values. A metric appears only when the completed workflow emitted the supporting artifact; unavailable coverage or validation evidence is reported as unavailable.",
      "Verification closure analysis is separate from the compact dashboard. If functional coverage is below target, the downloadable closure plan lists the missing bins and recommended next actions. Code coverage reports line, branch, condition, and toggle values when the simulator artifacts contain those data; older LCOV-only runs may show toggle coverage as unavailable.",
      "The handoff actions are also available after non-demo Arch2RTL runs. In that path, ChipLoop passes the generated artifacts and workflow lineage forward, while downstream agents derive verification, firmware, software, and validation work from the selected design rather than applying PWM-specific goals.",
      "The System Architecture Explorer gem5 demo is a separate CPU/cache/workload exploration path and is not used as evidence for the PWM peripheral demo.",
      "Segment: Embedded Control / Motor & Power Control.",
      "Step 1: Open Apps and choose PWM Controller Reference Journey, then run the prefilled Arch2RTL PWM controller.",
      "Step 2: After Arch2RTL completes, click Open in Verification and run the prefilled PWM verification.",
      "Step 3: After verification completes, click Open in Firmware and run Embedded.",
      "Step 4: After Embedded completes, click Open in System Software and run System Software.",
      "Step 5: Click Open in Full Validation to run the prefilled software to firmware to RTL validation path.",
      "Step 6: After validation completes, click Build Product App, run Product App Builder, download the ZIP, and open system/product/app/index.html to view the generated simulator-backed product interface.",
    ],
    actions: ["Open PWM Controller Reference Journey", "Generate PWM RTL", "Inspect Demo Evidence Dashboard", "Open in Verification", "Open in Firmware", "Open in Full Validation", "Build Product App"],
    exampleQuestions: [
      "How do I demonstrate RTL, firmware, and software together?",
      "Which artifacts are handed from Arch2RTL into Embedded?",
      "Is the Product App a real simulator-backed app or a static mockup?",
      "Why is System Architecture Explorer separate from the PWM demo?",
    ],
    links: [
      { label: "Apps", href: "/apps" },
      { label: "Arch2RTL", href: "/apps/arch2rtl?guided=1&pwm_chain=1" },
      { label: "Embedded Run", href: "/apps/embedded-run" },
      { label: "System Software Validation", href: "/apps/system-software-validation" },
      { label: "Product App Builder", href: "/apps/system-product-builder" },
    ],
    keywords: ["pwm", "full stack", "generic handoff", "arch2rtl", "verify", "coverage", "closure", "embedded", "rust", "firmware", "system software", "co-simulation", "product app", "dashboard"],
  },
  {
    slug: "apps-uart-packet-reference-journey",
    title: "UART Packet Engine Reference Journey",
    category: "Apps",
    summary: "Run a larger UART/FIFO/interrupt peripheral through the same RTL, verification, firmware, software, validation, and product app flow.",
    body: [
      "UART Packet Engine Reference Journey is the second full-stack demo. It uses the same reusable ChipLoop apps and agents as the PWM journey, but starts from a more complex UART packet engine with TX/RX FIFOs, baud-rate generation, packet counters, interrupt status, and error handling.",
      "The intended RTL size is roughly 150-200 flip-flops, depending on generated FIFO and control implementation. The design is still understandable in a live demo because users can see packet movement, FIFO levels, IRQ status, and error scenarios.",
      "The Verify stage uses UART-specific test intent covering reset, register programming, TX/RX FIFO transitions, loopback packet movement, packet completion, interrupt clear, framing error, and overflow cases.",
      "The Embedded and System Software stages produce a Rust packet driver, packet CLI, and telemetry packet service. Full Validation checks that software commands become firmware register operations and the imported RTL shows ordered packet movement and interrupt behavior.",
      "Product App Builder generates a UART packet dashboard where users can set baud divider and packet length, send a packet, watch TX/RX FIFO levels, observe IRQ status, and inject a framing error in the simulator-backed app.",
      "The Demo Evidence Dashboard also shows how many agents participated in each completed stage, using the workflow logs for that stage.",
      "Segment: Connectivity / Communications IP.",
    ],
    actions: ["Open Apps", "Start UART Reference Journey", "Run each stage", "Inspect agent count and generated evidence", "Build Product App"],
    exampleQuestions: [
      "How is the UART demo different from PWM?",
      "Does the UART demo use the same agents?",
      "What should I show in the product dashboard?",
    ],
    links: [
      { label: "Apps", href: "/apps" },
      { label: "Arch2RTL", href: "/apps/arch2rtl?guided=1&uart_chain=1" },
      { label: "Product App Builder", href: "/apps/system-product-builder" },
    ],
    keywords: ["uart", "packet engine", "fifo", "interrupt", "150 flip flops", "reference journey", "arch2rtl", "verify", "firmware", "software", "validation", "product app"],
  },
  {
    slug: "apps-image-dma-reference-journey",
    title: "Image DMA Pipeline Reference Journey",
    category: "Apps",
    summary: "Run a large visual image-processing pipeline demo targeting roughly 25k flip-flops through RTL, verification, firmware, software, validation, and product app.",
    body: [
      "Image DMA Pipeline Reference Journey is the large visual demo. It uses the same reusable ChipLoop apps and agents as the PWM and UART journeys, but starts from an image-processing pipeline with DMA read/write engines, register-based line buffers, 3x3 filtering, thresholding, histogram counters, and interrupts.",
      "The Arch2RTL spec explicitly asks for synthesizable register-based line buffers rather than inferred SRAM macros so the demo can target roughly 25,000 flip-flops. Exact counts depend on generated implementation and synthesis interpretation.",
      "The Verify stage uses image-specific intent covering reset, frame configuration, DMA progress, line-buffer window validity, filter modes, threshold behavior, histogram updates, frame_done interrupt behavior, and DMA backpressure.",
      "The Embedded and System Software stages produce a Rust image pipeline driver, image-processing CLI, and frame-processing service. Full Validation checks that software commands become firmware register operations and the imported RTL shows expected frame_done interrupts, DMA byte counts, output signatures, and histogram updates.",
      "Product App Builder generates a simulator-backed image dashboard with filter controls, threshold and brightness sliders, DMA progress, input/output previews, histogram view, IRQ/status fields, and workflow lineage.",
      "The Demo Evidence Dashboard also shows how many agents participated in each completed stage, using the workflow logs for that stage.",
      "Segment: Vision / Edge AI Preprocessing.",
    ],
    actions: ["Open Apps", "Start Image DMA Journey", "Run each stage", "Inspect FF/dashboard evidence", "Build Product App"],
    exampleQuestions: [
      "How do I run a larger visual demo?",
      "Why does the image demo target roughly 25k flip-flops?",
      "What does the image product dashboard show?",
    ],
    links: [
      { label: "Apps", href: "/apps" },
      { label: "Arch2RTL", href: "/apps/arch2rtl?guided=1&image_chain=1" },
      { label: "Product App Builder", href: "/apps/system-product-builder" },
    ],
    keywords: ["image", "dma", "pipeline", "25k flip flops", "line buffer", "filter", "histogram", "reference journey", "arch2rtl", "verify", "firmware", "software", "validation", "product app"],
  },
  {
    slug: "apps-sram-mbist-reference-journey",
    title: "SRAM MBIST Reference Journey",
    category: "Apps",
    summary: "Run a focused memory/DFT demo with an OpenRAM-style SRAM controller, scan DFT, ATPG readiness, and MBIST applicability evidence.",
    body: [
      "SRAM MBIST Reference Journey is a compact Memory / DFT demo. It starts from a small memory-mapped SRAM scratchpad controller instead of a large image pipeline.",
      "The Arch2RTL spec asks for an OpenRAM-compatible SRAM abstraction with a synthesizable fallback wrapper, so downstream synthesis and DFT agents can detect memory intent.",
      "After Arch2RTL, open Synthesis to inspect synthesis metrics, logic-equivalence evidence, scan DFT evidence, open-source ATPG tool readiness, and MBIST applicability.",
      "Scan DFT is backed by OpenROAD/OpenLane2 where supported. ATPG and MBIST report real coverage or insertion only when the corresponding open-source/customer tool adapter is configured.",
      "Segment: Memory / DFT.",
    ],
    actions: ["Open Apps", "Start MBIST SRAM Journey", "Run Arch2RTL", "Open Synthesis", "Inspect Scan, ATPG, and MBIST dashboard evidence"],
    exampleQuestions: [
      "How do I demo MBIST without the image pipeline?",
      "Does PWM have MBIST?",
      "Which DFT tools are configured for this run?",
    ],
    links: [
      { label: "Apps", href: "/apps" },
      { label: "Arch2RTL", href: "/apps/arch2rtl?guided=1&mbist_chain=1" },
      { label: "Arch2Synthesis", href: "/apps/arch2synthesis" },
    ],
    keywords: ["sram", "mbist", "openram", "autombist", "scan", "atpg", "dft", "reference journey", "arch2rtl", "synthesis"],
  },
  {
    slug: "apps-smart-sensor-hub-reference-journey",
    title: "Smart Sensor Hub MCU Reference Journey",
    category: "Apps",
    summary: "Run an IoT edge-node reference journey with sensor telemetry, thresholds, FIFO buffering, low-power control, firmware, software, validation, and product app.",
    body: [
      "Smart Sensor Hub MCU Reference Journey is the IoT/embedded-edge demo. It uses the same reusable ChipLoop apps and agents as the PWM, UART, and Image DMA journeys, but starts from a microcontroller-style sensor hub subsystem.",
      "The Arch2RTL spec models a firmware-facing sensor hub with sample timer, temperature/humidity/air-quality channels, threshold comparators, FIFO buffering, alert interrupts, sample counters, and low-power control.",
      "The Verify stage uses sensor-specific intent covering reset, register programming, sample capture, FIFO behavior, threshold alerts, ALERT_CLEAR, FIFO_CLEAR, overflow, and low-power state.",
      "The Embedded and System Software stages produce Rust firmware, a sensor-node CLI, and a telemetry alert service. Full Validation checks that software commands become firmware register operations and the imported RTL shows expected sampling, FIFO, IRQ, and alert behavior.",
      "Product App Builder generates an IoT product dashboard from the completed collateral with explanations for sample period, sensor channels, thresholds, telemetry, FIFO depth, alert state, sample count, and low-power mode.",
      "Segment: IoT / Embedded Edge Devices.",
    ],
    actions: ["Open Apps", "Start Sensor Hub Journey", "Run each stage", "Inspect telemetry and alert evidence", "Build Product App"],
    exampleQuestions: [
      "How do I demo an IoT edge-node subsystem?",
      "Does the sensor hub include a microcontroller?",
      "What does the sensor product dashboard show?",
    ],
    links: [
      { label: "Apps", href: "/apps" },
      { label: "Arch2RTL", href: "/apps/arch2rtl?guided=1&sensor_chain=1" },
      { label: "Product App Builder", href: "/apps/system-product-builder" },
    ],
    keywords: ["iot", "sensor hub", "microcontroller", "telemetry", "threshold", "fifo", "low power", "reference journey", "arch2rtl", "verify", "firmware", "software", "validation", "product app"],
  },
  {
    slug: "apps-secure-boot-reference-journey",
    title: "Secure Boot and Key Manager Reference Journey",
    category: "Apps",
    summary: "Run a root-of-trust reference journey with secure boot, key-slot selection, anti-rollback, tamper/debug-lock handling, firmware, software, validation, and product app.",
    body: [
      "Secure Boot and Key Manager Reference Journey is the Security / Root-of-Trust IP demo.",
      "The Arch2RTL spec models boot authentication, key-slot selection, image version checks, anti-rollback minimum version, tamper handling, debug lock, lifecycle state, security IRQ, and audit count.",
      "The Verify stage covers successful boot, hash mismatch, rollback failure, tamper, debug lock, IRQ clear, and audit events.",
      "The Embedded and System Software stages produce Rust security firmware, a provisioning CLI, and a boot-status service. Full Validation checks that software commands become firmware register operations and the imported RTL shows expected boot_allow, boot_fail, IRQ, lifecycle, and audit behavior.",
      "Segment: Security / Root-of-Trust IP.",
    ],
    actions: ["Open Apps", "Start Secure Boot Journey", "Run each stage", "Inspect security evidence", "Build Product App"],
    exampleQuestions: ["How do I demo root-of-trust IP?", "What does secure boot validation prove?", "What does the security dashboard show?"],
    links: [
      { label: "Apps", href: "/apps" },
      { label: "Arch2RTL", href: "/apps/arch2rtl?guided=1&secure_chain=1" },
      { label: "Product App Builder", href: "/apps/system-product-builder" },
    ],
    keywords: ["secure boot", "root of trust", "key manager", "anti rollback", "tamper", "debug lock", "reference journey", "arch2rtl", "verify", "firmware", "software", "validation", "product app"],
  },
  {
    slug: "apps-safety-fault-reference-journey",
    title: "Safety Fault Manager and Watchdog Reference Journey",
    category: "Apps",
    summary: "Run an automotive safety reference journey with watchdog heartbeat, fault masking, reset escalation, firmware diagnostics, software health monitor, validation, and product app.",
    body: [
      "Safety Fault Manager and Watchdog Reference Journey is the Automotive / Safety Control demo.",
      "The Arch2RTL spec models watchdog timeout, heartbeat service, fault masks, latched faults, escalation policy, reset request, safety IRQ, IRQ clear, and reset count.",
      "The Verify stage covers healthy heartbeat, watchdog timeout, masked and unmasked faults, reset escalation, external reset acknowledgement, FAULT_CLEAR, and IRQ_CLEAR.",
      "The Embedded and System Software stages produce Rust safety firmware, a safety health CLI, and a watchdog monitor service. Full Validation checks that software commands become firmware register operations and the imported RTL shows expected safety IRQ, reset request, fault_latched, watchdog_expired, and escalation behavior.",
      "Segment: Automotive / Safety Control.",
    ],
    actions: ["Open Apps", "Start Safety Journey", "Run each stage", "Inspect safety evidence", "Build Product App"],
    exampleQuestions: ["How do I demo automotive safety IP?", "What does watchdog validation prove?", "What does the safety dashboard show?"],
    links: [
      { label: "Apps", href: "/apps" },
      { label: "Arch2RTL", href: "/apps/arch2rtl?guided=1&safety_chain=1" },
      { label: "Product App Builder", href: "/apps/system-product-builder" },
    ],
    keywords: ["safety", "automotive", "watchdog", "fault manager", "reset escalation", "heartbeat", "reference journey", "arch2rtl", "verify", "firmware", "software", "validation", "product app"],
  },
  {
    slug: "apps-product-builder",
    title: "Product App Builder",
    category: "Apps",
    summary: "Turn validated RTL, firmware, software, and validation collateral into a simulator-backed product interface.",
    body: [
      "Product App Builder is the final demo handoff after System Software Validation. It reads workflow lineage and generated collateral from Arch2RTL, Verify, Firmware, System Software, and Validation, then builds a runnable product-facing dashboard package.",
      "For the PWM reference journey, the generated app visualizes a fan-control style product interface backed by a JavaScript simulator model derived from the generated register map, firmware/software capability model, and validation evidence. It is not a static screenshot or made-up chart.",
      "The generated product app is intended to prove the user-facing behavior before hardware is available. Later, the simulator adapter can be replaced by a real board or silicon transport such as UART, USB serial, JTAG/OpenOCD, Ethernet, or an FPGA/MMIO bridge.",
      "Generated artifacts include system/product/app/index.html, system_product_dashboard_manifest.json, system_product_package.json, and README_PRODUCT_APP.md.",
      "Step 1: Complete System Software Validation, then click Build Product App from the validation results.",
      "Step 2: Confirm the prefilled workflow IDs and product intent, then run Product App Builder.",
      "Step 3: Download the ZIP and open system/product/app/index.html to inspect the generated dashboard.",
      "Step 4: Review README_PRODUCT_APP.md when planning how to replace the simulator adapter with board or silicon access.",
    ],
    actions: ["Open Product App Builder", "Run with completed validation lineage", "Download ZIP", "Open system/product/app/index.html"],
    exampleQuestions: [
      "What inputs does Product App Builder need?",
      "Is the generated product app connected to real workflow collateral?",
      "How can the simulator later connect to a board or silicon?",
    ],
    links: [
      { label: "Product App Builder", href: "/apps/system-product-builder" },
      { label: "System Software Validation", href: "/apps/system-software-validation" },
      { label: "Apps", href: "/apps" },
    ],
    keywords: ["product app", "dashboard", "simulator", "validation", "firmware", "software", "rtl", "pwm", "board", "silicon"],
  },
  {
    slug: "apps-architecture-to-rtl-delivery",
    title: "Architecture-to-RTL Delivery",
    category: "Apps",
    summary: "Turn completed gem5 System Architecture results into reviewed Arch2RTL intent and traceability.",
    body: [
      "Architecture-to-RTL Delivery is a guided System Loop app that starts from a completed System Architecture workflow ID.",
      "The app loads gem5_run_results.json, lets users choose the recommended or another sweep point, and generates Arch2RTL-ready intent with architecture evidence.",
      "Generated handoff artifacts include rtl_intent.yaml, requirements_trace.md, architecture_decision.md, and arch2rtl_prefill.json.",
      "Users can review and edit the generated Arch2RTL spec before opening Arch2RTL or running Arch2RTL directly.",
      "This flow turns gem5-backed architecture evidence into reviewed RTL intent. It does not claim gem5 proves RTL correctness.",
    ],
    actions: ["Open Architecture-to-RTL Delivery", "Enter a completed System Architecture workflow ID", "Generate RTL Intent", "Review and run Arch2RTL"],
    exampleQuestions: [
      "How do I use gem5 results to start Arch2RTL?",
      "What traceability artifacts are created?",
      "Can I edit the generated RTL intent before running Arch2RTL?",
    ],
    links: [
      { label: "Architecture-to-RTL Delivery", href: "/apps/architecture-to-rtl" },
      { label: "System Architecture Explorer", href: "/apps/system-architecture" },
      { label: "Arch2RTL", href: "/apps/arch2rtl" },
    ],
    keywords: ["architecture to rtl", "arch2rtl", "gem5", "traceability", "rtl intent", "architecture decision", "requirements trace"],
  },
  {
    slug: "ask-this-run",
    title: "Ask This Run",
    category: "Inspection",
    summary: "Ask run-specific questions using logs, metadata, and text artifacts from a completed workflow.",
    body: [
      "Ask This Run appears after a run finishes. It helps users inspect generated reports, logs, and artifacts without manually opening every file.",
      "Good questions include: What was generated? What failed? Summarize the RTL handoff. List missing signals. What should I check next?",
      "Step 1: Run an App or Studio workflow and wait until it reaches a finished state.",
      "Step 2: Open Ask This Run from the completed run area near downloads and outputs.",
      "Step 3: Ask a specific question about the result, such as summarize generated RTL, list errors, explain reports, or identify missing artifacts.",
      "Step 4: Use the answer to decide whether to download, rerun with clearer requirements, or move the output into review.",
    ],
    actions: ["Wait for the run to finish", "Open Ask This Run", "Ask a specific question about the outputs"],
    exampleQuestions: [
      "When does Ask This Run appear?",
      "Can Ask This Run summarize reports and logs?",
      "What questions should I ask after a failed run?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["ask", "inspection", "logs", "reports", "artifacts", "summarize", "run"],
  },
  {
    slug: "studio-workflows",
    title: "Studio Workflows",
    category: "Studio",
    summary: "Studio is for composing, arranging, validating, and running directional agent workflows.",
    body: [
      "Studio shows prebuilt workflows and user-created workflows. Prebuilt workflows open on an arranged canvas, and connections show direction with arrowheads from each agent OUT port to the next agent IN port.",
      "Use the planner when the workflow needs a new agent or a different execution graph. Preview and validate the graph before running it.",
      "The main Studio building blocks are workflows, agents, design intent, and integrations. A workflow connects agents into an execution path. Agents perform scoped engineering tasks. Design intent records reusable requirements, constraints, and assumptions that should guide generation and review.",
      "Canvas controls support Auto-connect dropped agents, Delete selected edge, and Arrange. Use Arrange after adding or moving agents to reflow crowded canvases into readable left-to-right rows; wide canvases use more columns while compact canvases keep connections spaced clearly.",
      "The Studio plan and credit banner shows the current plan, trial status when applicable, and available credits before a workflow is run.",
      "Step 1: Go to Home -> Studio and choose a prebuilt workflow or create a new workflow.",
      "Step 2: Review the nodes and follow the arrow direction from OUT to IN so you know which agents run and what each handoff artifact should be.",
      "Step 3: Add or adjust agents, design intent, and GitHub context if the workflow needs project-specific information.",
      "Step 4: Use Arrange if the graph has multiple rows or overlapping agents, then preview and validate it before running.",
      "Step 5: Run the workflow, inspect outputs, and save useful changes for the next iteration.",
    ],
    actions: ["Open Studio", "Choose Prebuilt or create a workflow", "Arrange and review directional edges", "Preview and validate the graph before running"],
    exampleQuestions: [
      "What is a workflow in Studio?",
      "How do agents connect inside a workflow?",
      "How do I arrange a crowded workflow canvas?",
      "How should I use design intent in Studio?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["studio", "workflow", "prebuilt", "graph", "nodes", "edges", "planner", "agents", "design intent", "arrange", "canvas", "auto-connect", "input", "output", "credits"],
  },
  {
    slug: "system-planner",
    title: "System Planner",
    category: "Studio",
    summary: "Use System Planner to turn a system-level goal into an executable multi-agent workflow.",
    body: [
      "System Planner is for users who know the desired system outcome but need ChipLoop to structure the work. It helps translate requirements into workflow steps, agents, inputs, outputs, and review points.",
      "Use it when the problem spans RTL, firmware, validation, integration, or multiple artifacts rather than one isolated generation task.",
      "Step 1: Go to Home -> Studio -> System Planner.",
      "Step 2: Describe the system goal, target subsystem, constraints, available inputs, and expected outputs.",
      "Step 3: Include cross-domain details such as RTL, firmware, validation, software, power, timing, or integration assumptions.",
      "Step 4: Review the proposed workflow steps, agents, handoff artifacts, and inspection points.",
      "Step 5: Save or refine the workflow before running it.",
    ],
    actions: ["Open Studio", "Choose System Planner", "Describe the system goal, constraints, and expected outputs"],
    exampleQuestions: [
      "When should I use System Planner instead of Agent Planner?",
      "What should I write in a System Planner requirement?",
      "Can System Planner create a multi-agent workflow?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["system planner", "system", "planner", "multi-agent", "requirements", "workflow"],
  },
  {
    slug: "design-intent-analyzer",
    title: "Design Intent Analyzer",
    category: "Studio",
    summary: "Use Design Intent Planner to turn an idea into a reusable consolidated design spec.",
    body: [
      "Design Intent Planner helps convert an early idea, notes, or repository context into reusable design intent. It is useful before generation because it makes hidden assumptions explicit.",
      "The flow has three simple steps: Describe, Clarify, and Review. Review creates a consolidated design spec that can be saved or used to build a workflow.",
      "Step 1: Go to Home -> Studio -> Design Intent Planner.",
      "Step 2: In Design Your Idea, describe the functionality, interfaces, constraints, and expected outcome.",
      "Step 3: Click Continue Asking Questions and edit the suggested answers so they match your real requirement.",
      "Step 4: Click Generate Consolidated Spec and review the purpose, domain interpretation, decisions, assumptions, open questions, and verification intent.",
      "Step 5: Click Save Design Intent to store it in the design intent library, or Save & Build Workflow to save it and open System Planner with the spec preloaded.",
    ],
    actions: ["Open Studio", "Open Design Intent Planner", "Generate a consolidated spec", "Save & Build Workflow"],
    exampleQuestions: [
      "What does Design Intent Planner create?",
      "How is design intent different from a prompt?",
      "How do I save an idea and build a workflow from it?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["design intent", "analyzer", "requirements", "constraints", "assumptions", "library", "spec"],
  },
  {
    slug: "workflow-composer",
    title: "Workflow Composer",
    category: "Studio",
    summary: "Use Workflow Composer to combine workflows, suggest branch structure, and review parallel execution stages.",
    body: [
      "Workflow Composer works on a current Studio canvas or one or more saved workflows from Supabase. It can suggest branch-and-join edges, remove duplicate shared steps, and show which stages can run together.",
      "Composer does not execute agents. It prepares a better graph for review. Use Open on Canvas to inspect the suggested graph, or Save as Private Workflow when the structure looks right.",
      "Step 1: Go to Home -> Studio -> System Planner when you want ChipLoop to create the first system-level draft from requirements.",
      "Step 2: Build and save the draft workflow. The initial draft may be serial, which is normal.",
      "Step 3: Go to Home -> Studio -> Workflow Composer.",
      "Step 4: Choose Current workflow if the graph is already open on the canvas, or choose Saved workflow and select one or more saved workflows.",
      "Step 5: Keep Suggest branch structure enabled when you want Composer to propose better branch-and-join edges before analysis.",
      "Step 6: Click Analyze Parallelism. Review the summary: selected workflows, original steps, shared steps removed, composed steps, and parallel groups.",
      "Step 7: Review Current Serial Steps to see the original sequence and workflow provenance. Shared steps show when the same agent came from more than one selected workflow.",
      "Step 8: Review Parallel Stages Found to see which agents can run in the same stage. For example, Digital RTL work and Analog model work can run separately, then join at System Top Assembly before simulation and coverage stages.",
      "Step 9: Use Open on Canvas to inspect the suggested graph visually, or Save as Private Workflow to keep the composed version for later use.",
    ],
    actions: ["Open Studio", "Open Workflow Composer", "Analyze current or saved workflows", "Save the result as a private workflow"],
    exampleQuestions: [
      "What does Workflow Composer do?",
      "Can I select multiple saved workflows?",
      "Why are shared agents shown only once?",
      "How do I analyze a System Planner workflow for parallelism?",
      "What does Save as Private Workflow create?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["workflow composer", "optimize workflow", "compose", "parallelism", "workflow", "graph", "validation", "handoff", "agents", "system planner", "saved workflow", "private workflow", "shared step"],
  },
  {
    slug: "design-intent-library",
    title: "Design Intent Library",
    category: "Studio",
    summary: "Keep reusable requirements, constraints, assumptions, and review intent in one place.",
    body: [
      "The design intent library is where users should store reusable engineering intent instead of rewriting it for every run. It can include interface rules, reset assumptions, power constraints, verification goals, and style preferences.",
      "Use the library to make future workflows more consistent and easier to inspect.",
      "Step 1: Go to Home -> Studio -> Design Intent Library and capture intent from a spec, Design Intent Analyzer output, or a previous successful workflow.",
      "Step 2: Save the entry with a clear name that describes the block, subsystem, or rule set.",
      "Step 3: Keep the content focused on stable requirements, constraints, assumptions, and review expectations.",
      "Step 4: Use Save & Build Workflow from Design Intent Planner when you want to save the intent and immediately open System Planner with the consolidated spec preloaded.",
      "Step 5: Update the library when requirements change so future runs stay aligned.",
    ],
    actions: ["Capture intent from specs or analysis", "Save it with a clear name", "Attach relevant intent to future workflows"],
    exampleQuestions: [
      "What belongs in the design intent library?",
      "How should I name design intent entries?",
      "Can design intent be reused across workflows?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["design intent library", "library", "constraints", "requirements", "reuse", "intent"],
  },
  {
    slug: "marketplace",
    title: "Marketplace",
    category: "Studio",
    summary: "Use Marketplace to discover agents and workflow building blocks beyond your private workspace.",
    body: [
      "Marketplace is where reusable agents and capabilities can be discovered. Private agents start scoped to the user, while marketplace items are intended for broader reuse after review.",
      "Use Marketplace when a workflow needs an agent you do not want to create from scratch, or when you want to install a reusable building block into Studio.",
      "Step 1: Go to Home -> Marketplace and search for the capability you need.",
      "Step 2: Review what the agent does, what inputs it expects, and what outputs it produces.",
      "Step 3: Install or add the agent to your Studio workspace when it matches your workflow.",
      "Step 4: Connect it inside a Studio workflow and verify the handoff artifacts.",
      "Step 5: Use private agents first when the capability is specific to your company or project.",
      "Step 6: Use Submit for Review in Studio when a private capability is ready for marketplace review. Submission does not automatically make it public.",
    ],
    actions: ["Open Marketplace", "Review the agent capability and inputs", "Install or use it in a Studio workflow", "Submit reviewed private capabilities when ready"],
    exampleQuestions: [
      "When should I use Marketplace?",
      "What is the difference between a private agent and Marketplace agent?",
      "How do I add a Marketplace agent to Studio?",
    ],
    links: [
      { label: "Marketplace", href: "/marketplace" },
      { label: "Studio", href: "/workflow" },
    ],
    keywords: ["marketplace", "agent", "install", "private", "public", "reuse", "submit for review"],
  },
  {
    slug: "agent-planner",
    title: "Agent Planner",
    category: "Studio",
    summary: "Plan a private draft agent from requirements, generate missing dependency specs, then review and save it.",
    body: [
      "Agent Planner takes requirements and first checks reusable agents, skills, tools, and hooks. When Create a new private agent is selected, existing matches are shown as references instead of blocking the new draft.",
      "Private draft agents start scoped to the user. They can be reviewed, saved, opened from My Agents, edited, and saved again before broader marketplace review.",
      "For a new agent, define the goal, input artifacts, output artifacts, skills, Tools / MCP connections, and any hooks needed before or after execution.",
      "Step 1: Go to Home -> Studio -> Agent Planner.",
      "Step 2: Check Create new private agent when you want a fresh private agent instead of matching existing agents.",
      "Step 3: Fill in the planned agent name, loop, optional domain, and requirement. Keep the requirement concrete: what the agent reads, what it produces, and how success should be checked.",
      "Step 4: Click Run. Review exact matches, similar matches, reusable components, and missing capabilities.",
      "Step 5: Click Create Private Draft Agent or Generate Draft Agent to open Review Draft Agent.",
      "Step 6: In Review Draft Agent, fill or adjust Inputs, Outputs, Skills, Tools / MCP, and Hooks. Put one item per line.",
      "Step 7: Click Generate Draft Agent. If a skill, tool, or hook is missing, ChipLoop generates a private draft spec for that dependency and labels it as Generated spec.",
      "Step 8: Review the purpose, dependency status, validation checklist, warnings, and advanced details. Then click Save Private Draft.",
      "Step 9: Open My Agents in Studio to view or edit the saved private agent. Save with the same name to update it, or save with a different name to create a variant.",
    ],
    actions: ["Open Studio", "Select Agent Planner", "Create a private draft agent", "Review generated skill, tool, and hook specs"],
    exampleQuestions: [
      "How do I create a private agent?",
      "What happens when a skill or hook is missing?",
      "What fields should I fill for a new agent?",
      "Can I edit an agent after it is generated?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["agent", "planner", "private", "skill", "mcp", "tool", "hook", "template", "draft", "my agents", "generated spec"],
  },
  {
    slug: "github",
    title: "GitHub Integration",
    category: "Integrations",
    summary: "Connect your own GitHub account, then import repository context into Apps or Studio.",
    body: [
      "Each user installs the ChipLoop GitHub App for their own account or organization. The administrator configures the app once; users authorize their own installations.",
      "After connection, users can import repository files into a workflow prompt or Studio context. Repository access is scoped by the GitHub installation permissions.",
      "Step 1: Go to Home -> Settings -> Integrations and choose Connect GitHub.",
      "Step 2: Select the GitHub account or organization and choose which repositories ChipLoop can access.",
      "Step 3: Return to ChipLoop after GitHub redirects back to the integrations page.",
      "Step 4: In Apps or Studio, use GitHub import to select repo files that should become workflow context.",
      "Step 5: Disconnect GitHub from Settings, Integrations if access should be removed.",
    ],
    actions: ["Open Settings, Integrations", "Connect GitHub", "Import selected repository context into Apps or Studio"],
    exampleQuestions: [
      "How do I connect GitHub?",
      "Can each user connect their own GitHub?",
      "How do I import repository context into Studio?",
    ],
    links: [{ label: "GitHub settings", href: "/settings/integrations" }],
    keywords: ["github", "repository", "repo", "install", "integration", "settings", "import"],
  },
  {
    slug: "cli-sdk",
    title: "CLI and SDK",
    category: "Developer",
    summary: "Use API keys for scripted access once the account and plan are ready.",
    body: [
      "Developer access uses API keys created in Settings. Keep keys private and revoke keys that are no longer used.",
      "The normal flow is create an API key, call backend workflow endpoints from a script or SDK client, then inspect outputs in the platform.",
      "Step 1: Go to Home -> Settings -> API Keys and create a key with a clear name such as local-cli, ci-runner, or vscode-local.",
      "Step 2: Install the SDK/CLI in your environment.",
      "Command: pip install chiploop-sdk",
      "Step 3: Set CHIPLOOP_BASE_URL and CHIPLOOP_API_KEY in your shell, CI secrets, or IDE secret storage.",
      "macOS/Linux example: export CHIPLOOP_BASE_URL=https://api.getchiploops.com\nexport CHIPLOOP_API_KEY=cl_live_...",
      "Windows PowerShell example: $env:CHIPLOOP_BASE_URL=\"https://api.getchiploops.com\"\n$env:CHIPLOOP_API_KEY=\"cl_live_...\"",
      "Step 4: Run chiploop doctor to confirm configuration.",
      "Command: chiploop doctor",
      "Step 5: Run a workflow from a spec file, poll status, list artifacts, and download outputs for review.",
      "Command: chiploop run arch2rtl --spec specs/pwm.md\nchiploop status <workflow_id>\nchiploop artifacts list <workflow_id>\nchiploop artifacts download <workflow_id> --name rtl/top.v --out ./chiploop_outputs",
      "Step 6: Revoke old keys from Settings when a machine, CI job, or teammate no longer needs access.",
    ],
    actions: ["Open Settings, API Keys", "Create a scoped key", "Use the key from CLI or SDK automation"],
    exampleQuestions: [
      "How do I create an API key?",
      "What is the CLI or SDK flow?",
      "How do I keep API keys safe?",
    ],
    links: [{ label: "API keys", href: "/settings/api-keys" }],
    keywords: ["cli", "sdk", "api", "api key", "automation", "developer"],
  },
  {
    slug: "cursor-vscode",
    title: "Cursor and VS Code",
    category: "Developer",
    summary: "Use ChipLoop from Cursor or VS Code through the same CLI and API-key path.",
    body: [
      "Cursor is supported through the integrated terminal today. Install the ChipLoop SDK/CLI, set CHIPLOOP_BASE_URL and CHIPLOOP_API_KEY in your shell, then run workflows against local spec files.",
      "VS Code support follows the same CLI path. The MVP extension scaffold is command-palette oriented: configure ChipLoop, run the current spec file or Arch2RTL, check workflow status, download artifacts, and open Apps or Studio.",
      "IDE integrations should not call browser-only endpoints or store secrets in source files. Use Settings, API Keys to create a key, keep generated outputs in a review folder, and inspect artifacts before committing them.",
      "Step 1: Go to Home -> Settings -> API Keys and create a key named cursor-local, vscode-local, or another clear local name.",
      "Step 2: In Cursor or VS Code, open the design repository and install the CLI from the IDE terminal.",
      "Command: pip install chiploop-sdk",
      "Step 3: Set CHIPLOOP_BASE_URL to the ChipLoop backend URL and CHIPLOOP_API_KEY to the key created in Settings. Set these in the shell or IDE secret storage, not in source files.",
      "macOS/Linux example: export CHIPLOOP_BASE_URL=https://api.getchiploops.com\nexport CHIPLOOP_API_KEY=cl_live_...",
      "Windows PowerShell example: $env:CHIPLOOP_BASE_URL=\"https://api.getchiploops.com\"\n$env:CHIPLOOP_API_KEY=\"cl_live_...\"",
      "Step 4: Put the design requirement in a file such as specs/pwm.md, then run the workflow from the IDE terminal.",
      "Command: chiploop doctor\nchiploop run arch2rtl --spec specs/pwm.md",
      "Step 5: Inspect outputs locally.",
      "Command: chiploop status <workflow_id>\nchiploop artifacts list <workflow_id>\nchiploop artifacts download <workflow_id> --name rtl/top.v --out ./chiploop_outputs",
      "Step 6: Review generated RTL, SDC, UPF, reports, and logs before committing changes back to the repository.",
    ],
    actions: [
      "Create a ChipLoop API key",
      "Install the ChipLoop SDK/CLI in the IDE terminal",
      "Set CHIPLOOP_BASE_URL and CHIPLOOP_API_KEY in the shell or IDE secret store",
      "Run a workflow from a local spec file and download artifacts",
      "Review generated files before committing them",
    ],
    exampleQuestions: [
      "How do I use ChipLoop in Cursor?",
      "How do I use ChipLoop from VS Code?",
      "Where should I store the API key for IDE workflows?",
    ],
    links: [
      { label: "API keys", href: "/settings/api-keys" },
      { label: "Integrations", href: "/settings/integrations" },
    ],
    keywords: ["cursor", "vscode", "vs code", "ide", "extension", "terminal", "sdk", "cli", "api key"],
  },
  {
    slug: "example-pwm",
    title: "Example: PWM Controller",
    category: "Examples",
    summary: "A simple Arch2RTL example for a PWM controller.",
    body: [
      "Ask Arch2RTL to design a parameterized PWM controller with clk, reset_n, enable, duty_cycle[7:0], period[7:0], pwm_out, and counter_value[7:0].",
      "After the run completes, ask: summarize the generated RTL, list the reset behavior, and what should be verified in simulation.",
      "Step 1: Go to Home -> Apps -> Arch2RTL.",
      "Step 2: Paste the PWM requirement including clk, reset_n, enable, duty_cycle[7:0], period[7:0], pwm_out, and counter_value[7:0].",
      "Command: Design a parameterized PWM controller.\n\nInputs:\n- clk\n- reset_n\n- enable\n- duty_cycle[7:0]\n- period[7:0]\n\nOutputs:\n- pwm_out\n- counter_value[7:0]",
      "Step 3: State the behavior: counter increments when enabled, resets at period, pwm_out is high while counter_value is less than duty_cycle, and reset clears registers.",
      "Command: Counter increments every clock when enable is high.\nCounter resets to zero when it reaches period.\npwm_out is high when counter_value is less than duty_cycle.\nAll registers reset to zero when reset_n is low.",
      "Step 4: Run the workflow and wait for completion.",
      "Step 5: Ask This Run to summarize generated RTL, reset behavior, constraints, and simulation checks.",
    ],
    actions: ["Paste the PWM requirement into Arch2RTL", "Run the workflow", "Use Ask This Run for the verification checklist"],
    exampleQuestions: [
      "Can you give me a PWM Arch2RTL example?",
      "What should I ask after the PWM run finishes?",
      "What should be verified in the PWM output?",
    ],
    links: [{ label: "Arch2RTL", href: "/apps/arch2rtl" }],
    keywords: ["example", "pwm", "controller", "arch2rtl", "simulation", "verification"],
  },
];

export const helpCategories = ["Basics", "Apps", "Inspection", "Studio", "Integrations", "Developer", "Examples"] as const;

export function findHelpTopic(slug: string | null): HelpTopic {
  const normalizedSlug = slug === "optimize-workflow" ? "workflow-composer" : slug;
  return helpTopics.find((topic) => topic.slug === normalizedSlug) || helpTopics[0];
}
