export type HelpTopic = {
  slug: string;
  title: string;
  category: "Basics" | "Apps" | "Inspection" | "Studio" | "Integrations" | "Developer" | "Examples";
  summary: string;
  body: string[];
  actions: string[];
  exampleQuestions: string[];
  links: Array<{ label: string; href: string }>;
  keywords: string[];
};

export const helpTopics: HelpTopic[] = [
  {
    slug: "getting-started",
    title: "Getting Started",
    category: "Basics",
    summary: "Start with Apps for guided flows or Studio for custom workflows.",
    body: [
      "ChipLoop has two main work areas. Apps are guided workflows such as Arch2RTL, System Architecture Explorer, and Architecture-to-RTL Delivery. Studio is where users compose, inspect, and run agent workflows.",
      "A good first path is Apps, Arch2RTL, run the PWM demo, or System Architecture Explorer, run the matrix-multiply gem5 demo, then use Ask This Run after completion to inspect generated artifacts and logs. After a System Architecture run, Architecture-to-RTL Delivery can convert the selected gem5 result into reviewed Arch2RTL intent.",
      "Step 1: Log in and open Apps if you want a guided first run, or Studio if you want to compose a custom workflow.",
      "Step 2: Start with Arch2RTL or System Architecture Explorer so you can see inputs, execution, outputs, downloads, and Ask This Run in one path. Use Architecture-to-RTL Delivery when you want to bridge a completed architecture run into RTL intent.",
      "Step 3: After the run finishes, review downloads and open Ask This Run to ask what was generated, what needs review, and what to do next.",
      "Step 4: Move into Studio when you want to reuse agents, connect multiple steps, save private agents, or compose a workflow.",
    ],
    actions: ["Open Apps", "Run the Arch2RTL or System Architecture demo", "Ask This Run after the workflow finishes"],
    exampleQuestions: [
      "What should I try first in ChipLoop?",
      "Should I start with Apps or Studio?",
      "How do I inspect a completed demo run?",
    ],
    links: [
      { label: "Apps", href: "/apps" },
      { label: "Studio", href: "/workflow" },
    ],
    keywords: ["start", "begin", "onboarding", "apps", "studio", "demo"],
  },
  {
    slug: "apps-arch2rtl",
    title: "Apps and Arch2RTL",
    category: "Apps",
    summary: "Use Arch2RTL to turn a structured design requirement into RTL-oriented outputs.",
    body: [
      "Apps are the fastest way to run a prebuilt ChipLoop flow. Arch2RTL accepts a design requirement and produces workflow artifacts for RTL handoff.",
      "After a run completes, downloads and Ask This Run become available so users can inspect what was generated.",
      "Step 1: Open Apps and choose Arch2RTL.",
      "Step 2: Paste a clear architecture requirement with inputs, outputs, reset behavior, timing assumptions, and expected deliverables.",
      "Step 3: Optionally import repository context from GitHub if the design depends on existing files.",
      "Step 4: Run the workflow and wait for completion.",
      "Step 5: Download generated artifacts and use Ask This Run to summarize the RTL, constraints, reports, and missing review items.",
      "If the requirement came from System Architecture, use Architecture-to-RTL Delivery first so the Arch2RTL spec carries selected gem5 metrics, assumptions, and traceability.",
    ],
    actions: ["Go to Apps", "Choose Arch2RTL", "Review outputs and Ask This Run"],
    exampleQuestions: [
      "What does Arch2RTL generate?",
      "What should I put in the Arch2RTL requirement?",
      "How do I review the Arch2RTL outputs?",
    ],
    links: [
      { label: "Apps", href: "/apps" },
      { label: "Arch2RTL", href: "/apps/arch2rtl" },
    ],
    keywords: ["arch2rtl", "apps", "demo", "rtl", "download", "artifacts"],
  },
  {
    slug: "apps-system-architecture",
    title: "System Architecture and gem5 Apps",
    category: "Apps",
    summary: "Use System Architecture apps to explore X86/RISC-V workload, cache, CPU, memory, and PPA tradeoffs without writing gem5 configs.",
    body: [
      "System Architecture Explorer is a System Loop app family for no-code gem5 exploration. The startup demo uses matrix multiplication and cache sweeps, then shows PPA charts after the workflow completes.",
      "The app is run-driven like Arch2RTL: choose settings, click Run, wait for completion, then inspect charts, sweep tables, downloads, and Ask This Run.",
      "The current supported app entry points are System Architecture Explorer, System Cache Tuning, System ISA Compare, System Memory Bottleneck, and System CPU Model.",
      "ChipLoop supports gem5-backed X86 and RISC-V exploration for the current MVP. Users only choose workload and architecture settings in the app.",
      "Step 1: Open Apps and choose System Architecture Explorer or one of the focused System apps.",
      "Step 2: Review the prefilled workload and architecture settings. For the demo, matrix_multiply is already selected.",
      "Step 3: Adjust ISA, CPU model, cores, memory type, prefetcher, or L1/L2 cache sweep settings.",
      "Step 4: Run the workflow and wait for completion. PPA charts appear after the workflow reaches completed status.",
      "Step 5: Use Ask This Run or download the ZIP to inspect generated intent, gem5 config, sweep matrix, metrics, chart JSON, PPA summary, and report artifacts.",
      "Step 6: Click Open in Arch2RTL or open Architecture-to-RTL Delivery to review the selected sweep point, generate rtl_intent.yaml, requirements_trace.md, architecture_decision.md, and then open or run Arch2RTL.",
    ],
    actions: ["Open System Architecture Explorer", "Run the matrix-multiply gem5 demo", "Inspect PPA charts after completion", "Open Architecture-to-RTL Delivery"],
    exampleQuestions: [
      "What are the System Architecture apps?",
      "Can I compare X86 and RISC-V?",
      "Why do charts appear only after the run finishes?",
      "Do users need to install or configure gem5?",
    ],
    links: [
      { label: "System Architecture Explorer", href: "/apps/system-architecture" },
      { label: "Architecture-to-RTL Delivery", href: "/apps/architecture-to-rtl" },
      { label: "System Cache Tuning", href: "/apps/system-cache-tuning" },
      { label: "System ISA Compare", href: "/apps/system-isa-compare" },
      { label: "System Memory Bottleneck", href: "/apps/system-memory-bottleneck" },
      { label: "System CPU Model", href: "/apps/system-cpu-model" },
    ],
    keywords: ["system architecture", "gem5", "cache tuning", "isa compare", "riscv", "x86", "ppa", "power", "area", "memory bottleneck", "cpu model", "architecture to rtl", "traceability"],
  },
  {
    slug: "apps-architecture-to-rtl-delivery",
    title: "Architecture-to-RTL Delivery",
    category: "Apps",
    summary: "Turn completed gem5 System Architecture results into reviewed Arch2RTL intent and traceability.",
    body: [
      "Architecture-to-RTL Delivery is a guided System Loop app that starts from a completed System Architecture workflow ID.",
      "The app loads gem5_run_results.json, lets users choose the recommended or another sweep point, and generates Arch2RTL-ready intent with architecture evidence.",
      "Generated handoff artifacts include rtl_intent.yaml, requirements_trace.md, architecture_decision.md, and arch2rtl_prefill.json.",
      "Users can review and edit the generated Arch2RTL spec before opening Arch2RTL or running Arch2RTL directly.",
      "This flow turns gem5-backed architecture evidence into reviewed RTL intent. It does not claim gem5 proves RTL correctness.",
    ],
    actions: ["Open Architecture-to-RTL Delivery", "Enter a completed System Architecture workflow ID", "Generate RTL Intent", "Review and run Arch2RTL"],
    exampleQuestions: [
      "How do I use gem5 results to start Arch2RTL?",
      "What traceability artifacts are created?",
      "Can I edit the generated RTL intent before running Arch2RTL?",
    ],
    links: [
      { label: "Architecture-to-RTL Delivery", href: "/apps/architecture-to-rtl" },
      { label: "System Architecture Explorer", href: "/apps/system-architecture" },
      { label: "Arch2RTL", href: "/apps/arch2rtl" },
    ],
    keywords: ["architecture to rtl", "arch2rtl", "gem5", "traceability", "rtl intent", "architecture decision", "requirements trace"],
  },
  {
    slug: "ask-this-run",
    title: "Ask This Run",
    category: "Inspection",
    summary: "Ask run-specific questions using logs, metadata, and text artifacts from a completed workflow.",
    body: [
      "Ask This Run appears after a run finishes. It helps users inspect generated reports, logs, and artifacts without manually opening every file.",
      "Good questions include: What was generated? What failed? Summarize the RTL handoff. List missing signals. What should I check next?",
      "Step 1: Run an App or Studio workflow and wait until it reaches a finished state.",
      "Step 2: Open Ask This Run from the completed run area near downloads and outputs.",
      "Step 3: Ask a specific question about the result, such as summarize generated RTL, list errors, explain reports, or identify missing artifacts.",
      "Step 4: Use the answer to decide whether to download, rerun with clearer requirements, or move the output into review.",
    ],
    actions: ["Wait for the run to finish", "Open Ask This Run", "Ask a specific question about the outputs"],
    exampleQuestions: [
      "When does Ask This Run appear?",
      "Can Ask This Run summarize reports and logs?",
      "What questions should I ask after a failed run?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["ask", "inspection", "logs", "reports", "artifacts", "summarize", "run"],
  },
  {
    slug: "studio-workflows",
    title: "Studio Workflows",
    category: "Studio",
    summary: "Studio is for composing, arranging, validating, and running directional agent workflows.",
    body: [
      "Studio shows prebuilt workflows and user-created workflows. Prebuilt workflows open on an arranged canvas, and connections show direction with arrowheads from each agent OUT port to the next agent IN port.",
      "Use the planner when the workflow needs a new agent or a different execution graph. Preview and validate the graph before running it.",
      "The main Studio building blocks are workflows, agents, design intent, and integrations. A workflow connects agents into an execution path. Agents perform scoped engineering tasks. Design intent records reusable requirements, constraints, and assumptions that should guide generation and review.",
      "Canvas controls support Auto-connect dropped agents, Delete selected edge, and Arrange. Use Arrange after adding or moving agents to reflow crowded canvases into readable left-to-right rows; wide canvases use more columns while compact canvases keep connections spaced clearly.",
      "The Studio plan and credit banner shows the current plan, trial status when applicable, and available credits before a workflow is run.",
      "Step 1: Go to Home -> Studio and choose a prebuilt workflow or create a new workflow.",
      "Step 2: Review the nodes and follow the arrow direction from OUT to IN so you know which agents run and what each handoff artifact should be.",
      "Step 3: Add or adjust agents, design intent, and GitHub context if the workflow needs project-specific information.",
      "Step 4: Use Arrange if the graph has multiple rows or overlapping agents, then preview and validate it before running.",
      "Step 5: Run the workflow, inspect outputs, and save useful changes for the next iteration.",
    ],
    actions: ["Open Studio", "Choose Prebuilt or create a workflow", "Arrange and review directional edges", "Preview and validate the graph before running"],
    exampleQuestions: [
      "What is a workflow in Studio?",
      "How do agents connect inside a workflow?",
      "How do I arrange a crowded workflow canvas?",
      "How should I use design intent in Studio?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["studio", "workflow", "prebuilt", "graph", "nodes", "edges", "planner", "agents", "design intent", "arrange", "canvas", "auto-connect", "input", "output", "credits"],
  },
  {
    slug: "system-planner",
    title: "System Planner",
    category: "Studio",
    summary: "Use System Planner to turn a system-level goal into an executable multi-agent workflow.",
    body: [
      "System Planner is for users who know the desired system outcome but need ChipLoop to structure the work. It helps translate requirements into workflow steps, agents, inputs, outputs, and review points.",
      "Use it when the problem spans RTL, firmware, validation, integration, or multiple artifacts rather than one isolated generation task.",
      "Step 1: Go to Home -> Studio -> System Planner.",
      "Step 2: Describe the system goal, target subsystem, constraints, available inputs, and expected outputs.",
      "Step 3: Include cross-domain details such as RTL, firmware, validation, software, power, timing, or integration assumptions.",
      "Step 4: Review the proposed workflow steps, agents, handoff artifacts, and inspection points.",
      "Step 5: Save or refine the workflow before running it.",
    ],
    actions: ["Open Studio", "Choose System Planner", "Describe the system goal, constraints, and expected outputs"],
    exampleQuestions: [
      "When should I use System Planner instead of Agent Planner?",
      "What should I write in a System Planner requirement?",
      "Can System Planner create a multi-agent workflow?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["system planner", "system", "planner", "multi-agent", "requirements", "workflow"],
  },
  {
    slug: "design-intent-analyzer",
    title: "Design Intent Analyzer",
    category: "Studio",
    summary: "Use Design Intent Planner to turn an idea into a reusable consolidated design spec.",
    body: [
      "Design Intent Planner helps convert an early idea, notes, or repository context into reusable design intent. It is useful before generation because it makes hidden assumptions explicit.",
      "The flow has three simple steps: Describe, Clarify, and Review. Review creates a consolidated design spec that can be saved or used to build a workflow.",
      "Step 1: Go to Home -> Studio -> Design Intent Planner.",
      "Step 2: In Design Your Idea, describe the functionality, interfaces, constraints, and expected outcome.",
      "Step 3: Click Continue Asking Questions and edit the suggested answers so they match your real requirement.",
      "Step 4: Click Generate Consolidated Spec and review the purpose, domain interpretation, decisions, assumptions, open questions, and verification intent.",
      "Step 5: Click Save Design Intent to store it in the design intent library, or Save & Build Workflow to save it and open System Planner with the spec preloaded.",
    ],
    actions: ["Open Studio", "Open Design Intent Planner", "Generate a consolidated spec", "Save & Build Workflow"],
    exampleQuestions: [
      "What does Design Intent Planner create?",
      "How is design intent different from a prompt?",
      "How do I save an idea and build a workflow from it?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["design intent", "analyzer", "requirements", "constraints", "assumptions", "library", "spec"],
  },
  {
    slug: "workflow-composer",
    title: "Workflow Composer",
    category: "Studio",
    summary: "Use Workflow Composer to combine workflows, suggest branch structure, and review parallel execution stages.",
    body: [
      "Workflow Composer works on a current Studio canvas or one or more saved workflows from Supabase. It can suggest branch-and-join edges, remove duplicate shared steps, and show which stages can run together.",
      "Composer does not execute agents. It prepares a better graph for review. Use Open on Canvas to inspect the suggested graph, or Save as Private Workflow when the structure looks right.",
      "Step 1: Go to Home -> Studio -> System Planner when you want ChipLoop to create the first system-level draft from requirements.",
      "Step 2: Build and save the draft workflow. The initial draft may be serial, which is normal.",
      "Step 3: Go to Home -> Studio -> Workflow Composer.",
      "Step 4: Choose Current workflow if the graph is already open on the canvas, or choose Saved workflow and select one or more saved workflows.",
      "Step 5: Keep Suggest branch structure enabled when you want Composer to propose better branch-and-join edges before analysis.",
      "Step 6: Click Analyze Parallelism. Review the summary: selected workflows, original steps, shared steps removed, composed steps, and parallel groups.",
      "Step 7: Review Current Serial Steps to see the original sequence and workflow provenance. Shared steps show when the same agent came from more than one selected workflow.",
      "Step 8: Review Parallel Stages Found to see which agents can run in the same stage. For example, Digital RTL work and Analog model work can run separately, then join at System Top Assembly before simulation and coverage stages.",
      "Step 9: Use Open on Canvas to inspect the suggested graph visually, or Save as Private Workflow to keep the composed version for later use.",
    ],
    actions: ["Open Studio", "Open Workflow Composer", "Analyze current or saved workflows", "Save the result as a private workflow"],
    exampleQuestions: [
      "What does Workflow Composer do?",
      "Can I select multiple saved workflows?",
      "Why are shared agents shown only once?",
      "How do I analyze a System Planner workflow for parallelism?",
      "What does Save as Private Workflow create?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["workflow composer", "optimize workflow", "compose", "parallelism", "workflow", "graph", "validation", "handoff", "agents", "system planner", "saved workflow", "private workflow", "shared step"],
  },
  {
    slug: "design-intent-library",
    title: "Design Intent Library",
    category: "Studio",
    summary: "Keep reusable requirements, constraints, assumptions, and review intent in one place.",
    body: [
      "The design intent library is where users should store reusable engineering intent instead of rewriting it for every run. It can include interface rules, reset assumptions, power constraints, verification goals, and style preferences.",
      "Use the library to make future workflows more consistent and easier to inspect.",
      "Step 1: Go to Home -> Studio -> Design Intent Library and capture intent from a spec, Design Intent Analyzer output, or a previous successful workflow.",
      "Step 2: Save the entry with a clear name that describes the block, subsystem, or rule set.",
      "Step 3: Keep the content focused on stable requirements, constraints, assumptions, and review expectations.",
      "Step 4: Use Save & Build Workflow from Design Intent Planner when you want to save the intent and immediately open System Planner with the consolidated spec preloaded.",
      "Step 5: Update the library when requirements change so future runs stay aligned.",
    ],
    actions: ["Capture intent from specs or analysis", "Save it with a clear name", "Attach relevant intent to future workflows"],
    exampleQuestions: [
      "What belongs in the design intent library?",
      "How should I name design intent entries?",
      "Can design intent be reused across workflows?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["design intent library", "library", "constraints", "requirements", "reuse", "intent"],
  },
  {
    slug: "marketplace",
    title: "Marketplace",
    category: "Studio",
    summary: "Use Marketplace to discover agents and workflow building blocks beyond your private workspace.",
    body: [
      "Marketplace is where reusable agents and capabilities can be discovered. Private agents start scoped to the user, while marketplace items are intended for broader reuse after review.",
      "Use Marketplace when a workflow needs an agent you do not want to create from scratch, or when you want to install a reusable building block into Studio.",
      "Step 1: Go to Home -> Marketplace and search for the capability you need.",
      "Step 2: Review what the agent does, what inputs it expects, and what outputs it produces.",
      "Step 3: Install or add the agent to your Studio workspace when it matches your workflow.",
      "Step 4: Connect it inside a Studio workflow and verify the handoff artifacts.",
      "Step 5: Use private agents first when the capability is specific to your company or project.",
      "Step 6: Use Submit for Review in Studio when a private capability is ready for marketplace review. Submission does not automatically make it public.",
    ],
    actions: ["Open Marketplace", "Review the agent capability and inputs", "Install or use it in a Studio workflow", "Submit reviewed private capabilities when ready"],
    exampleQuestions: [
      "When should I use Marketplace?",
      "What is the difference between a private agent and Marketplace agent?",
      "How do I add a Marketplace agent to Studio?",
    ],
    links: [
      { label: "Marketplace", href: "/marketplace" },
      { label: "Studio", href: "/workflow" },
    ],
    keywords: ["marketplace", "agent", "install", "private", "public", "reuse", "submit for review"],
  },
  {
    slug: "agent-planner",
    title: "Agent Planner",
    category: "Studio",
    summary: "Plan a private draft agent from requirements, generate missing dependency specs, then review and save it.",
    body: [
      "Agent Planner takes requirements and first checks reusable agents, skills, tools, and hooks. When Create a new private agent is selected, existing matches are shown as references instead of blocking the new draft.",
      "Private draft agents start scoped to the user. They can be reviewed, saved, opened from My Agents, edited, and saved again before broader marketplace review.",
      "For a new agent, define the goal, input artifacts, output artifacts, skills, Tools / MCP connections, and any hooks needed before or after execution.",
      "Step 1: Go to Home -> Studio -> Agent Planner.",
      "Step 2: Check Create new private agent when you want a fresh private agent instead of matching existing agents.",
      "Step 3: Fill in the planned agent name, loop, optional domain, and requirement. Keep the requirement concrete: what the agent reads, what it produces, and how success should be checked.",
      "Step 4: Click Run. Review exact matches, similar matches, reusable components, and missing capabilities.",
      "Step 5: Click Create Private Draft Agent or Generate Draft Agent to open Review Draft Agent.",
      "Step 6: In Review Draft Agent, fill or adjust Inputs, Outputs, Skills, Tools / MCP, and Hooks. Put one item per line.",
      "Step 7: Click Generate Draft Agent. If a skill, tool, or hook is missing, ChipLoop generates a private draft spec for that dependency and labels it as Generated spec.",
      "Step 8: Review the purpose, dependency status, validation checklist, warnings, and advanced details. Then click Save Private Draft.",
      "Step 9: Open My Agents in Studio to view or edit the saved private agent. Save with the same name to update it, or save with a different name to create a variant.",
    ],
    actions: ["Open Studio", "Select Agent Planner", "Create a private draft agent", "Review generated skill, tool, and hook specs"],
    exampleQuestions: [
      "How do I create a private agent?",
      "What happens when a skill or hook is missing?",
      "What fields should I fill for a new agent?",
      "Can I edit an agent after it is generated?",
    ],
    links: [{ label: "Studio", href: "/workflow" }],
    keywords: ["agent", "planner", "private", "skill", "mcp", "tool", "hook", "template", "draft", "my agents", "generated spec"],
  },
  {
    slug: "github",
    title: "GitHub Integration",
    category: "Integrations",
    summary: "Connect your own GitHub account, then import repository context into Apps or Studio.",
    body: [
      "Each user installs the ChipLoop GitHub App for their own account or organization. The administrator configures the app once; users authorize their own installations.",
      "After connection, users can import repository files into a workflow prompt or Studio context. Repository access is scoped by the GitHub installation permissions.",
      "Step 1: Go to Home -> Settings -> Integrations and choose Connect GitHub.",
      "Step 2: Select the GitHub account or organization and choose which repositories ChipLoop can access.",
      "Step 3: Return to ChipLoop after GitHub redirects back to the integrations page.",
      "Step 4: In Apps or Studio, use GitHub import to select repo files that should become workflow context.",
      "Step 5: Disconnect GitHub from Settings, Integrations if access should be removed.",
    ],
    actions: ["Open Settings, Integrations", "Connect GitHub", "Import selected repository context into Apps or Studio"],
    exampleQuestions: [
      "How do I connect GitHub?",
      "Can each user connect their own GitHub?",
      "How do I import repository context into Studio?",
    ],
    links: [{ label: "GitHub settings", href: "/settings/integrations" }],
    keywords: ["github", "repository", "repo", "install", "integration", "settings", "import"],
  },
  {
    slug: "cli-sdk",
    title: "CLI and SDK",
    category: "Developer",
    summary: "Use API keys for scripted access once the account and plan are ready.",
    body: [
      "Developer access uses API keys created in Settings. Keep keys private and revoke keys that are no longer used.",
      "The normal flow is create an API key, call backend workflow endpoints from a script or SDK client, then inspect outputs in the platform.",
      "Step 1: Go to Home -> Settings -> API Keys and create a key with a clear name such as local-cli, ci-runner, or vscode-local.",
      "Step 2: Install the SDK/CLI in your environment.",
      "Command: pip install chiploop-sdk",
      "Step 3: Set CHIPLOOP_BASE_URL and CHIPLOOP_API_KEY in your shell, CI secrets, or IDE secret storage.",
      "macOS/Linux example: export CHIPLOOP_BASE_URL=https://api.getchiploops.com\nexport CHIPLOOP_API_KEY=cl_live_...",
      "Windows PowerShell example: $env:CHIPLOOP_BASE_URL=\"https://api.getchiploops.com\"\n$env:CHIPLOOP_API_KEY=\"cl_live_...\"",
      "Step 4: Run chiploop doctor to confirm configuration.",
      "Command: chiploop doctor",
      "Step 5: Run a workflow from a spec file, poll status, list artifacts, and download outputs for review.",
      "Command: chiploop run arch2rtl --spec specs/pwm.md\nchiploop status <workflow_id>\nchiploop artifacts list <workflow_id>\nchiploop artifacts download <workflow_id> --name rtl/top.v --out ./chiploop_outputs",
      "Step 6: Revoke old keys from Settings when a machine, CI job, or teammate no longer needs access.",
    ],
    actions: ["Open Settings, API Keys", "Create a scoped key", "Use the key from CLI or SDK automation"],
    exampleQuestions: [
      "How do I create an API key?",
      "What is the CLI or SDK flow?",
      "How do I keep API keys safe?",
    ],
    links: [{ label: "API keys", href: "/settings/api-keys" }],
    keywords: ["cli", "sdk", "api", "api key", "automation", "developer"],
  },
  {
    slug: "cursor-vscode",
    title: "Cursor and VS Code",
    category: "Developer",
    summary: "Use ChipLoop from Cursor or VS Code through the same CLI and API-key path.",
    body: [
      "Cursor is supported through the integrated terminal today. Install the ChipLoop SDK/CLI, set CHIPLOOP_BASE_URL and CHIPLOOP_API_KEY in your shell, then run workflows against local spec files.",
      "VS Code support follows the same CLI path. The MVP extension scaffold is command-palette oriented: configure ChipLoop, run the current spec file or Arch2RTL, check workflow status, download artifacts, and open Apps or Studio.",
      "IDE integrations should not call browser-only endpoints or store secrets in source files. Use Settings, API Keys to create a key, keep generated outputs in a review folder, and inspect artifacts before committing them.",
      "Step 1: Go to Home -> Settings -> API Keys and create a key named cursor-local, vscode-local, or another clear local name.",
      "Step 2: In Cursor or VS Code, open the design repository and install the CLI from the IDE terminal.",
      "Command: pip install chiploop-sdk",
      "Step 3: Set CHIPLOOP_BASE_URL to the ChipLoop backend URL and CHIPLOOP_API_KEY to the key created in Settings. Set these in the shell or IDE secret storage, not in source files.",
      "macOS/Linux example: export CHIPLOOP_BASE_URL=https://api.getchiploops.com\nexport CHIPLOOP_API_KEY=cl_live_...",
      "Windows PowerShell example: $env:CHIPLOOP_BASE_URL=\"https://api.getchiploops.com\"\n$env:CHIPLOOP_API_KEY=\"cl_live_...\"",
      "Step 4: Put the design requirement in a file such as specs/pwm.md, then run the workflow from the IDE terminal.",
      "Command: chiploop doctor\nchiploop run arch2rtl --spec specs/pwm.md",
      "Step 5: Inspect outputs locally.",
      "Command: chiploop status <workflow_id>\nchiploop artifacts list <workflow_id>\nchiploop artifacts download <workflow_id> --name rtl/top.v --out ./chiploop_outputs",
      "Step 6: Review generated RTL, SDC, UPF, reports, and logs before committing changes back to the repository.",
    ],
    actions: [
      "Create a ChipLoop API key",
      "Install the ChipLoop SDK/CLI in the IDE terminal",
      "Set CHIPLOOP_BASE_URL and CHIPLOOP_API_KEY in the shell or IDE secret store",
      "Run a workflow from a local spec file and download artifacts",
      "Review generated files before committing them",
    ],
    exampleQuestions: [
      "How do I use ChipLoop in Cursor?",
      "How do I use ChipLoop from VS Code?",
      "Where should I store the API key for IDE workflows?",
    ],
    links: [
      { label: "API keys", href: "/settings/api-keys" },
      { label: "Integrations", href: "/settings/integrations" },
    ],
    keywords: ["cursor", "vscode", "vs code", "ide", "extension", "terminal", "sdk", "cli", "api key"],
  },
  {
    slug: "example-pwm",
    title: "Example: PWM Controller",
    category: "Examples",
    summary: "A simple Arch2RTL example for a PWM controller.",
    body: [
      "Ask Arch2RTL to design a parameterized PWM controller with clk, reset_n, enable, duty_cycle[7:0], period[7:0], pwm_out, and counter_value[7:0].",
      "After the run completes, ask: summarize the generated RTL, list the reset behavior, and what should be verified in simulation.",
      "Step 1: Go to Home -> Apps -> Arch2RTL.",
      "Step 2: Paste the PWM requirement including clk, reset_n, enable, duty_cycle[7:0], period[7:0], pwm_out, and counter_value[7:0].",
      "Command: Design a parameterized PWM controller.\n\nInputs:\n- clk\n- reset_n\n- enable\n- duty_cycle[7:0]\n- period[7:0]\n\nOutputs:\n- pwm_out\n- counter_value[7:0]",
      "Step 3: State the behavior: counter increments when enabled, resets at period, pwm_out is high while counter_value is less than duty_cycle, and reset clears registers.",
      "Command: Counter increments every clock when enable is high.\nCounter resets to zero when it reaches period.\npwm_out is high when counter_value is less than duty_cycle.\nAll registers reset to zero when reset_n is low.",
      "Step 4: Run the workflow and wait for completion.",
      "Step 5: Ask This Run to summarize generated RTL, reset behavior, constraints, and simulation checks.",
    ],
    actions: ["Paste the PWM requirement into Arch2RTL", "Run the workflow", "Use Ask This Run for the verification checklist"],
    exampleQuestions: [
      "Can you give me a PWM Arch2RTL example?",
      "What should I ask after the PWM run finishes?",
      "What should be verified in the PWM output?",
    ],
    links: [{ label: "Arch2RTL", href: "/apps/arch2rtl" }],
    keywords: ["example", "pwm", "controller", "arch2rtl", "simulation", "verification"],
  },
];

export const helpCategories = ["Basics", "Apps", "Inspection", "Studio", "Integrations", "Developer", "Examples"] as const;

export function findHelpTopic(slug: string | null): HelpTopic {
  const normalizedSlug = slug === "optimize-workflow" ? "workflow-composer" : slug;
  return helpTopics.find((topic) => topic.slug === normalizedSlug) || helpTopics[0];
}
