export const DESIGN_CHAIN_CONTEXT_KEY = "chiploop_design_full_stack_context";
export const VERIFY_HANDOFF_PREFILL_KEY = "chiploop_verify_handoff_prefill";
export const EMBEDDED_HANDOFF_PREFILL_KEY = "chiploop_embedded_handoff_prefill";
export const SOFTWARE_HANDOFF_PREFILL_KEY = "chiploop_software_handoff_prefill";
export const VALIDATION_HANDOFF_PREFILL_KEY = "chiploop_validation_handoff_prefill";
export const PRODUCT_BUILDER_PREFILL_KEY = "chiploop_product_builder_prefill";

export const PWM_FULL_STACK_ARCH2RTL_SPEC = `Design a parameterized PWM controller.

This version is controlled by firmware through a memory-mapped register interface.

Inputs:
- clk
- reset_n
- wr_en
- wr_addr[7:0]
- wr_data[7:0]
- rd_en
- rd_addr[7:0]

Outputs:
- rd_data[7:0]
- pwm_out
- counter_value[7:0]

Register map:
- 0x00 CONTROL: bit 0 ENABLE, read/write
- 0x04 DUTY_CYCLE: duty_cycle[7:0], read/write
- 0x08 PERIOD: period[7:0], read/write
- 0x0C COUNTER_VALUE: counter_value[7:0], read-only status

Behavior:
- All registers and outputs reset to zero when reset_n is low.
- Counter increments every clock while CONTROL.ENABLE is high and PERIOD is nonzero.
- Counter wraps to zero when it reaches PERIOD.
- pwm_out is high while enabled and counter_value is less than duty_cycle[7:0].
- Reads return the addressed register value, including live COUNTER_VALUE status.

Generate synthesizable SystemVerilog, a register map, assertions, a simulation testbench, UPF-lite collateral, and a packaging manifest.`;

export const PWM_VERIFY_INTENT = `Verify the parameterized PWM controller generated by Arch2RTL.

Directed scenarios:
- Assert reset_n low and confirm pwm_out, counter_value, and readable registers clear to zero.
- Program CONTROL, DUTY_CYCLE, and PERIOD through the register write interface.
- Disable the controller and confirm pwm_out remains low.
- Run duty_cycle values representing 0%, 25%, 50%, and 90% duty for a fixed period.
- Change duty_cycle while enabled and confirm measured output follows the requested duty on subsequent periods.

Collect waveform evidence, measured versus commanded duty-cycle results, assertion outcomes, and functional coverage.`;

export const PWM_EMBEDDED_SPEC = `Rust PWM fan-control firmware for the verified pwm_controller RTL.

Hardware interface:
- PWM controller RTL and register map are imported from the completed Arch2RTL workflow.
- Firmware controls enable, period, and duty-cycle settings.
- pwm_out is the observable fan-control output.

Application policy:
- Below 30 C: fan off (0% duty).
- 30 C to 49 C: quiet cooling (25% duty).
- 50 C to 69 C: normal cooling (55% duty).
- 70 C or above: emergency cooling (90% duty).

Generate a Rust register layer and driver, build collateral, co-simulation collateral, validation report, and a software-facing handoff package.`;

export const PWM_SOFTWARE_GOAL = `Create a fan-control application and SDK over the verified Rust PWM firmware.

Provide fan status, temperature threshold configuration, quiet/normal/emergency profiles, and traceable commands that map to firmware PWM duty-cycle updates.`;

export const PWM_VALIDATION_GOAL = `Validate the PWM fan-control chain end to end.

Apply a temperature ramp of 25 C, 45 C, 60 C, and 80 C. Confirm software-selected fan policy becomes firmware register writes and the imported PWM RTL produces 0%, 25%, 55%, and 90% duty-cycle behavior with traceable results.`;

export const GENERIC_VERIFY_INTENT = `Verify the generated RTL from the selected Arch2RTL workflow.

Derive directed scenarios, assertions, corner cases, and coverage targets from the imported specification, generated RTL, and interface/register artifacts. Preserve traceability to the source workflow.`;

export const GENERIC_EMBEDDED_SPEC = `Generate firmware collateral from the imported Arch2RTL hardware package.

Read the generated RTL interface and register map from the source workflow. Create a register layer, driver scaffold, build and co-simulation collateral, validation report, and a software-facing handoff package for the actual imported design.`;

export const GENERIC_SOFTWARE_GOAL = `Create a software API and application package from the imported firmware handoff.

Derive capabilities, commands, and data structures from the firmware and RTL interface artifacts. Preserve traceability to the source workflows.`;

export const GENERIC_VALIDATION_GOAL = `Validate the generated software, firmware, and imported RTL together.

Derive integrated scenarios from the actual handoff artifacts and prove the software-to-firmware-to-RTL contract with traceable co-simulation results.`;

export const PWM_PRODUCT_INTENT = `Build a simulator-backed PWM fan-control product dashboard from the validated RTL, firmware, software, and validation collateral.

The dashboard should let a user enable PWM, adjust duty cycle, view counter/PWM output state, run a thermal fan-control scenario, and preserve lineage back to the generated workflows.`;

export const UART_PACKET_ENGINE_ARCH2RTL_SPEC = `Design a UART buffered packet engine with a memory-mapped register interface.

This block is more complex than the PWM demo and should include enough state for roughly 150-200 flip-flops through FIFOs, counters, shifters, state machines, and status registers.

Top module:
- uart_packet_engine

Inputs:
- clk
- reset_n
- wr_en
- wr_addr[7:0]
- wr_data[7:0]
- rd_en
- rd_addr[7:0]
- uart_rx

Outputs:
- rd_data[7:0]
- uart_tx
- irq
- rx_fifo_level[5:0]
- tx_fifo_level[5:0]
- packet_count[15:0]

Register map:
- 0x00 CONTROL: bit 0 ENABLE, bit 1 RX_ENABLE, bit 2 TX_ENABLE, bit 3 LOOPBACK, bit 4 IRQ_ENABLE
- 0x04 BAUD_DIV: baud-rate divider[15:0]
- 0x08 PACKET_LEN: expected packet length[7:0]
- 0x0C TX_DATA: write-only TX FIFO push data[7:0]
- 0x10 RX_DATA: read-only RX FIFO pop data[7:0]
- 0x14 STATUS: tx_empty, tx_full, rx_empty, rx_full, tx_busy, rx_busy, packet_active, error
- 0x18 IRQ_STATUS: rx_done, tx_done, rx_overflow, tx_underflow, framing_error, packet_done
- 0x1C IRQ_CLEAR: write one to clear matching IRQ_STATUS bits
- 0x20 DEBUG_COUNT: packet_count[15:0], read-only

Functional requirements:
- Reset clears all registers, FIFOs, counters, shifters, state machines, status bits, and irq.
- BAUD_DIV controls a baud tick generator used by both UART RX and TX.
- UART TX serializes bytes from TX FIFO using 1 start bit, 8 data bits, no parity, and 1 stop bit.
- UART RX samples uart_rx, reconstructs 8-bit bytes, checks start/stop framing, and pushes valid bytes into RX FIFO.
- TX FIFO depth is 16 entries by 8 bits.
- RX FIFO depth is 16 entries by 8 bits.
- Firmware pushes TX bytes by writing TX_DATA when STATUS.tx_full is zero.
- Firmware reads RX bytes by reading RX_DATA when STATUS.rx_empty is zero.
- PACKET_LEN controls packet completion. RX_DONE asserts when PACKET_LEN valid bytes have been received. TX_DONE asserts when PACKET_LEN bytes have been transmitted.
- IRQ_STATUS latches completion and error events until cleared through IRQ_CLEAR.
- irq is asserted when CONTROL.IRQ_ENABLE is set and any IRQ_STATUS bit is set.
- LOOPBACK mode internally routes transmitted bytes into the RX path for firmware and verification smoke tests.
- Overflow and underflow conditions must be detected and latched.

Generate synthesizable SystemVerilog, a register map, assertions, a simulation testbench, UPF-lite collateral, and a packaging manifest.`;

export const UART_VERIFY_INTENT = `Verify the UART buffered packet engine generated by Arch2RTL.

Directed scenarios:
- Assert reset_n low and confirm registers, FIFOs, state machines, irq, and status outputs clear.
- Program CONTROL, BAUD_DIV, and PACKET_LEN through the register interface.
- Write a four-byte packet through TX_DATA and confirm TX FIFO level, tx_busy, tx_done, and IRQ_STATUS behavior.
- Enable LOOPBACK and confirm transmitted bytes appear in RX_DATA in order.
- Exercise RX FIFO empty/full and TX FIFO empty/full transitions.
- Inject RX framing error and FIFO overflow cases and confirm IRQ_STATUS latches the error until IRQ_CLEAR.
- Confirm packet_count increments only after packet_done.

Collect waveform evidence, register readback, FIFO-level coverage, interrupt coverage, assertion outcomes, and functional coverage.`;

export const UART_EMBEDDED_SPEC = `Rust firmware for the verified uart_packet_engine RTL.

Hardware interface:
- UART packet engine RTL and register map are imported from the completed Arch2RTL workflow.
- Firmware configures baud rate, packet length, loopback mode, FIFO access, and interrupt enable.
- Firmware sends and receives packets through TX_DATA and RX_DATA registers.

Application policy:
- Initialize the engine at a configured baud divider.
- Send a telemetry packet.
- Receive a command packet in loopback/simulated mode.
- Handle rx_done, tx_done, packet_done, overflow, and framing-error interrupts.
- Provide a packet status API with FIFO levels, packet_count, last error, and irq state.

Generate a Rust register layer and driver, build collateral, co-simulation collateral, validation report, and a software-facing handoff package.`;

export const UART_SOFTWARE_GOAL = `Create a UART packet service and SDK over the verified Rust UART packet-engine firmware.

Provide commands to configure baud rate, send packets, receive packets, inspect FIFO levels, clear interrupts, and report packet/error counters.`;

export const UART_VALIDATION_GOAL = `Validate the UART packet-engine chain end to end.

Run a loopback telemetry scenario, a command receive scenario, an interrupt clear scenario, and an error injection scenario. Confirm software commands become firmware register actions and the imported UART RTL produces ordered packet movement, interrupt status, FIFO-level changes, and traceable validation results.`;

export const UART_PRODUCT_INTENT = `Build a simulator-backed UART packet-engine product dashboard from the validated RTL, firmware, software, and validation collateral.

The dashboard should let a user configure baud divider and packet length, send a telemetry packet, view TX/RX FIFO levels, observe irq and IRQ_STATUS, run loopback/error scenarios, and preserve lineage back to the generated workflows.`;

export const IMAGE_DMA_PIPELINE_ARCH2RTL_SPEC = `Design a large image processing pipeline with DMA and a memory-mapped control/status interface.

This is a large demo design. Target roughly 25,000 flip-flops by using synthesizable register-based line buffers and visible control/state registers rather than inferred SRAM macros for the demo line-buffer storage.

Top module:
- image_dma_pipeline

Data model:
- 8-bit grayscale pixels
- 256 pixels per line
- Frame height is programmable up to 256 lines
- Streaming 3x3 image-processing pipeline

Inputs:
- clk
- reset_n
- wr_en
- wr_addr[11:0]
- wr_data[31:0]
- rd_en
- rd_addr[11:0]
- dma_rd_data[31:0]
- dma_rd_valid
- dma_wr_ready

Outputs:
- rd_data[31:0]
- dma_rd_req
- dma_rd_addr[31:0]
- dma_wr_req
- dma_wr_addr[31:0]
- dma_wr_data[31:0]
- irq
- frame_active
- frame_done
- pixel_valid
- pixel_out[7:0]
- histogram_bin[7:0]
- histogram_count[15:0]

Register map:
- 0x000 CONTROL: bit 0 ENABLE, bit 1 START, bit 2 SOFT_RESET, bit 3 IRQ_ENABLE
- 0x004 STATUS: busy, frame_done, dma_rd_busy, dma_wr_busy, error, histogram_done
- 0x008 SRC_BASE: source frame base address[31:0]
- 0x00C DST_BASE: destination frame base address[31:0]
- 0x010 WIDTH: frame width, default 256
- 0x014 HEIGHT: frame height
- 0x018 STRIDE: source/destination stride bytes
- 0x01C FILTER_MODE: 0 bypass, 1 sharpen, 2 blur, 3 edge, 4 threshold
- 0x020 BRIGHTNESS: signed brightness offset[8:0]
- 0x024 CONTRAST: unsigned contrast scale[7:0]
- 0x028 THRESHOLD: threshold level[7:0]
- 0x02C IRQ_STATUS: frame_done, dma_done, histogram_done, read_error, write_error
- 0x030 IRQ_CLEAR: write one to clear IRQ_STATUS bits
- 0x034 PIXEL_COUNT: processed pixel count[31:0]
- 0x038 FRAME_COUNT: completed frame count[31:0]
- 0x03C ERROR_STATUS: sticky error detail bits
- 0x100-0x120 KERNEL0..KERNEL8: signed 3x3 convolution coefficients[7:0]
- 0x200-0x5FC HISTOGRAM[0..255]: 16-bit histogram counters, read-only

Architecture requirements:
- DMA read engine fetches packed 32-bit words from SRC_BASE using WIDTH, HEIGHT, and STRIDE.
- Pixel unpacker converts each 32-bit DMA word into four 8-bit pixels.
- Use three register-based 256-entry line buffers, each 8 bits wide, for 3x3 window generation. Do not infer SRAM for these line buffers in this demo.
- Generate a valid 3x3 window after enough pixels and lines have arrived.
- Pipeline stages: DMA read, pixel unpack, line-buffer/window, convolution, brightness/contrast, threshold, histogram update, output pack, DMA write.
- Implement at least six visible pipeline valid registers and metadata registers for x/y coordinates.
- 3x3 convolution uses programmable signed 8-bit kernel coefficients and saturation to 8-bit output.
- Brightness/contrast stage applies signed offset and scale with saturation.
- Threshold stage can force output to 0 or 255 when FILTER_MODE is threshold.
- Histogram stage maintains 256 16-bit counters for processed output pixels.
- DMA write engine writes packed 32-bit processed pixels to DST_BASE.
- Interrupt controller asserts irq when frame_done, dma_done, histogram_done, or error events occur and IRQ_ENABLE is set.
- STATUS.busy remains high from START until frame processing and DMA writeback complete.
- SOFT_RESET clears internal state, line buffers, counters, histogram, sticky errors, and irq.

Verification and observability requirements:
- Expose frame_active, frame_done, pixel_valid, pixel_out, histogram_bin, and histogram_count for simulation visibility.
- Include assertions for no write without data, no read beyond configured frame, line-buffer window validity, IRQ clear behavior, and frame_done only after expected PIXEL_COUNT.
- Generate synthesizable SystemVerilog, register map, assertions, simulation testbench, UPF-lite collateral, and packaging manifest.`;

export const IMAGE_VERIFY_INTENT = `Verify the image DMA pipeline generated by Arch2RTL.

Directed scenarios:
- Assert reset_n low and confirm registers, line buffers, histogram counters, DMA state machines, irq, and frame status clear.
- Program SRC_BASE, DST_BASE, WIDTH, HEIGHT, STRIDE, FILTER_MODE, THRESHOLD, and KERNEL registers through the control interface.
- Run a small 16x8 frame in bypass mode and confirm DMA read/write byte counts, PIXEL_COUNT, frame_done, and irq behavior.
- Run a 3x3 edge-detect kernel on a deterministic test pattern and compare output signature.
- Run threshold mode and confirm output pixels saturate to 0 or 255 around the threshold.
- Confirm histogram counters update for processed output pixels and histogram_done asserts.
- Inject DMA read/write backpressure and confirm the pipeline stalls without dropping pixels.
- Exercise IRQ_CLEAR and SOFT_RESET while idle.

Collect waveform evidence, frame signature checks, DMA progress checks, histogram coverage, pipeline-valid coverage, assertion outcomes, and functional coverage.`;

export const IMAGE_EMBEDDED_SPEC = `Rust firmware for the verified image_dma_pipeline RTL.

Hardware interface:
- Image DMA pipeline RTL and register map are imported from the completed Arch2RTL workflow.
- Firmware configures source/destination addresses, width, height, stride, filter mode, kernel coefficients, threshold, brightness, and contrast.
- Firmware starts frame processing, waits for interrupts, reads frame counters, and extracts histogram bins.

Application policy:
- Provide init, configure_frame, configure_filter, start_frame, poll_status, clear_irq, read_histogram, and read_error APIs.
- Include demo presets for bypass, blur, edge detect, and threshold.
- Validate a frame signature and histogram summary after processing.

Generate a Rust register layer and driver, build collateral, co-simulation collateral, validation report, and a software-facing handoff package.`;

export const IMAGE_SOFTWARE_GOAL = `Create an image-processing control application and SDK over the verified Rust image DMA firmware.

Provide commands to configure frame geometry, choose filter preset, start DMA processing, monitor progress, inspect histogram bins, read output signatures, clear interrupts, and export a processing report.`;

export const IMAGE_VALIDATION_GOAL = `Validate the image DMA pipeline chain end to end.

Run bypass, edge-detect, threshold, and DMA-backpressure scenarios. Confirm software commands become firmware register operations and the imported RTL produces expected frame_done interrupts, DMA byte counts, output signatures, histogram updates, and traceable validation results.`;

export const IMAGE_PRODUCT_INTENT = `Build a simulator-backed image processing product dashboard from the validated RTL, firmware, software, and validation collateral.

The dashboard should let a user select a filter mode, adjust threshold and brightness, start a frame, visualize DMA progress, show input/output frame previews, display a histogram, show irq/status/error fields, and preserve lineage back to the generated workflows.`;

export type DesignChainContext = {
  demoKind?: "pwm" | "uart_packet" | "image_dma";
  arch2rtlWorkflowId?: string;
  arch2rtlRunId?: string;
  verifyWorkflowId?: string;
  verifyRunId?: string;
  embeddedWorkflowId?: string;
  embeddedRunId?: string;
  softwareWorkflowId?: string;
  softwareRunId?: string;
  validationWorkflowId?: string;
  validationRunId?: string;
  productWorkflowId?: string;
  productRunId?: string;
};
