export const DESIGN_CHAIN_CONTEXT_KEY = "chiploop_design_full_stack_context";
export const VERIFY_HANDOFF_PREFILL_KEY = "chiploop_verify_handoff_prefill";
export const EMBEDDED_HANDOFF_PREFILL_KEY = "chiploop_embedded_handoff_prefill";
export const SOFTWARE_HANDOFF_PREFILL_KEY = "chiploop_software_handoff_prefill";
export const VALIDATION_HANDOFF_PREFILL_KEY = "chiploop_validation_handoff_prefill";
export const PRODUCT_BUILDER_PREFILL_KEY = "chiploop_product_builder_prefill";

export const PWM_FULL_STACK_ARCH2RTL_SPEC = `Design a parameterized PWM controller.

This version is controlled by firmware through a memory-mapped register interface.

Inputs:
- clk
- reset_n
- wr_en
- wr_addr[7:0]
- wr_data[7:0]
- rd_en
- rd_addr[7:0]

Outputs:
- rd_data[7:0]
- pwm_out
- counter_value[7:0]

Register map:
- 0x00 CONTROL: bit 0 ENABLE, read/write
- 0x04 DUTY_CYCLE: duty_cycle[7:0], read/write
- 0x08 PERIOD: period[7:0], read/write
- 0x0C COUNTER_VALUE: counter_value[7:0], read-only status

Behavior:
- All registers and outputs reset to zero when reset_n is low.
- Counter increments every clock while CONTROL.ENABLE is high and PERIOD is nonzero.
- Counter wraps to zero when it reaches PERIOD.
- pwm_out is high while enabled and counter_value is less than duty_cycle[7:0].
- Reads return the addressed register value, including live COUNTER_VALUE status.

Generate synthesizable SystemVerilog, a register map, assertions, a simulation testbench, UPF-lite collateral, and a packaging manifest.`;

export const PWM_VERIFY_INTENT = `Verify the parameterized PWM controller generated by Arch2RTL.

Directed scenarios:
- Assert reset_n low and confirm pwm_out, counter_value, and readable registers clear to zero.
- Program CONTROL, DUTY_CYCLE, and PERIOD through the register write interface.
- Disable the controller and confirm pwm_out remains low.
- Run duty_cycle values representing 0%, 25%, 50%, and 90% duty for a fixed period.
- Change duty_cycle while enabled and confirm measured output follows the requested duty on subsequent periods.

Collect waveform evidence, measured versus commanded duty-cycle results, assertion outcomes, and functional coverage.`;

export const PWM_EMBEDDED_SPEC = `Rust PWM fan-control firmware for the verified pwm_controller RTL.

Hardware interface:
- PWM controller RTL and register map are imported from the completed Arch2RTL workflow.
- Firmware controls enable, period, and duty-cycle settings.
- pwm_out is the observable fan-control output.

Application policy:
- Below 30 C: fan off (0% duty).
- 30 C to 49 C: quiet cooling (25% duty).
- 50 C to 69 C: normal cooling (55% duty).
- 70 C or above: emergency cooling (90% duty).

Generate a Rust register layer and driver, build collateral, co-simulation collateral, validation report, and a software-facing handoff package.`;

export const PWM_SOFTWARE_GOAL = `Create a fan-control application and SDK over the verified Rust PWM firmware.

Provide fan status, temperature threshold configuration, quiet/normal/emergency profiles, and traceable commands that map to firmware PWM duty-cycle updates.`;

export const PWM_VALIDATION_GOAL = `Validate the PWM fan-control chain end to end.

Apply a temperature ramp of 25 C, 45 C, 60 C, and 80 C. Confirm software-selected fan policy becomes firmware register writes and the imported PWM RTL produces 0%, 25%, 55%, and 90% duty-cycle behavior with traceable results.`;

export const GENERIC_VERIFY_INTENT = `Verify the generated RTL from the selected Arch2RTL workflow.

Derive directed scenarios, assertions, corner cases, and coverage targets from the imported specification, generated RTL, and interface/register artifacts. Preserve traceability to the source workflow.`;

export const GENERIC_EMBEDDED_SPEC = `Generate firmware collateral from the imported Arch2RTL hardware package.

Read the generated RTL interface and register map from the source workflow. Create a register layer, driver scaffold, build and co-simulation collateral, validation report, and a software-facing handoff package for the actual imported design.`;

export const GENERIC_SOFTWARE_GOAL = `Create a software API and application package from the imported firmware handoff.

Derive capabilities, commands, and data structures from the firmware and RTL interface artifacts. Preserve traceability to the source workflows.`;

export const GENERIC_VALIDATION_GOAL = `Validate the generated software, firmware, and imported RTL together.

Derive integrated scenarios from the actual handoff artifacts and prove the software-to-firmware-to-RTL contract with traceable co-simulation results.`;

export const PWM_PRODUCT_INTENT = `Build a simulator-backed PWM fan-control product dashboard from the validated RTL, firmware, software, and validation collateral.

The dashboard should let a user enable PWM, adjust duty cycle, view counter/PWM output state, run a thermal fan-control scenario, and preserve lineage back to the generated workflows.`;

export const UART_PACKET_ENGINE_ARCH2RTL_SPEC = `Design a UART buffered packet engine with a memory-mapped register interface.

This block is more complex than the PWM demo and should include enough state for roughly 150-200 flip-flops through FIFOs, counters, shifters, state machines, and status registers.

Top module:
- uart_packet_engine

Inputs:
- clk
- reset_n
- wr_en
- wr_addr[7:0]
- wr_data[7:0]
- rd_en
- rd_addr[7:0]
- uart_rx

Outputs:
- rd_data[7:0]
- uart_tx
- irq
- rx_fifo_level[5:0]
- tx_fifo_level[5:0]
- packet_count[15:0]

Register map:
- 0x00 CONTROL: bit 0 ENABLE, bit 1 RX_ENABLE, bit 2 TX_ENABLE, bit 3 LOOPBACK, bit 4 IRQ_ENABLE
- 0x04 BAUD_DIV: baud-rate divider[15:0]
- 0x08 PACKET_LEN: expected packet length[7:0]
- 0x0C TX_DATA: write-only TX FIFO push data[7:0]
- 0x10 RX_DATA: read-only RX FIFO pop data[7:0]
- 0x14 STATUS: tx_empty, tx_full, rx_empty, rx_full, tx_busy, rx_busy, packet_active, error
- 0x18 IRQ_STATUS: rx_done, tx_done, rx_overflow, tx_underflow, framing_error, packet_done
- 0x1C IRQ_CLEAR: write one to clear matching IRQ_STATUS bits
- 0x20 DEBUG_COUNT: packet_count[15:0], read-only

Functional requirements:
- Reset clears all registers, FIFOs, counters, shifters, state machines, status bits, and irq.
- BAUD_DIV controls a baud tick generator used by both UART RX and TX.
- UART TX serializes bytes from TX FIFO using 1 start bit, 8 data bits, no parity, and 1 stop bit.
- UART RX samples uart_rx, reconstructs 8-bit bytes, checks start/stop framing, and pushes valid bytes into RX FIFO.
- TX FIFO depth is 16 entries by 8 bits.
- RX FIFO depth is 16 entries by 8 bits.
- Firmware pushes TX bytes by writing TX_DATA when STATUS.tx_full is zero.
- Firmware reads RX bytes by reading RX_DATA when STATUS.rx_empty is zero.
- PACKET_LEN controls packet completion. RX_DONE asserts when PACKET_LEN valid bytes have been received. TX_DONE asserts when PACKET_LEN bytes have been transmitted.
- IRQ_STATUS latches completion and error events until cleared through IRQ_CLEAR.
- irq is asserted when CONTROL.IRQ_ENABLE is set and any IRQ_STATUS bit is set.
- LOOPBACK mode internally routes transmitted bytes into the RX path for firmware and verification smoke tests.
- Overflow and underflow conditions must be detected and latched.

Generate synthesizable SystemVerilog, a register map, assertions, a simulation testbench, UPF-lite collateral, and a packaging manifest.`;

export const UART_VERIFY_INTENT = `Verify the UART buffered packet engine generated by Arch2RTL.

Directed scenarios:
- Assert reset_n low and confirm registers, FIFOs, state machines, irq, and status outputs clear.
- Program CONTROL, BAUD_DIV, and PACKET_LEN through the register interface.
- Write a four-byte packet through TX_DATA and confirm TX FIFO level, tx_busy, tx_done, and IRQ_STATUS behavior.
- Enable LOOPBACK and confirm transmitted bytes appear in RX_DATA in order.
- Exercise RX FIFO empty/full and TX FIFO empty/full transitions.
- Inject RX framing error and FIFO overflow cases and confirm IRQ_STATUS latches the error until IRQ_CLEAR.
- Confirm packet_count increments only after packet_done.

Collect waveform evidence, register readback, FIFO-level coverage, interrupt coverage, assertion outcomes, and functional coverage.`;

export const UART_EMBEDDED_SPEC = `Rust firmware for the verified uart_packet_engine RTL.

Hardware interface:
- UART packet engine RTL and register map are imported from the completed Arch2RTL workflow.
- Firmware configures baud rate, packet length, loopback mode, FIFO access, and interrupt enable.
- Firmware sends and receives packets through TX_DATA and RX_DATA registers.

Application policy:
- Initialize the engine at a configured baud divider.
- Send a telemetry packet.
- Receive a command packet in loopback/simulated mode.
- Handle rx_done, tx_done, packet_done, overflow, and framing-error interrupts.
- Provide a packet status API with FIFO levels, packet_count, last error, and irq state.

Generate a Rust register layer and driver, build collateral, co-simulation collateral, validation report, and a software-facing handoff package.`;

export const UART_SOFTWARE_GOAL = `Create a UART packet service and SDK over the verified Rust UART packet-engine firmware.

Provide commands to configure baud rate, send packets, receive packets, inspect FIFO levels, clear interrupts, and report packet/error counters.`;

export const UART_VALIDATION_GOAL = `Validate the UART packet-engine chain end to end.

Run a loopback telemetry scenario, a command receive scenario, an interrupt clear scenario, and an error injection scenario. Confirm software commands become firmware register actions and the imported UART RTL produces ordered packet movement, interrupt status, FIFO-level changes, and traceable validation results.`;

export const UART_PRODUCT_INTENT = `Build a simulator-backed UART packet-engine product dashboard from the validated RTL, firmware, software, and validation collateral.

The dashboard should let a user configure baud divider and packet length, send a telemetry packet, view TX/RX FIFO levels, observe irq and IRQ_STATUS, run loopback/error scenarios, and preserve lineage back to the generated workflows.`;

export const IMAGE_DMA_PIPELINE_ARCH2RTL_SPEC = `Design a large image processing pipeline with DMA and a memory-mapped control/status interface.

This is a large demo design. Target roughly 25,000 flip-flops by using synthesizable register-based line buffers and visible control/state registers rather than inferred SRAM macros for the demo line-buffer storage.

Top module:
- image_dma_pipeline

Data model:
- 8-bit grayscale pixels
- 256 pixels per line
- Frame height is programmable up to 256 lines
- Streaming 3x3 image-processing pipeline

Inputs:
- clk
- reset_n
- wr_en
- wr_addr[11:0]
- wr_data[31:0]
- rd_en
- rd_addr[11:0]
- dma_rd_data[31:0]
- dma_rd_valid
- dma_wr_ready

Outputs:
- rd_data[31:0]
- dma_rd_req
- dma_rd_addr[31:0]
- dma_wr_req
- dma_wr_addr[31:0]
- dma_wr_data[31:0]
- irq
- frame_active
- frame_done
- pixel_valid
- pixel_out[7:0]
- histogram_bin[7:0]
- histogram_count[15:0]

Register map:
- 0x000 CONTROL: bit 0 ENABLE, bit 1 START, bit 2 SOFT_RESET, bit 3 IRQ_ENABLE
- 0x004 STATUS: busy, frame_done, dma_rd_busy, dma_wr_busy, error, histogram_done
- 0x008 SRC_BASE: source frame base address[31:0]
- 0x00C DST_BASE: destination frame base address[31:0]
- 0x010 WIDTH: frame width, default 256
- 0x014 HEIGHT: frame height
- 0x018 STRIDE: source/destination stride bytes
- 0x01C FILTER_MODE: 0 bypass, 1 sharpen, 2 blur, 3 edge, 4 threshold
- 0x020 BRIGHTNESS: signed brightness offset[8:0]
- 0x024 CONTRAST: unsigned contrast scale[7:0]
- 0x028 THRESHOLD: threshold level[7:0]
- 0x02C IRQ_STATUS: frame_done, dma_done, histogram_done, read_error, write_error
- 0x030 IRQ_CLEAR: write one to clear IRQ_STATUS bits
- 0x034 PIXEL_COUNT: processed pixel count[31:0]
- 0x038 FRAME_COUNT: completed frame count[31:0]
- 0x03C ERROR_STATUS: sticky error detail bits
- 0x100-0x120 KERNEL0..KERNEL8: signed 3x3 convolution coefficients[7:0]
- 0x200-0x5FC HISTOGRAM[0..255]: 16-bit histogram counters, read-only

Architecture requirements:
- DMA read engine fetches packed 32-bit words from SRC_BASE using WIDTH, HEIGHT, and STRIDE.
- Pixel unpacker converts each 32-bit DMA word into four 8-bit pixels.
- Use three register-based 256-entry line buffers, each 8 bits wide, for 3x3 window generation. Do not infer SRAM for these line buffers in this demo.
- Generate a valid 3x3 window after enough pixels and lines have arrived.
- Pipeline stages: DMA read, pixel unpack, line-buffer/window, convolution, brightness/contrast, threshold, histogram update, output pack, DMA write.
- Implement at least six visible pipeline valid registers and metadata registers for x/y coordinates.
- 3x3 convolution uses programmable signed 8-bit kernel coefficients and saturation to 8-bit output.
- Brightness/contrast stage applies signed offset and scale with saturation.
- Threshold stage can force output to 0 or 255 when FILTER_MODE is threshold.
- Histogram stage maintains 256 16-bit counters for processed output pixels.
- DMA write engine writes packed 32-bit processed pixels to DST_BASE.
- Interrupt controller asserts irq when frame_done, dma_done, histogram_done, or error events occur and IRQ_ENABLE is set.
- STATUS.busy remains high from START until frame processing and DMA writeback complete.
- SOFT_RESET clears internal state, line buffers, counters, histogram, sticky errors, and irq.

Verification and observability requirements:
- Expose frame_active, frame_done, pixel_valid, pixel_out, histogram_bin, and histogram_count for simulation visibility.
- Include assertions for no write without data, no read beyond configured frame, line-buffer window validity, IRQ clear behavior, and frame_done only after expected PIXEL_COUNT.
- Generate synthesizable SystemVerilog, register map, assertions, simulation testbench, UPF-lite collateral, and packaging manifest.`;

export const IMAGE_VERIFY_INTENT = `Verify the image DMA pipeline generated by Arch2RTL.

Directed scenarios:
- Assert reset_n low and confirm registers, line buffers, histogram counters, DMA state machines, irq, and frame status clear.
- Program SRC_BASE, DST_BASE, WIDTH, HEIGHT, STRIDE, FILTER_MODE, THRESHOLD, and KERNEL registers through the control interface.
- Run a small 16x8 frame in bypass mode and confirm DMA read/write byte counts, PIXEL_COUNT, frame_done, and irq behavior.
- Run a 3x3 edge-detect kernel on a deterministic test pattern and compare output signature.
- Run threshold mode and confirm output pixels saturate to 0 or 255 around the threshold.
- Confirm histogram counters update for processed output pixels and histogram_done asserts.
- Inject DMA read/write backpressure and confirm the pipeline stalls without dropping pixels.
- Exercise IRQ_CLEAR and SOFT_RESET while idle.

Collect waveform evidence, frame signature checks, DMA progress checks, histogram coverage, pipeline-valid coverage, assertion outcomes, and functional coverage.`;

export const IMAGE_EMBEDDED_SPEC = `Rust firmware for the verified image_dma_pipeline RTL.

Hardware interface:
- Image DMA pipeline RTL and register map are imported from the completed Arch2RTL workflow.
- Firmware configures source/destination addresses, width, height, stride, filter mode, kernel coefficients, threshold, brightness, and contrast.
- Firmware starts frame processing, waits for interrupts, reads frame counters, and extracts histogram bins.

Application policy:
- Provide init, configure_frame, configure_filter, start_frame, poll_status, clear_irq, read_histogram, and read_error APIs.
- Include demo presets for bypass, blur, edge detect, and threshold.
- Validate a frame signature and histogram summary after processing.

Generate a Rust register layer and driver, build collateral, co-simulation collateral, validation report, and a software-facing handoff package.`;

export const IMAGE_SOFTWARE_GOAL = `Create an image-processing control application and SDK over the verified Rust image DMA firmware.

Provide commands to configure frame geometry, choose filter preset, start DMA processing, monitor progress, inspect histogram bins, read output signatures, clear interrupts, and export a processing report.`;

export const IMAGE_VALIDATION_GOAL = `Validate the image DMA pipeline chain end to end.

Run bypass, edge-detect, threshold, and DMA-backpressure scenarios. Confirm software commands become firmware register operations and the imported RTL produces expected frame_done interrupts, DMA byte counts, output signatures, histogram updates, and traceable validation results.`;

export const IMAGE_PRODUCT_INTENT = `Build a simulator-backed image processing product dashboard from the validated RTL, firmware, software, and validation collateral.

The dashboard should let a user select a filter mode, adjust threshold and brightness, start a frame, visualize DMA progress, show input/output frame previews, display a histogram, show irq/status/error fields, and preserve lineage back to the generated workflows.`;

export const SENSOR_HUB_ARCH2RTL_SPEC = `Design a smart sensor hub microcontroller subsystem with a memory-mapped register interface.

This IoT edge-node demo should model a small microcontroller-style subsystem around sensor telemetry, local threshold policy, FIFO buffering, interrupt generation, and low-power sampling control. The CPU core may be represented as a firmware-facing control sequencer and register fabric for this reference journey; focus the generated RTL on the sensor hub peripherals and software-visible behavior.

Top module:
- smart_sensor_hub_mcu

Inputs:
- clk
- reset_n
- wr_en
- wr_addr[11:0]
- wr_data[31:0]
- rd_en
- rd_addr[11:0]
- sensor_temp_raw[15:0]
- sensor_humidity_raw[15:0]
- sensor_air_raw[15:0]
- sensor_valid

Outputs:
- rd_data[31:0]
- sensor_sample_req
- alert_irq
- fifo_level[5:0]
- low_power_active
- sample_count[31:0]
- alert_status[7:0]

Register map:
- 0x000 CONTROL: bit 0 ENABLE, bit 1 SAMPLE_START, bit 2 LOW_POWER_EN, bit 3 IRQ_ENABLE, bit 4 FIFO_CLEAR
- 0x004 STATUS: busy, sample_done, fifo_empty, fifo_full, alert_pending, low_power_active
- 0x008 SAMPLE_PERIOD: sample period in controller clock ticks[31:0]
- 0x00C SENSOR_SELECT: enable bits for temperature, humidity, and air-quality channels
- 0x010 TEMP_THRESHOLD: high temperature alert threshold[15:0]
- 0x014 HUMIDITY_THRESHOLD: high humidity alert threshold[15:0]
- 0x018 AIR_THRESHOLD: high air-quality alert threshold[15:0]
- 0x01C LATEST_TEMP: latest sampled temperature[15:0]
- 0x020 LATEST_HUMIDITY: latest sampled humidity[15:0]
- 0x024 LATEST_AIR: latest sampled air-quality value[15:0]
- 0x028 FIFO_DATA: packed sensor sample data, read pops FIFO
- 0x02C FIFO_LEVEL: current FIFO occupancy[5:0]
- 0x030 ALERT_STATUS: temp_alert, humidity_alert, air_alert, fifo_overflow, sample_timeout
- 0x034 ALERT_CLEAR: write one to clear alert bits
- 0x038 SAMPLE_COUNT: completed sample count[31:0]

Functional requirements:
- Reset clears registers, FIFO, sample counters, alert state, IRQ, and low-power state.
- SAMPLE_PERIOD controls periodic sensor_sample_req generation while CONTROL.ENABLE is set.
- SENSOR_SELECT enables sampling of temperature, humidity, and air-quality channels.
- On sensor_valid, capture enabled sensor channels into latest-value registers and push a packed sample record into a 16-entry FIFO.
- Compare captured readings against threshold registers and latch ALERT_STATUS bits when limits are crossed.
- alert_irq asserts when CONTROL.IRQ_ENABLE is set and any ALERT_STATUS bit is set.
- Firmware can read FIFO_DATA to pop buffered sample records and read FIFO_LEVEL for telemetry.
- FIFO overflow latches an alert bit without corrupting existing unread samples.
- LOW_POWER_EN gates periodic sample requests when no channels are enabled or when sample period is zero, and low_power_active reflects this state.
- SAMPLE_COUNT increments once per completed sample event.

Generate synthesizable SystemVerilog, a register map, assertions, a simulation testbench, UPF-lite collateral, and a packaging manifest.`;

export const SENSOR_VERIFY_INTENT = `Verify the smart sensor hub microcontroller subsystem generated by Arch2RTL.

Directed scenarios:
- Assert reset_n low and confirm registers, FIFO, counters, alert state, irq, and low-power state clear.
- Program CONTROL, SAMPLE_PERIOD, SENSOR_SELECT, and threshold registers through the memory-mapped interface.
- Drive temperature, humidity, and air-quality sensor samples and confirm latest-value registers and FIFO_DATA update.
- Cross each threshold independently and confirm ALERT_STATUS and alert_irq behavior.
- Exercise ALERT_CLEAR, FIFO_CLEAR, FIFO pop reads, FIFO overflow, and low-power enable behavior.
- Confirm SAMPLE_COUNT increments only on completed sample events.

Collect waveform evidence, register readback, FIFO coverage, threshold-alert coverage, low-power coverage, assertion outcomes, and functional coverage.`;

export const SENSOR_EMBEDDED_SPEC = `Rust firmware for the verified smart_sensor_hub_mcu RTL.

Hardware interface:
- Smart sensor hub RTL and register map are imported from the completed Arch2RTL workflow.
- Firmware configures sample period, enabled sensor channels, threshold limits, FIFO reads, alert interrupts, and low-power mode.

Application policy:
- Initialize the sensor hub for periodic temperature, humidity, and air-quality sampling.
- Set thresholds for comfort/safety alerts.
- Drain the sample FIFO into a telemetry buffer.
- Handle temperature, humidity, air-quality, FIFO overflow, and sample-timeout alerts.
- Provide a sensor health API with latest readings, FIFO depth, sample count, alert state, and low-power state.

Generate a Rust register layer and driver, build collateral, co-simulation collateral, validation report, and a software-facing handoff package.`;

export const SENSOR_SOFTWARE_GOAL = `Create an IoT sensor-node service and SDK over the verified Rust smart sensor hub firmware.

Provide commands to configure sample rate, select sensor channels, set alert thresholds, read latest telemetry, drain buffered samples, clear alerts, switch low-power mode, and report device health.`;

export const SENSOR_VALIDATION_GOAL = `Validate the smart sensor hub chain end to end.

Run a normal telemetry scenario, a threshold alert scenario, a FIFO buffering scenario, and a low-power sampling scenario. Confirm software commands become firmware register operations and the imported RTL produces expected sample requests, FIFO levels, alert interrupts, latest sensor values, and traceable validation results.`;

export const SENSOR_PRODUCT_INTENT = `Build a simulator-backed smart sensor hub product dashboard from the validated RTL, firmware, software, and validation collateral.

The dashboard should let a user configure sample rate, select sensor channels, set thresholds, view live temperature/humidity/air-quality readings, observe FIFO depth, alert state, sample count, and low-power mode, run an IoT telemetry/alert scenario, and preserve lineage back to the generated workflows.`;

export const SECURE_BOOT_ARCH2RTL_SPEC = `Design a secure boot and key manager controller with a memory-mapped register interface.

Top module:
- secure_boot_key_manager

Inputs:
- clk
- reset_n
- wr_en
- wr_addr[11:0]
- wr_data[31:0]
- rd_en
- rd_addr[11:0]
- image_word[31:0]
- image_valid
- hash_done
- hash_match
- tamper_detected

Outputs:
- rd_data[31:0]
- boot_allow
- boot_fail
- debug_locked
- hash_start
- key_slot_select[3:0]
- security_irq
- lifecycle_state[3:0]

Register map:
- 0x000 CONTROL: bit 0 ENABLE, bit 1 START_BOOT_CHECK, bit 2 LOCK_DEBUG, bit 3 IRQ_ENABLE
- 0x004 STATUS: busy, authenticated, failed, rollback_fail, tamper_seen, debug_locked
- 0x008 IMAGE_VERSION: firmware image version[31:0]
- 0x00C MIN_VERSION: anti-rollback minimum version[31:0]
- 0x010 KEY_SLOT: active key slot[3:0]
- 0x014 HASH_STATUS: hash_busy, hash_done, hash_match, hash_error
- 0x018 LIFECYCLE_STATE: device lifecycle state[3:0]
- 0x01C IRQ_STATUS: boot_done, boot_fail, tamper, rollback_fail
- 0x020 IRQ_CLEAR: write one to clear IRQ_STATUS bits
- 0x024 AUDIT_COUNT: security audit event count[31:0]

Functional requirements:
- Reset clears volatile state and leaves debug_locked asserted if LOCK_DEBUG was previously set in lifecycle state.
- START_BOOT_CHECK begins a secure boot transaction when ENABLE is set.
- The controller selects KEY_SLOT, asserts hash_start, waits for hash_done, and samples hash_match.
- boot_allow asserts only when hash_match is true, tamper_detected is false, and IMAGE_VERSION is greater than or equal to MIN_VERSION.
- boot_fail asserts and latches IRQ_STATUS on hash mismatch, rollback failure, or tamper.
- LOCK_DEBUG permanently locks debug access for the active run and sets debug_locked.
- AUDIT_COUNT increments for each boot_done, boot_fail, rollback_fail, or tamper event.
- IRQ_STATUS bits remain latched until cleared through IRQ_CLEAR.

Generate synthesizable SystemVerilog, a register map, assertions, a simulation testbench, UPF-lite collateral, and a packaging manifest.`;

export const SECURE_BOOT_VERIFY_INTENT = `Verify the secure boot and key manager controller generated by Arch2RTL.

Directed scenarios:
- Reset and confirm volatile status, IRQ, boot_allow, boot_fail, and hash_start behavior.
- Run successful image authentication with hash_match true and version above MIN_VERSION.
- Run hash mismatch, anti-rollback failure, and tamper scenarios and confirm boot_fail and IRQ_STATUS.
- Exercise LOCK_DEBUG and confirm debug_locked remains asserted.
- Clear each IRQ_STATUS bit and confirm AUDIT_COUNT increments for security events.

Collect waveform evidence, boot-state coverage, key-slot coverage, rollback/tamper coverage, assertion outcomes, and functional coverage.`;

export const SECURE_BOOT_EMBEDDED_SPEC = `Rust firmware for the verified secure_boot_key_manager RTL.

Hardware interface:
- Secure boot/key manager RTL and register map are imported from the completed Arch2RTL workflow.
- Firmware configures key slot, image version, minimum allowed version, debug lock, and interrupt handling.

Application policy:
- Start image authentication before releasing boot.
- Reject rollback, tamper, and hash mismatch cases.
- Lock debug when lifecycle policy requires it.
- Expose boot status, audit count, lifecycle state, and security IRQ state.

Generate a Rust register layer and driver, build collateral, co-simulation collateral, validation report, and a software-facing handoff package.`;

export const SECURE_BOOT_SOFTWARE_GOAL = `Create a secure provisioning and boot-status service over the verified Rust secure boot firmware.

Provide commands to select key slot, set anti-rollback minimum version, start boot authentication, inspect boot result, clear security interrupts, read audit count, and report debug lock/lifecycle state.`;

export const SECURE_BOOT_VALIDATION_GOAL = `Validate the secure boot chain end to end.

Run successful boot, hash mismatch, rollback failure, tamper, and debug-lock scenarios. Confirm software commands become firmware register operations and the imported RTL produces expected boot_allow, boot_fail, IRQ_STATUS, lifecycle, and audit behavior.`;

export const SECURE_BOOT_PRODUCT_INTENT = `Build a simulator-backed secure boot and key manager dashboard from the validated RTL, firmware, software, and validation collateral.

The dashboard should let a user select key slot, set firmware image/minimum versions, start authentication, view boot allow/fail state, debug lock, lifecycle state, security IRQs, audit count, and run secure boot failure/recovery scenarios.`;

export const SAFETY_FAULT_MANAGER_ARCH2RTL_SPEC = `Design an automotive safety fault manager and watchdog controller with a memory-mapped register interface.

Top module:
- safety_fault_watchdog

Inputs:
- clk
- reset_n
- wr_en
- wr_addr[11:0]
- wr_data[31:0]
- rd_en
- rd_addr[11:0]
- heartbeat
- fault_in[7:0]
- external_reset_done

Outputs:
- rd_data[31:0]
- safety_irq
- reset_request
- fault_latched[7:0]
- escalation_level[1:0]
- watchdog_expired

Register map:
- 0x000 CONTROL: bit 0 ENABLE, bit 1 WATCHDOG_ENABLE, bit 2 IRQ_ENABLE, bit 3 FAULT_CLEAR
- 0x004 STATUS: healthy, watchdog_expired, fault_pending, reset_requested, escalation_active
- 0x008 WATCHDOG_TIMEOUT: timeout value in controller ticks[31:0]
- 0x00C HEARTBEAT_COUNT: observed heartbeat count[31:0]
- 0x010 FAULT_MASK: enabled fault inputs[7:0]
- 0x014 FAULT_STATUS: latched fault inputs[7:0]
- 0x018 ESCALATION_POLICY: warn threshold, reset threshold, shutdown threshold fields
- 0x01C ESCALATION_LEVEL: 0 none, 1 warning, 2 reset, 3 shutdown
- 0x020 IRQ_STATUS: watchdog, fault, reset_request, escalation
- 0x024 IRQ_CLEAR: write one to clear IRQ_STATUS bits
- 0x028 RESET_COUNT: reset request count[31:0]

Functional requirements:
- Reset clears counters, status, latched faults, IRQ, reset_request, and escalation state.
- WATCHDOG_ENABLE starts a down counter that is refreshed by heartbeat.
- If heartbeat is not observed before WATCHDOG_TIMEOUT, watchdog_expired latches and IRQ_STATUS.watchdog asserts.
- Enabled fault_in bits latch into FAULT_STATUS and fault_latched.
- Escalation level increases based on repeated watchdog/fault events using ESCALATION_POLICY.
- reset_request asserts when escalation reaches reset level and clears after external_reset_done.
- FAULT_CLEAR and IRQ_CLEAR clear corresponding latched state without clearing RESET_COUNT.
- safety_irq asserts when IRQ_ENABLE is set and any IRQ_STATUS bit is set.

Generate synthesizable SystemVerilog, a register map, assertions, a simulation testbench, UPF-lite collateral, and a packaging manifest.`;

export const SAFETY_VERIFY_INTENT = `Verify the safety fault manager and watchdog controller generated by Arch2RTL.

Directed scenarios:
- Reset and confirm status, faults, IRQ, reset_request, counters, and escalation clear.
- Program watchdog timeout and observe heartbeat refresh behavior.
- Let watchdog expire and confirm watchdog_expired, IRQ_STATUS, and escalation behavior.
- Inject masked and unmasked faults and confirm only enabled faults latch.
- Exercise reset escalation, external_reset_done, FAULT_CLEAR, and IRQ_CLEAR.

Collect waveform evidence, watchdog coverage, fault-mask coverage, escalation coverage, reset-request coverage, assertion outcomes, and functional coverage.`;

export const SAFETY_EMBEDDED_SPEC = `Rust firmware for the verified safety_fault_watchdog RTL.

Hardware interface:
- Safety fault manager RTL and register map are imported from the completed Arch2RTL workflow.
- Firmware configures watchdog timeout, fault masks, escalation policy, interrupt handling, heartbeat service, and reset acknowledgement.

Application policy:
- Service watchdog heartbeat during healthy operation.
- Capture and classify faults.
- Escalate repeated faults from warning to reset request.
- Report safety health, latched faults, reset count, and escalation level.

Generate a Rust register layer and driver, build collateral, co-simulation collateral, validation report, and a software-facing handoff package.`;

export const SAFETY_SOFTWARE_GOAL = `Create an automotive safety health monitor service over the verified Rust safety fault manager firmware.

Provide commands to configure watchdog timeout, set fault masks, feed heartbeat, inject/report faults, clear interrupts, acknowledge reset, and export safety health and escalation reports.`;

export const SAFETY_VALIDATION_GOAL = `Validate the safety fault manager chain end to end.

Run healthy heartbeat, watchdog timeout, masked fault, reset escalation, and recovery scenarios. Confirm software commands become firmware register operations and the imported RTL produces expected IRQ, reset_request, fault_latched, watchdog_expired, and escalation behavior.`;

export const SAFETY_PRODUCT_INTENT = `Build a simulator-backed safety fault manager and watchdog dashboard from the validated RTL, firmware, software, and validation collateral.

The dashboard should let a user configure watchdog timeout, feed heartbeat, inject faults, view latched faults, safety IRQ, reset request, escalation level, reset count, and run safety fault/recovery scenarios.`;

export type DesignChainContext = {
  demoKind?: "pwm" | "uart_packet" | "image_dma" | "sensor_hub" | "secure_boot" | "safety_fault";
  arch2rtlWorkflowId?: string;
  arch2rtlRunId?: string;
  verifyWorkflowId?: string;
  verifyRunId?: string;
  embeddedWorkflowId?: string;
  embeddedRunId?: string;
  softwareWorkflowId?: string;
  softwareRunId?: string;
  validationWorkflowId?: string;
  validationRunId?: string;
  productWorkflowId?: string;
  productRunId?: string;
};
