# Auto-generated by ChipLoop Testbench Generator Agent
# Explicit RTL sources used by simulation
VERILOG_SOURCES += ../../handoff/rtl/actuator_clamper.v
VERILOG_SOURCES += ../../handoff/rtl/actuator_tx.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_top.v
VERILOG_SOURCES += ../../handoff/rtl/adaptive_aero_control_top_spi_fpga_top.sv
VERILOG_SOURCES += ../../handoff/rtl/command_validator.v
VERILOG_SOURCES += ../../handoff/rtl/control_register_bank.v
VERILOG_SOURCES += ../../handoff/rtl/fallback_fsm.v
VERILOG_SOURCES += ../../handoff/rtl/status_telemetry.v
VERILOG_SOURCES += ../../handoff/rtl/stream_rx.v
VERILOG_SOURCES += ../../handoff/rtl/timeout_monitor.v
